In [1]:
import sys
import logging
from pathlib import Path
from typing import List, Mapping, Sequence, Union, Dict
import pandas as pd
import os

import pandas as pd
import dycomutils as common_utils

repo_root = Path.cwd().resolve()
while repo_root != repo_root.parent and not (repo_root / "src").exists():
    repo_root = repo_root.parent

os.chdir(repo_root)
print(repo_root)
sys.path.append(str(repo_root))

from src.utils.graph_manager import GraphManager
from src.utils.utils import load_config, format_dataframe_to_string, regex_add_strings
from src.config.experiment import ExperimentConfig
from src.experiment.ground_truth import GT, SPARQLTemplate, GTAnswer
from evaluations.test_questions.templates import build_gt_from_template

CONFIG_PATH = "evaluations/calibration/config.yaml"
logging.info(f"Loading config: {CONFIG_PATH}")
lconfig = load_config(CONFIG_PATH)
config = ExperimentConfig.model_validate(lconfig)
config

/home/desild/work/research/LLM-Workflow-Explorer

ExperimentConfig(application=ApplicationInfo(description='The application that utilizes a functional approach to support unittesting of LLMs on user designed prompts. This application contains functions generated by LLMs and functions that utilizes LLM generated output within the system. In this experiments are represented as provone:Executions of provone:Programs (a step of the experiment pipeline) while some of these provone:Programs are generated by LLM as Generative_Tasks. dc:identifier represents the unique experiment id.'), file_paths=InputFiles(schema_loc='schema/schemaV2.json', execution_kg_loc='usecases/chatbs/data/1_sample_graph/chatbs_sample.ttl', metadata_loc='usecases/chatbs/data/1_sample_graph/chatbs_sample_metadata.json'), explorer_config=ExplorerConfig(kg_name='ChatBS-NexGen', ontology_triples_path='schema/extracted_ontology_triples.csv', parallel=True, temp_folder='evaluations/calibration/exeprog_creation/tmp/programs', use_cache=False, explorer_metadata_loc='evaluations/calibration/exeprog_creation/exeplorer_metadata.pkl', exeprog_save_loc='evaluations/calibration/exeprog_creation/exeplored_programs.pkl', log_file='evaluations/calibration/exeprog_creation/explorer_log.txt'), question_creation_config=QuestionCreationConfig(save_questions='evaluations/calibration/ques_creation/SyntheticQuestionKG.csv', llm_type='lmstudio', llm_config={'model': 'lm_studio/qwen/qwen3.5-4b', 'base_url': 'http://localhost:1234/v1'}, log_file='evaluations/calibration/ques_creation/question_creation_log.txt'), explainer_config=ExplainerConfig(llm_type='lmstudio', embedding_type='lmstudio', vectordb_type='milvus', save_answer_loc='evaluations/calibration/explainer/results', llm_config={'model': 'lm_studio/qwen/qwen3.5-4b', 'base_url': 'http://localhost:1234/v1'}, embedding_config={'model': 'text-embedding-bge-large-en-v1.5'}, vectordb_config={'vector_dim': 1024, 'collection_name': 'calibration'}, object_search_config={'search_limit': 3}, log_file='evaluations/calibration/explainer/explainer_log.txt'), ttl=TTLConfig(prefixes=[{'name': 'provone', 'uri': 'http://purl.dataone.org/provone/2015/01/15/ontology#'}, {'name': 'skos', 'uri': 'http://www.w3.org/2004/02/skos/core#'}, {'name': 'prov', 'uri': 'http://www.w3.org/ns/prov#'}, {'name': 'rdfs', 'uri': 'http://www.w3.org/2000/01/rdf-schema#'}, {'name': 'cwfo', 'uri': 'http://cwf.tw.rpi.edu/vocab#'}, {'name': 'dcterms', 'uri': 'http://purl.org/dc/terms#'}, {'name': 'ChatBS-NexGen', 'uri': 'http://testwebsite/testProgram#'}, {'name': 'user', 'uri': 'http://testwebsite/testUser#'}, {'name': 'eo', 'uri': 'https://purl.org/heals/eo#'}, {'name': 'ep', 'uri': 'http://linkedu.eu/dedalo/explanationPattern.owl#'}, {'name': 'sio', 'uri': 'http://semanticscience.org/resource/'}, {'name': 'dc', 'uri': 'http://purl.org/dc/elements/1.1/'}, {'name': 'DFColumn', 'uri': 'http://testwebsite/testDFColumn#'}, {'name': 'fnom', 'uri': 'https://w3id.org/function/vocabulary/mapping#'}, {'name': 'fnoi', 'uri': 'https://w3id.org/function/vocabulary/implementation#'}, {'name': 'fnoc', 'uri': 'https://w3id.org/function/vocabulary/composition/0.1.0/'}, {'name': 'food', 'uri': 'http://purl.org/heals/food/'}, {'name': 'dbo', 'uri': 'http://dbpedia.org/ontology/'}, {'name': 'dbp', 'uri': 'http://dbpedia.org/property/'}, {'name': 'dbt', 'uri': 'http://dbpedia.org/resource/Template:'}, {'name': 'ques', 'uri': 'http://atomic_questions.org/'}, {'name': 'xsd', 'uri': 'http://www.w3.org/2001/XMLSchema#'}, {'name': 'fno', 'uri': 'https://w3id.org/function/vocabulary/core#'}, {'name': 'workflow', 'uri': 'http://www.semanticweb.org/acer/ontologies/2026/1/WorkFlow/'}]), gt=GTConfig(log_file='evaluations/calibration/ground_truth/ground_truth_log.txt', save_loc='evaluations/calibration/ground_truth/ground_truth_data.json'))

In [2]:
graph_manager = GraphManager(
    config.ttl,
    config.file_paths.execution_kg_loc,
)

gt_list: List[GT] = []

In [3]:
# Question 1
question1 = """
How many unique \"experiment execution\" are there in this?
"""
question_sparql1 = """
SELECT (count(distinct ?ids) AS ?obj_count)
WHERE {
     ?obj a provone:Execution ;
          dcterms:identifier ?ids .
}
"""

entities1 = graph_manager.query(question_sparql1)
entities1

  obj_count
0         1

In [4]:
answer1 = "The answer to the question is 1 unique executions."

gt_list.append(
    GT(
        question=question1,
        answer=answer1,
        sparql_querys=[
            SPARQLTemplate(
                template=question_sparql1,
                description="This SPARQL query counts the number of unique executions by counting distinct identifiers in the provone:Execution class.",
            )
        ],
        entities=entities1.to_dict(orient="records"),
    )
)

In [7]:
# Question 3
question3 = """
In what places do we utilize AI in this workflow?
"""
question_sparql3 = """
SELECT distinct ?obj ?desc
WHERE {
     ?obj a workflow:Generative_Task .
     ?obj dc:description ?desc .
}
"""

entities3 = graph_manager.query(question_sparql3, resolve_curie=True)
entities3

,obj,desc
0,ChatBS-NexGen:Generative_Task-id_2026032423045...,Generates the answer using gpt-4o@en^^<xsd:st...
1,ChatBS-NexGen:Generative_Task-id_2026032423050...,Extracts the information using gpt-4o@en^^<xs...
2,ChatBS-NexGen:Generative_Task-information_extr...,Generates the Information Extractor Function u...
3,ChatBS-NexGen:Generative_Task-query_result_pos...,Generates the post processing Function using L...
4,ChatBS-NexGen:Generative_Task-system_prompt_ge...,Generates the System Prompt Template using Lar...

In [8]:
answer3 = """
The ChatBS System utilizes LLMs to generate the following functions

1. Information extraction function
2. System Prompt template function
3. Sparql result post processing function

and further it's used within functions to
1. Generate the LLM outputs,
2. Used to extract key information from the system.
"""

gt_list.append(
    GT(
        question=question3,
        answer=answer3,
        sparql_querys=[SPARQLTemplate(template=question_sparql3, description="")],
        entities=entities3.to_dict(orient="records"),
    )
)

In [9]:
# Question 4
question4 = """
What are the extracted KG entities for the execution with id 1_1
"""
question_sparql4 = """
SELECT DISTINCT ?member ?prop ?value
WHERE {
     ?obj dc:description ?desc .
     FILTER(REGEX(?desc, "SPARQL queries to extract information", "i"))

     ?obj a provone:Program .
     ?exe prov:qualifiedAssociation/prov:hadPlan ?obj .
     ?exe dcterms:identifier ?id .
     FILTER(REGEX(?id, "1_1", "i"))

     ?data prov:wasGeneratedBy ?exe .
     ?data a ?class .

     {
         ?data a provone:Collection .
         ?data provone:hadMember ?member .
         ?member ?prop ?value .
     }
     UNION
     {
         ?data a provone:Data .
         BIND(?data AS ?member)
         ?data ?prop ?value .
     }
}
"""

entities4 = graph_manager.query(question_sparql4, resolve_curie=True)
entities4

,member,prop,value
0,ChatBS-NexGen:Data-id_20260324230500_890-kg_info,DFColumn:sugarG,4@en^^<xsd:string>
1,ChatBS-NexGen:Data-id_20260324230500_890-kg_info,DFColumn:ingredientName,Yogurt@en^^<xsd:string>
2,ChatBS-NexGen:Data-id_20260324230500_890-kg_info,DFColumn:ingredientCat,Desserts@en^^<xsd:string>
3,ChatBS-NexGen:Data-id_20260324230500_890-kg_info,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,provone:Data
4,ChatBS-NexGen:Data-id_20260324230500_396-kg_info,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,provone:Data
...,...,...,...
71,ChatBS-NexGen:Data-id_20260324230502_542-kg_info,DFColumn:ingredientCat,NA@en^^<xsd:string>
72,ChatBS-NexGen:Data-id_20260324230502_962-kg_info,DFColumn:ingredientCat,American cuisine@en^^<xsd:string>
73,ChatBS-NexGen:Data-id_20260324230502_962-kg_info,DFColumn:ingredientName,Cottage cheese@en^^<xsd:string>
74,ChatBS-NexGen:Data-id_20260324230502_962-kg_info,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,provone:Data
75,ChatBS-NexGen:Data-id_20260324230502_962-kg_info,DFColumn:sugarG,NA@en^^<xsd:string>

In [10]:
pentities4 = set(
    entities4.loc[entities4["prop"] == "DFColumn:ingredientName", "value"]
    .apply(lambda x: x.split("@")[0])
    .tolist()
) - {"", "NA"}

answer4 = """
The retrieved entities from the knowledge graph includes the following ingredients,

1. Yogurt
2. Berry
3. Cheese
4. Carrot
5. Turkey
6. Bell pepper
7. Hummus
8. Almond
9. Avocado
10. Pumpkin seed
11. Water
12. Pineapple
13. Cottage cheese
"""

gt_list.append(
    GT(
        question=question4,
        answer=answer4,
        sparql_querys=[SPARQLTemplate(template=question_sparql4, description="")],
        entities=list(pentities4),
    )
)

In [11]:
# Question 5
question5 = """
why did some ingredients have missing values for `sugarG` and `ingredientCat` columns in the final output of the workflow?
"""
question_sparql5 = """
SELECT DISTINCT ?member ?prop ?value
WHERE {
     ?obj dc:description ?desc .
     FILTER(REGEX(?desc, "SPARQL queries to extract information", "i"))

     ?obj a provone:Program .
     ?exe prov:qualifiedAssociation/prov:hadPlan ?obj .
     ?exe dcterms:identifier ?id .
     FILTER(REGEX(?id, "1_1", "i"))

     ?data prov:wasGeneratedBy ?exe .
     ?data a ?class .

     {
         ?data a provone:Collection .
         ?data provone:hadMember ?member .
         ?member ?prop ?value .
     }
     UNION
     {
         ?data a provone:Data .
         BIND(?data AS ?member)
         ?data ?prop ?value .
     }
}

order by ?member ?prop
"""

entities5 = graph_manager.query(question_sparql5, resolve_curie=True)
entities5

,member,prop,value
0,ChatBS-NexGen:Data-id_20260324230500_287-kg_info,DFColumn:ingredientCat,@en^^<xsd:string>
1,ChatBS-NexGen:Data-id_20260324230500_287-kg_info,DFColumn:ingredientName,@en^^<xsd:string>
2,ChatBS-NexGen:Data-id_20260324230500_287-kg_info,DFColumn:sugarG,@en^^<xsd:string>
3,ChatBS-NexGen:Data-id_20260324230500_287-kg_info,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,provone:Data
4,ChatBS-NexGen:Data-id_20260324230500_396-kg_info,DFColumn:ingredientCat,Berries@en^^<xsd:string>
...,...,...,...
71,ChatBS-NexGen:Data-id_20260324230502_910-kg_info,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,provone:Data
72,ChatBS-NexGen:Data-id_20260324230502_962-kg_info,DFColumn:ingredientCat,American cuisine@en^^<xsd:string>
73,ChatBS-NexGen:Data-id_20260324230502_962-kg_info,DFColumn:ingredientName,Cottage cheese@en^^<xsd:string>
74,ChatBS-NexGen:Data-id_20260324230502_962-kg_info,DFColumn:sugarG,NA@en^^<xsd:string>
75,ChatBS-NexGen:Data-id_20260324230502_962-kg_info,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,provone:Data

In [12]:
na_entities = entities5.loc[
    entities5["value"].isin(["@en^^<xsd:string>", "NA@en^^<xsd:string>"]),
    "member",
].unique().tolist()
pentities5 = set(
    entities5.loc[
        entities5["member"].isin(na_entities)
        & (entities5["prop"] == "DFColumn:ingredientName"),
        "value",
    ]
    .apply(lambda x: x.split("@")[0])
    .tolist()
) - {"", "NA"}

answer5 = """
Due to the fact that some information is not available in the knowledge graph for ingredients such as
'Turkey', 'Hummus', 'Cheese', 'Cottage cheese', 'Berry', 'Water' the sugarG and ingredientCat is not available.
"""

gt_list.append(
    GT(
        question=question5,
        answer=answer5,
        sparql_querys=[SPARQLTemplate(template=question_sparql5, description="")],
        entities=list(pentities5),
    )
)

In [ ]:
# Question MULT 1


template_spec = [{
    "func_desc":"sparql query post processing"
}, {
    "func_desc": "system prompt template"
}, {
    "func_desc": "information extraction"
}]

sparql_spec = [{
    "func_desc_term":"Post-processes the query results"
},{
    "func_desc_term":"Generates a system prompt"
},{
    "func_desc_term":"Extracts entities or relevant information"
},]

question_template = """
what are the instructions used by the LLM to generate the {func_desc} function step in the pipeline?
"""
sparql_template = """
SELECT distinct ?obj ?llm ?inpd
WHERE {
     ?obj dc:description ?desc .
     ?obj a ?class .
     FILTER(REGEX(?desc, "{func_desc_term}","i"))

     ?llm_out sio:SIO_000202 ?obj .
     ?llm_out sio:SIO_000232 ?llm .
     ?llm sio:SIO_000230 ?inp .
     ?inp prov:value ?inpd
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    We utilize the following input instructions to generate the function that is used to {func_desc} from the previous step.

    {answer_inst}
    """
    
    _temp_ent = entities[['obj', 'inpd']]
    _temp_ent = format_dataframe_to_string(
        _temp_ent,
        header_map={
            "obj": "Funtion",
            "inpd": "Instruction for function generation"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= entities.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

gt_list.extend(gts)

ic| rquestion: '''
                what are the instructions used by the LLM to generate the sparql query post processing function step in the pipeline?
                '''
ic| entities:                                                  obj  \
              0  http://testwebsite/testProgram#query_result_po...
              1  http://testwebsite/testProgram#query_result_po...

                                                               llm  \
              0  http://testwebsite/testProgram#LLM-query_resul...
              1  http://testwebsite/testProgram#LLM-query_resul...

                                                              inpd
              0  Concat all the rows into single row at each co...
              1  If there are duplicate ingredients then select...
ic| answer: GTAnswer(answer_nlp="
                We utilize the following input instructions to generate the function that is used to sparql query post processing from the previous step.

                Funtion | Instruction for function generation
            http://testwebsite/testProgram#query_result_post_processor | Concat all the rows into single row at each column by '|' concatenation marker.@en^^<xsd:string>
            http://testwebsite/testProgram#query_result_post_processor | If there are duplicate ingredients then select row with most information on `sugarG` and `ingredientCat` columns. Fill all the missing values with '0' in `sugarG` column and with '-' in 'ingredientCat` column.@en^^<xsd:string>
                ", entities=[{'obj': 'http://testwebsite/testProgram#query_result_post_processor', 'llm': 'http://testwebsite/testProgram#LLM-query_result_post_processor', 'inpd': "Concat all the rows into single row at each column by '|' concatenation marker.@en^^<xsd:string>"}, {'obj': 'http://testwebsite/testProgram#query_result_post_processor', 'llm': 'http://testwebsite/testProgram#LLM-query_result_post_processor', 'inpd': "If there are duplicate ingredients then select row with most information on `sugarG` and `ingredientCat` columns. Fill all the missing values with '0' in `sugarG` column and with '-' in 'ingredientCat` column.@en^^<xsd:string>"}])
ic| rquestion: '''
                what are the instructions used by the LLM to generate the system prompt template function step in the pipeline?
                '''
ic| entities: Empty DataFrame
              Columns: [obj, llm, inpd]
              Index: []
ic| answer: GTAnswer(answer_nlp='
                We utilize the following input instructions to generate the function that is used to system prompt template from the previous step.

                Funtion | Instruction for function generation
                ', entities=[])
ic| rquestion: '''
                what are the instructions used by the LLM to generate the information extraction function step in the pipeline?
                '''
ic| entities:                                                  obj  \
              0  http://testwebsite/testProgram#system_prompt_g...
              1  http://testwebsite/testProgram#system_prompt_g...

                                                               llm  \
              0  http://testwebsite/testProgram#LLM-system_prom...
              1  http://testwebsite/testProgram#LLM-system_prom...

                                                             inpd
              0  You are a health care assistant@en^^<xsd:string>
              1                           gpt-4o@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                We utilize the following input instructions to generate the function that is used to information extraction from the previous step.

                Funtion | Instruction for function generation
            http://testwebsite/testProgram#system_prompt_generator | You are a health care assistant@en^^<xsd:string>
            http://testwebsite/testProgram#system_prompt_generator | gpt-4o@en^^<xsd:string>
                ', entities=[{'obj': 'http://testwebsite/testProgram#system_prompt_generator', 'llm': 'http://testwebsite/testProgram#LLM-system_prompt_generator', 'inpd': 'You are a health care assistant@en^^<xsd:string>'}, {'obj': 'http://testwebsite/testProgram#system_prompt_generator', 'llm': 'http://testwebsite/testProgram#LLM-system_prompt_generator', 'inpd': 'gpt-4o@en^^<xsd:string>'}])

In [14]:
gts

[GT(id='05df54ea-6b08-4c14-99cf-f209df262b95', question='\nwhat are the instructions used by the LLM to generate the sparql query post processing function step in the pipeline?\n', answer="\n    We utilize the following input instructions to generate the function that is used to sparql query post processing from the previous step.\n\n    Funtion | Instruction for function generation\nhttp://testwebsite/testProgram#query_result_post_processor | Concat all the rows into single row at each column by '|' concatenation marker.@en^^<xsd:string>\nhttp://testwebsite/testProgram#query_result_post_processor | If there are duplicate ingredients then select row with most information on `sugarG` and `ingredientCat` columns. Fill all the missing values with '0' in `sugarG` column and with '-' in 'ingredientCat` column.@en^^<xsd:string>\n    ", entities=[{'obj': 'http://testwebsite/testProgram#query_result_post_processor', 'llm': 'http://testwebsite/testProgram#LLM-query_result_post_processor', 'inpd': "Concat all the rows into single row at each column by '|' concatenation marker.@en^^<xsd:string>"}, {'obj': 'http://testwebsite/testProgram#query_result_post_processor', 'llm': 'http://testwebsite/testProgram#LLM-query_result_post_processor', 'inpd': "If there are duplicate ingredients then select row with most information on `sugarG` and `ingredientCat` columns. Fill all the missing values with '0' in `sugarG` column and with '-' in 'ingredientCat` column.@en^^<xsd:string>"}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?obj ?llm ?inpd\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Post-processes the query results","i"))\n\n     ?llm_out sio:SIO_000202 ?obj .\n     ?llm_out sio:SIO_000232 ?llm .\n     ?llm sio:SIO_000230 ?inp .\n     ?inp prov:value ?inpd\n}\n', description='', inputs=None)])]

In [15]:
os.makedirs(os.path.dirname(config.gt.save_loc), exist_ok=True)
for i, gt in enumerate(gt_list):
    gt.id = f"gt_{i}"

common_utils.serialization.save_json(
    {gt.id: gt.model_dump() for gt in gt_list}, config.gt.save_loc
)

In [16]:
gt_list

[GT(id='gt_0', question='\nHow many unique "experiment execution" are there in this?\n', answer='The answer to the question is 1 unique executions.', entities=[{'obj_count': '1'}], sparql_querys=[SPARQLTemplate(template='\nSELECT (count(distinct ?ids) AS ?obj_count)\nWHERE {\n     ?obj a provone:Execution ;\n          dcterms:identifier ?ids .\n}\n', description='This SPARQL query counts the number of unique executions by counting distinct identifiers in the provone:Execution class.', inputs=None)]),
 GT(id='gt_1', question='\nwhat are the instructions used by the LLM to generate the sparql query post processing function step in the pipeline?\n', answer="\nWe utilize the following input instructions to generate the function that is used to post process the sparql query results from the previous step.\n\n1. Concat all the rows into single row at each column by '|' concatenation marker.@en^^<xsd:string>\n2. If there are duplicate ingredients then select row with most information on `sugarG` and `ingredientCat` columns.\n   Fill all the missing values with '0' in `sugarG` column and with '-' in 'ingredientCat` column.@en^^<xsd:string>\n", entities=[{'obj': 'ChatBS-NexGen:query_result_post_processor', 'llm': 'ChatBS-NexGen:LLM-query_result_post_processor', 'inpd': "Concat all the rows into single row at each column by '|' concatenation marker.@en^^<xsd:string>"}, {'obj': 'ChatBS-NexGen:query_result_post_processor', 'llm': 'ChatBS-NexGen:LLM-query_result_post_processor', 'inpd': "If there are duplicate ingredients then select row with most information on `sugarG` and `ingredientCat` columns. Fill all the missing values with '0' in `sugarG` column and with '-' in 'ingredientCat` column.@en^^<xsd:string>"}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?obj ?llm ?inpd\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Post-processes the query results","i"))\n\n     ?llm_out sio:SIO_000202 ?obj .\n     ?llm_out sio:SIO_000232 ?llm .\n     ?llm sio:SIO_000230 ?inp .\n     ?inp prov:value ?inpd\n}\n', description='', inputs=None)]),
 GT(id='gt_2', question='\nIn what places do we utilize AI in this workflow?\n', answer="\nThe ChatBS System utilizes LLMs to generate the following functions\n\n1. Information extraction function\n2. System Prompt template function\n3. Sparql result post processing function\n\nand further it's used within functions to\n1. Generate the LLM outputs,\n2. Used to extract key information from the system.\n", entities=[{'obj': 'ChatBS-NexGen:Generative_Task-id_20260324230458_784', 'desc': 'Generates the answer using  gpt-4o@en^^<xsd:string>'}, {'obj': 'ChatBS-NexGen:Generative_Task-id_20260324230500_68', 'desc': 'Extracts the information using  gpt-4o@en^^<xsd:string>'}, {'obj': 'ChatBS-NexGen:Generative_Task-information_extractor', 'desc': 'Generates the Information Extractor Function using Large language models@en^^<xsd:string>'}, {'obj': 'ChatBS-NexGen:Generative_Task-query_result_post_processor', 'desc': 'Generates the post processing Function using Large language models@en^^<xsd:string>'}, {'obj': 'ChatBS-NexGen:Generative_Task-system_prompt_generator', 'desc': 'Generates the System Prompt Template using Large language models@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?obj ?desc\nWHERE {\n     ?obj a workflow:Generative_Task .\n     ?obj dc:description ?desc .\n}\n', description='', inputs=None)]),
 GT(id='gt_3', question='\nWhat are the extracted KG entities for the execution with id 1_1\n', answer='\nThe retrieved entities from the knowledge graph includes the following ingredients,\n\n1. Yogurt\n2. Berry\n3. Cheese\n4. Carrot\n5. Turkey\n6. Bell pepper\n7. Hummus\n8. Almond\n9. Avocado\n10. Pumpkin seed\n11. Water\n12. Pineapple\n13. Cottage cheese\n', entities=['Berry', 'Carrot', 'Turkey', 'Water', 'Cottage cheese', 'Almond', 'Avocado', 'Pumpkin seed', 'Hummus', 'Pineapple', 'Cheese', 'Yogurt', 'Bell pepper'], sparql_querys=[SPARQLTemplate(template='\nSELECT DISTINCT ?member ?prop ?value\nWHERE {\n     ?obj dc:description ?desc .\n     FILTER(REGEX(?desc, "SPARQL queries to extract information", "i"))\n\n     ?obj a provone:Program .\n     ?exe prov:qualifiedAssociation/prov:hadPlan ?obj .\n     ?exe dcterms:identifier ?id .\n     FILTER(REGEX(?id, "1_1", "i"))\n\n     ?data prov:wasGeneratedBy ?exe .\n     ?data a ?class .\n\n     {\n         ?data a provone:Collection .\n         ?data provone:hadMember ?member .\n         ?member ?prop ?value .\n     }\n     UNION\n     {\n         ?data a provone:Data .\n         BIND(?data AS ?member)\n         ?data ?prop ?value .\n     }\n}\n', description='', inputs=None)]),
 GT(id='gt_4', question='\nwhy did some ingredients have missing values for `sugarG` and `ingredientCat` columns in the final output of the workflow?\n', answer="\nDue to the fact that some information is not available in the knowledge graph for ingredients such as\n'Turkey', 'Hummus', 'Cheese', 'Cottage cheese', 'Berry', 'Water' the sugarG and ingredientCat is not available.\n", entities=['Berry', 'Turkey', 'Water', 'Cottage cheese', 'Hummus', 'Cheese'], sparql_querys=[SPARQLTemplate(template='\nSELECT DISTINCT ?member ?prop ?value\nWHERE {\n     ?obj dc:description ?desc .\n     FILTER(REGEX(?desc, "SPARQL queries to extract information", "i"))\n\n     ?obj a provone:Program .\n     ?exe prov:qualifiedAssociation/prov:hadPlan ?obj .\n     ?exe dcterms:identifier ?id .\n     FILTER(REGEX(?id, "1_1", "i"))\n\n     ?data prov:wasGeneratedBy ?exe .\n     ?data a ?class .\n\n     {\n         ?data a provone:Collection .\n         ?data provone:hadMember ?member .\n         ?member ?prop ?value .\n     }\n     UNION\n     {\n         ?data a provone:Data .\n         BIND(?data AS ?member)\n         ?data ?prop ?value .\n     }\n}\n\norder by ?member ?prop\n', description='', inputs=None)])]