In [1]:
import sys
import logging
from pathlib import Path
from typing import List, Mapping, Sequence, Union, Dict
import pandas as pd
import os

import pandas as pd
import dycomutils as common_utils

repo_root = Path.cwd().resolve()
while repo_root != repo_root.parent and not (repo_root / "src").exists():
    repo_root = repo_root.parent

os.chdir(repo_root)
print(repo_root)
sys.path.append(str(repo_root))

from src.utils.graph_manager import GraphManager
from src.utils.utils import load_config, format_dataframe_to_string, regex_add_strings
from src.config.experiment import ExperimentConfig
from src.experiment.ground_truth import GT, SPARQLTemplate, GTAnswer
from evaluations.test_questions.templates import build_gt_from_template

CONFIG_PATH = "evaluations/calibration/config.yaml"
logging.info(f"Loading config: {CONFIG_PATH}")
lconfig = load_config(CONFIG_PATH)
config = ExperimentConfig.model_validate(lconfig)
config

/home/desild/work/research/LLM-Workflow-Explorer

ExperimentConfig(application=ApplicationInfo(description='The application that utilizes a functional approach to support unittesting of LLMs on user designed prompts. This application contains functions generated by LLMs and functions that utilizes LLM generated output within the system. In this experiments are represented as provone:Executions of provone:Programs (a step of the experiment pipeline) while some of these provone:Programs are generated by LLM as Generative_Tasks. dc:identifier represents the unique experiment id.'), file_paths=InputFiles(schema_loc='schema/schemaV2.json', execution_kg_loc='usecases/chatbs/data/1_sample_graph/chatbs_sample.ttl', metadata_loc='usecases/chatbs/data/1_sample_graph/chatbs_sample_metadata.json'), explorer_config=ExplorerConfig(kg_name='ChatBS-NexGen', ontology_triples_path='schema/extracted_ontology_triples.csv', parallel=True, temp_folder='evaluations/calibration/exeprog_creation/tmp/programs', use_cache=False, explorer_metadata_loc='evaluations/calibration/exeprog_creation/exeplorer_metadata.pkl', exeprog_save_loc='evaluations/calibration/exeprog_creation/exeplored_programs.pkl', log_file='evaluations/calibration/exeprog_creation/explorer_log.txt'), question_creation_config=QuestionCreationConfig(save_questions='evaluations/calibration/ques_creation/SyntheticQuestionKG.csv', llm_type='lmstudio', llm_config={'model': 'lm_studio/qwen/qwen3.5-4b', 'base_url': 'http://localhost:1234/v1'}, log_file='evaluations/calibration/ques_creation/question_creation_log.txt'), explainer_config=ExplainerConfig(llm_type='lmstudio', embedding_type='lmstudio', vectordb_type='milvus', save_answer_loc='evaluations/calibration/explainer/results', llm_config={'model': 'lm_studio/qwen/qwen3.5-4b', 'base_url': 'http://localhost:1234/v1'}, embedding_config={'model': 'text-embedding-bge-large-en-v1.5'}, vectordb_config={'vector_dim': 1024, 'collection_name': 'calibration'}, object_search_config={'search_limit': 3}, log_file='evaluations/calibration/explainer/explainer_log.txt'), ttl=TTLConfig(prefixes=[{'name': 'provone', 'uri': 'http://purl.dataone.org/provone/2015/01/15/ontology#'}, {'name': 'skos', 'uri': 'http://www.w3.org/2004/02/skos/core#'}, {'name': 'prov', 'uri': 'http://www.w3.org/ns/prov#'}, {'name': 'rdfs', 'uri': 'http://www.w3.org/2000/01/rdf-schema#'}, {'name': 'cwfo', 'uri': 'http://cwf.tw.rpi.edu/vocab#'}, {'name': 'dcterms', 'uri': 'http://purl.org/dc/terms#'}, {'name': 'ChatBS-NexGen', 'uri': 'http://testwebsite/testProgram#'}, {'name': 'user', 'uri': 'http://testwebsite/testUser#'}, {'name': 'eo', 'uri': 'https://purl.org/heals/eo#'}, {'name': 'ep', 'uri': 'http://linkedu.eu/dedalo/explanationPattern.owl#'}, {'name': 'sio', 'uri': 'http://semanticscience.org/resource/'}, {'name': 'dc', 'uri': 'http://purl.org/dc/elements/1.1/'}, {'name': 'DFColumn', 'uri': 'http://testwebsite/testDFColumn#'}, {'name': 'fnom', 'uri': 'https://w3id.org/function/vocabulary/mapping#'}, {'name': 'fnoi', 'uri': 'https://w3id.org/function/vocabulary/implementation#'}, {'name': 'fnoc', 'uri': 'https://w3id.org/function/vocabulary/composition/0.1.0/'}, {'name': 'food', 'uri': 'http://purl.org/heals/food/'}, {'name': 'dbo', 'uri': 'http://dbpedia.org/ontology/'}, {'name': 'dbp', 'uri': 'http://dbpedia.org/property/'}, {'name': 'dbt', 'uri': 'http://dbpedia.org/resource/Template:'}, {'name': 'ques', 'uri': 'http://atomic_questions.org/'}, {'name': 'xsd', 'uri': 'http://www.w3.org/2001/XMLSchema#'}, {'name': 'fno', 'uri': 'https://w3id.org/function/vocabulary/core#'}, {'name': 'workflow', 'uri': 'http://www.semanticweb.org/acer/ontologies/2026/1/WorkFlow/'}]), gt=GTConfig(log_file='evaluations/calibration/ground_truth/ground_truth_log.txt', save_loc='evaluations/calibration/ground_truth/ground_truth_data.json'))

In [2]:
graph_manager = GraphManager(
    config.ttl,
    config.file_paths.execution_kg_loc,
)

gt_list: List[GT] = []

In [3]:
# Question 1
question1 = """
How many unique \"experiment execution\" are there in this?
"""
question_sparql1 = """
SELECT (count(distinct ?ids) AS ?obj_count)
WHERE {
     ?obj a provone:Execution ;
          dcterms:identifier ?ids .
}
"""

entities1 = graph_manager.query(question_sparql1)
entities1

  obj_count
0         1

In [4]:
answer1 = "The answer to the question is 1 unique executions."

gt_list.append(
    GT(
        question=question1,
        answer=answer1,
        sparql_querys=[
            SPARQLTemplate(
                template=question_sparql1,
                description="This SPARQL query counts the number of unique executions by counting distinct identifiers in the provone:Execution class.",
            )
        ],
        qtype=["single", "numeric"],
        entities=entities1.to_dict(orient="records"),
    )
)

In [5]:
# Question 3
question3 = """
In what places do we utilize AI in this workflow?
"""
question_sparql3 = """
SELECT distinct ?obj ?desc
WHERE {
     ?obj a workflow:Generative_Task .
     ?obj dc:description ?desc .
}
"""

entities3 = graph_manager.query(question_sparql3, resolve_curie=True)
entities3

,obj,desc
0,ChatBS-NexGen:Generative_Task-id_2026041220074...,LLM Generates an text for \nsystem prompt: You...
1,ChatBS-NexGen:Generative_Task-id_2026041220074...,Extracts important entities for \ntext: Before...
2,ChatBS-NexGen:Generative_Task-information_extr...,Generates the Information Extractor Function u...
3,ChatBS-NexGen:Generative_Task-query_result_pos...,Generates the post processing Function using L...
4,ChatBS-NexGen:Generative_Task-system_prompt_ge...,Generates the System Prompt Template using Lar...

In [6]:
answer3 = """
The ChatBS System utilizes LLMs to generate the following functions

1. Information extraction function
2. System Prompt template function
3. Sparql result post processing function

and further it's used within functions to
1. Generate the LLM outputs,
2. Used to extract key information from the system.
"""

gt_list.append(
    GT(
        question=question3,
        answer=answer3,
        sparql_querys=[SPARQLTemplate(template=question_sparql3, description="")],
        entities=entities3.to_dict(orient="records"),
        qtype=["multi", "entity"],
    )
)

In [7]:
# Question 4
question4 = """
What are the extracted KG entities for the execution with id 1_1
"""
question_sparql4 = """
SELECT DISTINCT ?member ?prop ?value
WHERE {
     ?obj dc:description ?desc .
     FILTER(REGEX(?desc, "SPARQL queries to extract information", "i"))

     ?obj a provone:Program .
     ?exe prov:qualifiedAssociation/prov:hadPlan ?obj .
     ?exe dcterms:identifier ?id .
     FILTER(REGEX(?id, "1_1", "i"))

     ?data prov:wasGeneratedBy ?exe .
     ?data a ?class .

     {
         ?data a provone:Collection .
         ?data provone:hadMember ?member .
         ?member ?prop ?value .
     }
     UNION
     {
         ?data a provone:Data .
         BIND(?data AS ?member)
         ?data ?prop ?value .
     }
}
"""

entities4 = graph_manager.query(question_sparql4, resolve_curie=True)
entities4

,member,prop,value
0,ChatBS-NexGen:Data-id_20260412200743_406-kg_info,DFColumn:sugarG,NA@en^^<xsd:string>
1,ChatBS-NexGen:Data-id_20260412200743_406-kg_info,rdfs:label,row_1@en^^<xsd:string>
2,ChatBS-NexGen:Data-id_20260412200743_720-kg_info,DFColumn:sugarG,@en^^<xsd:string>
3,ChatBS-NexGen:Data-id_20260412200743_720-kg_info,DFColumn:ingredientCat,@en^^<xsd:string>
4,ChatBS-NexGen:Data-id_20260412200743_406-kg_info,DFColumn:ingredientCat,NA@en^^<xsd:string>
...,...,...,...
168,ChatBS-NexGen:Data-id_20260412200742_324-extracts,prov:wasGeneratedBy,ChatBS-NexGen:id_20260412200745_473
169,ChatBS-NexGen:Data-id_20260412200742_324-extracts,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,provone:Data
170,ChatBS-NexGen:Data-id_20260412200742_324-extracts,rdfs:label,extracts@en^^<xsd:string>
171,ChatBS-NexGen:Data-id_20260412200742_324-extracts,prov:value,Lettuce@en^^<xsd:string>
172,ChatBS-NexGen:Data-id_20260412200742_324-extracts,prov:wasGeneratedBy,ChatBS-NexGen:id_20260412200742_397

In [8]:
pentities4 = set(
    entities4.loc[entities4["prop"] == "DFColumn:ingredientName", "value"]
    .apply(lambda x: x.split("@")[0])
    .tolist()
) - {"", "NA"}

answer4 = """
The retrieved entities from the knowledge graph includes the following ingredients,

1. Yogurt
2. Berry
3. Cheese
4. Carrot
5. Turkey
6. Bell pepper
7. Hummus
8. Almond
9. Avocado
10. Pumpkin seed
11. Water
12. Pineapple
13. Cottage cheese
"""

gt_list.append(
    GT(
        question=question4,
        answer=answer4,
        sparql_querys=[SPARQLTemplate(template=question_sparql4, description="")],
        entities=list(pentities4),
        qtype=["multi", "literal"]
    )
)

In [9]:
# Question 5
question5 = """
why did some ingredients have missing values for `sugarG` and `ingredientCat` columns in the final output of the workflow?
"""
question_sparql5 = """
SELECT DISTINCT ?member ?prop ?value
WHERE {
     ?obj dc:description ?desc .
     FILTER(REGEX(?desc, "SPARQL queries to extract information", "i"))

     ?obj a provone:Program .
     ?exe prov:qualifiedAssociation/prov:hadPlan ?obj .
     ?exe dcterms:identifier ?id .
     FILTER(REGEX(?id, "1_1", "i"))

     ?data prov:wasGeneratedBy ?exe .
     ?data a ?class .

     {
         ?data a provone:Collection .
         ?data provone:hadMember ?member .
         ?member ?prop ?value .
     }
     UNION
     {
         ?data a provone:Data .
         BIND(?data AS ?member)
         ?data ?prop ?value .
     }
}

order by ?member ?prop
"""

entities5 = graph_manager.query(question_sparql5, resolve_curie=True)
entities5

,member,prop,value
0,ChatBS-NexGen:Data-id_20260412200742_128-extracts,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,provone:Data
1,ChatBS-NexGen:Data-id_20260412200742_128-extracts,rdfs:label,extracts@en^^<xsd:string>
2,ChatBS-NexGen:Data-id_20260412200742_128-extracts,prov:value,Berry@en^^<xsd:string>
3,ChatBS-NexGen:Data-id_20260412200742_128-extracts,prov:wasGeneratedBy,ChatBS-NexGen:id_20260412200743_952
4,ChatBS-NexGen:Data-id_20260412200742_128-extracts,prov:wasGeneratedBy,ChatBS-NexGen:id_20260412200742_397
...,...,...,...
168,ChatBS-NexGen:Data-id_20260412200745_516-kg_info,DFColumn:ingredientName,@en^^<xsd:string>
169,ChatBS-NexGen:Data-id_20260412200745_516-kg_info,DFColumn:sugarG,@en^^<xsd:string>
170,ChatBS-NexGen:Data-id_20260412200745_516-kg_info,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,provone:Data
171,ChatBS-NexGen:Data-id_20260412200745_516-kg_info,rdfs:label,row_0@en^^<xsd:string>
172,ChatBS-NexGen:Data-id_20260412200745_516-kg_info,prov:wasGeneratedBy,ChatBS-NexGen:id_20260412200745_467

In [10]:
na_entities = entities5.loc[
    entities5["value"].isin(["@en^^<xsd:string>", "NA@en^^<xsd:string>"]),
    "member",
].unique().tolist()
pentities5 = set(
    entities5.loc[
        entities5["member"].isin(na_entities)
        & (entities5["prop"] == "DFColumn:ingredientName"),
        "value",
    ]
    .apply(lambda x: x.split("@")[0])
    .tolist()
) - {"", "NA"}

answer5 = """
Due to the fact that some information is not available in the knowledge graph for ingredients such as
'Turkey', 'Hummus', 'Cheese', 'Cottage cheese', 'Berry', 'Water' the sugarG and ingredientCat is not available.
"""

gt_list.append(
    GT(
        question=question5,
        answer=answer5,
        sparql_querys=[SPARQLTemplate(template=question_sparql5, description="")],
        entities=list(pentities5),
        qtype=["multi", "literal"]
    )
)

In [11]:
# Question MULT 1: instructions for function generation.


template_spec = [{
    "func_desc":"sparql query post processing"
}, {
    "func_desc": "system prompt template"
}, {
    "func_desc": "information extraction"
}]

sparql_spec = [{
    "func_desc_term":"Post-processes the query results"
},{
    "func_desc_term":"Generates a system prompt"
},{
    "func_desc_term":"Extracts entities or relevant information"
},]

question_template = """
what are the instructions used by the LLM to generate the {func_desc} function step in the pipeline?
"""
sparql_template = """
SELECT distinct ?obj ?llm ?inpd
WHERE {
     ?obj dc:description ?desc .
     ?obj a ?class .
     FILTER(REGEX(?desc, "{func_desc_term}","i"))

     ?llm_out sio:SIO_000202 ?obj .
     ?llm_out sio:SIO_000232 ?llm .
     ?llm sio:SIO_000230 ?inp .
     ?inp prov:value ?inpd
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    We utilize the following input instructions to generate the function responsible for {func_desc}.

    {answer_inst}
    """
    
    
    _ent = entities[['obj', 'inpd']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "obj": "Funtion",
            "inpd": "Instruction for function generation"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    gt.qtype = ["multi", "entity", "literal"]
gt_list.extend(gts)

ic| rquestion: '''
                what are the instructions used by the LLM to generate the sparql query post processing function step in the pipeline?
                '''
ic| entities:                                                  obj  \
              0  http://testwebsite/testProgram#query_result_po...
              1  http://testwebsite/testProgram#query_result_po...

                                                               llm  \
              0  http://testwebsite/testProgram#LLM-query_resul...
              1  http://testwebsite/testProgram#LLM-query_resul...

                                                              inpd
              0  Concat all the rows into single row at each co...
              1  If there are duplicate ingredients then select...
ic| answer: GTAnswer(answer_nlp="
                We utilize the following input instructions to generate the function responsible for sparql query post processing.

                Funtion | Instruction for function generation
            http://testwebsite/testProgram#query_result_post_processor | Concat all the rows into single row at each column by '|' concatenation marker.@en^^<xsd:string>
            http://testwebsite/testProgram#query_result_post_processor | If there are duplicate ingredients then select row with most information on `sugarG` and `ingredientCat` columns. Fill all the missing values with '0' in `sugarG` column and with '-' in 'ingredientCat` column.@en^^<xsd:string>
                ", entities=[{'obj': 'http://testwebsite/testProgram#query_result_post_processor', 'inpd': "Concat all the rows into single row at each column by '|' concatenation marker.@en^^<xsd:string>"}, {'obj': 'http://testwebsite/testProgram#query_result_post_processor', 'inpd': "If there are duplicate ingredients then select row with most information on `sugarG` and `ingredientCat` columns. Fill all the missing values with '0' in `sugarG` column and with '-' in 'ingredientCat` column.@en^^<xsd:string>"}])
ic| rquestion: '''
                what are the instructions used by the LLM to generate the system prompt template function step in the pipeline?
                '''
ic| entities:                                                  obj  \
              0  http://testwebsite/testProgram#system_prompt_g...
              1  http://testwebsite/testProgram#system_prompt_g...

                                                               llm  \
              0  http://testwebsite/testProgram#LLM-system_prom...
              1  http://testwebsite/testProgram#LLM-system_prom...

                                                             inpd
              0  You are a health care assistant@en^^<xsd:string>
              1                           gpt-4o@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                We utilize the following input instructions to generate the function responsible for system prompt template.

                Funtion | Instruction for function generation
            http://testwebsite/testProgram#system_prompt_generator | You are a health care assistant@en^^<xsd:string>
            http://testwebsite/testProgram#system_prompt_generator | gpt-4o@en^^<xsd:string>
                ', entities=[{'obj': 'http://testwebsite/testProgram#system_prompt_generator', 'inpd': 'You are a health care assistant@en^^<xsd:string>'}, {'obj': 'http://testwebsite/testProgram#system_prompt_generator', 'inpd': 'gpt-4o@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the instructions used by the LLM to generate the information extraction function step in the pipeline?
                '''
ic| entities:                                                  obj  \
              0  http://testwebsite/testProgram#information_ext...
              1  http://testwebsite/testProgram#information_ext...

                                                               llm  \
              0  http://testwebsite/testProgram#LLM-information...
              1  http://testwebsite/testProgram#LLM-information...

                                                              inpd
              0                            gpt-4o@en^^<xsd:string>
              1  Extract all the main ingredients without any s...
ic| answer: GTAnswer(answer_nlp="
                We utilize the following input instructions to generate the function responsible for information extraction.

                Funtion | Instruction for function generation
            http://testwebsite/testProgram#information_extractor | gpt-4o@en^^<xsd:string>
            http://testwebsite/testProgram#information_extractor | Extract all the main ingredients without any subsidiary; return in singular noun form and First letter capital. Extract mean and dairy product in its' base form. (e.g., from 'egg white' extract 'Egg')@en^^<xsd:string>
                ", entities=[{'obj': 'http://testwebsite/testProgram#information_extractor', 'inpd': 'gpt-4o@en^^<xsd:string>'}, {'obj': 'http://testwebsite/testProgram#information_extractor', 'inpd': "Extract all the main ingredients without any subsidiary; return in singular noun form and First letter capital. Extract mean and dairy product in its' base form. (e.g., from 'egg white' extract 'Egg')@en^^<xsd:string>"}])

In [12]:
# Question MULT 2: input ports of the functions


template_spec = [{
    "func_desc":"sparql query post processing"
}, {
    "func_desc": "system prompt template"
}, {
    "func_desc": "information extraction"
}, {
    "func_desc": "sparql query function"
}, {
    "func_desc": "llm chat function"
}]

sparql_spec = [{
    "func_desc_term":"Post-processes the query results"
},{
    "func_desc_term":"Generates a system prompt"
},{
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc_term": "Builds SPARQL"
}, {
    "func_desc_term": "Chat with"
}]

question_template = """
what are the input parameters of the function used in {func_desc} step in the pipeline?
"""
sparql_template = """
SELECT distinct ?flbl ?lbl
WHERE {
     ?obj dc:description ?desc .
     ?obj rdfs:label ?flbl . 
     ?obj a ?class .
     FILTER(REGEX(?desc, "{func_desc_term}","i"))

     ?obj provone:hasInPort ?port .
     ?port rdfs:label ?lbl .
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The input parameters to {func_desc} function.

    {answer_inst}
    """
    
    _ent = entities[['flbl', 'lbl']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "flbl": "Funtion name",
            "lbl": "Function returns"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )


for gt in gts:
    gt.qtype = ["multi", "literal"]
gt_list.extend(gts)

ic| rquestion: '''
                what are the input parameters of the function used in sparql query post processing step in the pipeline?
                '''
ic| entities:                                            flbl  \
              0  Query Result Post-Processor@en^^<xsd:string>

                                                               lbl
              0  Post-processing input port: kg_knowledge@en^^<...
ic| answer: GTAnswer(answer_nlp='
                The input parameters to sparql query post processing function.

                Funtion name | Function returns
            Query Result Post-Processor@en^^<xsd:string> | Post-processing input port: kg_knowledge@en^^<xsd:string>
                ', entities=[{'flbl': 'Query Result Post-Processor@en^^<xsd:string>', 'lbl': 'Post-processing input port: kg_knowledge@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the input parameters of the function used in system prompt template step in the pipeline?
                '''
ic| entities:                                                 flbl  \
              0  System Prompt Template Generator@en^^<xsd:string>
              1  System Prompt Template Generator@en^^<xsd:string>
              2  System Prompt Template Generator@en^^<xsd:string>
              3  System Prompt Template Generator@en^^<xsd:string>
              4  System Prompt Template Generator@en^^<xsd:string>
              5  System Prompt Template Generator@en^^<xsd:string>
              6  System Prompt Template Generator@en^^<xsd:string>
              7  System Prompt Template Generator@en^^<xsd:string>

                                                             lbl
              0              Input port for age@en^^<xsd:string>
              1        Input port for allergies@en^^<xsd:string>
              2    Input port for bodyMassIndex@en^^<xsd:string>
              3        Input port for diagnosis@en^^<xsd:string>
              4  Input port for foodPreferences@en^^<xsd:string>
              5           Input port for gender@en^^<xsd:string>
              6           Input port for height@en^^<xsd:string>
              7           Input port for weight@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The input parameters to system prompt template function.

                Funtion name | Function returns
            System Prompt Template Generator@en^^<xsd:string> | Input port for age@en^^<xsd:string>
            System Prompt Template Generator@en^^<xsd:string> | Input port for allergies@en^^<xsd:string>
            System Prompt Template Generator@en^^<xsd:string> | Input port for bodyMassIndex@en^^<xsd:string>
            System Prompt Template Generator@en^^<xsd:string> | Input port for diagnosis@en^^<xsd:string>
            System Prompt Template Generator@en^^<xsd:string> | Input port for foodPreferences@en^^<xsd:string>
            System Prompt Template Generator@en^^<xsd:string> | Input port for gender@en^^<xsd:string>
            System Prompt Template Generator@en^^<xsd:string> | Input port for height@en^^<xsd:string>
            System Prompt Template Generator@en^^<xsd:string> | Input port for weight@en^^<xsd:string>
                ', entities=[{'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for age@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for allergies@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for bodyMassIndex@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for diagnosis@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for foodPreferences@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for gender@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for height@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for weight@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the input parameters of the function used in information extraction step in the pipeline?
                '''
ic| entities:                                      flbl  \
              0  Information Extractor@en^^<xsd:string>

                                                  lbl
              0  Input port for text@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The input parameters to information extraction function.

                Funtion name | Function returns
            Information Extractor@en^^<xsd:string> | Input port for text@en^^<xsd:string>
                ', entities=[{'flbl': 'Information Extractor@en^^<xsd:string>', 'lbl': 'Input port for text@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the input parameters of the function used in sparql query function step in the pipeline?
                '''
ic| entities:                                     flbl  \
              0  SPARQL Query Builder@en^^<xsd:string>

                                                    lbl
              0  Input port for entity@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The input parameters to sparql query function function.

                Funtion name | Function returns
            SPARQL Query Builder@en^^<xsd:string> | Input port for entity@en^^<xsd:string>
                ', entities=[{'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'lbl': 'Input port for entity@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the input parameters of the function used in llm chat function step in the pipeline?
                '''
ic| entities:                         flbl  \
              0  LLM Chat@en^^<xsd:string>
              1  LLM Chat@en^^<xsd:string>

                                                               lbl
              0  LLM Chat input port: system_prompt@en^^<xsd:st...
              1  LLM Chat input port: user_prompt@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The input parameters to llm chat function function.

                Funtion name | Function returns
            LLM Chat@en^^<xsd:string> | LLM Chat input port: system_prompt@en^^<xsd:string>
            LLM Chat@en^^<xsd:string> | LLM Chat input port: user_prompt@en^^<xsd:string>
                ', entities=[{'flbl': 'LLM Chat@en^^<xsd:string>', 'lbl': 'LLM Chat input port: system_prompt@en^^<xsd:string>'}, {'flbl': 'LLM Chat@en^^<xsd:string>', 'lbl': 'LLM Chat input port: user_prompt@en^^<xsd:string>'}])

In [13]:
# Question MULT 3 : output ports of functions


template_spec = [{
    "func_desc":"sparql query post processing"
}, {
    "func_desc": "system prompt template"
}, {
    "func_desc": "information extraction"
}, {
    "func_desc": "sparql query function"
}, {
    "func_desc": "llm chat function"
}]

sparql_spec = [{
    "func_desc_term":"Post-processes the query results"
},{
    "func_desc_term":"Generates a system prompt"
},{
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc_term": "Builds SPARQL queries to extract"
}, {
    "func_desc_term": "Chat with the LLM"
}]

question_template = """
what are the input parameters of the function used in {func_desc} step in the pipeline?
"""
sparql_template = """
SELECT distinct ?flbl ?lbl
WHERE {
     ?obj dc:description ?desc .
     ?obj rdfs:label ?flbl . 
     ?obj a ?class .
     FILTER(REGEX(?desc, "{func_desc_term}","i"))

     ?obj provone:hasOutPort ?port .
     ?port rdfs:label ?lbl .
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The input parameters to {func_desc} function.

    {answer_inst}
    """
    
    _ent = entities[['flbl', 'lbl']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "flbl": "Funtion name",
            "lbl": "Function returns"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    gt.qtype = ["multi", "literal"]
gt_list.extend(gts)

ic| rquestion: '''
                what are the input parameters of the function used in sparql query post processing step in the pipeline?
                '''
ic| entities:                                            flbl  \
              0  Query Result Post-Processor@en^^<xsd:string>

                                                               lbl
              0  Post-processed output port: post_processed_out...
ic| answer: GTAnswer(answer_nlp='
                The input parameters to sparql query post processing function.

                Funtion name | Function returns
            Query Result Post-Processor@en^^<xsd:string> | Post-processed output port: post_processed_output@en^^<xsd:string>
                ', entities=[{'flbl': 'Query Result Post-Processor@en^^<xsd:string>', 'lbl': 'Post-processed output port: post_processed_output@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the input parameters of the function used in system prompt template step in the pipeline?
                '''
ic| entities:                                                 flbl  \
              0  System Prompt Template Generator@en^^<xsd:string>

                                            lbl
              0  System Prompt@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The input parameters to system prompt template function.

                Funtion name | Function returns
            System Prompt Template Generator@en^^<xsd:string> | System Prompt@en^^<xsd:string>
                ', entities=[{'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'System Prompt@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the input parameters of the function used in information extraction step in the pipeline?
                '''
ic| entities:                                      flbl                                  lbl
              0  Information Extractor@en^^<xsd:string>  Extracted Entities@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The input parameters to information extraction function.

                Funtion name | Function returns
            Information Extractor@en^^<xsd:string> | Extracted Entities@en^^<xsd:string>
                ', entities=[{'flbl': 'Information Extractor@en^^<xsd:string>', 'lbl': 'Extracted Entities@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the input parameters of the function used in sparql query function step in the pipeline?
                '''
ic| entities:                                     flbl  \
              0  SPARQL Query Builder@en^^<xsd:string>

                                                      lbl
              0  Output port for kg_info@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The input parameters to sparql query function function.

                Funtion name | Function returns
            SPARQL Query Builder@en^^<xsd:string> | Output port for kg_info@en^^<xsd:string>
                ', entities=[{'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'lbl': 'Output port for kg_info@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the input parameters of the function used in llm chat function step in the pipeline?
                '''
ic| entities:                         flbl  \
              0  LLM Chat@en^^<xsd:string>

                                                               lbl
              0  LLM Chat output port: generated_answer@en^^<xs...
ic| answer: GTAnswer(answer_nlp='
                The input parameters to llm chat function function.

                Funtion name | Function returns
            LLM Chat@en^^<xsd:string> | LLM Chat output port: generated_answer@en^^<xsd:string>
                ', entities=[{'flbl': 'LLM Chat@en^^<xsd:string>', 'lbl': 'LLM Chat output port: generated_answer@en^^<xsd:string>'}])

In [14]:
# Question MULT 4 : connected functions


template_spec = [{
    "func_desc":"sparql query post processing"
}, {
    "func_desc": "system prompt template"
}, {
    "func_desc": "information extraction"
}, {
    "func_desc": "sparql query function"
}, {
    "func_desc": "llm chat function"
}]

sparql_spec = [{
    "func_desc_term":"Post-processes the query results"
},{
    "func_desc_term":"Generates a system prompt"
},{
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc_term": "Builds SPARQL queries to extract"
}, {
    "func_desc_term": "Chat with the LLM"
}]

question_template = """
what are the connected functions to the function used in {func_desc} step in the pipeline?
"""
sparql_template = """

SELECT DISTINCT ?fn2 ?fn2lbl
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl . 
    ?obj a ?class .
    FILTER(REGEX(?desc, "{func_desc_term}","i"))

    ?obj (provone:hasInPort | provone:hasOutPort) ?port .
    ?port provone:connectsTo ?channel .
    ?portt provone:connectsTo ?channel .
    ?fn2 (provone:hasInPort | provone:hasOutPort) ?portt .
    FILTER(?obj != ?fn2)
    
    ?fn2 rdfs:label ?fn2lbl .
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The connected functions to {func_desc} function.

    {answer_inst}
    """
    
    _ent = entities[['fn2', 'fn2lbl']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "fn2": "Funtion URI",
            "fn2lbl": "Function name"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    gt.qtype = ["multi", "literal", "entity"]
gt_list.extend(gts)

ic| rquestion: '''
                what are the connected functions to the function used in sparql query post processing step in the pipeline?
                '''
ic| entities:                                                  fn2  \
              0  http://testwebsite/testProgram#batch_sparql_qu...

                                                        fn2lbl
              0  Batch SPARQL Query Extractor@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The connected functions to sparql query post processing function.

                Funtion URI | Function name
            http://testwebsite/testProgram#batch_sparql_query_extractor | Batch SPARQL Query Extractor@en^^<xsd:string>
                ', entities=[{'fn2': 'http://testwebsite/testProgram#batch_sparql_query_extractor', 'fn2lbl': 'Batch SPARQL Query Extractor@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the connected functions to the function used in system prompt template step in the pipeline?
                '''
ic| entities:                                        fn2                     fn2lbl
              0  http://testwebsite/testProgram#llm_chat  LLM Chat@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The connected functions to system prompt template function.

                Funtion URI | Function name
            http://testwebsite/testProgram#llm_chat | LLM Chat@en^^<xsd:string>
                ', entities=[{'fn2': 'http://testwebsite/testProgram#llm_chat', 'fn2lbl': 'LLM Chat@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the connected functions to the function used in information extraction step in the pipeline?
                '''
ic| entities:                                                  fn2  \
              0            http://testwebsite/testProgram#llm_chat
              1  http://testwebsite/testProgram#batch_sparql_qu...

                                                        fn2lbl
              0                      LLM Chat@en^^<xsd:string>
              1  Batch SPARQL Query Extractor@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The connected functions to information extraction function.

                Funtion URI | Function name
            http://testwebsite/testProgram#llm_chat | LLM Chat@en^^<xsd:string>
            http://testwebsite/testProgram#batch_sparql_query_extractor | Batch SPARQL Query Extractor@en^^<xsd:string>
                ', entities=[{'fn2': 'http://testwebsite/testProgram#llm_chat', 'fn2lbl': 'LLM Chat@en^^<xsd:string>'}, {'fn2': 'http://testwebsite/testProgram#batch_sparql_query_extractor', 'fn2lbl': 'Batch SPARQL Query Extractor@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the connected functions to the function used in sparql query function step in the pipeline?
                '''
ic| entities: Empty DataFrame
              Columns: [fn2, fn2lbl]
              Index: []
ic| answer: GTAnswer(answer_nlp='
                The connected functions to sparql query function function.

                Funtion URI | Function name
                ', entities=[])
ic| rquestion: '''
                what are the connected functions to the function used in llm chat function step in the pipeline?
                '''
ic| entities:                                                  fn2  \
              0  http://testwebsite/testProgram#system_prompt_g...
              1  http://testwebsite/testProgram#information_ext...

                                                            fn2lbl
              0  System Prompt Template Generator@en^^<xsd:string>
              1             Information Extractor@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The connected functions to llm chat function function.

                Funtion URI | Function name
            http://testwebsite/testProgram#system_prompt_generator | System Prompt Template Generator@en^^<xsd:string>
            http://testwebsite/testProgram#information_extractor | Information Extractor@en^^<xsd:string>
                ', entities=[{'fn2': 'http://testwebsite/testProgram#system_prompt_generator', 'fn2lbl': 'System Prompt Template Generator@en^^<xsd:string>'}, {'fn2': 'http://testwebsite/testProgram#information_extractor', 'fn2lbl': 'Information Extractor@en^^<xsd:string>'}])

In [15]:
# Question MULT 5 : number of execution of the functions


template_spec = [{
    "func_desc":"sparql query post processing"
}, {
    "func_desc": "system prompt template"
}, {
    "func_desc": "information extraction"
}, {
    "func_desc": "sparql query function"
}, {
    "func_desc": "llm chat function"
}]

sparql_spec = [{
    "func_desc_term":"Post-processes the query results"
},{
    "func_desc_term":"Generates a system prompt"
},{
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc_term": "Builds SPARQL queries to extract"
}, {
    "func_desc_term": "Chat with the LLM"
}]

question_template = """
what are the executions of the {func_desc} step in the pipeline?
"""
sparql_template = """

SELECT DISTINCT ?exe
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl . 
    ?obj a ?class .
    FILTER(REGEX(?desc, "{func_desc_term}","i"))

    ?asso prov:hadPlan ?obj .
    ?exe prov:qualifiedAssociation ?asso .
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The executions of the  {func_desc} function are.

    {answer_inst}
    """
    
    _ent = entities[['exe']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "exe": "Executions"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    gt.qtype = ["multi", "entity"]
gt_list.extend(gts)

ic| rquestion: '''
                what are the executions of the sparql query post processing step in the pipeline?
                '''
ic| entities:                                                  exe
              0  http://testwebsite/testProgram#id_202604122007...
ic| answer: GTAnswer(answer_nlp='
                The executions of the  sparql query post processing function are.

                Executions
            http://testwebsite/testProgram#id_20260412200745_507
                ', entities=[{'exe': 'http://testwebsite/testProgram#id_20260412200745_507'}])
ic| rquestion: '''
                what are the executions of the system prompt template step in the pipeline?
                '''
ic| entities:                                                  exe
              0  http://testwebsite/testProgram#id_202604122007...
ic| answer: GTAnswer(answer_nlp='
                The executions of the  system prompt template function are.

                Executions
            http://testwebsite/testProgram#id_20260412200734_778
                ', entities=[{'exe': 'http://testwebsite/testProgram#id_20260412200734_778'}])
ic| rquestion: '''
                what are the executions of the information extraction step in the pipeline?
                '''
ic| entities:                                                  exe
              0  http://testwebsite/testProgram#id_202604122007...
ic| answer: GTAnswer(answer_nlp='
                The executions of the  information extraction function are.

                Executions
            http://testwebsite/testProgram#id_20260412200742_397
                ', entities=[{'exe': 'http://testwebsite/testProgram#id_20260412200742_397'}])
ic| rquestion: '''
                what are the executions of the sparql query function step in the pipeline?
                '''
ic| entities:                                                   exe
              0   http://testwebsite/testProgram#id_202604122007...
              1   http://testwebsite/testProgram#id_202604122007...
              2   http://testwebsite/testProgram#id_202604122007...
              3   http://testwebsite/testProgram#id_202604122007...
              4   http://testwebsite/testProgram#id_202604122007...
              5   http://testwebsite/testProgram#id_202604122007...
              6   http://testwebsite/testProgram#id_202604122007...
              7   http://testwebsite/testProgram#id_202604122007...
              8   http://testwebsite/testProgram#id_202604122007...
              9   http://testwebsite/testProgram#id_202604122007...
              10  http://testwebsite/testProgram#id_202604122007...
              11  http://testwebsite/testProgram#id_202604122007...
              12  http://testwebsite/testProgram#id_202604122007...
ic| answer: GTAnswer(answer_nlp='
                The executions of the  sparql query function function are.

                Executions
            http://testwebsite/testProgram#id_20260412200743_103
            http://testwebsite/testProgram#id_20260412200743_290
            http://testwebsite/testProgram#id_20260412200743_818
            http://testwebsite/testProgram#id_20260412200743_952
            http://testwebsite/testProgram#id_20260412200744_221
            http://testwebsite/testProgram#id_20260412200744_387
            http://testwebsite/testProgram#id_20260412200744_460
            http://testwebsite/testProgram#id_20260412200744_624
            http://testwebsite/testProgram#id_20260412200744_720
            http://testwebsite/testProgram#id_20260412200744_854
            http://testwebsite/testProgram#id_20260412200744_909
            http://testwebsite/testProgram#id_20260412200745_467
            http://testwebsite/testProgram#id_20260412200745_473
                ', entities=[{'exe': 'http://testwebsite/testProgram#id_20260412200743_103'}, {'exe': 'http://testwebsite/testProgram#id_20260412200743_290'}, {'exe': 'http://testwebsite/testProgram#id_20260412200743_818'}, {'exe': 'http://testwebsite/testProgram#id_20260412200743_952'}, {'exe': 'http://testwebsite/testProgram#id_20260412200744_221'}, {'exe': 'http://testwebsite/testProgram#id_20260412200744_387'}, {'exe': 'http://testwebsite/testProgram#id_20260412200744_460'}, {'exe': 'http://testwebsite/testProgram#id_20260412200744_624'}, {'exe': 'http://testwebsite/testProgram#id_20260412200744_720'}, {'exe': 'http://testwebsite/testProgram#id_20260412200744_854'}, {'exe': 'http://testwebsite/testProgram#id_20260412200744_909'}, {'exe': 'http://testwebsite/testProgram#id_20260412200745_467'}, {'exe': 'http://testwebsite/testProgram#id_20260412200745_473'}])
ic| rquestion: '''
                what are the executions of the llm chat function step in the pipeline?
                '''
ic| entities:                                                  exe
              0  http://testwebsite/testProgram#id_202604122007...
ic| answer: GTAnswer(answer_nlp='
                The executions of the  llm chat function function are.

                Executions
            http://testwebsite/testProgram#id_20260412200740_99
                ', entities=[{'exe': 'http://testwebsite/testProgram#id_20260412200740_99'}])

In [16]:
# Question MULT 6 : who was the agent that ran the functions 


template_spec = [{
    "func_desc":"sparql query post processing"
}, {
    "func_desc": "system prompt template"
}, {
    "func_desc": "information extraction"
}, {
    "func_desc": "sparql query function"
}, {
    "func_desc": "llm chat function"
}]

sparql_spec = [{
    "func_desc_term":"Post-processes the query results"
},{
    "func_desc_term":"Generates a system prompt"
},{
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc_term": "Builds SPARQL queries to extract"
}, {
    "func_desc_term": "Chat with the LLM"
}]

question_template = """
who were the agents that ran the {func_desc} step in the pipeline?
"""
sparql_template = """

SELECT DISTINCT ?agent ?albl
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl . 
    ?obj a ?class .
    FILTER(REGEX(?desc, "{func_desc_term}","i"))

    ?asso prov:hadPlan ?obj .
    ?asso prov:agent ?agent .
    ?agent rdfs:label ?albl
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The executions of the  {func_desc} function are.

    {answer_inst}
    """
    
    _ent = entities[['albl']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "albl": "Agents"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    gt.qtype = ["multi", "entity", "literal"]
gt_list.extend(gts)

ic| rquestion: '''
                who were the agents that ran the sparql query post processing step in the pipeline?
                '''
ic| entities:                                       agent       albl
              0  http://testwebsite/testProgram#test_user  Test User
ic| answer: GTAnswer(answer_nlp='
                The executions of the  sparql query post processing function are.

                Agents
            Test User
                ', entities=[{'albl': 'Test User'}])
ic| rquestion: '''
                who were the agents that ran the system prompt template step in the pipeline?
                '''
ic| entities:                                       agent       albl
              0  http://testwebsite/testProgram#test_user  Test User
ic| answer: GTAnswer(answer_nlp='
                The executions of the  system prompt template function are.

                Agents
            Test User
                ', entities=[{'albl': 'Test User'}])
ic| rquestion: '''
                who were the agents that ran the information extraction step in the pipeline?
                '''
ic| entities:                                       agent       albl
              0  http://testwebsite/testProgram#test_user  Test User
ic| answer: GTAnswer(answer_nlp='
                The executions of the  information extraction function are.

                Agents
            Test User
                ', entities=[{'albl': 'Test User'}])
ic| rquestion: '''
                who were the agents that ran the sparql query function step in the pipeline?
                '''
ic| entities:                                       agent       albl
              0  http://testwebsite/testProgram#test_user  Test User
ic| answer: GTAnswer(answer_nlp='
                The executions of the  sparql query function function are.

                Agents
            Test User
                ', entities=[{'albl': 'Test User'}])
ic| rquestion: '''
                who were the agents that ran the llm chat function step in the pipeline?
                '''
ic| entities:                                       agent       albl
              0  http://testwebsite/testProgram#test_user  Test User
ic| answer: GTAnswer(answer_nlp='
                The executions of the  llm chat function function are.

                Agents
            Test User
                ', entities=[{'albl': 'Test User'}])

In [17]:
# Question MULT 7 : Is the function made by a Generative Task  


template_spec = [{
    "func_desc":"sparql query post processing"
}, {
    "func_desc": "system prompt template"
}, {
    "func_desc": "information extraction"
}, {
    "func_desc": "sparql query function"
}, {
    "func_desc": "llm chat function"
}]

sparql_spec = [{
    "func_desc_term":"Post-processes the query results"
},{
    "func_desc_term":"Generates a system prompt"
},{
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc_term": "Builds SPARQL queries to extract"
}, {
    "func_desc_term": "Chat with the LLM"
}]

question_template = """
Is the {func_desc} function made by a Generative Task using AI?
"""

sparql_template = """
SELECT DISTINCT ?fnlbl ?llm_gen_out
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?fnlbl .
    FILTER(REGEX(?desc, "{func_desc_term}", "i"))

    OPTIONAL {
        ?llm_out sio:SIO_000202 ?obj .
        ?llm_out sio:SIO_000232 ?llm .
        ?llm_gen prov:used ?llm .
    }

    BIND(COALESCE(?llm_gen, "None") AS ?llm_gen_out)
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The {func_desc} function {decision} by a Generative Task.

    {answer_inst}
    """
    
    _ent = entities[['fnlbl', 'llm_gen_out']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "obj": "Function",
            'llm_gen_out': "Generative Task used to generate function"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent,
        decision = "is made" if _ent['llm_gen_out'].tolist()[0] != "None" else "is not made"
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    gt.qtype = ["single", "bool"]
    gt.decision = gt.entities[0]['llm_gen_out'] != "None"
gt_list.extend(gts)

ic| rquestion: '''
                Is the sparql query post processing function made by a Generative Task using AI?
                '''
ic| entities:                                           fnlbl  \
              0  Query Result Post-Processor@en^^<xsd:string>

                                                       llm_gen_out
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The sparql query post processing function is made by a Generative Task.

                fnlbl | Generative Task used to generate function
            Query Result Post-Processor@en^^<xsd:string> | http://testwebsite/testProgram#Generative_Task-query_result_post_processor
                ', entities=[{'fnlbl': 'Query Result Post-Processor@en^^<xsd:string>', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-query_result_post_processor'}])
ic| rquestion: '''
                Is the system prompt template function made by a Generative Task using AI?
                '''
ic| entities:                                                fnlbl  \
              0  System Prompt Template Generator@en^^<xsd:string>

                                                       llm_gen_out
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The system prompt template function is made by a Generative Task.

                fnlbl | Generative Task used to generate function
            System Prompt Template Generator@en^^<xsd:string> | http://testwebsite/testProgram#Generative_Task-system_prompt_generator
                ', entities=[{'fnlbl': 'System Prompt Template Generator@en^^<xsd:string>', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-system_prompt_generator'}])
ic| rquestion: '''
                Is the information extraction function made by a Generative Task using AI?
                '''
ic| entities:                                     fnlbl  \
              0  Information Extractor@en^^<xsd:string>

                                                       llm_gen_out
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The information extraction function is made by a Generative Task.

                fnlbl | Generative Task used to generate function
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#Generative_Task-information_extractor
                ', entities=[{'fnlbl': 'Information Extractor@en^^<xsd:string>', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-information_extractor'}])

ic| rquestion: '''
                Is the sparql query function function made by a Generative Task using AI?
                '''
ic| entities:                                    fnlbl llm_gen_out
              0  SPARQL Query Builder@en^^<xsd:string>        None
ic| answer: GTAnswer(answer_nlp='
                The sparql query function function is not made by a Generative Task.

                fnlbl | Generative Task used to generate function
            SPARQL Query Builder@en^^<xsd:string> | None
                ', entities=[{'fnlbl': 'SPARQL Query Builder@en^^<xsd:string>', 'llm_gen_out': 'None'}])
ic| rquestion: '''
                Is the llm chat function function made by a Generative Task using AI?
                '''
ic| entities:                        fnlbl llm_gen_out
              0  LLM Chat@en^^<xsd:string>        None
ic| answer: GTAnswer(answer_nlp='
                The llm chat function function is not made by a Generative Task.

                fnlbl | Generative Task used to generate function
            LLM Chat@en^^<xsd:string> | None
                ', entities=[{'fnlbl': 'LLM Chat@en^^<xsd:string>', 'llm_gen_out': 'None'}])

In [18]:
# Question MULT 8 : Does any of the executions of the function contain a Generative Task  


template_spec = [{
    "func_desc":"sparql query post processing"
}, {
    "func_desc": "system prompt template"
}, {
    "func_desc": "information extraction"
}, {
    "func_desc": "sparql query function"
}, {
    "func_desc": "llm chat function"
}]

sparql_spec = [{
    "func_desc_term":"Post-processes the query results"
},{
    "func_desc_term":"Generates a system prompt"
},{
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc_term": "Builds SPARQL queries to extract"
}, {
    "func_desc_term": "Chat with the LLM"
}]

question_template = """
Does any of the executions of the {func_desc} function made has a Generative Task as a component within?
"""

sparql_template = """
SELECT DISTINCT ?flbl ?exe ?llm_gen_out
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl .
    FILTER(REGEX(?desc, "{func_desc_term}","i"))

    ?asso prov:hadPlan ?obj .
    ?exe prov:qualifiedAssociation ?asso .

    OPTIONAL {
        ?exe sio:SIO_000369 ?llm_gen .
    }

    BIND(COALESCE(?llm_gen, "None") AS ?llm_gen_out)
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    Executions of the {func_desc} function {decision} a Generative Task that utilize an LLM.

    {answer_inst}
    """
    
    _ent = entities[['flbl', 'exe', 'llm_gen_out']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "flbl": "Function",
            'exe': "Execution",
            'llm_gen_out': "Generative Task used within execution"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent,
        decision = "contains" if _ent['llm_gen_out'].tolist()[0] != "None" else "does not contain"
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    gt.qtype = ["single", "bool"]
    gt.decision = gt.entities[0]['llm_gen_out'] != "None"
gt_list.extend(gts)

ic| rquestion: '''
                Does any of the executions of the sparql query post processing function made has a Generative Task as a component within?
                '''
ic| entities:                                            flbl  \
              0  Query Result Post-Processor@en^^<xsd:string>

                                                               exe llm_gen_out
              0  http://testwebsite/testProgram#id_202604122007...        None
ic| answer: GTAnswer(answer_nlp='
                Executions of the sparql query post processing function does not contain a Generative Task that utilize an LLM.

                Function | Execution | Generative Task used within execution
            Query Result Post-Processor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200745_507 | None
                ', entities=[{'flbl': 'Query Result Post-Processor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200745_507', 'llm_gen_out': 'None'}])
ic| rquestion: '''
                Does any of the executions of the system prompt template function made has a Generative Task as a component within?
                '''
ic| entities:                                                 flbl  \
              0  System Prompt Template Generator@en^^<xsd:string>

                                                               exe llm_gen_out
              0  http://testwebsite/testProgram#id_202604122007...        None
ic| answer: GTAnswer(answer_nlp='
                Executions of the system prompt template function does not contain a Generative Task that utilize an LLM.

                Function | Execution | Generative Task used within execution
            System Prompt Template Generator@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200734_778 | None
                ', entities=[{'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200734_778', 'llm_gen_out': 'None'}])
ic| rquestion: '''
                Does any of the executions of the information extraction function made has a Generative Task as a component within?
                '''
ic| entities:                                      flbl  \
              0  Information Extractor@en^^<xsd:string>

                                                               exe  \
              0  http://testwebsite/testProgram#id_202604122007...

                                                       llm_gen_out
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                Executions of the information extraction function contains a Generative Task that utilize an LLM.

                Function | Execution | Generative Task used within execution
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200742_397 | http://testwebsite/testProgram#Generative_Task-id_20260412200742_397
                ', entities=[{'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200742_397', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                Does any of the executions of the sparql query function function made has a Generative Task as a component within?
                '''
ic| entities:                                      flbl  \
              0   SPARQL Query Builder@en^^<xsd:string>
              1   SPARQL Query Builder@en^^<xsd:string>
              2   SPARQL Query Builder@en^^<xsd:string>
              3   SPARQL Query Builder@en^^<xsd:string>
              4   SPARQL Query Builder@en^^<xsd:string>
              5   SPARQL Query Builder@en^^<xsd:string>
              6   SPARQL Query Builder@en^^<xsd:string>
              7   SPARQL Query Builder@en^^<xsd:string>
              8   SPARQL Query Builder@en^^<xsd:string>
              9   SPARQL Query Builder@en^^<xsd:string>
              10  SPARQL Query Builder@en^^<xsd:string>
              11  SPARQL Query Builder@en^^<xsd:string>
              12  SPARQL Query Builder@en^^<xsd:string>

                                                                exe llm_gen_out
              0   http://testwebsite/testProgram#id_202604122007...        None
              1   http://testwebsite/testProgram#id_202604122007...        None
              2   http://testwebsite/testProgram#id_202604122007...        None
              3   http://testwebsite/testProgram#id_202604122007...        None
              4   http://testwebsite/testProgram#id_202604122007...        None
              5   http://testwebsite/testProgram#id_202604122007...        None
              6   http://testwebsite/testProgram#id_202604122007...        None
              7   http://testwebsite/testProgram#id_202604122007...        None
              8   http://testwebsite/testProgram#id_202604122007...        None
              9   http://testwebsite/testProgram#id_202604122007...        None
              10  http://testwebsite/testProgram#id_202604122007...        None
              11  http://testwebsite/testProgram#id_202604122007...        None
              12  http://testwebsite/testProgram#id_202604122007...        None
ic| answer: GTAnswer(answer_nlp='
                Executions of the sparql query function function does not contain a Generative Task that utilize an LLM.

                Function | Execution | Generative Task used within execution
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200743_103 | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200743_290 | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200743_818 | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200743_952 | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200744_221 | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200744_387 | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200744_460 | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200744_624 | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200744_720 | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200744_854 | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200744_909 | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200745_467 | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200745_473 | None
                ', entities=[{'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200743_103', 'llm_gen_out': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200743_290', 'llm_gen_out': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200743_818', 'llm_gen_out': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200743_952', 'llm_gen_out': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200744_221', 'llm_gen_out': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200744_387', 'llm_gen_out': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200744_460', 'llm_gen_out': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200744_624', 'llm_gen_out': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200744_720', 'llm_gen_out': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200744_854', 'llm_gen_out': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200744_909', 'llm_gen_out': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200745_467', 'llm_gen_out': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200745_473', 'llm_gen_out': 'None'}])
ic| rquestion: '''
                Does any of the executions of the llm chat function function made has a Generative Task as a component within?
                '''
ic| entities:                         flbl  \
              0  LLM Chat@en^^<xsd:string>

                                                               exe  \
              0  http://testwebsite/testProgram#id_202604122007...

                                                       llm_gen_out
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                Executions of the llm chat function function contains a Generative Task that utilize an LLM.

                Function | Execution | Generative Task used within execution
            LLM Chat@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200740_99 | http://testwebsite/testProgram#Generative_Task-id_20260412200740_99
                ', entities=[{'flbl': 'LLM Chat@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200740_99', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-id_20260412200740_99'}])

In [19]:
# Question MULT 9 : Does any of the executions of the function contain a Generative Task within and the function itself is generated by an LLM


template_spec = [{
    "func_desc":"sparql query post processing"
}, {
    "func_desc": "system prompt template"
}, {
    "func_desc": "information extraction"
}, {
    "func_desc": "sparql query function"
}, {
    "func_desc": "llm chat function"
}]

sparql_spec = [{
    "func_desc_term":"Post-processes the query results"
},{
    "func_desc_term":"Generates a system prompt"
},{
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc_term": "Builds SPARQL queries to extract"
}, {
    "func_desc_term": "Chat with the LLM"
}]

question_template = """
Does any of the executions of the {func_desc} function made has a Generative Task within as a component and also {func_desc} 
function itself is generated by a Generative Task?
"""

sparql_template = """
SELECT DISTINCT ?flbl ?exe ?llm_gen_out ?llm_gen_out2
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl .
    FILTER(REGEX(?desc, "{func_desc_term}","i"))

    ?asso prov:hadPlan ?obj .
    ?exe prov:qualifiedAssociation ?asso .

    OPTIONAL {
        ?exe sio:SIO_000369 ?llm_gen .
    }

    BIND(COALESCE(?llm_gen, "None") AS ?llm_gen_out)
    
    OPTIONAL {
        ?llm_out2 sio:SIO_000202 ?obj .
        ?llm_out2 sio:SIO_000232 ?llm2 .
        ?llm_gen2 prov:used ?llm2 .
    }

    BIND(COALESCE(?llm_gen2, "None") AS ?llm_gen_out2)
}

"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    1. Executions of the {func_desc} function {decision1} a Generative Task that utilize an LLM.
    2. The {func_desc} function {decision2} by a Generative Task.

    {answer_inst}
    """
    
    _ent = entities[['flbl', 'exe', 'llm_gen_out', 'llm_gen_out2']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "flbl": "Function",
            'exe': "Execution",
            'llm_gen_out': "Generative Task used within execution",
            'llm_gen_out2': "Generative Task used to generate function"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent,
        decision1 = "contains" if _ent['llm_gen_out'].tolist()[0] != "None" else "does not contain",
        decision2 = "is generated" if _ent['llm_gen_out2'].tolist()[0] != "None" else "is not generated"
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    gt.qtype = ["single", "bool"]
    gt.decision = (gt.entities[0]['llm_gen_out'] != "None") and (gt.entities[0]['llm_gen_out2'] != "None")

gt_list.extend(gts)

ic| rquestion: '''
                Does any of the executions of the sparql query post processing function made has a Generative Task within as a component and also sparql query post processing
                function itself is generated by a Generative Task?
                '''
ic| entities:                                            flbl  \
              0  Query Result Post-Processor@en^^<xsd:string>

                                                               exe llm_gen_out  \
              0  http://testwebsite/testProgram#id_202604122007...        None

                                                      llm_gen_out2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                1. Executions of the sparql query post processing function does not contain a Generative Task that utilize an LLM.
                2. The sparql query post processing function is generated by a Generative Task.

                Function | Execution | Generative Task used within execution | Generative Task used to generate function
            Query Result Post-Processor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200745_507 | None | http://testwebsite/testProgram#Generative_Task-query_result_post_processor
                ', entities=[{'flbl': 'Query Result Post-Processor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200745_507', 'llm_gen_out': 'None', 'llm_gen_out2': 'http://testwebsite/testProgram#Generative_Task-query_result_post_processor'}])

ic| rquestion: '''
                Does any of the executions of the system prompt template function made has a Generative Task within as a component and also system prompt template
                function itself is generated by a Generative Task?
                '''
ic| entities:                                                 flbl  \
              0  System Prompt Template Generator@en^^<xsd:string>

                                                               exe llm_gen_out  \
              0  http://testwebsite/testProgram#id_202604122007...        None

                                                      llm_gen_out2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                1. Executions of the system prompt template function does not contain a Generative Task that utilize an LLM.
                2. The system prompt template function is generated by a Generative Task.

                Function | Execution | Generative Task used within execution | Generative Task used to generate function
            System Prompt Template Generator@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200734_778 | None | http://testwebsite/testProgram#Generative_Task-system_prompt_generator
                ', entities=[{'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200734_778', 'llm_gen_out': 'None', 'llm_gen_out2': 'http://testwebsite/testProgram#Generative_Task-system_prompt_generator'}])
ic| rquestion: '''
                Does any of the executions of the information extraction function made has a Generative Task within as a component and also information extraction
                function itself is generated by a Generative Task?
                '''
ic| entities:                                      flbl  \
              0  Information Extractor@en^^<xsd:string>

                                                               exe  \
              0  http://testwebsite/testProgram#id_202604122007...

                                                       llm_gen_out  \
              0  http://testwebsite/testProgram#Generative_Task...

                                                      llm_gen_out2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                1. Executions of the information extraction function contains a Generative Task that utilize an LLM.
                2. The information extraction function is generated by a Generative Task.

                Function | Execution | Generative Task used within execution | Generative Task used to generate function
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200742_397 | http://testwebsite/testProgram#Generative_Task-id_20260412200742_397 | http://testwebsite/testProgram#Generative_Task-information_extractor
                ', entities=[{'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200742_397', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397', 'llm_gen_out2': 'http://testwebsite/testProgram#Generative_Task-information_extractor'}])
ic| rquestion: '''
                Does any of the executions of the sparql query function function made has a Generative Task within as a component and also sparql query function
                function itself is generated by a Generative Task?
                '''
ic| entities:                                      flbl  \
              0   SPARQL Query Builder@en^^<xsd:string>
              1   SPARQL Query Builder@en^^<xsd:string>
              2   SPARQL Query Builder@en^^<xsd:string>
              3   SPARQL Query Builder@en^^<xsd:string>
              4   SPARQL Query Builder@en^^<xsd:string>
              5   SPARQL Query Builder@en^^<xsd:string>
              6   SPARQL Query Builder@en^^<xsd:string>
              7   SPARQL Query Builder@en^^<xsd:string>
              8   SPARQL Query Builder@en^^<xsd:string>
              9   SPARQL Query Builder@en^^<xsd:string>
              10  SPARQL Query Builder@en^^<xsd:string>
              11  SPARQL Query Builder@en^^<xsd:string>
              12  SPARQL Query Builder@en^^<xsd:string>

                                                                exe llm_gen_out llm_gen_out2
              0   http://testwebsite/testProgram#id_202604122007...        None         None
              1   http://testwebsite/testProgram#id_202604122007...        None         None
              2   http://testwebsite/testProgram#id_202604122007...        None         None
              3   http://testwebsite/testProgram#id_202604122007...        None         None
              4   http://testwebsite/testProgram#id_202604122007...        None         None
              5   http://testwebsite/testProgram#id_202604122007...        None         None
              6   http://testwebsite/testProgram#id_202604122007...        None         None
              7   http://testwebsite/testProgram#id_202604122007...        None         None
              8   http://testwebsite/testProgram#id_202604122007...        None         None
              9   http://testwebsite/testProgram#id_202604122007...        None         None
              10  http://testwebsite/testProgram#id_202604122007...        None         None
              11  http://testwebsite/testProgram#id_202604122007...        None         None
              12  http://testwebsite/testProgram#id_202604122007...        None         None
ic| answer: GTAnswer(answer_nlp='
                1. Executions of the sparql query function function does not contain a Generative Task that utilize an LLM.
                2. The sparql query function function is not generated by a Generative Task.

                Function | Execution | Generative Task used within execution | Generative Task used to generate function
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200743_103 | None | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200743_290 | None | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200743_818 | None | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200743_952 | None | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200744_221 | None | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200744_387 | None | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200744_460 | None | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200744_624 | None | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200744_720 | None | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200744_854 | None | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200744_909 | None | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200745_467 | None | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200745_473 | None | None
                ', entities=[{'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200743_103', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200743_290', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200743_818', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200743_952', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200744_221', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200744_387', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200744_460', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200744_624', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200744_720', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200744_854', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200744_909', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200745_467', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200745_473', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}])
ic| rquestion: '''
                Does any of the executions of the llm chat function function made has a Generative Task within as a component and also llm chat function
                function itself is generated by a Generative Task?
                '''
ic| entities:                         flbl  \
              0  LLM Chat@en^^<xsd:string>

                                                               exe  \
              0  http://testwebsite/testProgram#id_202604122007...

                                                       llm_gen_out llm_gen_out2
              0  http://testwebsite/testProgram#Generative_Task...         None
ic| answer: GTAnswer(answer_nlp='
                1. Executions of the llm chat function function contains a Generative Task that utilize an LLM.
                2. The llm chat function function is not generated by a Generative Task.

                Function | Execution | Generative Task used within execution | Generative Task used to generate function
            LLM Chat@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200740_99 | http://testwebsite/testProgram#Generative_Task-id_20260412200740_99 | None
                ', entities=[{'flbl': 'LLM Chat@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200740_99', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-id_20260412200740_99', 'llm_gen_out2': 'None'}])

In [20]:
# Question MULT 10 : Does any of the executions of the function contain a Generative Task within and the function itself is generated by an LLM


template_spec = [ {
    "func_desc": "information extraction"
}, {
    "func_desc": "llm chat function"
}]

sparql_spec = [{
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc_term": "Chat with the LLM"
}]

question_template = """
What are the inputs of the Generative Task that was a component in the executions of  the {func_desc} function?
"""

sparql_template = """
SELECT DISTINCT ?flbl ?exe ?lbl
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl .
    FILTER(REGEX(?desc, "{func_desc_term}","i"))

    ?asso prov:hadPlan ?obj .
    ?exe prov:qualifiedAssociation ?asso .

    ?exe sio:SIO_000369 ?llm_gen .
    ?llm_gen prov:used ?llm .
    ?llm sio:SIO_000230 ?inp .
    ?inp prov:value ?lbl . 
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The inputs to the LLM used for the Generative Task in the executions of the {func_desc} function

    {answer_inst}
    """
    
    _ent = entities[['flbl', 'exe', 'lbl']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "flbl": "Function",
            'exe': "Execution",
            'lbl': "Inputs for the Generative Task used within execution"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent[['exe', 'lbl']].to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    gt.qtype = ["multi", "entity", 'label']
gt_list.extend(gts)

ic| rquestion: '''
                What are the inputs of the Generative Task that was a component in the executions of  the information extraction function?
                '''
ic| entities:                                      flbl  \
              0  Information Extractor@en^^<xsd:string>

                                                               exe  \
              0  http://testwebsite/testProgram#id_202604122007...

                                                               lbl
              0  Before your workout, it's essential to eat foo...
ic| answer: GTAnswer(answer_nlp="
                The inputs to the LLM used for the Generative Task in the executions of the information extraction function

                Function | Execution | Inputs for the Generative Task used within execution
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200742_397 | Before your workout, it's essential to eat foods that provide a quick energy boost while being mindful of your diabetes management. Since your diet preference is carnivorous, let's focus on protein-rich and low-carb options that are also easy on your blood sugar levels.

            1. **Chicken or Turkey Breast**: Lean poultry is an excellent source of protein and can provide sustained energy. Consider having a small portion, like a grilled chicken/turkey slice, about an hour before your workout.

            2. **Greek Yogurt with Berries**: While fruits are generally high in carbohydrates, a small handful of berries like blueberries combined with unsweetened Greek yogurt can provide an antioxidant boost and moderate carbs. The protein from the yogurt will help sustain energy.

            3. **Hard-Boiled Eggs**: Eggs are a compact protein source. Consuming a couple of hard-boiled eggs can help keep your energy levels up without spiking your blood sugar.

            4. **Nuts or Nut Butter**: Small amounts of nuts, like almonds or walnuts, or a spoonful of nut butter can provide healthy fats and protein. They're also convenient and easy to carry.

            5. **Cheese Sticks or Slices**: Cheese is low in carbohydrates and a good protein source. Opt for low-fat cheese if you're concerned about saturated fats.

            6. **Tuna Salad**: A small portion of tuna mixed with a bit of olive oil or mayonnaise can provide a good mix of protein and healthy fats. You can have it on a slice of cucumber or lettuce wrap.

            7. **Beef Jerky**: Look for a low-sodium, low-sugar variety. It’s high in protein and can be an excellent pre-workout snack.

            Remember to monitor your blood sugar levels before and after your workout to ensure they stay within your target range. Drink plenty of water to stay hydrated, especially during workouts. Adjust portions according to your specific energy needs and preferences. Always consult with your healthcare provider or a dietitian when making significant changes to your diet, especially with a condition like diabetes.@en^^<xsd:string>
                ", entities=[{'exe': 'http://testwebsite/testProgram#id_20260412200742_397', 'lbl': "Before your workout, it's essential to eat foods that provide a quick energy boost while being mindful of your diabetes management. Since your diet preference is carnivorous, let's focus on protein-rich and low-carb options that are also easy on your blood sugar levels.

            1. **Chicken or Turkey Breast**: Lean poultry is an excellent source of protein and can provide sustained energy. Consider having a small portion, like a grilled chicken/turkey slice, about an hour before your workout.

            2. **Greek Yogurt with Berries**: While fruits are generally high in carbohydrates, a small handful of berries like blueberries combined with unsweetened Greek yogurt can provide an antioxidant boost and moderate carbs. The protein from the yogurt will help sustain energy.

            3. **Hard-Boiled Eggs**: Eggs are a compact protein source. Consuming a couple of hard-boiled eggs can help keep your energy levels up without spiking your blood sugar.

            4. **Nuts or Nut Butter**: Small amounts of nuts, like almonds or walnuts, or a spoonful of nut butter can provide healthy fats and protein. They're also convenient and easy to carry.

            5. **Cheese Sticks or Slices**: Cheese is low in carbohydrates and a good protein source. Opt for low-fat cheese if you're concerned about saturated fats.

            6. **Tuna Salad**: A small portion of tuna mixed with a bit of olive oil or mayonnaise can provide a good mix of protein and healthy fats. You can have it on a slice of cucumber or lettuce wrap.

            7. **Beef Jerky**: Look for a low-sodium, low-sugar variety. It’s high in protein and can be an excellent pre-workout snack.

            Remember to monitor your blood sugar levels before and after your workout to ensure they stay within your target range. Drink plenty of water to stay hydrated, especially during workouts. Adjust portions according to your specific energy needs and preferences. Always consult with your healthcare provider or a dietitian when making significant changes to your diet, especially with a condition like diabetes.@en^^<xsd:string>"}])
ic| rquestion: '''
                What are the inputs of the Generative Task that was a component in the executions of  the llm chat function function?
                '''
ic| entities:                         flbl  \
              0  LLM Chat@en^^<xsd:string>
              1  LLM Chat@en^^<xsd:string>

                                                               exe  \
              0  http://testwebsite/testProgram#id_202604122007...
              1  http://testwebsite/testProgram#id_202604122007...

                                                               lbl
              0  You are a health care assistant and you will r...
              1  I need suggestions for light and energy-boosti...
ic| answer: GTAnswer(answer_nlp='
                The inputs to the LLM used for the Generative Task in the executions of the llm chat function function

                Function | Execution | Inputs for the Generative Task used within execution
            LLM Chat@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200740_99 | You are a health care assistant and you will respond to the user who is 30 years old, identifies as Male, diagnosed with Diabetic. Consider their height: 182.3, weight: 95.2, body mass index: 28.6, food preferences: Carnivore, and allergies: None when providing a dietary guideline.@en^^<xsd:string>
            LLM Chat@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200740_99 | I need suggestions for light and energy-boosting foods to eat before my gym workout.@en^^<xsd:string>
                ', entities=[{'exe': 'http://testwebsite/testProgram#id_20260412200740_99', 'lbl': 'You are a health care assistant and you will respond to the user who is 30 years old, identifies as Male, diagnosed with Diabetic. Consider their height: 182.3, weight: 95.2, body mass index: 28.6, food preferences: Carnivore, and allergies: None when providing a dietary guideline.@en^^<xsd:string>'}, {'exe': 'http://testwebsite/testProgram#id_20260412200740_99', 'lbl': 'I need suggestions for light and energy-boosting foods to eat before my gym workout.@en^^<xsd:string>'}])

In [21]:
# Question MULT 11 :


template_spec = [ {
    "func_desc": "information extraction"
}, {
    "func_desc": "llm chat function"
}]

sparql_spec = [{
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc_term": "Chat with the LLM"
}]

question_template = """
What are the outputs of the Generative Task that was a component in the executions of the {func_desc} function?
"""

sparql_template = """
SELECT DISTINCT ?flbl ?exe ?lbl
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl .
    FILTER(REGEX(?desc, "{func_desc_term}","i"))

    ?asso prov:hadPlan ?obj .
    ?exe prov:qualifiedAssociation ?asso .

    ?exe sio:SIO_000369 ?llm_gen .
    ?llm_gen prov:used ?llm .
    ?llm sio:SIO_000229 ?out .
    ?out sio:SIO_000202 ?data . 
    ?data prov:value ?lbl . 
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The inputs to the LLM used for the Generative Task in the executions of the {func_desc} function

    {answer_inst}
    """
    
    _ent = entities[['flbl', 'exe', 'lbl']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "flbl": "Function",
            'exe': "Execution",
            'lbl': "Inputs for the Generative Task used within execution"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    gt.qtype = ["multi", "entity", 'label']
gt_list.extend(gts)

ic| rquestion: '''
                What are the outputs of the Generative Task that was a component in the executions of the information extraction function?
                '''
ic| entities:                                       flbl  \
              0   Information Extractor@en^^<xsd:string>
              1   Information Extractor@en^^<xsd:string>
              2   Information Extractor@en^^<xsd:string>
              3   Information Extractor@en^^<xsd:string>
              4   Information Extractor@en^^<xsd:string>
              5   Information Extractor@en^^<xsd:string>
              6   Information Extractor@en^^<xsd:string>
              7   Information Extractor@en^^<xsd:string>
              8   Information Extractor@en^^<xsd:string>
              9   Information Extractor@en^^<xsd:string>
              10  Information Extractor@en^^<xsd:string>
              11  Information Extractor@en^^<xsd:string>
              12  Information Extractor@en^^<xsd:string>

                                                                exe  \
              0   http://testwebsite/testProgram#id_202604122007...
              1   http://testwebsite/testProgram#id_202604122007...
              2   http://testwebsite/testProgram#id_202604122007...
              3   http://testwebsite/testProgram#id_202604122007...
              4   http://testwebsite/testProgram#id_202604122007...
              5   http://testwebsite/testProgram#id_202604122007...
              6   http://testwebsite/testProgram#id_202604122007...
              7   http://testwebsite/testProgram#id_202604122007...
              8   http://testwebsite/testProgram#id_202604122007...
              9   http://testwebsite/testProgram#id_202604122007...
              10  http://testwebsite/testProgram#id_202604122007...
              11  http://testwebsite/testProgram#id_202604122007...
              12  http://testwebsite/testProgram#id_202604122007...

                                            lbl
              0          Berry@en^^<xsd:string>
              1        Chicken@en^^<xsd:string>
              2     Mayonnaise@en^^<xsd:string>
              3         Cheese@en^^<xsd:string>
              4        Lettuce@en^^<xsd:string>
              5         Turkey@en^^<xsd:string>
              6      Olive oil@en^^<xsd:string>
              7            Egg@en^^<xsd:string>
              8       Cucumber@en^^<xsd:string>
              9   Greek yogurt@en^^<xsd:string>
              10           Nut@en^^<xsd:string>
              11    Beef jerky@en^^<xsd:string>
              12          Tuna@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The inputs to the LLM used for the Generative Task in the executions of the information extraction function

                Function | Execution | Inputs for the Generative Task used within execution
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200742_397 | Berry@en^^<xsd:string>
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200742_397 | Chicken@en^^<xsd:string>
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200742_397 | Mayonnaise@en^^<xsd:string>
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200742_397 | Cheese@en^^<xsd:string>
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200742_397 | Lettuce@en^^<xsd:string>
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200742_397 | Turkey@en^^<xsd:string>
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200742_397 | Olive oil@en^^<xsd:string>
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200742_397 | Egg@en^^<xsd:string>
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200742_397 | Cucumber@en^^<xsd:string>
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200742_397 | Greek yogurt@en^^<xsd:string>
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200742_397 | Nut@en^^<xsd:string>
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200742_397 | Beef jerky@en^^<xsd:string>
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200742_397 | Tuna@en^^<xsd:string>
                ', entities=[{'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200742_397', 'lbl': 'Berry@en^^<xsd:string>'}, {'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200742_397', 'lbl': 'Chicken@en^^<xsd:string>'}, {'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200742_397', 'lbl': 'Mayonnaise@en^^<xsd:string>'}, {'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200742_397', 'lbl': 'Cheese@en^^<xsd:string>'}, {'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200742_397', 'lbl': 'Lettuce@en^^<xsd:string>'}, {'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200742_397', 'lbl': 'Turkey@en^^<xsd:string>'}, {'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200742_397', 'lbl': 'Olive oil@en^^<xsd:string>'}, {'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200742_397', 'lbl': 'Egg@en^^<xsd:string>'}, {'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200742_397', 'lbl': 'Cucumber@en^^<xsd:string>'}, {'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200742_397', 'lbl': 'Greek yogurt@en^^<xsd:string>'}, {'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200742_397', 'lbl': 'Nut@en^^<xsd:string>'}, {'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200742_397', 'lbl': 'Beef jerky@en^^<xsd:string>'}, {'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200742_397', 'lbl': 'Tuna@en^^<xsd:string>'}])
ic| rquestion: '''
                What are the outputs of the Generative Task that was a component in the executions of the llm chat function function?
                '''
ic| entities:                         flbl  \
              0  LLM Chat@en^^<xsd:string>

                                                               exe  \
              0  http://testwebsite/testProgram#id_202604122007...

                                                               lbl
              0  Before your workout, it's essential to eat foo...
ic| answer: GTAnswer(answer_nlp="
                The inputs to the LLM used for the Generative Task in the executions of the llm chat function function

                Function | Execution | Inputs for the Generative Task used within execution
            LLM Chat@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412200740_99 | Before your workout, it's essential to eat foods that provide a quick energy boost while being mindful of your diabetes management. Since your diet preference is carnivorous, let's focus on protein-rich and low-carb options that are also easy on your blood sugar levels.

            1. **Chicken or Turkey Breast**: Lean poultry is an excellent source of protein and can provide sustained energy. Consider having a small portion, like a grilled chicken/turkey slice, about an hour before your workout.

            2. **Greek Yogurt with Berries**: While fruits are generally high in carbohydrates, a small handful of berries like blueberries combined with unsweetened Greek yogurt can provide an antioxidant boost and moderate carbs. The protein from the yogurt will help sustain energy.

            3. **Hard-Boiled Eggs**: Eggs are a compact protein source. Consuming a couple of hard-boiled eggs can help keep your energy levels up without spiking your blood sugar.

            4. **Nuts or Nut Butter**: Small amounts of nuts, like almonds or walnuts, or a spoonful of nut butter can provide healthy fats and protein. They're also convenient and easy to carry.

            5. **Cheese Sticks or Slices**: Cheese is low in carbohydrates and a good protein source. Opt for low-fat cheese if you're concerned about saturated fats.

            6. **Tuna Salad**: A small portion of tuna mixed with a bit of olive oil or mayonnaise can provide a good mix of protein and healthy fats. You can have it on a slice of cucumber or lettuce wrap.

            7. **Beef Jerky**: Look for a low-sodium, low-sugar variety. It’s high in protein and can be an excellent pre-workout snack.

            Remember to monitor your blood sugar levels before and after your workout to ensure they stay within your target range. Drink plenty of water to stay hydrated, especially during workouts. Adjust portions according to your specific energy needs and preferences. Always consult with your healthcare provider or a dietitian when making significant changes to your diet, especially with a condition like diabetes.@en^^<xsd:string>
                ", entities=[{'flbl': 'LLM Chat@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412200740_99', 'lbl': "Before your workout, it's essential to eat foods that provide a quick energy boost while being mindful of your diabetes management. Since your diet preference is carnivorous, let's focus on protein-rich and low-carb options that are also easy on your blood sugar levels.

            1. **Chicken or Turkey Breast**: Lean poultry is an excellent source of protein and can provide sustained energy. Consider having a small portion, like a grilled chicken/turkey slice, about an hour before your workout.

            2. **Greek Yogurt with Berries**: While fruits are generally high in carbohydrates, a small handful of berries like blueberries combined with unsweetened Greek yogurt can provide an antioxidant boost and moderate carbs. The protein from the yogurt will help sustain energy.

            3. **Hard-Boiled Eggs**: Eggs are a compact protein source. Consuming a couple of hard-boiled eggs can help keep your energy levels up without spiking your blood sugar.

            4. **Nuts or Nut Butter**: Small amounts of nuts, like almonds or walnuts, or a spoonful of nut butter can provide healthy fats and protein. They're also convenient and easy to carry.

            5. **Cheese Sticks or Slices**: Cheese is low in carbohydrates and a good protein source. Opt for low-fat cheese if you're concerned about saturated fats.

            6. **Tuna Salad**: A small portion of tuna mixed with a bit of olive oil or mayonnaise can provide a good mix of protein and healthy fats. You can have it on a slice of cucumber or lettuce wrap.

            7. **Beef Jerky**: Look for a low-sodium, low-sugar variety. It’s high in protein and can be an excellent pre-workout snack.

            Remember to monitor your blood sugar levels before and after your workout to ensure they stay within your target range. Drink plenty of water to stay hydrated, especially during workouts. Adjust portions according to your specific energy needs and preferences. Always consult with your healthcare provider or a dietitian when making significant changes to your diet, especially with a condition like diabetes.@en^^<xsd:string>"}])

In [22]:
# Question MULT 11 :

_spec = [ {
    "func_desc": "information extraction",
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc": "llm chat function",
    "func_desc_term": "Chat with the LLM"
}]

template_spec = []
sparql_spec = []

for _s in _spec:
    exe_query = """
    SELECT DISTINCT ?exe
    WHERE {
        ?obj dc:description ?desc .
        ?obj rdfs:label ?flbl .
        FILTER(REGEX(?desc, "{func_desc_term}","i"))
        
        ?asso prov:hadPlan ?obj .
        ?exe prov:qualifiedAssociation ?asso .      
        
        }
    """
    executions = graph_manager.query(
        regex_add_strings(exe_query, func_desc_term = _s["func_desc_term"])
    )


    for obj in executions.to_dict("records"):
        template_spec.append({
            "exe_id":obj['exe']
        })
        
        sparql_spec.append({
            "exe_id":obj['exe']
        })

question_template = """
What execution created the output data that was used as an input for the generative task within the execution {exe_id}?
"""

sparql_template = """
SELECT DISTINCT ?exe2
    WHERE {
        <{exe_id}> sio:SIO_000369 ?llm_gen .
        ?llm_gen prov:used ?llm .
        ?llm sio:SIO_000229 ?out .
        ?out sio:SIO_000202 ?data . 
        ?data prov:wasGeneratedBy ?exe2 . 
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The inputs to the Generative Task in the execution of {exe_id} was generated by executions

    {answer_inst}
    """
    
    _ent = entities[['exe2']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            'exe2': "Execution"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        exe_id = question_specs["exe_id"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    gt.qtype = ["multi", "entity", 'label']
gt_list.extend(gts)

ic| rquestion: '''
                What execution created the output data that was used as an input for the generative task within the execution http://testwebsite/testProgram#id_20260412200742_397?
                '''
ic| entities:                                                  exe2
              0   http://testwebsite/testProgram#id_202604122007...
              1   http://testwebsite/testProgram#id_202604122007...
              2   http://testwebsite/testProgram#id_202604122007...
              3   http://testwebsite/testProgram#id_202604122007...
              4   http://testwebsite/testProgram#id_202604122007...
              5   http://testwebsite/testProgram#id_202604122007...
              6   http://testwebsite/testProgram#id_202604122007...
              7   http://testwebsite/testProgram#id_202604122007...
              8   http://testwebsite/testProgram#id_202604122007...
              9   http://testwebsite/testProgram#id_202604122007...
              10  http://testwebsite/testProgram#id_202604122007...
              11  http://testwebsite/testProgram#id_202604122007...
              12  http://testwebsite/testProgram#id_202604122007...
              13  http://testwebsite/testProgram#id_202604122007...
ic| answer: GTAnswer(answer_nlp='
                The inputs to the Generative Task in the execution of http://testwebsite/testProgram#id_20260412200742_397 was generated by executions

                Execution
            http://testwebsite/testProgram#id_20260412200742_397
            http://testwebsite/testProgram#id_20260412200743_952
            http://testwebsite/testProgram#id_20260412200743_290
            http://testwebsite/testProgram#id_20260412200744_909
            http://testwebsite/testProgram#id_20260412200744_460
            http://testwebsite/testProgram#id_20260412200745_473
            http://testwebsite/testProgram#id_20260412200743_818
            http://testwebsite/testProgram#id_20260412200744_720
            http://testwebsite/testProgram#id_20260412200744_221
            http://testwebsite/testProgram#id_20260412200744_387
            http://testwebsite/testProgram#id_20260412200743_103
            http://testwebsite/testProgram#id_20260412200744_624
            http://testwebsite/testProgram#id_20260412200745_467
            http://testwebsite/testProgram#id_20260412200744_854
                ', entities=[{'exe2': 'http://testwebsite/testProgram#id_20260412200742_397'}, {'exe2': 'http://testwebsite/testProgram#id_20260412200743_952'}, {'exe2': 'http://testwebsite/testProgram#id_20260412200743_290'}, {'exe2': 'http://testwebsite/testProgram#id_20260412200744_909'}, {'exe2': 'http://testwebsite/testProgram#id_20260412200744_460'}, {'exe2': 'http://testwebsite/testProgram#id_20260412200745_473'}, {'exe2': 'http://testwebsite/testProgram#id_20260412200743_818'}, {'exe2': 'http://testwebsite/testProgram#id_20260412200744_720'}, {'exe2': 'http://testwebsite/testProgram#id_20260412200744_221'}, {'exe2': 'http://testwebsite/testProgram#id_20260412200744_387'}, {'exe2': 'http://testwebsite/testProgram#id_20260412200743_103'}, {'exe2': 'http://testwebsite/testProgram#id_20260412200744_624'}, {'exe2': 'http://testwebsite/testProgram#id_20260412200745_467'}, {'exe2': 'http://testwebsite/testProgram#id_20260412200744_854'}])
ic| rquestion: '''
                What execution created the output data that was used as an input for the generative task within the execution http://testwebsite/testProgram#id_20260412200740_99?
                '''
ic| entities:                                                 exe2
              0  http://testwebsite/testProgram#id_202604122007...
              1  http://testwebsite/testProgram#id_202604122007...
ic| answer: GTAnswer(answer_nlp='
                The inputs to the Generative Task in the execution of http://testwebsite/testProgram#id_20260412200740_99 was generated by executions

                Execution
            http://testwebsite/testProgram#id_20260412200740_99
            http://testwebsite/testProgram#id_20260412200742_397
                ', entities=[{'exe2': 'http://testwebsite/testProgram#id_20260412200740_99'}, {'exe2': 'http://testwebsite/testProgram#id_20260412200742_397'}])

In [23]:
# Question MULT 12 :

_spec = [ {
    "func_desc": "information extraction",
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc": "sparql query function",
    "func_desc_term": "Builds SPARQL queries to extract"
}]

template_spec = []
sparql_spec = []

for _s in _spec:
    exe_query = """
    SELECT DISTINCT ?exe
    WHERE {
        ?obj dc:description ?desc .
        ?obj rdfs:label ?flbl .
        FILTER(REGEX(?desc, "{func_desc_term}","i"))
        
        ?asso prov:hadPlan ?obj .
        ?exe prov:qualifiedAssociation ?asso .      
        
        }
    """
    executions = graph_manager.query(
        regex_add_strings(exe_query, func_desc_term = _s["func_desc_term"])
    )


    for obj in executions.to_dict("records"):
        template_spec.append({
            "exe_id":obj['exe']
        })
        
        sparql_spec.append({
            "exe_id":obj['exe']
        })

question_template = """
What Generative Task generated the data that was used by the execution {exe_id}?
"""

sparql_template = """
SELECT DISTINCT ?gtask ?glbl
            WHERE {
                <{exe_id}> prov:used ?data .
                ?llm_out sio:SIO_000202 ?data .
                ?llm_out sio:SIO_000232 ?llm .
                ?gtask prov:used ?llm .
                ?gtask rdfs:label ?glbl
        }
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The Generative Task that generated the data that was used by the execution {exe_id} is 

    {answer_inst}
    """
    
    _ent = entities[['gtask', 'glbl']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            'gtask': "Generative Task"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        exe_id = question_specs["exe_id"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent[['gtask']].to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    gt.qtype = ["single", "entity"]
gt_list.extend(gts)

ic| rquestion: '''
                What Generative Task generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200742_397?
                '''
ic| entities:                                                gtask  \
              0  http://testwebsite/testProgram#Generative_Task...

                                                              glbl
              0  LLM Generates an text for
              system prompt: You...
ic| answer: GTAnswer(answer_nlp='
                The Generative Task that generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200742_397 is

                Generative Task | glbl
            http://testwebsite/testProgram#Generative_Task-id_20260412200740_99 | LLM Generates an text for
            system prompt: You are a health care assistant and you will respond to the user who is 30 years old, identifies as Male, diagnosed with Diabetic. Consider their height: 182.3, weight: 95.2, body mass index: 28.6, food preferences: Carnivore, and allergies: None when providing a dietary guideline.

            user prompt: I need suggestions for light and energy-boosting foods to eat before my gym workout.

            using: gpt-4o@en^^<xsd:string>
                ', entities=[{'gtask': 'http://testwebsite/testProgram#Generative_Task-id_20260412200740_99'}])
ic| rquestion: '''
                What Generative Task generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200743_103?
                '''
ic| entities:                                                gtask  \
              0  http://testwebsite/testProgram#Generative_Task...

                                                              glbl
              0  Extracts important entities for
              text: Before...
ic| answer: GTAnswer(answer_nlp="
                The Generative Task that generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200743_103 is

                Generative Task | glbl
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397 | Extracts important entities for
            text: Before your workout, it's essential to eat foods that provide a quick energy boost while being mindful of your diabetes management. Since your diet preference is carnivorous, let's focus on protein-rich and low-carb options that are also easy on your blood sugar levels.

            1. **Chicken or Turkey Breast**: Lean poultry is an excellent source of protein and can provide sustained energy. Consider having a small portion, like a grilled chicken/turkey slice, about an hour before your workout.

            2. **Greek Yogurt with Berries**: While fruits are generally high in carbohydrates, a small handful of berries like blueberries combined with unsweetened Greek yogurt can provide an antioxidant boost and moderate carbs. The protein from the yogurt will help sustain energy.

            3. **Hard-Boiled Eggs**: Eggs are a compact protein source. Consuming a couple of hard-boiled eggs can help keep your energy levels up without spiking your blood sugar.

            4. **Nuts or Nut Butter**: Small amounts of nuts, like almonds or walnuts, or a spoonful of nut butter can provide healthy fats and protein. They're also convenient and easy to carry.

            5. **Cheese Sticks or Slices**: Cheese is low in carbohydrates and a good protein source. Opt for low-fat cheese if you're concerned about saturated fats.

            6. **Tuna Salad**: A small portion of tuna mixed with a bit of olive oil or mayonnaise can provide a good mix of protein and healthy fats. You can have it on a slice of cucumber or lettuce wrap.

            7. **Beef Jerky**: Look for a low-sodium, low-sugar variety. It’s high in protein and can be an excellent pre-workout snack.

            Remember to monitor your blood sugar levels before and after your workout to ensure they stay within your target range. Drink plenty of water to stay hydrated, especially during workouts. Adjust portions according to your specific energy needs and preferences. Always consult with your healthcare provider or a dietitian when making significant changes to your diet, especially with a condition like diabetes.

            using: gpt-4o@en^^<xsd:string>
                ", entities=[{'gtask': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                What Generative Task generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200743_290?
                '''
ic| entities:                                                gtask  \
              0  http://testwebsite/testProgram#Generative_Task...

                                                              glbl
              0  Extracts important entities for
              text: Before...
ic| answer: GTAnswer(answer_nlp="
                The Generative Task that generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200743_290 is

                Generative Task | glbl
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397 | Extracts important entities for
            text: Before your workout, it's essential to eat foods that provide a quick energy boost while being mindful of your diabetes management. Since your diet preference is carnivorous, let's focus on protein-rich and low-carb options that are also easy on your blood sugar levels.

            1. **Chicken or Turkey Breast**: Lean poultry is an excellent source of protein and can provide sustained energy. Consider having a small portion, like a grilled chicken/turkey slice, about an hour before your workout.

            2. **Greek Yogurt with Berries**: While fruits are generally high in carbohydrates, a small handful of berries like blueberries combined with unsweetened Greek yogurt can provide an antioxidant boost and moderate carbs. The protein from the yogurt will help sustain energy.

            3. **Hard-Boiled Eggs**: Eggs are a compact protein source. Consuming a couple of hard-boiled eggs can help keep your energy levels up without spiking your blood sugar.

            4. **Nuts or Nut Butter**: Small amounts of nuts, like almonds or walnuts, or a spoonful of nut butter can provide healthy fats and protein. They're also convenient and easy to carry.

            5. **Cheese Sticks or Slices**: Cheese is low in carbohydrates and a good protein source. Opt for low-fat cheese if you're concerned about saturated fats.

            6. **Tuna Salad**: A small portion of tuna mixed with a bit of olive oil or mayonnaise can provide a good mix of protein and healthy fats. You can have it on a slice of cucumber or lettuce wrap.

            7. **Beef Jerky**: Look for a low-sodium, low-sugar variety. It’s high in protein and can be an excellent pre-workout snack.

            Remember to monitor your blood sugar levels before and after your workout to ensure they stay within your target range. Drink plenty of water to stay hydrated, especially during workouts. Adjust portions according to your specific energy needs and preferences. Always consult with your healthcare provider or a dietitian when making significant changes to your diet, especially with a condition like diabetes.

            using: gpt-4o@en^^<xsd:string>
                ", entities=[{'gtask': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                What Generative Task generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200743_818?
                '''
ic| entities:                                                gtask  \
              0  http://testwebsite/testProgram#Generative_Task...

                                                              glbl
              0  Extracts important entities for
              text: Before...
ic| answer: GTAnswer(answer_nlp="
                The Generative Task that generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200743_818 is

                Generative Task | glbl
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397 | Extracts important entities for
            text: Before your workout, it's essential to eat foods that provide a quick energy boost while being mindful of your diabetes management. Since your diet preference is carnivorous, let's focus on protein-rich and low-carb options that are also easy on your blood sugar levels.

            1. **Chicken or Turkey Breast**: Lean poultry is an excellent source of protein and can provide sustained energy. Consider having a small portion, like a grilled chicken/turkey slice, about an hour before your workout.

            2. **Greek Yogurt with Berries**: While fruits are generally high in carbohydrates, a small handful of berries like blueberries combined with unsweetened Greek yogurt can provide an antioxidant boost and moderate carbs. The protein from the yogurt will help sustain energy.

            3. **Hard-Boiled Eggs**: Eggs are a compact protein source. Consuming a couple of hard-boiled eggs can help keep your energy levels up without spiking your blood sugar.

            4. **Nuts or Nut Butter**: Small amounts of nuts, like almonds or walnuts, or a spoonful of nut butter can provide healthy fats and protein. They're also convenient and easy to carry.

            5. **Cheese Sticks or Slices**: Cheese is low in carbohydrates and a good protein source. Opt for low-fat cheese if you're concerned about saturated fats.

            6. **Tuna Salad**: A small portion of tuna mixed with a bit of olive oil or mayonnaise can provide a good mix of protein and healthy fats. You can have it on a slice of cucumber or lettuce wrap.

            7. **Beef Jerky**: Look for a low-sodium, low-sugar variety. It’s high in protein and can be an excellent pre-workout snack.

            Remember to monitor your blood sugar levels before and after your workout to ensure they stay within your target range. Drink plenty of water to stay hydrated, especially during workouts. Adjust portions according to your specific energy needs and preferences. Always consult with your healthcare provider or a dietitian when making significant changes to your diet, especially with a condition like diabetes.

            using: gpt-4o@en^^<xsd:string>
                ", entities=[{'gtask': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])

ic| rquestion: '''
                What Generative Task generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200743_952?
                '''
ic| entities:                                                gtask  \
              0  http://testwebsite/testProgram#Generative_Task...

                                                              glbl
              0  Extracts important entities for
              text: Before...
ic| answer: GTAnswer(answer_nlp="
                The Generative Task that generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200743_952 is

                Generative Task | glbl
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397 | Extracts important entities for
            text: Before your workout, it's essential to eat foods that provide a quick energy boost while being mindful of your diabetes management. Since your diet preference is carnivorous, let's focus on protein-rich and low-carb options that are also easy on your blood sugar levels.

            1. **Chicken or Turkey Breast**: Lean poultry is an excellent source of protein and can provide sustained energy. Consider having a small portion, like a grilled chicken/turkey slice, about an hour before your workout.

            2. **Greek Yogurt with Berries**: While fruits are generally high in carbohydrates, a small handful of berries like blueberries combined with unsweetened Greek yogurt can provide an antioxidant boost and moderate carbs. The protein from the yogurt will help sustain energy.

            3. **Hard-Boiled Eggs**: Eggs are a compact protein source. Consuming a couple of hard-boiled eggs can help keep your energy levels up without spiking your blood sugar.

            4. **Nuts or Nut Butter**: Small amounts of nuts, like almonds or walnuts, or a spoonful of nut butter can provide healthy fats and protein. They're also convenient and easy to carry.

            5. **Cheese Sticks or Slices**: Cheese is low in carbohydrates and a good protein source. Opt for low-fat cheese if you're concerned about saturated fats.

            6. **Tuna Salad**: A small portion of tuna mixed with a bit of olive oil or mayonnaise can provide a good mix of protein and healthy fats. You can have it on a slice of cucumber or lettuce wrap.

            7. **Beef Jerky**: Look for a low-sodium, low-sugar variety. It’s high in protein and can be an excellent pre-workout snack.

            Remember to monitor your blood sugar levels before and after your workout to ensure they stay within your target range. Drink plenty of water to stay hydrated, especially during workouts. Adjust portions according to your specific energy needs and preferences. Always consult with your healthcare provider or a dietitian when making significant changes to your diet, especially with a condition like diabetes.

            using: gpt-4o@en^^<xsd:string>
                ", entities=[{'gtask': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                What Generative Task generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200744_221?
                '''
ic| entities:                                                gtask  \
              0  http://testwebsite/testProgram#Generative_Task...

                                                              glbl
              0  Extracts important entities for
              text: Before...
ic| answer: GTAnswer(answer_nlp="
                The Generative Task that generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200744_221 is

                Generative Task | glbl
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397 | Extracts important entities for
            text: Before your workout, it's essential to eat foods that provide a quick energy boost while being mindful of your diabetes management. Since your diet preference is carnivorous, let's focus on protein-rich and low-carb options that are also easy on your blood sugar levels.

            1. **Chicken or Turkey Breast**: Lean poultry is an excellent source of protein and can provide sustained energy. Consider having a small portion, like a grilled chicken/turkey slice, about an hour before your workout.

            2. **Greek Yogurt with Berries**: While fruits are generally high in carbohydrates, a small handful of berries like blueberries combined with unsweetened Greek yogurt can provide an antioxidant boost and moderate carbs. The protein from the yogurt will help sustain energy.

            3. **Hard-Boiled Eggs**: Eggs are a compact protein source. Consuming a couple of hard-boiled eggs can help keep your energy levels up without spiking your blood sugar.

            4. **Nuts or Nut Butter**: Small amounts of nuts, like almonds or walnuts, or a spoonful of nut butter can provide healthy fats and protein. They're also convenient and easy to carry.

            5. **Cheese Sticks or Slices**: Cheese is low in carbohydrates and a good protein source. Opt for low-fat cheese if you're concerned about saturated fats.

            6. **Tuna Salad**: A small portion of tuna mixed with a bit of olive oil or mayonnaise can provide a good mix of protein and healthy fats. You can have it on a slice of cucumber or lettuce wrap.

            7. **Beef Jerky**: Look for a low-sodium, low-sugar variety. It’s high in protein and can be an excellent pre-workout snack.

            Remember to monitor your blood sugar levels before and after your workout to ensure they stay within your target range. Drink plenty of water to stay hydrated, especially during workouts. Adjust portions according to your specific energy needs and preferences. Always consult with your healthcare provider or a dietitian when making significant changes to your diet, especially with a condition like diabetes.

            using: gpt-4o@en^^<xsd:string>
                ", entities=[{'gtask': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                What Generative Task generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200744_387?
                '''
ic| entities:                                                gtask  \
              0  http://testwebsite/testProgram#Generative_Task...

                                                              glbl
              0  Extracts important entities for
              text: Before...
ic| answer: GTAnswer(answer_nlp="
                The Generative Task that generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200744_387 is

                Generative Task | glbl
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397 | Extracts important entities for
            text: Before your workout, it's essential to eat foods that provide a quick energy boost while being mindful of your diabetes management. Since your diet preference is carnivorous, let's focus on protein-rich and low-carb options that are also easy on your blood sugar levels.

            1. **Chicken or Turkey Breast**: Lean poultry is an excellent source of protein and can provide sustained energy. Consider having a small portion, like a grilled chicken/turkey slice, about an hour before your workout.

            2. **Greek Yogurt with Berries**: While fruits are generally high in carbohydrates, a small handful of berries like blueberries combined with unsweetened Greek yogurt can provide an antioxidant boost and moderate carbs. The protein from the yogurt will help sustain energy.

            3. **Hard-Boiled Eggs**: Eggs are a compact protein source. Consuming a couple of hard-boiled eggs can help keep your energy levels up without spiking your blood sugar.

            4. **Nuts or Nut Butter**: Small amounts of nuts, like almonds or walnuts, or a spoonful of nut butter can provide healthy fats and protein. They're also convenient and easy to carry.

            5. **Cheese Sticks or Slices**: Cheese is low in carbohydrates and a good protein source. Opt for low-fat cheese if you're concerned about saturated fats.

            6. **Tuna Salad**: A small portion of tuna mixed with a bit of olive oil or mayonnaise can provide a good mix of protein and healthy fats. You can have it on a slice of cucumber or lettuce wrap.

            7. **Beef Jerky**: Look for a low-sodium, low-sugar variety. It’s high in protein and can be an excellent pre-workout snack.

            Remember to monitor your blood sugar levels before and after your workout to ensure they stay within your target range. Drink plenty of water to stay hydrated, especially during workouts. Adjust portions according to your specific energy needs and preferences. Always consult with your healthcare provider or a dietitian when making significant changes to your diet, especially with a condition like diabetes.

            using: gpt-4o@en^^<xsd:string>
                ", entities=[{'gtask': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                What Generative Task generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200744_460?
                '''
ic| entities:                                                gtask  \
              0  http://testwebsite/testProgram#Generative_Task...

                                                              glbl
              0  Extracts important entities for
              text: Before...
ic| answer: GTAnswer(answer_nlp="
                The Generative Task that generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200744_460 is

                Generative Task | glbl
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397 | Extracts important entities for
            text: Before your workout, it's essential to eat foods that provide a quick energy boost while being mindful of your diabetes management. Since your diet preference is carnivorous, let's focus on protein-rich and low-carb options that are also easy on your blood sugar levels.

            1. **Chicken or Turkey Breast**: Lean poultry is an excellent source of protein and can provide sustained energy. Consider having a small portion, like a grilled chicken/turkey slice, about an hour before your workout.

            2. **Greek Yogurt with Berries**: While fruits are generally high in carbohydrates, a small handful of berries like blueberries combined with unsweetened Greek yogurt can provide an antioxidant boost and moderate carbs. The protein from the yogurt will help sustain energy.

            3. **Hard-Boiled Eggs**: Eggs are a compact protein source. Consuming a couple of hard-boiled eggs can help keep your energy levels up without spiking your blood sugar.

            4. **Nuts or Nut Butter**: Small amounts of nuts, like almonds or walnuts, or a spoonful of nut butter can provide healthy fats and protein. They're also convenient and easy to carry.

            5. **Cheese Sticks or Slices**: Cheese is low in carbohydrates and a good protein source. Opt for low-fat cheese if you're concerned about saturated fats.

            6. **Tuna Salad**: A small portion of tuna mixed with a bit of olive oil or mayonnaise can provide a good mix of protein and healthy fats. You can have it on a slice of cucumber or lettuce wrap.

            7. **Beef Jerky**: Look for a low-sodium, low-sugar variety. It’s high in protein and can be an excellent pre-workout snack.

            Remember to monitor your blood sugar levels before and after your workout to ensure they stay within your target range. Drink plenty of water to stay hydrated, especially during workouts. Adjust portions according to your specific energy needs and preferences. Always consult with your healthcare provider or a dietitian when making significant changes to your diet, especially with a condition like diabetes.

            using: gpt-4o@en^^<xsd:string>
                ", entities=[{'gtask': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                What Generative Task generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200744_624?
                '''
ic| entities:                                                gtask  \
              0  http://testwebsite/testProgram#Generative_Task...

                                                              glbl
              0  Extracts important entities for
              text: Before...
ic| answer: GTAnswer(answer_nlp="
                The Generative Task that generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200744_624 is

                Generative Task | glbl
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397 | Extracts important entities for
            text: Before your workout, it's essential to eat foods that provide a quick energy boost while being mindful of your diabetes management. Since your diet preference is carnivorous, let's focus on protein-rich and low-carb options that are also easy on your blood sugar levels.

            1. **Chicken or Turkey Breast**: Lean poultry is an excellent source of protein and can provide sustained energy. Consider having a small portion, like a grilled chicken/turkey slice, about an hour before your workout.

            2. **Greek Yogurt with Berries**: While fruits are generally high in carbohydrates, a small handful of berries like blueberries combined with unsweetened Greek yogurt can provide an antioxidant boost and moderate carbs. The protein from the yogurt will help sustain energy.

            3. **Hard-Boiled Eggs**: Eggs are a compact protein source. Consuming a couple of hard-boiled eggs can help keep your energy levels up without spiking your blood sugar.

            4. **Nuts or Nut Butter**: Small amounts of nuts, like almonds or walnuts, or a spoonful of nut butter can provide healthy fats and protein. They're also convenient and easy to carry.

            5. **Cheese Sticks or Slices**: Cheese is low in carbohydrates and a good protein source. Opt for low-fat cheese if you're concerned about saturated fats.

            6. **Tuna Salad**: A small portion of tuna mixed with a bit of olive oil or mayonnaise can provide a good mix of protein and healthy fats. You can have it on a slice of cucumber or lettuce wrap.

            7. **Beef Jerky**: Look for a low-sodium, low-sugar variety. It’s high in protein and can be an excellent pre-workout snack.

            Remember to monitor your blood sugar levels before and after your workout to ensure they stay within your target range. Drink plenty of water to stay hydrated, especially during workouts. Adjust portions according to your specific energy needs and preferences. Always consult with your healthcare provider or a dietitian when making significant changes to your diet, especially with a condition like diabetes.

            using: gpt-4o@en^^<xsd:string>
                ", entities=[{'gtask': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                What Generative Task generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200744_720?
                '''
ic| entities:                                                gtask  \
              0  http://testwebsite/testProgram#Generative_Task...

                                                              glbl
              0  Extracts important entities for
              text: Before...
ic| answer: GTAnswer(answer_nlp="
                The Generative Task that generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200744_720 is

                Generative Task | glbl
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397 | Extracts important entities for
            text: Before your workout, it's essential to eat foods that provide a quick energy boost while being mindful of your diabetes management. Since your diet preference is carnivorous, let's focus on protein-rich and low-carb options that are also easy on your blood sugar levels.

            1. **Chicken or Turkey Breast**: Lean poultry is an excellent source of protein and can provide sustained energy. Consider having a small portion, like a grilled chicken/turkey slice, about an hour before your workout.

            2. **Greek Yogurt with Berries**: While fruits are generally high in carbohydrates, a small handful of berries like blueberries combined with unsweetened Greek yogurt can provide an antioxidant boost and moderate carbs. The protein from the yogurt will help sustain energy.

            3. **Hard-Boiled Eggs**: Eggs are a compact protein source. Consuming a couple of hard-boiled eggs can help keep your energy levels up without spiking your blood sugar.

            4. **Nuts or Nut Butter**: Small amounts of nuts, like almonds or walnuts, or a spoonful of nut butter can provide healthy fats and protein. They're also convenient and easy to carry.

            5. **Cheese Sticks or Slices**: Cheese is low in carbohydrates and a good protein source. Opt for low-fat cheese if you're concerned about saturated fats.

            6. **Tuna Salad**: A small portion of tuna mixed with a bit of olive oil or mayonnaise can provide a good mix of protein and healthy fats. You can have it on a slice of cucumber or lettuce wrap.

            7. **Beef Jerky**: Look for a low-sodium, low-sugar variety. It’s high in protein and can be an excellent pre-workout snack.

            Remember to monitor your blood sugar levels before and after your workout to ensure they stay within your target range. Drink plenty of water to stay hydrated, especially during workouts. Adjust portions according to your specific energy needs and preferences. Always consult with your healthcare provider or a dietitian when making significant changes to your diet, especially with a condition like diabetes.

            using: gpt-4o@en^^<xsd:string>
                ", entities=[{'gtask': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                What Generative Task generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200744_854?
                '''
ic| entities:                                                gtask  \
              0  http://testwebsite/testProgram#Generative_Task...

                                                              glbl
              0  Extracts important entities for
              text: Before...
ic| answer: GTAnswer(answer_nlp="
                The Generative Task that generated the data that was used by the execution http://testwebsite/testProgram#id_20260412200744_854 is

                Generative Task | glbl
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397 | Extracts important entities for
            text: Before your workout, it's essential to eat foods that provide a quick energy boost while being mindful of your diabetes management. Since your diet preference is carnivorous, let's focus on protein-rich and low-carb options that are also easy on your blood sugar levels.

            1. **Chicken or Turkey Breast**: Lean poultry is an excellent source of protein and can provide sustained energy. Consider having a small portion, like a grilled chicken/turkey slice, about an hour before your workout.


In [24]:
# Input port data created by AI 

_spec = [{
    "func_desc":"sparql query post processing",
    "func_desc_term":"Post-processes the query results"
}, {
    "func_desc": "system prompt template",
    "func_desc_term":"Generates a system prompt"
}, {
    "func_desc": "information extraction",
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc": "sparql query function",
    "func_desc_term": "Builds SPARQL queries to extract"
}, {
    "func_desc": "llm chat function",
    "func_desc_term": "Chat with the LLM"
}]

template_spec = []
sparql_spec = []

for _s in _spec:
    exe_query = """
    SELECT DISTINCT ?exe
    WHERE {
        ?obj dc:description ?desc .
        ?obj rdfs:label ?flbl .
        FILTER(REGEX(?desc, "{func_desc_term}","i"))
        
        ?asso prov:hadPlan ?obj .
        ?exe prov:qualifiedAssociation ?asso .      
        
        }
    """
    executions = graph_manager.query(
        regex_add_strings(exe_query, func_desc_term = _s["func_desc_term"])
    )


    for obj in executions.to_dict("records"):
        usage_query = """
        SELECT DISTINCT ?usage ?lbl
        WHERE {
            <{exe_id}> prov:qualifiedUsage ?usage .
            ?usage provone:hadInPort ?port .
            ?port rdfs:label ?lbl .
            }
        """
        usages = graph_manager.query(
                regex_add_strings(
                    usage_query,
                    exe_id = obj["exe"]
                )
            )
        
        for usage in usages.to_dict("records"):
            # df = graph_manager.query(
            #     regex_add_strings(
            #         sparql_template,
            #         exe_id = obj["exe"],
            #         port_label = usage["lbl"].split("@")[0]
            #     )
            # )

            # print(df)
            
            template_spec.append({
                "exe_id":obj['exe'],
                "port_label" : usage["lbl"].split("@")[0]
            })
            
            sparql_spec.append({
                "exe_id":obj['exe'],
                "port_label" : usage["lbl"].split("@")[0]
            })
            
question_template = """
Was the input to the {port_label} in the execution {exe_id} generated by a Generative Task?
"""

sparql_template = """
SELECT DISTINCT ?plbl ?gtask2
            WHERE {
                <{exe_id}> prov:qualifiedUsage ?usage .
                ?usage provone:hadInPort ?port .
                ?port rdfs:label ?plbl .
                FILTER(REGEX(?plbl, "{port_label}","i"))
                
                ?usage provone:hadEntity ?data .
                OPTIONAL {
                    ?llm_out sio:SIO_000202 ?data .
                    ?llm_out sio:SIO_000232 ?llm .
                    ?gtask prov:used ?llm .
                }
                
                BIND(COALESCE(?gtask, "None") AS ?gtask2)
        }
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The input to the {port_label} in the execution {exe_id} {decision} generated by a 
    Generative Task

    {answer_inst}
    """
    
    _ent = entities[['gtask2']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            'gtask2': "Generative Task"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        exe_id = question_specs["exe_id"],
        port_label = question_specs["port_label"],
        decision = "was" if _ent['gtask2'].tolist()[0] != "None" else "was not",
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    gt.qtype = ["single", "bool"]
gt_list.extend(gts)

ic| rquestion: '''
                Was the input to the Post-processing input port: kg_knowledge in the execution http://testwebsite/testProgram#id_20260412200745_507 generated by a Generative Task?
                '''
ic| entities:                                                 plbl gtask2
              0  Post-processing input port: kg_knowledge@en^^<...   None
ic| answer: GTAnswer(answer_nlp='
                The input to the Post-processing input port: kg_knowledge in the execution http://testwebsite/testProgram#id_20260412200745_507 was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the Input port for gender in the execution http://testwebsite/testProgram#id_20260412200734_778 generated by a Generative Task?
                '''
ic| entities:                                      plbl gtask2
              0  Input port for gender@en^^<xsd:string>   None

ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for gender in the execution http://testwebsite/testProgram#id_20260412200734_778 was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the Input port for height in the execution http://testwebsite/testProgram#id_20260412200734_778 generated by a Generative Task?
                '''
ic| entities:                                      plbl gtask2
              0  Input port for height@en^^<xsd:string>   None
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for height in the execution http://testwebsite/testProgram#id_20260412200734_778 was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the Input port for allergies in the execution http://testwebsite/testProgram#id_20260412200734_778 generated by a Generative Task?
                '''
ic| entities:                                         plbl gtask2
              0  Input port for allergies@en^^<xsd:string>   None
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for allergies in the execution http://testwebsite/testProgram#id_20260412200734_778 was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the Input port for foodPreferences in the execution http://testwebsite/testProgram#id_20260412200734_778 generated by a Generative Task?
                '''
ic| entities:                                               plbl gtask2
              0  Input port for foodPreferences@en^^<xsd:string>   None
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for foodPreferences in the execution http://testwebsite/testProgram#id_20260412200734_778 was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the Input port for bodyMassIndex in the execution http://testwebsite/testProgram#id_20260412200734_778 generated by a Generative Task?
                '''
ic| entities:                                             plbl gtask2
              0  Input port for bodyMassIndex@en^^<xsd:string>   None
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for bodyMassIndex in the execution http://testwebsite/testProgram#id_20260412200734_778 was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the Input port for age in the execution http://testwebsite/testProgram#id_20260412200734_778 generated by a Generative Task?
                '''
ic| entities:                                   plbl gtask2
              0  Input port for age@en^^<xsd:string>   None
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for age in the execution http://testwebsite/testProgram#id_20260412200734_778 was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the Input port for weight in the execution http://testwebsite/testProgram#id_20260412200734_778 generated by a Generative Task?
                '''
ic| entities:                                      plbl gtask2
              0  Input port for weight@en^^<xsd:string>   None
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for weight in the execution http://testwebsite/testProgram#id_20260412200734_778 was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the Input port for diagnosis in the execution http://testwebsite/testProgram#id_20260412200734_778 generated by a Generative Task?
                '''
ic| entities:                                         plbl gtask2
              0  Input port for diagnosis@en^^<xsd:string>   None
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for diagnosis in the execution http://testwebsite/testProgram#id_20260412200734_778 was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the Input port for text in the execution http://testwebsite/testProgram#id_20260412200742_397 generated by a Generative Task?
                '''
ic| entities:                                    plbl  \
              0  Input port for text@en^^<xsd:string>

                                                            gtask2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for text in the execution http://testwebsite/testProgram#id_20260412200742_397 was generated by a
                Generative Task

                Generative Task
            http://testwebsite/testProgram#Generative_Task-id_20260412200740_99
                ', entities=[{'gtask2': 'http://testwebsite/testProgram#Generative_Task-id_20260412200740_99'}])
ic| rquestion: '''
                Was the input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200743_103 generated by a Generative Task?
                '''
ic| entities:                                      plbl  \
              0  Input port for entity@en^^<xsd:string>

                                                            gtask2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200743_103 was generated by a
                Generative Task

                Generative Task
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397
                ', entities=[{'gtask2': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                Was the input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200743_290 generated by a Generative Task?
                '''
ic| entities:                                      plbl  \
              0  Input port for entity@en^^<xsd:string>

                                                            gtask2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200743_290 was generated by a
                Generative Task

                Generative Task
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397
                ', entities=[{'gtask2': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                Was the input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200743_818 generated by a Generative Task?
                '''
ic| entities:                                      plbl  \
              0  Input port for entity@en^^<xsd:string>

                                                            gtask2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200743_818 was generated by a
                Generative Task

                Generative Task
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397
                ', entities=[{'gtask2': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                Was the input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200743_952 generated by a Generative Task?
                '''
ic| entities:                                      plbl  \
              0  Input port for entity@en^^<xsd:string>

                                                            gtask2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200743_952 was generated by a
                Generative Task

                Generative Task
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397
                ', entities=[{'gtask2': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                Was the input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200744_221 generated by a Generative Task?
                '''
ic| entities:                                      plbl  \
              0  Input port for entity@en^^<xsd:string>

                                                            gtask2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200744_221 was generated by a
                Generative Task

                Generative Task
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397
                ', entities=[{'gtask2': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                Was the input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200744_387 generated by a Generative Task?
                '''
ic| entities:                                      plbl  \
              0  Input port for entity@en^^<xsd:string>

                                                            gtask2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200744_387 was generated by a
                Generative Task

                Generative Task
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397
                ', entities=[{'gtask2': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                Was the input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200744_460 generated by a Generative Task?
                '''
ic| entities:                                      plbl  \
              0  Input port for entity@en^^<xsd:string>

                                                            gtask2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200744_460 was generated by a
                Generative Task

                Generative Task
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397
                ', entities=[{'gtask2': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                Was the input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200744_624 generated by a Generative Task?
                '''
ic| entities:                                      plbl  \
              0  Input port for entity@en^^<xsd:string>

                                                            gtask2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200744_624 was generated by a
                Generative Task

                Generative Task
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397
                ', entities=[{'gtask2': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                Was the input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200744_720 generated by a Generative Task?
                '''
ic| entities:                                      plbl  \
              0  Input port for entity@en^^<xsd:string>

                                                            gtask2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200744_720 was generated by a
                Generative Task

                Generative Task
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397
                ', entities=[{'gtask2': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                Was the input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200744_854 generated by a Generative Task?
                '''
ic| entities:                                      plbl  \
              0  Input port for entity@en^^<xsd:string>

                                                            gtask2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200744_854 was generated by a
                Generative Task

                Generative Task
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397
                ', entities=[{'gtask2': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                Was the input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200744_909 generated by a Generative Task?
                '''
ic| entities:                                      plbl  \
              0  Input port for entity@en^^<xsd:string>

                                                            gtask2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200744_909 was generated by a
                Generative Task

                Generative Task
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397
                ', entities=[{'gtask2': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                Was the input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200745_467 generated by a Generative Task?
                '''
ic| entities:                                      plbl  \
              0  Input port for entity@en^^<xsd:string>

                                                            gtask2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200745_467 was generated by a
                Generative Task

                Generative Task
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397
                ', entities=[{'gtask2': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                Was the input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200745_473 generated by a Generative Task?
                '''
ic| entities:                                      plbl  \
              0  Input port for entity@en^^<xsd:string>

                                                            gtask2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The input to the Input port for entity in the execution http://testwebsite/testProgram#id_20260412200745_473 was generated by a
                Generative Task

                Generative Task
            http://testwebsite/testProgram#Generative_Task-id_20260412200742_397
                ', entities=[{'gtask2': 'http://testwebsite/testProgram#Generative_Task-id_20260412200742_397'}])
ic| rquestion: '''
                Was the input to the LLM Chat input port: system_prompt in the execution http://testwebsite/testProgram#id_20260412200740_99 generated by a Generative Task?
                '''
ic| entities:                                                 plbl gtask2
              0  LLM Chat input port: system_prompt@en^^<xsd:st...   None
ic| answer: GTAnswer(answer_nlp='
                The input to the LLM Chat input port: system_prompt in the execution http://testwebsite/testProgram#id_20260412200740_99 was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the LLM Chat input port: user_prompt in the execution http://testwebsite/testProgram#id_20260412200740_99 generated by a Generative Task?
                '''
ic| entities:                                                 plbl gtask2
              0  LLM Chat input port: user_prompt@en^^<xsd:string>   None
ic| answer: GTAnswer(answer_nlp='
                The input to the LLM Chat input port: user_prompt in the execution http://testwebsite/testProgram#id_20260412200740_99 was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])

In [25]:
# Input port data created by AI 

_spec = [{
    "func_desc":"sparql query post processing",
    "func_desc_term":"Post-processes the query results"
}, {
    "func_desc": "system prompt template",
    "func_desc_term":"Generates a system prompt"
}, {
    "func_desc": "information extraction",
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc": "sparql query function",
    "func_desc_term": "Builds SPARQL queries to extract"
}, {
    "func_desc": "llm chat function",
    "func_desc_term": "Chat with the LLM"
}]

sparql_template = """
SELECT DISTINCT ?plbl ?gtask2
            WHERE {
                <{exe_id}> prov:qualifiedUsage ?usage .
                ?usage provone:hadInPort ?port .
                ?port rdfs:label ?plbl .
                FILTER(REGEX(?plbl, "{port_label}","i"))
                
                ?usage provone:hadEntity ?data .
                OPTIONAL {
                    ?llm_out sio:SIO_000202 ?data .
                    ?llm_out sio:SIO_000232 ?llm .
                    ?gtask prov:used ?llm .
                }
                
                BIND(COALESCE(?gtask, "None") AS ?gtask2)
        }
"""

template_spec = []
sparql_spec = []

for _s in _spec:
    exe_query = """
    SELECT DISTINCT ?exe
    WHERE {
        ?obj dc:description ?desc .
        ?obj rdfs:label ?flbl .
        FILTER(REGEX(?desc, "{func_desc_term}","i"))
        
        ?asso prov:hadPlan ?obj .
        ?exe prov:qualifiedAssociation ?asso .      
        
        }
    """
    executions = graph_manager.query(
        regex_add_strings(exe_query, func_desc_term = _s["func_desc_term"])
    )


    for obj in executions.to_dict("records"):
        usage_query = """
        SELECT DISTINCT ?usage ?lbl
        WHERE {
            <{exe_id}> prov:qualifiedUsage ?usage .
            ?usage provone:hadInPort ?port .
            ?port rdfs:label ?lbl .
            }
        """
        usages = graph_manager.query(
                regex_add_strings(
                    usage_query,
                    exe_id = obj["exe"]
                )
            )
        
        for usage in usages.to_dict("records"):
            df = graph_manager.query(
                regex_add_strings(
                    sparql_template,
                    exe_id = obj["exe"],
                    port_label = usage["lbl"].split("@")[0]
                )
            )

            print(df)
            
            template_spec.append({
                "exe_id":obj['exe'],
                "port_label" : usage["lbl"].split("@")[0]
            })
            
            sparql_spec.append({
                "exe_id":obj['exe'],
                "port_label" : usage["lbl"].split("@")[0]
            })

                                                plbl gtask2
0  Post-processing input port: kg_knowledge@en^^<...   None
                                     plbl gtask2
0  Input port for gender@en^^<xsd:string>   None
                                     plbl gtask2
0  Input port for height@en^^<xsd:string>   None
                                        plbl gtask2
0  Input port for allergies@en^^<xsd:string>   None
                                              plbl gtask2
0  Input port for foodPreferences@en^^<xsd:string>   None
                                            plbl gtask2
0  Input port for bodyMassIndex@en^^<xsd:string>   None
                                  plbl gtask2
0  Input port for age@en^^<xsd:string>   None
                                     plbl gtask2
0  Input port for weight@en^^<xsd:string>   None
                                        plbl gtask2
0  Input port for diagnosis@en^^<xsd:string>   None
                                   plbl  \
0  Input port for text@en^^<xsd:string>

                                              gtask2
0  http://testwebsite/testProgram#Generative_Task...
                                     plbl  \
0  Input port for entity@en^^<xsd:string>

                                              gtask2
0  http://testwebsite/testProgram#Generative_Task...
                                     plbl  \
0  Input port for entity@en^^<xsd:string>

                                              gtask2
0  http://testwebsite/testProgram#Generative_Task...
                                     plbl  \
0  Input port for entity@en^^<xsd:string>

                                              gtask2
0  http://testwebsite/testProgram#Generative_Task...
                                     plbl  \
0  Input port for entity@en^^<xsd:string>

                                              gtask2
0  http://testwebsite/testProgram#Generative_Task...
                                     plbl  \
0  Input port for entity@en^^<xsd:string>

                                              gtask2
0  http://testwebsite/testProgram#Generative_Task...
                                     plbl  \
0  Input port for entity@en^^<xsd:string>

                                              gtask2
0  http://testwebsite/testProgram#Generative_Task...
                                     plbl  \
0  Input port for entity@en^^<xsd:string>

                                              gtask2
0  http://testwebsite/testProgram#Generative_Task...
                                     plbl  \
0  Input port for entity@en^^<xsd:string>

                                              gtask2
0  http://testwebsite/testProgram#Generative_Task...
                                     plbl  \
0  Input port for entity@en^^<xsd:string>

                                              gtask2
0  http://testwebsite/testProgram#Generative_Task...
                                     plbl  \
0  Input port for entity@en^^<xsd:string>

                                              gtask2
0  http://testwebsite/testProgram#Generative_Task...
                                     plbl  \
0  Input port for entity@en^^<xsd:string>

                                              gtask2
0  http://testwebsite/testProgram#Generative_Task...
                                     plbl  \
0  Input port for entity@en^^<xsd:string>

                                              gtask2
0  http://testwebsite/testProgram#Generative_Task...
                                     plbl  \
0  Input port for entity@en^^<xsd:string>

                                              gtask2
0  http://testwebsite/testProgram#Generative_Task...
                                                plbl gtask2
0  LLM Chat input port: system_prompt@en^^<xsd:st...   None
                                                plbl gtask2
0  LLM Chat input port: user_prompt@en^^<xsd:string>   None

In [26]:
# execution + port + was data

In [27]:
# Question MULT 13 : Does a specific execution contain a Generative Task

In [28]:
# what are the output data of the generative task that was used within an execution task

In [29]:
# what are the  input data used by generative tasks that were used within an execution task

In [30]:
#

In [31]:
os.makedirs(os.path.dirname(config.gt.save_loc), exist_ok=True)
for i, gt in enumerate(gt_list):
    gt.id = f"gt_{i}"

# common_utils.serialization.save_json(
#     {gt.id: gt.model_dump() for gt in gt_list}, config.gt.save_loc
# )

In [32]:
gt_list

[GT(id='gt_0', question='\nHow many unique "experiment execution" are there in this?\n', answer='The answer to the question is 1 unique executions.', entities=[{'obj_count': '1'}], sparql_querys=[SPARQLTemplate(template='\nSELECT (count(distinct ?ids) AS ?obj_count)\nWHERE {\n     ?obj a provone:Execution ;\n          dcterms:identifier ?ids .\n}\n', description='This SPARQL query counts the number of unique executions by counting distinct identifiers in the provone:Execution class.', inputs=None)], qtype=['single', 'numeric'], decision=None, tags={}),
 GT(id='gt_1', question='\nIn what places do we utilize AI in this workflow?\n', answer="\nThe ChatBS System utilizes LLMs to generate the following functions\n\n1. Information extraction function\n2. System Prompt template function\n3. Sparql result post processing function\n\nand further it's used within functions to\n1. Generate the LLM outputs,\n2. Used to extract key information from the system.\n", entities=[{'obj': 'ChatBS-NexGen:Generative_Task-id_20260412200740_99', 'desc': 'LLM Generates an text for \nsystem prompt: You are a health care assistant and you will respond to the user who is 30 years old, identifies as Male, diagnosed with Diabetic. Consider their height: 182.3, weight: 95.2, body mass index: 28.6, food preferences: Carnivore, and allergies: None when providing a dietary guideline. \n\nuser prompt: I need suggestions for light and energy-boosting foods to eat before my gym workout. \n\nusing: gpt-4o@en^^<xsd:string>'}, {'obj': 'ChatBS-NexGen:Generative_Task-id_20260412200742_397', 'desc': "Extracts important entities for \ntext: Before your workout, it's essential to eat foods that provide a quick energy boost while being mindful of your diabetes management. Since your diet preference is carnivorous, let's focus on protein-rich and low-carb options that are also easy on your blood sugar levels.\n\n1. **Chicken or Turkey Breast**: Lean poultry is an excellent source of protein and can provide sustained energy. Consider having a small portion, like a grilled chicken/turkey slice, about an hour before your workout.\n\n2. **Greek Yogurt with Berries**: While fruits are generally high in carbohydrates, a small handful of berries like blueberries combined with unsweetened Greek yogurt can provide an antioxidant boost and moderate carbs. The protein from the yogurt will help sustain energy.\n\n3. **Hard-Boiled Eggs**: Eggs are a compact protein source. Consuming a couple of hard-boiled eggs can help keep your energy levels up without spiking your blood sugar.\n\n4. **Nuts or Nut Butter**: Small amounts of nuts, like almonds or walnuts, or a spoonful of nut butter can provide healthy fats and protein. They're also convenient and easy to carry.\n\n5. **Cheese Sticks or Slices**: Cheese is low in carbohydrates and a good protein source. Opt for low-fat cheese if you're concerned about saturated fats.\n\n6. **Tuna Salad**: A small portion of tuna mixed with a bit of olive oil or mayonnaise can provide a good mix of protein and healthy fats. You can have it on a slice of cucumber or lettuce wrap.\n\n7. **Beef Jerky**: Look for a low-sodium, low-sugar variety. It’s high in protein and can be an excellent pre-workout snack.\n\nRemember to monitor your blood sugar levels before and after your workout to ensure they stay within your target range. Drink plenty of water to stay hydrated, especially during workouts. Adjust portions according to your specific energy needs and preferences. Always consult with your healthcare provider or a dietitian when making significant changes to your diet, especially with a condition like diabetes. \n\nusing: gpt-4o@en^^<xsd:string>"}, {'obj': 'ChatBS-NexGen:Generative_Task-information_extractor', 'desc': 'Generates the Information Extractor Function using Large language models@en^^<xsd:string>'}, {'obj': 'ChatBS-NexGen:Generative_Task-query_result_post_processor', 'desc': 'Generates the post processing Function using Large language models@en^^<xsd:string>'}, {'obj': 'ChatBS-NexGen:Generative_Task-system_prompt_generator', 'desc': 'Generates the System Prompt Template using Large language models@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?obj ?desc\nWHERE {\n     ?obj a workflow:Generative_Task .\n     ?obj dc:description ?desc .\n}\n', description='', inputs=None)], qtype=['multi', 'entity'], decision=None, tags={}),
 GT(id='gt_2', question='\nWhat are the extracted KG entities for the execution with id 1_1\n', answer='\nThe retrieved entities from the knowledge graph includes the following ingredients,\n\n1. Yogurt\n2. Berry\n3. Cheese\n4. Carrot\n5. Turkey\n6. Bell pepper\n7. Hummus\n8. Almond\n9. Avocado\n10. Pumpkin seed\n11. Water\n12. Pineapple\n13. Cottage cheese\n', entities=['Tuna', 'Olive oil', 'Chicken', 'Lettuce', 'Berry', 'Turkey', 'Cheese', 'Mayonnaise'], sparql_querys=[SPARQLTemplate(template='\nSELECT DISTINCT ?member ?prop ?value\nWHERE {\n     ?obj dc:description ?desc .\n     FILTER(REGEX(?desc, "SPARQL queries to extract information", "i"))\n\n     ?obj a provone:Program .\n     ?exe prov:qualifiedAssociation/prov:hadPlan ?obj .\n     ?exe dcterms:identifier ?id .\n     FILTER(REGEX(?id, "1_1", "i"))\n\n     ?data prov:wasGeneratedBy ?exe .\n     ?data a ?class .\n\n     {\n         ?data a provone:Collection .\n         ?data provone:hadMember ?member .\n         ?member ?prop ?value .\n     }\n     UNION\n     {\n         ?data a provone:Data .\n         BIND(?data AS ?member)\n         ?data ?prop ?value .\n     }\n}\n', description='', inputs=None)], qtype=['multi', 'literal'], decision=None, tags={}),
 GT(id='gt_3', question='\nwhy did some ingredients have missing values for `sugarG` and `ingredientCat` columns in the final output of the workflow?\n', answer="\nDue to the fact that some information is not available in the knowledge graph for ingredients such as\n'Turkey', 'Hummus', 'Cheese', 'Cottage cheese', 'Berry', 'Water' the sugarG and ingredientCat is not available.\n", entities=['Tuna', 'Olive oil', 'Chicken', 'Berry', 'Turkey', 'Cheese', 'Mayonnaise'], sparql_querys=[SPARQLTemplate(template='\nSELECT DISTINCT ?member ?prop ?value\nWHERE {\n     ?obj dc:description ?desc .\n     FILTER(REGEX(?desc, "SPARQL queries to extract information", "i"))\n\n     ?obj a provone:Program .\n     ?exe prov:qualifiedAssociation/prov:hadPlan ?obj .\n     ?exe dcterms:identifier ?id .\n     FILTER(REGEX(?id, "1_1", "i"))\n\n     ?data prov:wasGeneratedBy ?exe .\n     ?data a ?class .\n\n     {\n         ?data a provone:Collection .\n         ?data provone:hadMember ?member .\n         ?member ?prop ?value .\n     }\n     UNION\n     {\n         ?data a provone:Data .\n         BIND(?data AS ?member)\n         ?data ?prop ?value .\n     }\n}\n\norder by ?member ?prop\n', description='', inputs=None)], qtype=['multi', 'literal'], decision=None, tags={}),
 GT(id='gt_4', question='\nwhat are the instructions used by the LLM to generate the sparql query post processing function step in the pipeline?\n', answer="\n    We utilize the following input instructions to generate the function responsible for sparql query post processing.\n\n    Funtion | Instruction for function generation\nhttp://testwebsite/testProgram#query_result_post_processor | Concat all the rows into single row at each column by '|' concatenation marker.@en^^<xsd:string>\nhttp://testwebsite/testProgram#query_result_post_processor | If there are duplicate ingredients then select row with most information on `sugarG` and `ingredientCat` columns. Fill all the missing values with '0' in `sugarG` column and with '-' in 'ingredientCat` column.@en^^<xsd:string>\n    ", entities=[{'obj': 'http://testwebsite/testProgram#query_result_post_processor', 'inpd': "Concat all the rows into single row at each column by '|' concatenation marker.@en^^<xsd:string>"}, {'obj': 'http://testwebsite/testProgram#query_result_post_processor', 'inpd': "If there are duplicate ingredients then select row with most information on `sugarG` and `ingredientCat` columns. Fill all the missing values with '0' in `sugarG` column and with '-' in 'ingredientCat` column.@en^^<xsd:string>"}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?obj ?llm ?inpd\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Post-processes the query results","i"))\n\n     ?llm_out sio:SIO_000202 ?obj .\n     ?llm_out sio:SIO_000232 ?llm .\n     ?llm sio:SIO_000230 ?inp .\n     ?inp prov:value ?inpd\n}\n', description='', inputs=None)], qtype=['multi', 'entity', 'literal'], decision=None, tags={}),
 GT(id='gt_5', question='\nwhat are the instructions used by the LLM to generate the system prompt template function step in the pipeline?\n', answer='\n    We utilize the following input instructions to generate the function responsible for system prompt template.\n\n    Funtion | Instruction for function generation\nhttp://testwebsite/testProgram#system_prompt_generator | You are a health care assistant@en^^<xsd:string>\nhttp://testwebsite/testProgram#system_prompt_generator | gpt-4o@en^^<xsd:string>\n    ', entities=[{'obj': 'http://testwebsite/testProgram#system_prompt_generator', 'inpd': 'You are a health care assistant@en^^<xsd:string>'}, {'obj': 'http://testwebsite/testProgram#system_prompt_generator', 'inpd': 'gpt-4o@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?obj ?llm ?inpd\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Generates a system prompt","i"))\n\n     ?llm_out sio:SIO_000202 ?obj .\n     ?llm_out sio:SIO_000232 ?llm .\n     ?llm sio:SIO_000230 ?inp .\n     ?inp prov:value ?inpd\n}\n', description='', inputs=None)], qtype=['multi', 'entity', 'literal'], decision=None, tags={}),
 GT(id='gt_6', question='\nwhat are the instructions used by the LLM to generate the information extraction function step in the pipeline?\n', answer="\n    We utilize the following input instructions to generate the function responsible for information extraction.\n\n    Funtion | Instruction for function generation\nhttp://testwebsite/testProgram#information_extractor | gpt-4o@en^^<xsd:string>\nhttp://testwebsite/testProgram#information_extractor | Extract all the main ingredients without any subsidiary; return in singular noun form and First letter capital. Extract mean and dairy product in its' base form. (e.g., from 'egg white' extract 'Egg')@en^^<xsd:string>\n    ", entities=[{'obj': 'http://testwebsite/testProgram#information_extractor', 'inpd': 'gpt-4o@en^^<xsd:string>'}, {'obj': 'http://testwebsite/testProgram#information_extractor', 'inpd': "Extract all the main ingredients without any subsidiary; return in singular noun form and First letter capital. Extract mean and dairy product in its' base form. (e.g., from 'egg white' extract 'Egg')@en^^<xsd:string>"}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?obj ?llm ?inpd\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Extracts entities or relevant information","i"))\n\n     ?llm_out sio:SIO_000202 ?obj .\n     ?llm_out sio:SIO_000232 ?llm .\n     ?llm sio:SIO_000230 ?inp .\n     ?inp prov:value ?inpd\n}\n', description='', inputs=None)], qtype=['multi', 'entity', 'literal'], decision=None, tags={}),
 GT(id='gt_7', question='\nwhat are the input parameters of the function used in sparql query post processing step in the pipeline?\n', answer='\n    The input parameters to sparql query post processing function.\n\n    Funtion name | Function returns\nQuery Result Post-Processor@en^^<xsd:string> | Post-processing input port: kg_knowledge@en^^<xsd:string>\n    ', entities=[{'flbl': 'Query Result Post-Processor@en^^<xsd:string>', 'lbl': 'Post-processing input port: kg_knowledge@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Post-processes the query results","i"))\n\n     ?obj provone:hasInPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], qtype=['multi', 'literal'], decision=None, tags={}),
 GT(id='gt_8', question='\nwhat are the input parameters of the function used in system prompt template step in the pipeline?\n', answer='\n    The input parameters to system prompt template function.\n\n    Funtion name | Function returns\nSystem Prompt Template Generator@en^^<xsd:string> | Input port for age@en^^<xsd:string>\nSystem Prompt Template Generator@en^^<xsd:string> | Input port for allergies@en^^<xsd:string>\nSystem Prompt Template Generator@en^^<xsd:string> | Input port for bodyMassIndex@en^^<xsd:string>\nSystem Prompt Template Generator@en^^<xsd:string> | Input port for diagnosis@en^^<xsd:string>\nSystem Prompt Template Generator@en^^<xsd:string> | Input port for foodPreferences@en^^<xsd:string>\nSystem Prompt Template Generator@en^^<xsd:string> | Input port for gender@en^^<xsd:string>\nSystem Prompt Template Generator@en^^<xsd:string> | Input port for height@en^^<xsd:string>\nSystem Prompt Template Generator@en^^<xsd:string> | Input port for weight@en^^<xsd:string>\n    ', entities=[{'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for age@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for allergies@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for bodyMassIndex@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for diagnosis@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for foodPreferences@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for gender@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for height@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for weight@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Generates a system prompt","i"))\n\n     ?obj provone:hasInPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], qtype=['multi', 'literal'], decision=None, tags={}),
 GT(id='gt_9', question='\nwhat are the input parameters of the function used in information extraction step in the pipeline?\n', answer='\n    The input parameters to information extraction function.\n\n    Funtion name | Function returns\nInformation Extractor@en^^<xsd:string> | Input port for text@en^^<xsd:string>\n    ', entities=[{'flbl': 'Information Extractor@en^^<xsd:string>', 'lbl': 'Input port for text@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Extracts entities or relevant information","i"))\n\n     ?obj provone:hasInPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], qtype=['multi', 'literal'], decision=None, tags={}),
 GT(id='gt_10', question='\nwhat are the input parameters of the function used in sparql query function step in the pipeline?\n', answer='\n    The input parameters to sparql query function function.\n\n    Funtion name | Function returns\nSPARQL Query Builder@en^^<xsd:string> | Input port for entity@en^^<xsd:string>\n    ', entities=[{'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'lbl': 'Input port for entity@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Builds SPARQL","i"))\n\n     ?obj provone:hasInPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], qtype=['multi', 'literal'], decision=None, tags={}),
 GT(id='gt_11', question='\nwhat are the input parameters of the function used in llm chat function step in the pipeline?\n', answer='\n    The input parameters to llm chat function function.\n\n    Funtion name | Function returns\nLLM Chat@en^^<xsd:string> | LLM Chat input port: system_prompt@en^^<xsd:string>\nLLM Chat@en^^<xsd:string> | LLM Chat input port: user_prompt@en^^<xsd:string>\n    ', entities=[{'flbl': 'LLM Chat@en^^<xsd:string>', 'lbl': 'LLM Chat input port: system_prompt@en^^<xsd:string>'}, {'flbl': 'LLM Chat@en^^<xsd:string>', 'lbl': 'LLM Chat input port: user_prompt@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Chat with","i"))\n\n     ?obj provone:hasInPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], qtype=['multi', 'literal'], decision=None, tags={}),
 GT(id='gt_12', question='\nwhat are the input parameters of the function used in sparql query post processing step in the pipeline?\n', answer='\n    The input parameters to sparql query post processing function.\n\n    Funtion name | Function returns\nQuery Result Post-Processor@en^^<xsd:string> | Post-processed output port: post_processed_output@en^^<xsd:string>\n    ', entities=[{'flbl': 'Query Result Post-Processor@en^^<xsd:string>', 'lbl': 'Post-processed output port: post_processed_output@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Post-processes the query results","i"))\n\n     ?obj provone:hasOutPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], qtype=['multi', 'literal'], decision=None, tags={}),
 GT(id='gt_13', question='\nwhat are the input parameters of the function used in system prompt template step in the pipeline?\n', answer='\n    The input parameters to system prompt template function.\n\n    Funtion name | Function returns\nSystem Prompt Template Generator@en^^<xsd:string> | System Prompt@en^^<xsd:string>\n    ', entities=[{'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'System Prompt@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Generates a system prompt","i"))\n\n     ?obj provone:hasOutPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], qtype=['multi', 'literal'], decision=None, tags={}),
 GT(id='gt_14', question='\nwhat are the input parameters of the function used in information extraction step in the pipeline?\n', answer='\n    The input parameters to information extraction function.\n\n    Funtion name | Function returns\nInformation Extractor@en^^<xsd:string> | Extracted Entities@en^^<xsd:string>\n    ', entities=[{'flbl': 'Information Extractor@en^^<xsd:string>', 'lbl': 'Extracted Entities@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Extracts entities or relevant information","i"))\n\n     ?obj provone:hasOutPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], qtype=['multi', 'literal'], decision=None, tags={}),