In [25]:
import sys
import logging
from pathlib import Path
from typing import List, Mapping, Sequence, Union, Dict
import pandas as pd
import os

import pandas as pd
import dycomutils as common_utils

repo_root = Path.cwd().resolve()
while repo_root != repo_root.parent and not (repo_root / "src").exists():
    repo_root = repo_root.parent

os.chdir(repo_root)
print(repo_root)
sys.path.append(str(repo_root))

from src.utils.graph_manager import GraphManager
from src.utils.utils import load_config, format_dataframe_to_string, regex_add_strings
from src.config.experiment import ExperimentConfig
from src.experiment.ground_truth import GT, SPARQLTemplate, GTAnswer
from evaluations.test_questions.templates import build_gt_from_template

CONFIG_PATH = "evaluations/calibration/config.yaml"
logging.info(f"Loading config: {CONFIG_PATH}")
lconfig = load_config(CONFIG_PATH)
config = ExperimentConfig.model_validate(lconfig)
config

/home/desild/work/research/LLM-Workflow-Explorer

ExperimentConfig(application=ApplicationInfo(description='The application that utilizes a functional approach to support unittesting of LLMs on user designed prompts. This application contains functions generated by LLMs and functions that utilizes LLM generated output within the system. In this experiments are represented as provone:Executions of provone:Programs (a step of the experiment pipeline) while some of these provone:Programs are generated by LLM as Generative_Tasks. dc:identifier represents the unique experiment id.'), file_paths=InputFiles(schema_loc='schema/schemaV2.json', execution_kg_loc='usecases/chatbs/data/1_sample_graph/chatbs_sample.ttl', metadata_loc='usecases/chatbs/data/1_sample_graph/chatbs_sample_metadata.json'), explorer_config=ExplorerConfig(kg_name='ChatBS-NexGen', ontology_triples_path='schema/extracted_ontology_triples.csv', parallel=True, temp_folder='evaluations/calibration/exeprog_creation/tmp/programs', use_cache=False, explorer_metadata_loc='evaluations/calibration/exeprog_creation/exeplorer_metadata.pkl', exeprog_save_loc='evaluations/calibration/exeprog_creation/exeplored_programs.pkl', log_file='evaluations/calibration/exeprog_creation/explorer_log.txt'), question_creation_config=QuestionCreationConfig(save_questions='evaluations/calibration/ques_creation/SyntheticQuestionKG.csv', llm_type='lmstudio', llm_config={'model': 'lm_studio/qwen/qwen3.5-4b', 'base_url': 'http://localhost:1234/v1'}, log_file='evaluations/calibration/ques_creation/question_creation_log.txt'), explainer_config=ExplainerConfig(llm_type='lmstudio', embedding_type='lmstudio', vectordb_type='milvus', save_answer_loc='evaluations/calibration/explainer/results', llm_config={'model': 'lm_studio/qwen/qwen3.5-4b', 'base_url': 'http://localhost:1234/v1'}, embedding_config={'model': 'text-embedding-bge-large-en-v1.5'}, vectordb_config={'vector_dim': 1024, 'collection_name': 'calibration'}, object_search_config={'search_limit': 3}, log_file='evaluations/calibration/explainer/explainer_log.txt'), ttl=TTLConfig(prefixes=[{'name': 'provone', 'uri': 'http://purl.dataone.org/provone/2015/01/15/ontology#'}, {'name': 'skos', 'uri': 'http://www.w3.org/2004/02/skos/core#'}, {'name': 'prov', 'uri': 'http://www.w3.org/ns/prov#'}, {'name': 'rdfs', 'uri': 'http://www.w3.org/2000/01/rdf-schema#'}, {'name': 'cwfo', 'uri': 'http://cwf.tw.rpi.edu/vocab#'}, {'name': 'dcterms', 'uri': 'http://purl.org/dc/terms#'}, {'name': 'ChatBS-NexGen', 'uri': 'http://testwebsite/testProgram#'}, {'name': 'user', 'uri': 'http://testwebsite/testUser#'}, {'name': 'eo', 'uri': 'https://purl.org/heals/eo#'}, {'name': 'ep', 'uri': 'http://linkedu.eu/dedalo/explanationPattern.owl#'}, {'name': 'sio', 'uri': 'http://semanticscience.org/resource/'}, {'name': 'dc', 'uri': 'http://purl.org/dc/elements/1.1/'}, {'name': 'DFColumn', 'uri': 'http://testwebsite/testDFColumn#'}, {'name': 'fnom', 'uri': 'https://w3id.org/function/vocabulary/mapping#'}, {'name': 'fnoi', 'uri': 'https://w3id.org/function/vocabulary/implementation#'}, {'name': 'fnoc', 'uri': 'https://w3id.org/function/vocabulary/composition/0.1.0/'}, {'name': 'food', 'uri': 'http://purl.org/heals/food/'}, {'name': 'dbo', 'uri': 'http://dbpedia.org/ontology/'}, {'name': 'dbp', 'uri': 'http://dbpedia.org/property/'}, {'name': 'dbt', 'uri': 'http://dbpedia.org/resource/Template:'}, {'name': 'ques', 'uri': 'http://atomic_questions.org/'}, {'name': 'xsd', 'uri': 'http://www.w3.org/2001/XMLSchema#'}, {'name': 'fno', 'uri': 'https://w3id.org/function/vocabulary/core#'}, {'name': 'workflow', 'uri': 'http://www.semanticweb.org/acer/ontologies/2026/1/WorkFlow/'}]), gt=GTConfig(log_file='evaluations/calibration/ground_truth/ground_truth_log.txt', save_loc='evaluations/calibration/ground_truth/ground_truth_data.json'))

In [26]:
graph_manager = GraphManager(
    config.ttl,
    config.file_paths.execution_kg_loc,
)

gt_list: List[GT] = []

In [27]:
# Question 1
question1 = """
How many unique \"experiment execution\" are there in this?
"""
question_sparql1 = """
SELECT (count(distinct ?ids) AS ?obj_count)
WHERE {
     ?obj a provone:Execution ;
          dcterms:identifier ?ids .
}
"""

entities1 = graph_manager.query(question_sparql1)
entities1

  obj_count
0         1

In [28]:
answer1 = "The answer to the question is 1 unique executions."

gt_list.append(
    GT(
        question=question1,
        answer=answer1,
        sparql_querys=[
            SPARQLTemplate(
                template=question_sparql1,
                description="This SPARQL query counts the number of unique executions by counting distinct identifiers in the provone:Execution class.",
            )
        ],
        entities=entities1.to_dict(orient="records"),
    )
)

In [29]:
# Question 2
question2 = """
what are the instructions used by the LLM to generate the sparql query post processing function step in the pipeline?
"""
question_sparql2 = """
SELECT distinct ?obj ?llm ?inpd
WHERE {
     ?obj dc:description ?desc .
     ?obj a ?class .
     FILTER(REGEX(?desc, "Post-processes the query results","i"))

     ?llm_out sio:SIO_000202 ?obj .
     ?llm_out sio:SIO_000232 ?llm .
     ?llm sio:SIO_000230 ?inp .
     ?inp prov:value ?inpd
}
"""

entities2 = graph_manager.query(question_sparql2, resolve_curie=True)
entities2

,obj,llm,inpd
0,ChatBS-NexGen:query_result_post_processor,ChatBS-NexGen:LLM-query_result_post_processor,Concat all the rows into single row at each co...
1,ChatBS-NexGen:query_result_post_processor,ChatBS-NexGen:LLM-query_result_post_processor,If there are duplicate ingredients then select...

In [30]:
# Question 3
question3 = """
In what places do we utilize AI in this workflow?
"""
question_sparql3 = """
SELECT distinct ?obj ?desc
WHERE {
     ?obj a workflow:Generative_Task .
     ?obj dc:description ?desc .
}
"""

entities3 = graph_manager.query(question_sparql3, resolve_curie=True)
entities3

,obj,desc
0,ChatBS-NexGen:Generative_Task-id_2026041219340...,LLM Generates an text for \nsystem prompt: \n...
1,ChatBS-NexGen:Generative_Task-id_2026041219340...,Extracts important entities for \ntext: \n\nu...
2,ChatBS-NexGen:Generative_Task-information_extr...,Generates the Information Extractor Function u...
3,ChatBS-NexGen:Generative_Task-query_result_pos...,Generates the post processing Function using L...
4,ChatBS-NexGen:Generative_Task-system_prompt_ge...,Generates the System Prompt Template using Lar...

In [31]:
answer3 = """
The ChatBS System utilizes LLMs to generate the following functions

1. Information extraction function
2. System Prompt template function
3. Sparql result post processing function

and further it's used within functions to
1. Generate the LLM outputs,
2. Used to extract key information from the system.
"""

gt_list.append(
    GT(
        question=question3,
        answer=answer3,
        sparql_querys=[SPARQLTemplate(template=question_sparql3, description="")],
        entities=entities3.to_dict(orient="records"),
    )
)

In [32]:
# Question 4
question4 = """
What are the extracted KG entities for the execution with id 1_1
"""
question_sparql4 = """
SELECT DISTINCT ?member ?prop ?value
WHERE {
     ?obj dc:description ?desc .
     FILTER(REGEX(?desc, "SPARQL queries to extract information", "i"))

     ?obj a provone:Program .
     ?exe prov:qualifiedAssociation/prov:hadPlan ?obj .
     ?exe dcterms:identifier ?id .
     FILTER(REGEX(?id, "1_1", "i"))

     ?data prov:wasGeneratedBy ?exe .
     ?data a ?class .

     {
         ?data a provone:Collection .
         ?data provone:hadMember ?member .
         ?member ?prop ?value .
     }
     UNION
     {
         ?data a provone:Data .
         BIND(?data AS ?member)
         ?data ?prop ?value .
     }
}
"""

entities4 = graph_manager.query(question_sparql4, resolve_curie=True)
entities4

,member,prop,value
0,ChatBS-NexGen:Data-id_20260412193409_525-kg_info,rdfs:label,row_1@en^^<xsd:string>
1,ChatBS-NexGen:Data-id_20260412193409_525-kg_info,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,provone:Data
2,ChatBS-NexGen:Data-id_20260412193409_525-kg_info,DFColumn:ingredientCat,Animal taxa named by Carl Linnaeus@en^^<xsd:st...
3,ChatBS-NexGen:Data-id_20260412193409_525-kg_info,prov:wasGeneratedBy,ChatBS-NexGen:id_20260412193409_378
4,ChatBS-NexGen:Data-id_20260412193409_525-kg_info,DFColumn:sugarG,NA@en^^<xsd:string>
...,...,...,...
112,ChatBS-NexGen:Data-id_20260412193409_244-extracts,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,provone:Data
113,ChatBS-NexGen:Data-id_20260412193409_244-extracts,prov:wasGeneratedBy,ChatBS-NexGen:id_20260412193409_267
114,ChatBS-NexGen:Data-id_20260412193409_244-extracts,prov:value,Beef@en^^<xsd:string>
115,ChatBS-NexGen:Data-id_20260412193409_244-extracts,prov:wasGeneratedBy,ChatBS-NexGen:id_20260412193411_732
116,ChatBS-NexGen:Data-id_20260412193409_244-extracts,rdfs:label,extracts@en^^<xsd:string>

In [33]:
pentities4 = set(
    entities4.loc[entities4["prop"] == "DFColumn:ingredientName", "value"]
    .apply(lambda x: x.split("@")[0])
    .tolist()
) - {"", "NA"}

answer4 = """
The retrieved entities from the knowledge graph includes the following ingredients,

1. Yogurt
2. Berry
3. Cheese
4. Carrot
5. Turkey
6. Bell pepper
7. Hummus
8. Almond
9. Avocado
10. Pumpkin seed
11. Water
12. Pineapple
13. Cottage cheese
"""

gt_list.append(
    GT(
        question=question4,
        answer=answer4,
        sparql_querys=[SPARQLTemplate(template=question_sparql4, description="")],
        entities=list(pentities4),
    )
)

In [34]:
# Question 5
question5 = """
why did some ingredients have missing values for `sugarG` and `ingredientCat` columns in the final output of the workflow?
"""
question_sparql5 = """
SELECT DISTINCT ?member ?prop ?value
WHERE {
     ?obj dc:description ?desc .
     FILTER(REGEX(?desc, "SPARQL queries to extract information", "i"))

     ?obj a provone:Program .
     ?exe prov:qualifiedAssociation/prov:hadPlan ?obj .
     ?exe dcterms:identifier ?id .
     FILTER(REGEX(?id, "1_1", "i"))

     ?data prov:wasGeneratedBy ?exe .
     ?data a ?class .

     {
         ?data a provone:Collection .
         ?data provone:hadMember ?member .
         ?member ?prop ?value .
     }
     UNION
     {
         ?data a provone:Data .
         BIND(?data AS ?member)
         ?data ?prop ?value .
     }
}

order by ?member ?prop
"""

entities5 = graph_manager.query(question_sparql5, resolve_curie=True)
entities5

,member,prop,value
0,ChatBS-NexGen:Data-id_20260412193409_244-extracts,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,provone:Data
1,ChatBS-NexGen:Data-id_20260412193409_244-extracts,rdfs:label,extracts@en^^<xsd:string>
2,ChatBS-NexGen:Data-id_20260412193409_244-extracts,prov:value,Beef@en^^<xsd:string>
3,ChatBS-NexGen:Data-id_20260412193409_244-extracts,prov:wasGeneratedBy,ChatBS-NexGen:id_20260412193409_267
4,ChatBS-NexGen:Data-id_20260412193409_244-extracts,prov:wasGeneratedBy,ChatBS-NexGen:id_20260412193411_732
...,...,...,...
112,ChatBS-NexGen:Data-id_20260412193411_834-kg_info,DFColumn:ingredientName,NA@en^^<xsd:string>
113,ChatBS-NexGen:Data-id_20260412193411_834-kg_info,DFColumn:sugarG,NA@en^^<xsd:string>
114,ChatBS-NexGen:Data-id_20260412193411_834-kg_info,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,provone:Data
115,ChatBS-NexGen:Data-id_20260412193411_834-kg_info,rdfs:label,row_1@en^^<xsd:string>
116,ChatBS-NexGen:Data-id_20260412193411_834-kg_info,prov:wasGeneratedBy,ChatBS-NexGen:id_20260412193411_732

In [35]:
na_entities = entities5.loc[
    entities5["value"].isin(["@en^^<xsd:string>", "NA@en^^<xsd:string>"]),
    "member",
].unique().tolist()
pentities5 = set(
    entities5.loc[
        entities5["member"].isin(na_entities)
        & (entities5["prop"] == "DFColumn:ingredientName"),
        "value",
    ]
    .apply(lambda x: x.split("@")[0])
    .tolist()
) - {"", "NA"}

answer5 = """
Due to the fact that some information is not available in the knowledge graph for ingredients such as
'Turkey', 'Hummus', 'Cheese', 'Cottage cheese', 'Berry', 'Water' the sugarG and ingredientCat is not available.
"""

gt_list.append(
    GT(
        question=question5,
        answer=answer5,
        sparql_querys=[SPARQLTemplate(template=question_sparql5, description="")],
        entities=list(pentities5),
    )
)

In [36]:
# Question MULT 1: instructions for function generation.


template_spec = [{
    "func_desc":"sparql query post processing"
}, {
    "func_desc": "system prompt template"
}, {
    "func_desc": "information extraction"
}]

sparql_spec = [{
    "func_desc_term":"Post-processes the query results"
},{
    "func_desc_term":"Generates a system prompt"
},{
    "func_desc_term":"Extracts entities or relevant information"
},]

question_template = """
what are the instructions used by the LLM to generate the {func_desc} function step in the pipeline?
"""
sparql_template = """
SELECT distinct ?obj ?llm ?inpd
WHERE {
     ?obj dc:description ?desc .
     ?obj a ?class .
     FILTER(REGEX(?desc, "{func_desc_term}","i"))

     ?llm_out sio:SIO_000202 ?obj .
     ?llm_out sio:SIO_000232 ?llm .
     ?llm sio:SIO_000230 ?inp .
     ?inp prov:value ?inpd
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    We utilize the following input instructions to generate the function responsible for {func_desc}.

    {answer_inst}
    """
    
    
    _ent = entities[['obj', 'inpd']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "obj": "Funtion",
            "inpd": "Instruction for function generation"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

gt_list.extend(gts)

ic| rquestion: '''
                what are the instructions used by the LLM to generate the sparql query post processing function step in the pipeline?
                '''
ic| entities:                                                  obj  \
              0  http://testwebsite/testProgram#query_result_po...
              1  http://testwebsite/testProgram#query_result_po...

                                                               llm  \
              0  http://testwebsite/testProgram#LLM-query_resul...
              1  http://testwebsite/testProgram#LLM-query_resul...

                                                              inpd
              0  Concat all the rows into single row at each co...
              1  If there are duplicate ingredients then select...
ic| answer: GTAnswer(answer_nlp="
                We utilize the following input instructions to generate the function responsible for sparql query post processing.

                Funtion | Instruction for function generation
            http://testwebsite/testProgram#query_result_post_processor | Concat all the rows into single row at each column by '|' concatenation marker.@en^^<xsd:string>
            http://testwebsite/testProgram#query_result_post_processor | If there are duplicate ingredients then select row with most information on `sugarG` and `ingredientCat` columns. Fill all the missing values with '0' in `sugarG` column and with '-' in 'ingredientCat` column.@en^^<xsd:string>
                ", entities=[{'obj': 'http://testwebsite/testProgram#query_result_post_processor', 'inpd': "Concat all the rows into single row at each column by '|' concatenation marker.@en^^<xsd:string>"}, {'obj': 'http://testwebsite/testProgram#query_result_post_processor', 'inpd': "If there are duplicate ingredients then select row with most information on `sugarG` and `ingredientCat` columns. Fill all the missing values with '0' in `sugarG` column and with '-' in 'ingredientCat` column.@en^^<xsd:string>"}])
ic| rquestion: '''
                what are the instructions used by the LLM to generate the system prompt template function step in the pipeline?
                '''
ic| entities:                                                  obj  \
              0  http://testwebsite/testProgram#system_prompt_g...
              1  http://testwebsite/testProgram#system_prompt_g...

                                                               llm  \
              0  http://testwebsite/testProgram#LLM-system_prom...
              1  http://testwebsite/testProgram#LLM-system_prom...

                                                             inpd
              0  You are a health care assistant@en^^<xsd:string>
              1                           gpt-4o@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                We utilize the following input instructions to generate the function responsible for system prompt template.

                Funtion | Instruction for function generation
            http://testwebsite/testProgram#system_prompt_generator | You are a health care assistant@en^^<xsd:string>
            http://testwebsite/testProgram#system_prompt_generator | gpt-4o@en^^<xsd:string>
                ', entities=[{'obj': 'http://testwebsite/testProgram#system_prompt_generator', 'inpd': 'You are a health care assistant@en^^<xsd:string>'}, {'obj': 'http://testwebsite/testProgram#system_prompt_generator', 'inpd': 'gpt-4o@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the instructions used by the LLM to generate the information extraction function step in the pipeline?
                '''
ic| entities:                                                  obj  \
              0  http://testwebsite/testProgram#information_ext...
              1  http://testwebsite/testProgram#information_ext...

                                                               llm  \
              0  http://testwebsite/testProgram#LLM-information...
              1  http://testwebsite/testProgram#LLM-information...

                                                              inpd
              0                            gpt-4o@en^^<xsd:string>
              1  Extract all the main ingredients without any s...
ic| answer: GTAnswer(answer_nlp="
                We utilize the following input instructions to generate the function responsible for information extraction.

                Funtion | Instruction for function generation
            http://testwebsite/testProgram#information_extractor | gpt-4o@en^^<xsd:string>
            http://testwebsite/testProgram#information_extractor | Extract all the main ingredients without any subsidiary; return in singular noun form and First letter capital. Extract mean and dairy product in its' base form. (e.g., from 'egg white' extract 'Egg')@en^^<xsd:string>
                ", entities=[{'obj': 'http://testwebsite/testProgram#information_extractor', 'inpd': 'gpt-4o@en^^<xsd:string>'}, {'obj': 'http://testwebsite/testProgram#information_extractor', 'inpd': "Extract all the main ingredients without any subsidiary; return in singular noun form and First letter capital. Extract mean and dairy product in its' base form. (e.g., from 'egg white' extract 'Egg')@en^^<xsd:string>"}])

In [37]:
# Question MULT 2: input ports of the functions


template_spec = [{
    "func_desc":"sparql query post processing"
}, {
    "func_desc": "system prompt template"
}, {
    "func_desc": "information extraction"
}, {
    "func_desc": "sparql query function"
}, {
    "func_desc": "llm chat function"
}]

sparql_spec = [{
    "func_desc_term":"Post-processes the query results"
},{
    "func_desc_term":"Generates a system prompt"
},{
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc_term": "Builds SPARQL"
}, {
    "func_desc_term": "Chat with"
}]

question_template = """
what are the input parameters of the function used in {func_desc} step in the pipeline?
"""
sparql_template = """
SELECT distinct ?flbl ?lbl
WHERE {
     ?obj dc:description ?desc .
     ?obj rdfs:label ?flbl . 
     ?obj a ?class .
     FILTER(REGEX(?desc, "{func_desc_term}","i"))

     ?obj provone:hasInPort ?port .
     ?port rdfs:label ?lbl .
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The input parameters to {func_desc} function.

    {answer_inst}
    """
    
    _ent = entities[['flbl', 'lbl']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "flbl": "Funtion name",
            "lbl": "Function returns"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

gt_list.extend(gts)

ic| rquestion: '''
                what are the input parameters of the function used in sparql query post processing step in the pipeline?
                '''
ic| entities:                                            flbl  \
              0  Query Result Post-Processor@en^^<xsd:string>

                                                               lbl
              0  Post-processing input port: kg_knowledge@en^^<...
ic| answer: GTAnswer(answer_nlp='
                The input parameters to sparql query post processing function.

                Funtion name | Function returns
            Query Result Post-Processor@en^^<xsd:string> | Post-processing input port: kg_knowledge@en^^<xsd:string>
                ', entities=[{'flbl': 'Query Result Post-Processor@en^^<xsd:string>', 'lbl': 'Post-processing input port: kg_knowledge@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the input parameters of the function used in system prompt template step in the pipeline?
                '''
ic| entities:                                                 flbl  \
              0  System Prompt Template Generator@en^^<xsd:string>
              1  System Prompt Template Generator@en^^<xsd:string>
              2  System Prompt Template Generator@en^^<xsd:string>
              3  System Prompt Template Generator@en^^<xsd:string>
              4  System Prompt Template Generator@en^^<xsd:string>
              5  System Prompt Template Generator@en^^<xsd:string>
              6  System Prompt Template Generator@en^^<xsd:string>
              7  System Prompt Template Generator@en^^<xsd:string>

                                                             lbl
              0              Input port for age@en^^<xsd:string>
              1        Input port for allergies@en^^<xsd:string>
              2    Input port for bodyMassIndex@en^^<xsd:string>
              3        Input port for diagnosis@en^^<xsd:string>
              4  Input port for foodPreferences@en^^<xsd:string>
              5           Input port for gender@en^^<xsd:string>
              6           Input port for height@en^^<xsd:string>
              7           Input port for weight@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The input parameters to system prompt template function.

                Funtion name | Function returns
            System Prompt Template Generator@en^^<xsd:string> | Input port for age@en^^<xsd:string>
            System Prompt Template Generator@en^^<xsd:string> | Input port for allergies@en^^<xsd:string>
            System Prompt Template Generator@en^^<xsd:string> | Input port for bodyMassIndex@en^^<xsd:string>
            System Prompt Template Generator@en^^<xsd:string> | Input port for diagnosis@en^^<xsd:string>
            System Prompt Template Generator@en^^<xsd:string> | Input port for foodPreferences@en^^<xsd:string>
            System Prompt Template Generator@en^^<xsd:string> | Input port for gender@en^^<xsd:string>
            System Prompt Template Generator@en^^<xsd:string> | Input port for height@en^^<xsd:string>
            System Prompt Template Generator@en^^<xsd:string> | Input port for weight@en^^<xsd:string>
                ', entities=[{'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for age@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for allergies@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for bodyMassIndex@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for diagnosis@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for foodPreferences@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for gender@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for height@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for weight@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the input parameters of the function used in information extraction step in the pipeline?
                '''
ic| entities:                                      flbl  \
              0  Information Extractor@en^^<xsd:string>

                                                  lbl
              0  Input port for text@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The input parameters to information extraction function.

                Funtion name | Function returns
            Information Extractor@en^^<xsd:string> | Input port for text@en^^<xsd:string>
                ', entities=[{'flbl': 'Information Extractor@en^^<xsd:string>', 'lbl': 'Input port for text@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the input parameters of the function used in sparql query function step in the pipeline?
                '''
ic| entities:                                     flbl  \
              0  SPARQL Query Builder@en^^<xsd:string>

                                                    lbl
              0  Input port for entity@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The input parameters to sparql query function function.

                Funtion name | Function returns
            SPARQL Query Builder@en^^<xsd:string> | Input port for entity@en^^<xsd:string>
                ', entities=[{'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'lbl': 'Input port for entity@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the input parameters of the function used in llm chat function step in the pipeline?
                '''
ic| entities:                         flbl  \
              0  LLM Chat@en^^<xsd:string>
              1  LLM Chat@en^^<xsd:string>

                                                               lbl
              0  LLM Chat input port: system_prompt@en^^<xsd:st...
              1  LLM Chat input port: user_prompt@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The input parameters to llm chat function function.

                Funtion name | Function returns
            LLM Chat@en^^<xsd:string> | LLM Chat input port: system_prompt@en^^<xsd:string>
            LLM Chat@en^^<xsd:string> | LLM Chat input port: user_prompt@en^^<xsd:string>
                ', entities=[{'flbl': 'LLM Chat@en^^<xsd:string>', 'lbl': 'LLM Chat input port: system_prompt@en^^<xsd:string>'}, {'flbl': 'LLM Chat@en^^<xsd:string>', 'lbl': 'LLM Chat input port: user_prompt@en^^<xsd:string>'}])

In [38]:
# Question MULT 3 : output ports of functions


template_spec = [{
    "func_desc":"sparql query post processing"
}, {
    "func_desc": "system prompt template"
}, {
    "func_desc": "information extraction"
}, {
    "func_desc": "sparql query function"
}, {
    "func_desc": "llm chat function"
}]

sparql_spec = [{
    "func_desc_term":"Post-processes the query results"
},{
    "func_desc_term":"Generates a system prompt"
},{
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc_term": "Builds SPARQL queries to extract"
}, {
    "func_desc_term": "Chat with the LLM"
}]

question_template = """
what are the input parameters of the function used in {func_desc} step in the pipeline?
"""
sparql_template = """
SELECT distinct ?flbl ?lbl
WHERE {
     ?obj dc:description ?desc .
     ?obj rdfs:label ?flbl . 
     ?obj a ?class .
     FILTER(REGEX(?desc, "{func_desc_term}","i"))

     ?obj provone:hasOutPort ?port .
     ?port rdfs:label ?lbl .
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The input parameters to {func_desc} function.

    {answer_inst}
    """
    
    _ent = entities[['flbl', 'lbl']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "flbl": "Funtion name",
            "lbl": "Function returns"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

gt_list.extend(gts)

ic| rquestion: '''
                what are the input parameters of the function used in sparql query post processing step in the pipeline?
                '''
ic| entities:                                            flbl  \
              0  Query Result Post-Processor@en^^<xsd:string>

                                                               lbl
              0  Post-processed output port: post_processed_out...
ic| answer: GTAnswer(answer_nlp='
                The input parameters to sparql query post processing function.

                Funtion name | Function returns
            Query Result Post-Processor@en^^<xsd:string> | Post-processed output port: post_processed_output@en^^<xsd:string>
                ', entities=[{'flbl': 'Query Result Post-Processor@en^^<xsd:string>', 'lbl': 'Post-processed output port: post_processed_output@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the input parameters of the function used in system prompt template step in the pipeline?
                '''
ic| entities:                                                 flbl  \
              0  System Prompt Template Generator@en^^<xsd:string>

                                            lbl
              0  System Prompt@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The input parameters to system prompt template function.

                Funtion name | Function returns
            System Prompt Template Generator@en^^<xsd:string> | System Prompt@en^^<xsd:string>
                ', entities=[{'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'System Prompt@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the input parameters of the function used in information extraction step in the pipeline?
                '''
ic| entities:                                      flbl                                  lbl
              0  Information Extractor@en^^<xsd:string>  Extracted Entities@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The input parameters to information extraction function.

                Funtion name | Function returns
            Information Extractor@en^^<xsd:string> | Extracted Entities@en^^<xsd:string>
                ', entities=[{'flbl': 'Information Extractor@en^^<xsd:string>', 'lbl': 'Extracted Entities@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the input parameters of the function used in sparql query function step in the pipeline?
                '''
ic| entities:                                     flbl  \
              0  SPARQL Query Builder@en^^<xsd:string>

                                                      lbl
              0  Output port for kg_info@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The input parameters to sparql query function function.

                Funtion name | Function returns
            SPARQL Query Builder@en^^<xsd:string> | Output port for kg_info@en^^<xsd:string>
                ', entities=[{'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'lbl': 'Output port for kg_info@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the input parameters of the function used in llm chat function step in the pipeline?
                '''
ic| entities:                         flbl  \
              0  LLM Chat@en^^<xsd:string>

                                                               lbl
              0  LLM Chat output port: generated_answer@en^^<xs...
ic| answer: GTAnswer(answer_nlp='
                The input parameters to llm chat function function.

                Funtion name | Function returns
            LLM Chat@en^^<xsd:string> | LLM Chat output port: generated_answer@en^^<xsd:string>
                ', entities=[{'flbl': 'LLM Chat@en^^<xsd:string>', 'lbl': 'LLM Chat output port: generated_answer@en^^<xsd:string>'}])

In [39]:
# Question MULT 4 : connected functions


template_spec = [{
    "func_desc":"sparql query post processing"
}, {
    "func_desc": "system prompt template"
}, {
    "func_desc": "information extraction"
}, {
    "func_desc": "sparql query function"
}, {
    "func_desc": "llm chat function"
}]

sparql_spec = [{
    "func_desc_term":"Post-processes the query results"
},{
    "func_desc_term":"Generates a system prompt"
},{
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc_term": "Builds SPARQL queries to extract"
}, {
    "func_desc_term": "Chat with the LLM"
}]

question_template = """
what are the connected functions to the function used in {func_desc} step in the pipeline?
"""
sparql_template = """

SELECT DISTINCT ?fn2 ?fn2lbl
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl . 
    ?obj a ?class .
    FILTER(REGEX(?desc, "{func_desc_term}","i"))

    ?obj (provone:hasInPort | provone:hasOutPort) ?port .
    ?port provone:connectsTo ?channel .
    ?portt provone:connectsTo ?channel .
    ?fn2 (provone:hasInPort | provone:hasOutPort) ?portt .
    FILTER(?obj != ?fn2)
    
    ?fn2 rdfs:label ?fn2lbl .
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The connected functions to {func_desc} function.

    {answer_inst}
    """
    
    _ent = entities[['fn2', 'fn2lbl']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "fn2": "Funtion URI",
            "fn2lbl": "Function name"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

gt_list.extend(gts)

ic| rquestion: '''
                what are the connected functions to the function used in sparql query post processing step in the pipeline?
                '''
ic| entities:                                                  fn2  \
              0  http://testwebsite/testProgram#batch_sparql_qu...

                                                        fn2lbl
              0  Batch SPARQL Query Extractor@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The connected functions to sparql query post processing function.

                Funtion URI | Function name
            http://testwebsite/testProgram#batch_sparql_query_extractor | Batch SPARQL Query Extractor@en^^<xsd:string>
                ', entities=[{'fn2': 'http://testwebsite/testProgram#batch_sparql_query_extractor', 'fn2lbl': 'Batch SPARQL Query Extractor@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the connected functions to the function used in system prompt template step in the pipeline?
                '''
ic| entities:                                        fn2                     fn2lbl
              0  http://testwebsite/testProgram#llm_chat  LLM Chat@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The connected functions to system prompt template function.

                Funtion URI | Function name
            http://testwebsite/testProgram#llm_chat | LLM Chat@en^^<xsd:string>
                ', entities=[{'fn2': 'http://testwebsite/testProgram#llm_chat', 'fn2lbl': 'LLM Chat@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the connected functions to the function used in information extraction step in the pipeline?
                '''
ic| entities:                                                  fn2  \
              0            http://testwebsite/testProgram#llm_chat
              1  http://testwebsite/testProgram#batch_sparql_qu...

                                                        fn2lbl
              0                      LLM Chat@en^^<xsd:string>
              1  Batch SPARQL Query Extractor@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The connected functions to information extraction function.

                Funtion URI | Function name
            http://testwebsite/testProgram#llm_chat | LLM Chat@en^^<xsd:string>
            http://testwebsite/testProgram#batch_sparql_query_extractor | Batch SPARQL Query Extractor@en^^<xsd:string>
                ', entities=[{'fn2': 'http://testwebsite/testProgram#llm_chat', 'fn2lbl': 'LLM Chat@en^^<xsd:string>'}, {'fn2': 'http://testwebsite/testProgram#batch_sparql_query_extractor', 'fn2lbl': 'Batch SPARQL Query Extractor@en^^<xsd:string>'}])
ic| rquestion: '''
                what are the connected functions to the function used in sparql query function step in the pipeline?
                '''
ic| entities: Empty DataFrame
              Columns: [fn2, fn2lbl]
              Index: []
ic| answer: GTAnswer(answer_nlp='
                The connected functions to sparql query function function.

                Funtion URI | Function name
                ', entities=[])
ic| rquestion: '''
                what are the connected functions to the function used in llm chat function step in the pipeline?
                '''
ic| entities:                                                  fn2  \
              0  http://testwebsite/testProgram#system_prompt_g...
              1  http://testwebsite/testProgram#information_ext...

                                                            fn2lbl
              0  System Prompt Template Generator@en^^<xsd:string>
              1             Information Extractor@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The connected functions to llm chat function function.

                Funtion URI | Function name
            http://testwebsite/testProgram#system_prompt_generator | System Prompt Template Generator@en^^<xsd:string>
            http://testwebsite/testProgram#information_extractor | Information Extractor@en^^<xsd:string>
                ', entities=[{'fn2': 'http://testwebsite/testProgram#system_prompt_generator', 'fn2lbl': 'System Prompt Template Generator@en^^<xsd:string>'}, {'fn2': 'http://testwebsite/testProgram#information_extractor', 'fn2lbl': 'Information Extractor@en^^<xsd:string>'}])

In [40]:
# Question MULT 5 : number of execution of the functions


template_spec = [{
    "func_desc":"sparql query post processing"
}, {
    "func_desc": "system prompt template"
}, {
    "func_desc": "information extraction"
}, {
    "func_desc": "sparql query function"
}, {
    "func_desc": "llm chat function"
}]

sparql_spec = [{
    "func_desc_term":"Post-processes the query results"
},{
    "func_desc_term":"Generates a system prompt"
},{
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc_term": "Builds SPARQL queries to extract"
}, {
    "func_desc_term": "Chat with the LLM"
}]

question_template = """
what are the executions of the {func_desc} step in the pipeline?
"""
sparql_template = """

SELECT DISTINCT ?exe
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl . 
    ?obj a ?class .
    FILTER(REGEX(?desc, "{func_desc_term}","i"))

    ?asso prov:hadPlan ?obj .
    ?exe prov:qualifiedAssociation ?asso .
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The executions of the  {func_desc} function are.

    {answer_inst}
    """
    
    _ent = entities[['exe']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "exe": "Executions"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

gt_list.extend(gts)

ic| rquestion: '''
                what are the executions of the sparql query post processing step in the pipeline?
                '''
ic| entities:                                                  exe
              0  http://testwebsite/testProgram#id_202604121934...
ic| answer: GTAnswer(answer_nlp='
                The executions of the  sparql query post processing function are.

                Executions
            http://testwebsite/testProgram#id_20260412193411_282
                ', entities=[{'exe': 'http://testwebsite/testProgram#id_20260412193411_282'}])
ic| rquestion: '''
                what are the executions of the system prompt template step in the pipeline?
                '''
ic| entities:                                                  exe
              0  http://testwebsite/testProgram#id_202604121934...
ic| answer: GTAnswer(answer_nlp='
                The executions of the  system prompt template function are.

                Executions
            http://testwebsite/testProgram#id_20260412193403_334
                ', entities=[{'exe': 'http://testwebsite/testProgram#id_20260412193403_334'}])
ic| rquestion: '''
                what are the executions of the information extraction step in the pipeline?
                '''
ic| entities:                                                  exe
              0  http://testwebsite/testProgram#id_202604121934...
ic| answer: GTAnswer(answer_nlp='
                The executions of the  information extraction function are.

                Executions
            http://testwebsite/testProgram#id_20260412193409_267
                ', entities=[{'exe': 'http://testwebsite/testProgram#id_20260412193409_267'}])
ic| rquestion: '''
                what are the executions of the sparql query function step in the pipeline?
                '''
ic| entities:                                                  exe
              0  http://testwebsite/testProgram#id_202604121934...
              1  http://testwebsite/testProgram#id_202604121934...
              2  http://testwebsite/testProgram#id_202604121934...
              3  http://testwebsite/testProgram#id_202604121934...
              4  http://testwebsite/testProgram#id_202604121934...
              5  http://testwebsite/testProgram#id_202604121934...
              6  http://testwebsite/testProgram#id_202604121934...
              7  http://testwebsite/testProgram#id_202604121934...
              8  http://testwebsite/testProgram#id_202604121934...
ic| answer: GTAnswer(answer_nlp='
                The executions of the  sparql query function function are.

                Executions
            http://testwebsite/testProgram#id_20260412193409_378
            http://testwebsite/testProgram#id_20260412193409_379
            http://testwebsite/testProgram#id_20260412193409_974
            http://testwebsite/testProgram#id_20260412193410_245
            http://testwebsite/testProgram#id_20260412193410_757
            http://testwebsite/testProgram#id_20260412193411_381
            http://testwebsite/testProgram#id_20260412193411_429
            http://testwebsite/testProgram#id_20260412193411_661
            http://testwebsite/testProgram#id_20260412193411_732
                ', entities=[{'exe': 'http://testwebsite/testProgram#id_20260412193409_378'}, {'exe': 'http://testwebsite/testProgram#id_20260412193409_379'}, {'exe': 'http://testwebsite/testProgram#id_20260412193409_974'}, {'exe': 'http://testwebsite/testProgram#id_20260412193410_245'}, {'exe': 'http://testwebsite/testProgram#id_20260412193410_757'}, {'exe': 'http://testwebsite/testProgram#id_20260412193411_381'}, {'exe': 'http://testwebsite/testProgram#id_20260412193411_429'}, {'exe': 'http://testwebsite/testProgram#id_20260412193411_661'}, {'exe': 'http://testwebsite/testProgram#id_20260412193411_732'}])
ic| rquestion: '''
                what are the executions of the llm chat function step in the pipeline?
                '''
ic| entities:                                                  exe
              0  http://testwebsite/testProgram#id_202604121934...
ic| answer: GTAnswer(answer_nlp='
                The executions of the  llm chat function function are.

                Executions
            http://testwebsite/testProgram#id_20260412193407_99
                ', entities=[{'exe': 'http://testwebsite/testProgram#id_20260412193407_99'}])

In [41]:
# Question MULT 6 : who was the agent that ran the functions 


template_spec = [{
    "func_desc":"sparql query post processing"
}, {
    "func_desc": "system prompt template"
}, {
    "func_desc": "information extraction"
}, {
    "func_desc": "sparql query function"
}, {
    "func_desc": "llm chat function"
}]

sparql_spec = [{
    "func_desc_term":"Post-processes the query results"
},{
    "func_desc_term":"Generates a system prompt"
},{
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc_term": "Builds SPARQL queries to extract"
}, {
    "func_desc_term": "Chat with the LLM"
}]

question_template = """
who were the agents that ran the {func_desc} step in the pipeline?
"""
sparql_template = """

SELECT DISTINCT ?agent ?albl
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl . 
    ?obj a ?class .
    FILTER(REGEX(?desc, "{func_desc_term}","i"))

    ?asso prov:hadPlan ?obj .
    ?asso prov:agent ?agent .
    ?agent rdfs:label ?albl
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The executions of the  {func_desc} function are.

    {answer_inst}
    """
    
    _ent = entities[['albl']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "albl": "Agents"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

gt_list.extend(gts)

ic| rquestion: '''
                who were the agents that ran the sparql query post processing step in the pipeline?
                '''
ic| entities: Empty DataFrame
              Columns: [agent, albl]
              Index: []
ic| answer: GTAnswer(answer_nlp='
                The executions of the  sparql query post processing function are.

                Agents
                ', entities=[])
ic| rquestion: '''
                who were the agents that ran the system prompt template step in the pipeline?
                '''
ic| entities: Empty DataFrame
              Columns: [agent, albl]
              Index: []
ic| answer: GTAnswer(answer_nlp='
                The executions of the  system prompt template function are.

                Agents
                ', entities=[])
ic| rquestion: '''
                who were the agents that ran the information extraction step in the pipeline?
                '''
ic| entities: Empty DataFrame
              Columns: [agent, albl]
              Index: []
ic| answer: GTAnswer(answer_nlp='
                The executions of the  information extraction function are.

                Agents
                ', entities=[])
ic| rquestion: '''
                who were the agents that ran the sparql query function step in the pipeline?
                '''
ic| entities: Empty DataFrame
              Columns: [agent, albl]
              Index: []
ic| answer: GTAnswer(answer_nlp='
                The executions of the  sparql query function function are.

                Agents
                ', entities=[])
ic| rquestion: '''
                who were the agents that ran the llm chat function step in the pipeline?
                '''
ic| entities: Empty DataFrame
              Columns: [agent, albl]
              Index: []
ic| answer: GTAnswer(answer_nlp='
                The executions of the  llm chat function function are.

                Agents
                ', entities=[])

In [42]:
# Question MULT 7 : Is the function made by a Generative Task  


template_spec = [{
    "func_desc":"sparql query post processing"
}, {
    "func_desc": "system prompt template"
}, {
    "func_desc": "information extraction"
}, {
    "func_desc": "sparql query function"
}, {
    "func_desc": "llm chat function"
}]

sparql_spec = [{
    "func_desc_term":"Post-processes the query results"
},{
    "func_desc_term":"Generates a system prompt"
},{
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc_term": "Builds SPARQL queries to extract"
}, {
    "func_desc_term": "Chat with the LLM"
}]

question_template = """
Is the {func_desc} function made by a Generative Task using AI?
"""

sparql_template = """
SELECT DISTINCT ?fnlbl ?llm_gen_out
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?fnlbl .
    FILTER(REGEX(?desc, "{func_desc_term}", "i"))

    OPTIONAL {
        ?llm_out sio:SIO_000202 ?obj .
        ?llm_out sio:SIO_000232 ?llm .
        ?llm_gen prov:used ?llm .
    }

    BIND(COALESCE(?llm_gen, "None") AS ?llm_gen_out)
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The {func_desc} function {decision} by a Generative Task.

    {answer_inst}
    """
    
    _ent = entities[['fnlbl', 'llm_gen_out']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "obj": "Function",
            'llm_gen_out': "Generative Task used to generate function"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent,
        decision = "is made" if _ent['llm_gen_out'].tolist()[0] != "None" else "is not made"
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

gt_list.extend(gts)

ic| rquestion: '''
                Is the sparql query post processing function made by a Generative Task using AI?
                '''
ic| entities:                                           fnlbl  \
              0  Query Result Post-Processor@en^^<xsd:string>

                                                       llm_gen_out
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The sparql query post processing function is made by a Generative Task.

                fnlbl | Generative Task used to generate function
            Query Result Post-Processor@en^^<xsd:string> | http://testwebsite/testProgram#Generative_Task-query_result_post_processor
                ', entities=[{'fnlbl': 'Query Result Post-Processor@en^^<xsd:string>', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-query_result_post_processor'}])
ic| rquestion: '''
                Is the system prompt template function made by a Generative Task using AI?
                '''
ic| entities:                                                fnlbl  \
              0  System Prompt Template Generator@en^^<xsd:string>

                                                       llm_gen_out
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The system prompt template function is made by a Generative Task.

                fnlbl | Generative Task used to generate function
            System Prompt Template Generator@en^^<xsd:string> | http://testwebsite/testProgram#Generative_Task-system_prompt_generator
                ', entities=[{'fnlbl': 'System Prompt Template Generator@en^^<xsd:string>', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-system_prompt_generator'}])
ic| rquestion: '''
                Is the information extraction function made by a Generative Task using AI?
                '''
ic| entities:                                     fnlbl  \
              0  Information Extractor@en^^<xsd:string>

                                                       llm_gen_out
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The information extraction function is made by a Generative Task.

                fnlbl | Generative Task used to generate function
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#Generative_Task-information_extractor
                ', entities=[{'fnlbl': 'Information Extractor@en^^<xsd:string>', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-information_extractor'}])
ic| rquestion: '''
                Is the sparql query function function made by a Generative Task using AI?
                '''
ic| entities:                                    fnlbl llm_gen_out
              0  SPARQL Query Builder@en^^<xsd:string>        None
ic| answer: GTAnswer(answer_nlp='
                The sparql query function function is not made by a Generative Task.

                fnlbl | Generative Task used to generate function
            SPARQL Query Builder@en^^<xsd:string> | None
                ', entities=[{'fnlbl': 'SPARQL Query Builder@en^^<xsd:string>', 'llm_gen_out': 'None'}])
ic| rquestion: '''
                Is the llm chat function function made by a Generative Task using AI?
                '''
ic| entities:                        fnlbl llm_gen_out
              0  LLM Chat@en^^<xsd:string>        None
ic| answer: GTAnswer(answer_nlp='
                The llm chat function function is not made by a Generative Task.

                fnlbl | Generative Task used to generate function
            LLM Chat@en^^<xsd:string> | None
                ', entities=[{'fnlbl': 'LLM Chat@en^^<xsd:string>', 'llm_gen_out': 'None'}])

In [43]:
# Question MULT 8 : Does any of the executions of the function contain a Generative Task  


template_spec = [{
    "func_desc":"sparql query post processing"
}, {
    "func_desc": "system prompt template"
}, {
    "func_desc": "information extraction"
}, {
    "func_desc": "sparql query function"
}, {
    "func_desc": "llm chat function"
}]

sparql_spec = [{
    "func_desc_term":"Post-processes the query results"
},{
    "func_desc_term":"Generates a system prompt"
},{
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc_term": "Builds SPARQL queries to extract"
}, {
    "func_desc_term": "Chat with the LLM"
}]

question_template = """
Does any of the executions of the {func_desc} function made has a Generative Task as a component within?
"""

sparql_template = """
SELECT DISTINCT ?flbl ?exe ?llm_gen_out
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl .
    FILTER(REGEX(?desc, "{func_desc_term}","i"))

    ?asso prov:hadPlan ?obj .
    ?exe prov:qualifiedAssociation ?asso .

    OPTIONAL {
        ?exe sio:SIO_000369 ?llm_gen .
    }

    BIND(COALESCE(?llm_gen, "None") AS ?llm_gen_out)
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    Executions of the {func_desc} function {decision} a Generative Task that utilize an LLM.

    {answer_inst}
    """
    
    _ent = entities[['flbl', 'exe', 'llm_gen_out']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "flbl": "Function",
            'exe': "Execution",
            'llm_gen_out': "Generative Task used within execution"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent,
        decision = "contains" if _ent['llm_gen_out'].tolist()[0] != "None" else "does not contain"
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

gt_list.extend(gts)

ic| rquestion: '''
                Does any of the executions of the sparql query post processing function made has a Generative Task as a component within?
                '''
ic| entities:                                            flbl  \
              0  Query Result Post-Processor@en^^<xsd:string>

                                                               exe llm_gen_out
              0  http://testwebsite/testProgram#id_202604121934...        None
ic| answer: GTAnswer(answer_nlp='
                Executions of the sparql query post processing function does not contain a Generative Task that utilize an LLM.

                Function | Execution | Generative Task used within execution
            Query Result Post-Processor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193411_282 | None
                ', entities=[{'flbl': 'Query Result Post-Processor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193411_282', 'llm_gen_out': 'None'}])
ic| rquestion: '''
                Does any of the executions of the system prompt template function made has a Generative Task as a component within?
                '''
ic| entities:                                                 flbl  \
              0  System Prompt Template Generator@en^^<xsd:string>

                                                               exe llm_gen_out
              0  http://testwebsite/testProgram#id_202604121934...        None
ic| answer: GTAnswer(answer_nlp='
                Executions of the system prompt template function does not contain a Generative Task that utilize an LLM.

                Function | Execution | Generative Task used within execution
            System Prompt Template Generator@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193403_334 | None
                ', entities=[{'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193403_334', 'llm_gen_out': 'None'}])
ic| rquestion: '''
                Does any of the executions of the information extraction function made has a Generative Task as a component within?
                '''
ic| entities:                                      flbl  \
              0  Information Extractor@en^^<xsd:string>

                                                               exe  \
              0  http://testwebsite/testProgram#id_202604121934...

                                                       llm_gen_out
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                Executions of the information extraction function contains a Generative Task that utilize an LLM.

                Function | Execution | Generative Task used within execution
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193409_267 | http://testwebsite/testProgram#Generative_Task-id_20260412193409_267
                ', entities=[{'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193409_267', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-id_20260412193409_267'}])
ic| rquestion: '''
                Does any of the executions of the sparql query function function made has a Generative Task as a component within?
                '''
ic| entities:                                     flbl  \
              0  SPARQL Query Builder@en^^<xsd:string>
              1  SPARQL Query Builder@en^^<xsd:string>
              2  SPARQL Query Builder@en^^<xsd:string>
              3  SPARQL Query Builder@en^^<xsd:string>
              4  SPARQL Query Builder@en^^<xsd:string>
              5  SPARQL Query Builder@en^^<xsd:string>
              6  SPARQL Query Builder@en^^<xsd:string>
              7  SPARQL Query Builder@en^^<xsd:string>
              8  SPARQL Query Builder@en^^<xsd:string>

                                                               exe llm_gen_out
              0  http://testwebsite/testProgram#id_202604121934...        None
              1  http://testwebsite/testProgram#id_202604121934...        None
              2  http://testwebsite/testProgram#id_202604121934...        None
              3  http://testwebsite/testProgram#id_202604121934...        None
              4  http://testwebsite/testProgram#id_202604121934...        None
              5  http://testwebsite/testProgram#id_202604121934...        None
              6  http://testwebsite/testProgram#id_202604121934...        None
              7  http://testwebsite/testProgram#id_202604121934...        None
              8  http://testwebsite/testProgram#id_202604121934...        None
ic| answer: GTAnswer(answer_nlp='
                Executions of the sparql query function function does not contain a Generative Task that utilize an LLM.

                Function | Execution | Generative Task used within execution
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193409_378 | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193409_379 | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193409_974 | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193410_245 | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193410_757 | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193411_381 | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193411_429 | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193411_661 | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193411_732 | None
                ', entities=[{'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193409_378', 'llm_gen_out': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193409_379', 'llm_gen_out': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193409_974', 'llm_gen_out': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193410_245', 'llm_gen_out': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193410_757', 'llm_gen_out': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193411_381', 'llm_gen_out': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193411_429', 'llm_gen_out': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193411_661', 'llm_gen_out': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193411_732', 'llm_gen_out': 'None'}])
ic| rquestion: '''
                Does any of the executions of the llm chat function function made has a Generative Task as a component within?
                '''
ic| entities:                         flbl  \
              0  LLM Chat@en^^<xsd:string>

                                                               exe  \
              0  http://testwebsite/testProgram#id_202604121934...

                                                       llm_gen_out
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                Executions of the llm chat function function contains a Generative Task that utilize an LLM.

                Function | Execution | Generative Task used within execution
            LLM Chat@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193407_99 | http://testwebsite/testProgram#Generative_Task-id_20260412193407_99
                ', entities=[{'flbl': 'LLM Chat@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193407_99', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-id_20260412193407_99'}])

In [44]:
# Question MULT 9 : Does any of the executions of the function contain a Generative Task within and the function itself is generated by an LLM


template_spec = [{
    "func_desc":"sparql query post processing"
}, {
    "func_desc": "system prompt template"
}, {
    "func_desc": "information extraction"
}, {
    "func_desc": "sparql query function"
}, {
    "func_desc": "llm chat function"
}]

sparql_spec = [{
    "func_desc_term":"Post-processes the query results"
},{
    "func_desc_term":"Generates a system prompt"
},{
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc_term": "Builds SPARQL queries to extract"
}, {
    "func_desc_term": "Chat with the LLM"
}]

question_template = """
Does any of the executions of the {func_desc} function made has a Generative Task within as a component and also {func_desc} 
function itself is generated by a Generative Task?
"""

sparql_template = """
SELECT DISTINCT ?flbl ?exe ?llm_gen_out ?llm_gen_out2
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl .
    FILTER(REGEX(?desc, "{func_desc_term}","i"))

    ?asso prov:hadPlan ?obj .
    ?exe prov:qualifiedAssociation ?asso .

    OPTIONAL {
        ?exe sio:SIO_000369 ?llm_gen .
    }

    BIND(COALESCE(?llm_gen, "None") AS ?llm_gen_out)
    
    OPTIONAL {
        ?llm_out2 sio:SIO_000202 ?obj .
        ?llm_out2 sio:SIO_000232 ?llm2 .
        ?llm_gen2 prov:used ?llm2 .
    }

    BIND(COALESCE(?llm_gen2, "None") AS ?llm_gen_out2)
}

"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    1. Executions of the {func_desc} function {decision1} a Generative Task that utilize an LLM.
    2. The {func_desc} function {decision2} by a Generative Task.

    {answer_inst}
    """
    
    _ent = entities[['flbl', 'exe', 'llm_gen_out', 'llm_gen_out2']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "flbl": "Function",
            'exe': "Execution",
            'llm_gen_out': "Generative Task used within execution",
            'llm_gen_out2': "Generative Task used to generate function"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent,
        decision1 = "contains" if _ent['llm_gen_out'].tolist()[0] != "None" else "does not contain",
        decision2 = "is generated" if _ent['llm_gen_out'].tolist()[0] != "None" else "is not generated"
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

gt_list.extend(gts)

ic| rquestion: '''
                Does any of the executions of the sparql query post processing function made has a Generative Task within as a component and also sparql query post processing
                function itself is generated by a Generative Task?
                '''
ic| entities:                                            flbl  \
              0  Query Result Post-Processor@en^^<xsd:string>

                                                               exe llm_gen_out  \
              0  http://testwebsite/testProgram#id_202604121934...        None

                                                      llm_gen_out2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                1. Executions of the sparql query post processing function does not contain a Generative Task that utilize an LLM.
                2. The sparql query post processing function is not generated by a Generative Task.

                Function | Execution | Generative Task used within execution | Generative Task used to generate function
            Query Result Post-Processor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193411_282 | None | http://testwebsite/testProgram#Generative_Task-query_result_post_processor
                ', entities=[{'flbl': 'Query Result Post-Processor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193411_282', 'llm_gen_out': 'None', 'llm_gen_out2': 'http://testwebsite/testProgram#Generative_Task-query_result_post_processor'}])
ic| rquestion: '''
                Does any of the executions of the system prompt template function made has a Generative Task within as a component and also system prompt template
                function itself is generated by a Generative Task?
                '''
ic| entities:                                                 flbl  \
              0  System Prompt Template Generator@en^^<xsd:string>

                                                               exe llm_gen_out  \
              0  http://testwebsite/testProgram#id_202604121934...        None

                                                      llm_gen_out2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                1. Executions of the system prompt template function does not contain a Generative Task that utilize an LLM.
                2. The system prompt template function is not generated by a Generative Task.

                Function | Execution | Generative Task used within execution | Generative Task used to generate function
            System Prompt Template Generator@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193403_334 | None | http://testwebsite/testProgram#Generative_Task-system_prompt_generator
                ', entities=[{'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193403_334', 'llm_gen_out': 'None', 'llm_gen_out2': 'http://testwebsite/testProgram#Generative_Task-system_prompt_generator'}])
ic| rquestion: '''
                Does any of the executions of the information extraction function made has a Generative Task within as a component and also information extraction
                function itself is generated by a Generative Task?
                '''
ic| entities:                                      flbl  \
              0  Information Extractor@en^^<xsd:string>

                                                               exe  \
              0  http://testwebsite/testProgram#id_202604121934...

                                                       llm_gen_out  \
              0  http://testwebsite/testProgram#Generative_Task...

                                                      llm_gen_out2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                1. Executions of the information extraction function contains a Generative Task that utilize an LLM.
                2. The information extraction function is generated by a Generative Task.

                Function | Execution | Generative Task used within execution | Generative Task used to generate function
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193409_267 | http://testwebsite/testProgram#Generative_Task-id_20260412193409_267 | http://testwebsite/testProgram#Generative_Task-information_extractor
                ', entities=[{'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193409_267', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-id_20260412193409_267', 'llm_gen_out2': 'http://testwebsite/testProgram#Generative_Task-information_extractor'}])
ic| rquestion: '''
                Does any of the executions of the sparql query function function made has a Generative Task within as a component and also sparql query function
                function itself is generated by a Generative Task?
                '''
ic| entities:                                     flbl  \
              0  SPARQL Query Builder@en^^<xsd:string>
              1  SPARQL Query Builder@en^^<xsd:string>
              2  SPARQL Query Builder@en^^<xsd:string>
              3  SPARQL Query Builder@en^^<xsd:string>
              4  SPARQL Query Builder@en^^<xsd:string>
              5  SPARQL Query Builder@en^^<xsd:string>
              6  SPARQL Query Builder@en^^<xsd:string>
              7  SPARQL Query Builder@en^^<xsd:string>
              8  SPARQL Query Builder@en^^<xsd:string>

                                                               exe llm_gen_out llm_gen_out2
              0  http://testwebsite/testProgram#id_202604121934...        None         None
              1  http://testwebsite/testProgram#id_202604121934...        None         None
              2  http://testwebsite/testProgram#id_202604121934...        None         None
              3  http://testwebsite/testProgram#id_202604121934...        None         None
              4  http://testwebsite/testProgram#id_202604121934...        None         None
              5  http://testwebsite/testProgram#id_202604121934...        None         None
              6  http://testwebsite/testProgram#id_202604121934...        None         None
              7  http://testwebsite/testProgram#id_202604121934...        None         None
              8  http://testwebsite/testProgram#id_202604121934...        None         None
ic| answer: GTAnswer(answer_nlp='
                1. Executions of the sparql query function function does not contain a Generative Task that utilize an LLM.
                2. The sparql query function function is not generated by a Generative Task.

                Function | Execution | Generative Task used within execution | Generative Task used to generate function
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193409_378 | None | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193409_379 | None | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193409_974 | None | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193410_245 | None | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193410_757 | None | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193411_381 | None | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193411_429 | None | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193411_661 | None | None
            SPARQL Query Builder@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193411_732 | None | None
                ', entities=[{'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193409_378', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193409_379', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193409_974', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193410_245', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193410_757', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193411_381', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193411_429', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193411_661', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}, {'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193411_732', 'llm_gen_out': 'None', 'llm_gen_out2': 'None'}])
ic| rquestion: '''
                Does any of the executions of the llm chat function function made has a Generative Task within as a component and also llm chat function
                function itself is generated by a Generative Task?
                '''
ic| entities:                         flbl  \
              0  LLM Chat@en^^<xsd:string>

                                                               exe  \
              0  http://testwebsite/testProgram#id_202604121934...

                                                       llm_gen_out llm_gen_out2
              0  http://testwebsite/testProgram#Generative_Task...         None
ic| answer: GTAnswer(answer_nlp='
                1. Executions of the llm chat function function contains a Generative Task that utilize an LLM.
                2. The llm chat function function is generated by a Generative Task.

                Function | Execution | Generative Task used within execution | Generative Task used to generate function
            LLM Chat@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193407_99 | http://testwebsite/testProgram#Generative_Task-id_20260412193407_99 | None
                ', entities=[{'flbl': 'LLM Chat@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193407_99', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-id_20260412193407_99', 'llm_gen_out2': 'None'}])

In [45]:
# Question MULT 10 : Does any of the executions of the function contain a Generative Task within and the function itself is generated by an LLM


template_spec = [ {
    "func_desc": "information extraction"
}, {
    "func_desc": "llm chat function"
}]

sparql_spec = [{
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc_term": "Chat with the LLM"
}]

question_template = """
What are the inputs of the Generative Task that was a component in the executions of  the {func_desc} function?
"""

sparql_template = """
SELECT DISTINCT ?flbl ?exe ?lbl
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl .
    FILTER(REGEX(?desc, "{func_desc_term}","i"))

    ?asso prov:hadPlan ?obj .
    ?exe prov:qualifiedAssociation ?asso .

    ?exe sio:SIO_000369 ?llm_gen .
    ?llm_gen prov:used ?llm .
    ?llm sio:SIO_000230 ?inp .
    ?inp prov:value ?lbl . 
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The inputs to the LLM used for the Generative Task in the executions of the {func_desc} function

    {answer_inst}
    """
    
    _ent = entities[['flbl', 'exe', 'lbl']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "flbl": "Function",
            'exe': "Execution",
            'lbl': "Inputs for the Generative Task used within execution"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

gt_list.extend(gts)

ic| rquestion: '''
                What are the inputs of the Generative Task that was a component in the executions of  the information extraction function?
                '''
ic| entities:                                      flbl  \
              0  Information Extractor@en^^<xsd:string>

                                                               exe  \
              0  http://testwebsite/testProgram#id_202604121934...

                                                               lbl
              0  As a 30-year-old male managing diabetes, it's ...
ic| answer: GTAnswer(answer_nlp="
                The inputs to the LLM used for the Generative Task in the executions of the information extraction function

                Function | Execution | Inputs for the Generative Task used within execution
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193409_267 | As a 30-year-old male managing diabetes, it's important to fuel your body with nutritious foods that will provide energy without causing significant spikes in blood sugar levels. Here are some light and energy-boosting food suggestions that align with your carnivore diet preference:

            1. **Lean Protein Snacks:** Opt for a small portion of lean protein before your workout. You could have a few slices of turkey or grilled chicken breast. Protein helps in muscle repair and provides lasting energy.

            2. **Hard-Boiled Eggs:** Eggs are a great source of high-quality protein and healthy fats. They can keep you satiated and provide a steady release of energy.

            3. **Greek Yogurt:** Though predominantly a carnivore, if you include some dairy, plain Greek yogurt is a great option. It's high in protein and low in carbohydrates, helping to maintain muscle mass while boosting energy levels.

            4. **Tuna or Salmon:** A small portion of canned tuna or salmon is convenient and provides omega-3 fatty acids along with protein, which can help in managing inflammation and sustaining energy.

            5. **Beef Jerky:** Look for options that are low in sugar and sodium. Beef jerky is a portable and protein-rich snack to keep your energy up before exercise.

            6. **Nuts and Seeds:** If you allow for some nuts, almonds or chia seeds can be sprinkled with your meat snacks for additional fats and energy, though they aren't typically part of a strict carnivore diet.

            In terms of proportion, aim to consume these foods about 30 to 60 minutes before your workout to allow your body to start digesting and producing energy. Remember to stay hydrated with water before, during, and after your exercise session.

            Also, it's fundamental to regularly monitor your blood sugar levels to understand how different foods and physical activity affect you. Continue to adjust portions and meal timing as needed. Always consult with your healthcare provider or a dietitian to ensure your pre-workout nutrition aligns with your diabetes management plan.@en^^<xsd:string>
                ", entities=[{'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193409_267', 'lbl': "As a 30-year-old male managing diabetes, it's important to fuel your body with nutritious foods that will provide energy without causing significant spikes in blood sugar levels. Here are some light and energy-boosting food suggestions that align with your carnivore diet preference:

            1. **Lean Protein Snacks:** Opt for a small portion of lean protein before your workout. You could have a few slices of turkey or grilled chicken breast. Protein helps in muscle repair and provides lasting energy.

            2. **Hard-Boiled Eggs:** Eggs are a great source of high-quality protein and healthy fats. They can keep you satiated and provide a steady release of energy.

            3. **Greek Yogurt:** Though predominantly a carnivore, if you include some dairy, plain Greek yogurt is a great option. It's high in protein and low in carbohydrates, helping to maintain muscle mass while boosting energy levels.

            4. **Tuna or Salmon:** A small portion of canned tuna or salmon is convenient and provides omega-3 fatty acids along with protein, which can help in managing inflammation and sustaining energy.

            5. **Beef Jerky:** Look for options that are low in sugar and sodium. Beef jerky is a portable and protein-rich snack to keep your energy up before exercise.

            6. **Nuts and Seeds:** If you allow for some nuts, almonds or chia seeds can be sprinkled with your meat snacks for additional fats and energy, though they aren't typically part of a strict carnivore diet.

            In terms of proportion, aim to consume these foods about 30 to 60 minutes before your workout to allow your body to start digesting and producing energy. Remember to stay hydrated with water before, during, and after your exercise session.

            Also, it's fundamental to regularly monitor your blood sugar levels to understand how different foods and physical activity affect you. Continue to adjust portions and meal timing as needed. Always consult with your healthcare provider or a dietitian to ensure your pre-workout nutrition aligns with your diabetes management plan.@en^^<xsd:string>"}])
ic| rquestion: '''
                What are the inputs of the Generative Task that was a component in the executions of  the llm chat function function?
                '''
ic| entities:                         flbl  \
              0  LLM Chat@en^^<xsd:string>
              1  LLM Chat@en^^<xsd:string>

                                                               exe  \
              0  http://testwebsite/testProgram#id_202604121934...
              1  http://testwebsite/testProgram#id_202604121934...

                                                               lbl
              0  You are a health care assistant and you will r...
              1  I need suggestions for light and energy-boosti...
ic| answer: GTAnswer(answer_nlp='
                The inputs to the LLM used for the Generative Task in the executions of the llm chat function function

                Function | Execution | Inputs for the Generative Task used within execution
            LLM Chat@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193407_99 | You are a health care assistant and you will respond to the user who is 30 years old, identifies as Male, diagnosed with Diabetic. Consider their height: 182.3, weight: 95.2, body mass index: 28.6, food preferences: Carnivore, and allergies: None when providing a dietary guideline.@en^^<xsd:string>
            LLM Chat@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193407_99 | I need suggestions for light and energy-boosting foods to eat before my gym workout.@en^^<xsd:string>
                ', entities=[{'flbl': 'LLM Chat@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193407_99', 'lbl': 'You are a health care assistant and you will respond to the user who is 30 years old, identifies as Male, diagnosed with Diabetic. Consider their height: 182.3, weight: 95.2, body mass index: 28.6, food preferences: Carnivore, and allergies: None when providing a dietary guideline.@en^^<xsd:string>'}, {'flbl': 'LLM Chat@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193407_99', 'lbl': 'I need suggestions for light and energy-boosting foods to eat before my gym workout.@en^^<xsd:string>'}])

In [46]:
# Question MULT 11 :


template_spec = [ {
    "func_desc": "information extraction"
}, {
    "func_desc": "llm chat function"
}]

sparql_spec = [{
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc_term": "Chat with the LLM"
}]

question_template = """
What are the outputs of the Generative Task that was a component in the executions of the {func_desc} function?
"""

sparql_template = """
SELECT DISTINCT ?flbl ?exe ?lbl
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl .
    FILTER(REGEX(?desc, "{func_desc_term}","i"))

    ?asso prov:hadPlan ?obj .
    ?exe prov:qualifiedAssociation ?asso .

    ?exe sio:SIO_000369 ?llm_gen .
    ?llm_gen prov:used ?llm .
    ?llm sio:SIO_000229 ?out .
    ?out sio:SIO_000202 ?data . 
    ?data prov:value ?lbl . 
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The inputs to the LLM used for the Generative Task in the executions of the {func_desc} function

    {answer_inst}
    """
    
    _ent = entities[['flbl', 'exe', 'lbl']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "flbl": "Function",
            'exe': "Execution",
            'lbl': "Inputs for the Generative Task used within execution"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

gt_list.extend(gts)

ic| rquestion: '''
                What are the outputs of the Generative Task that was a component in the executions of the information extraction function?
                '''
ic| entities:                                      flbl  \
              0  Information Extractor@en^^<xsd:string>
              1  Information Extractor@en^^<xsd:string>
              2  Information Extractor@en^^<xsd:string>
              3  Information Extractor@en^^<xsd:string>
              4  Information Extractor@en^^<xsd:string>
              5  Information Extractor@en^^<xsd:string>
              6  Information Extractor@en^^<xsd:string>
              7  Information Extractor@en^^<xsd:string>
              8  Information Extractor@en^^<xsd:string>

                                                               exe                       lbl
              0  http://testwebsite/testProgram#id_202604121934...     Beef@en^^<xsd:string>
              1  http://testwebsite/testProgram#id_202604121934...   Turkey@en^^<xsd:string>
              2  http://testwebsite/testProgram#id_202604121934...  Chicken@en^^<xsd:string>
              3  http://testwebsite/testProgram#id_202604121934...   Almond@en^^<xsd:string>
              4  http://testwebsite/testProgram#id_202604121934...      Egg@en^^<xsd:string>
              5  http://testwebsite/testProgram#id_202604121934...   Salmon@en^^<xsd:string>
              6  http://testwebsite/testProgram#id_202604121934...     Chia@en^^<xsd:string>
              7  http://testwebsite/testProgram#id_202604121934...   Yogurt@en^^<xsd:string>
              8  http://testwebsite/testProgram#id_202604121934...     Tuna@en^^<xsd:string>
ic| answer: GTAnswer(answer_nlp='
                The inputs to the LLM used for the Generative Task in the executions of the information extraction function

                Function | Execution | Inputs for the Generative Task used within execution
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193409_267 | Beef@en^^<xsd:string>
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193409_267 | Turkey@en^^<xsd:string>
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193409_267 | Chicken@en^^<xsd:string>
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193409_267 | Almond@en^^<xsd:string>
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193409_267 | Egg@en^^<xsd:string>
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193409_267 | Salmon@en^^<xsd:string>
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193409_267 | Chia@en^^<xsd:string>
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193409_267 | Yogurt@en^^<xsd:string>
            Information Extractor@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193409_267 | Tuna@en^^<xsd:string>
                ', entities=[{'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193409_267', 'lbl': 'Beef@en^^<xsd:string>'}, {'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193409_267', 'lbl': 'Turkey@en^^<xsd:string>'}, {'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193409_267', 'lbl': 'Chicken@en^^<xsd:string>'}, {'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193409_267', 'lbl': 'Almond@en^^<xsd:string>'}, {'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193409_267', 'lbl': 'Egg@en^^<xsd:string>'}, {'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193409_267', 'lbl': 'Salmon@en^^<xsd:string>'}, {'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193409_267', 'lbl': 'Chia@en^^<xsd:string>'}, {'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193409_267', 'lbl': 'Yogurt@en^^<xsd:string>'}, {'flbl': 'Information Extractor@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193409_267', 'lbl': 'Tuna@en^^<xsd:string>'}])
ic| rquestion: '''
                What are the outputs of the Generative Task that was a component in the executions of the llm chat function function?
                '''
ic| entities:                         flbl  \
              0  LLM Chat@en^^<xsd:string>

                                                               exe  \
              0  http://testwebsite/testProgram#id_202604121934...

                                                               lbl
              0  As a 30-year-old male managing diabetes, it's ...
ic| answer: GTAnswer(answer_nlp="
                The inputs to the LLM used for the Generative Task in the executions of the llm chat function function

                Function | Execution | Inputs for the Generative Task used within execution
            LLM Chat@en^^<xsd:string> | http://testwebsite/testProgram#id_20260412193407_99 | As a 30-year-old male managing diabetes, it's important to fuel your body with nutritious foods that will provide energy without causing significant spikes in blood sugar levels. Here are some light and energy-boosting food suggestions that align with your carnivore diet preference:

            1. **Lean Protein Snacks:** Opt for a small portion of lean protein before your workout. You could have a few slices of turkey or grilled chicken breast. Protein helps in muscle repair and provides lasting energy.

            2. **Hard-Boiled Eggs:** Eggs are a great source of high-quality protein and healthy fats. They can keep you satiated and provide a steady release of energy.

            3. **Greek Yogurt:** Though predominantly a carnivore, if you include some dairy, plain Greek yogurt is a great option. It's high in protein and low in carbohydrates, helping to maintain muscle mass while boosting energy levels.

            4. **Tuna or Salmon:** A small portion of canned tuna or salmon is convenient and provides omega-3 fatty acids along with protein, which can help in managing inflammation and sustaining energy.

            5. **Beef Jerky:** Look for options that are low in sugar and sodium. Beef jerky is a portable and protein-rich snack to keep your energy up before exercise.

            6. **Nuts and Seeds:** If you allow for some nuts, almonds or chia seeds can be sprinkled with your meat snacks for additional fats and energy, though they aren't typically part of a strict carnivore diet.

            In terms of proportion, aim to consume these foods about 30 to 60 minutes before your workout to allow your body to start digesting and producing energy. Remember to stay hydrated with water before, during, and after your exercise session.

            Also, it's fundamental to regularly monitor your blood sugar levels to understand how different foods and physical activity affect you. Continue to adjust portions and meal timing as needed. Always consult with your healthcare provider or a dietitian to ensure your pre-workout nutrition aligns with your diabetes management plan.@en^^<xsd:string>
                ", entities=[{'flbl': 'LLM Chat@en^^<xsd:string>', 'exe': 'http://testwebsite/testProgram#id_20260412193407_99', 'lbl': "As a 30-year-old male managing diabetes, it's important to fuel your body with nutritious foods that will provide energy without causing significant spikes in blood sugar levels. Here are some light and energy-boosting food suggestions that align with your carnivore diet preference:

            1. **Lean Protein Snacks:** Opt for a small portion of lean protein before your workout. You could have a few slices of turkey or grilled chicken breast. Protein helps in muscle repair and provides lasting energy.

            2. **Hard-Boiled Eggs:** Eggs are a great source of high-quality protein and healthy fats. They can keep you satiated and provide a steady release of energy.

            3. **Greek Yogurt:** Though predominantly a carnivore, if you include some dairy, plain Greek yogurt is a great option. It's high in protein and low in carbohydrates, helping to maintain muscle mass while boosting energy levels.

            4. **Tuna or Salmon:** A small portion of canned tuna or salmon is convenient and provides omega-3 fatty acids along with protein, which can help in managing inflammation and sustaining energy.

            5. **Beef Jerky:** Look for options that are low in sugar and sodium. Beef jerky is a portable and protein-rich snack to keep your energy up before exercise.

            6. **Nuts and Seeds:** If you allow for some nuts, almonds or chia seeds can be sprinkled with your meat snacks for additional fats and energy, though they aren't typically part of a strict carnivore diet.

            In terms of proportion, aim to consume these foods about 30 to 60 minutes before your workout to allow your body to start digesting and producing energy. Remember to stay hydrated with water before, during, and after your exercise session.

            Also, it's fundamental to regularly monitor your blood sugar levels to understand how different foods and physical activity affect you. Continue to adjust portions and meal timing as needed. Always consult with your healthcare provider or a dietitian to ensure your pre-workout nutrition aligns with your diabetes management plan.@en^^<xsd:string>"}])

In [47]:
# Question MULT 11 :

_spec = [ {
    "func_desc": "information extraction",
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc": "llm chat function",
    "func_desc_term": "Chat with the LLM"
}]

template_spec = []
sparql_spec = []

for _s in _spec:
    exe_query = """
    SELECT DISTINCT ?exe
    WHERE {
        ?obj dc:description ?desc .
        ?obj rdfs:label ?flbl .
        FILTER(REGEX(?desc, "{func_desc_term}","i"))
        
        ?asso prov:hadPlan ?obj .
        ?exe prov:qualifiedAssociation ?asso .      
        
        }
    """
    executions = graph_manager.query(
        regex_add_strings(exe_query, func_desc_term = _s["func_desc_term"])
    )


    for obj in executions.to_dict("records"):
        template_spec.append({
            "exe_id":obj['exe']
        })
        
        sparql_spec.append({
            "exe_id":obj['exe']
        })

question_template = """
What execution created the output data that was used as an input for the generative task within the execution {exe_id}?
"""

sparql_template = """
SELECT DISTINCT ?exe2
    WHERE {
        <{exe_id}> sio:SIO_000369 ?llm_gen .
        ?llm_gen prov:used ?llm .
        ?llm sio:SIO_000229 ?out .
        ?out sio:SIO_000202 ?data . 
        ?data prov:wasGeneratedBy ?exe2 . 
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The inputs to the Generative Task in the execution of {exe_id} was generated by executions

    {answer_inst}
    """
    
    _ent = entities[['exe2']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            'exe2': "Execution"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        exe_id = question_specs["exe_id"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

gt_list.extend(gts)

ic| rquestion: '''
                What execution created the output data that was used as an input for the generative task within the execution http://testwebsite/testProgram#id_20260412193409_267?
                '''
ic| entities:                                                 exe2
              0  http://testwebsite/testProgram#id_202604121934...
              1  http://testwebsite/testProgram#id_202604121934...
              2  http://testwebsite/testProgram#id_202604121934...
              3  http://testwebsite/testProgram#id_202604121934...
              4  http://testwebsite/testProgram#id_202604121934...
              5  http://testwebsite/testProgram#id_202604121934...
              6  http://testwebsite/testProgram#id_202604121934...
              7  http://testwebsite/testProgram#id_202604121934...
              8  http://testwebsite/testProgram#id_202604121934...
              9  http://testwebsite/testProgram#id_202604121934...
ic| answer: GTAnswer(answer_nlp='
                The inputs to the Generative Task in the execution of http://testwebsite/testProgram#id_20260412193409_267 was generated by executions

                Execution
            http://testwebsite/testProgram#id_20260412193409_267
            http://testwebsite/testProgram#id_20260412193411_732
            http://testwebsite/testProgram#id_20260412193409_379
            http://testwebsite/testProgram#id_20260412193409_378
            http://testwebsite/testProgram#id_20260412193411_381
            http://testwebsite/testProgram#id_20260412193409_974
            http://testwebsite/testProgram#id_20260412193411_429
            http://testwebsite/testProgram#id_20260412193411_661
            http://testwebsite/testProgram#id_20260412193410_245
            http://testwebsite/testProgram#id_20260412193410_757
                ', entities=[{'exe2': 'http://testwebsite/testProgram#id_20260412193409_267'}, {'exe2': 'http://testwebsite/testProgram#id_20260412193411_732'}, {'exe2': 'http://testwebsite/testProgram#id_20260412193409_379'}, {'exe2': 'http://testwebsite/testProgram#id_20260412193409_378'}, {'exe2': 'http://testwebsite/testProgram#id_20260412193411_381'}, {'exe2': 'http://testwebsite/testProgram#id_20260412193409_974'}, {'exe2': 'http://testwebsite/testProgram#id_20260412193411_429'}, {'exe2': 'http://testwebsite/testProgram#id_20260412193411_661'}, {'exe2': 'http://testwebsite/testProgram#id_20260412193410_245'}, {'exe2': 'http://testwebsite/testProgram#id_20260412193410_757'}])
ic| rquestion: '''
                What execution created the output data that was used as an input for the generative task within the execution http://testwebsite/testProgram#id_20260412193407_99?
                '''
ic| entities:                                                 exe2
              0  http://testwebsite/testProgram#id_202604121934...
              1  http://testwebsite/testProgram#id_202604121934...
ic| answer: GTAnswer(answer_nlp='
                The inputs to the Generative Task in the execution of http://testwebsite/testProgram#id_20260412193407_99 was generated by executions

                Execution
            http://testwebsite/testProgram#id_20260412193407_99
            http://testwebsite/testProgram#id_20260412193409_267
                ', entities=[{'exe2': 'http://testwebsite/testProgram#id_20260412193407_99'}, {'exe2': 'http://testwebsite/testProgram#id_20260412193409_267'}])

In [50]:
_spec = [ {
    "func_desc": "information extraction",
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc": "sparql query function",
    "func_desc_term": "Builds SPARQL queries to extract"
}]

template_spec = []
sparql_spec = []

for _s in _spec:
    exe_query = """
    SELECT DISTINCT ?exe
    WHERE {
        ?obj dc:description ?desc .
        ?obj rdfs:label ?flbl .
        FILTER(REGEX(?desc, "{func_desc_term}","i"))
        
        ?asso prov:hadPlan ?obj .
        ?exe prov:qualifiedAssociation ?asso .      
        
        }
    """
    executions = graph_manager.query(
        regex_add_strings(exe_query, func_desc_term = _s["func_desc_term"])
    )


    for obj in executions.to_dict("records"):
        
        sparql_template = """
        SELECT DISTINCT ?glbl
            WHERE {
                <{exe_id}> prov:used ?data .
                ?llm_out sio:SIO_000202 ?data .
                ?llm_out sio:SIO_000232 ?llm .
                ?gtask prov:used ?llm .
                ?gtask rdfs:label ?glbl
        }
        """
        
        df = graph_manager.query(
            regex_add_strings(
                sparql_template,
                exe_id = obj["exe"]
            )
        )
        
        print(df.iloc[0,0])
        template_spec.append({
            "exe_id":obj['exe']
        })
        
        sparql_spec.append({
            "exe_id":obj['exe']
        })

LLM Generates an text for
system prompt:

user prompt: I need suggestions for light and energy-boosting foods to eat before my gym workout.

using: gpt-4o@en^^<xsd:string>
Extracts important entities for
text:

using: gpt-4o@en^^<xsd:string>
Extracts important entities for
text:

using: gpt-4o@en^^<xsd:string>
Extracts important entities for
text:

using: gpt-4o@en^^<xsd:string>
Extracts important entities for
text:

using: gpt-4o@en^^<xsd:string>
Extracts important entities for
text:

using: gpt-4o@en^^<xsd:string>
Extracts important entities for
text:

using: gpt-4o@en^^<xsd:string>
Extracts important entities for
text:

using: gpt-4o@en^^<xsd:string>
Extracts important entities for
text:

using: gpt-4o@en^^<xsd:string>
Extracts important entities for
text:

using: gpt-4o@en^^<xsd:string>

In [ ]:
# Question MULT 12 :

_spec = [ {
    "func_desc": "information extraction",
    "func_desc_term":"Extracts entities or relevant information"
}, {
    "func_desc": "sparql query function",
    "func_desc_term": "Builds SPARQL queries to extract"
}]

template_spec = []
sparql_spec = []

for _s in _spec:
    exe_query = """
    SELECT DISTINCT ?exe
    WHERE {
        ?obj dc:description ?desc .
        ?obj rdfs:label ?flbl .
        FILTER(REGEX(?desc, "{func_desc_term}","i"))
        
        ?asso prov:hadPlan ?obj .
        ?exe prov:qualifiedAssociation ?asso .      
        
        }
    """
    executions = graph_manager.query(
        regex_add_strings(exe_query, func_desc_term = _s["func_desc_term"])
    )


    for obj in executions.to_dict("records"):
        template_spec.append({
            "exe_id":obj['exe']
        })
        
        sparql_spec.append({
            "exe_id":obj['exe']
        })

question_template = """
What Generative Task generated the data that was used by the execution {exe_id}?
"""

sparql_template = """
SELECT DISTINCT ?exe2
    WHERE {
        <{exe_id}> sio:SIO_000369 ?llm_gen .
        ?llm_gen prov:used ?llm .
        ?llm sio:SIO_000229 ?out .
        ?out sio:SIO_000202 ?data . 
        ?data prov:wasGeneratedBy ?exe2 . 
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The inputs to the Generative Task in the execution of {exe_id} was generated by executions

    {answer_inst}
    """
    
    _ent = entities[['exe2']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            'exe2': "Execution"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        exe_id = question_specs["exe_id"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

gt_list.extend(gts)

In [23]:
# Question MULT 10 : Does a specific execution contain a Generative Task

In [25]:
# what are the output data of the generative task that was used within an execution task

In [26]:
# what are the  input data used by generative tasks that were used within an execution task

In [27]:
#

In [28]:
os.makedirs(os.path.dirname(config.gt.save_loc), exist_ok=True)
for i, gt in enumerate(gt_list):
    gt.id = f"gt_{i}"

# common_utils.serialization.save_json(
#     {gt.id: gt.model_dump() for gt in gt_list}, config.gt.save_loc
# )

In [29]:
gt_list

[GT(id='gt_0', question='\nHow many unique "experiment execution" are there in this?\n', answer='The answer to the question is 1 unique executions.', entities=[{'obj_count': '1'}], sparql_querys=[SPARQLTemplate(template='\nSELECT (count(distinct ?ids) AS ?obj_count)\nWHERE {\n     ?obj a provone:Execution ;\n          dcterms:identifier ?ids .\n}\n', description='This SPARQL query counts the number of unique executions by counting distinct identifiers in the provone:Execution class.', inputs=None)], tags={}),
 GT(id='gt_1', question='\nwhat are the instructions used by the LLM to generate the sparql query post processing function step in the pipeline?\n', answer="\nWe utilize the following input instructions to generate the function that is used to post process the sparql query results from the previous step.\n\n1. Concat all the rows into single row at each column by '|' concatenation marker.@en^^<xsd:string>\n2. If there are duplicate ingredients then select row with most information on `sugarG` and `ingredientCat` columns.\n   Fill all the missing values with '0' in `sugarG` column and with '-' in 'ingredientCat` column.@en^^<xsd:string>\n", entities=[{'obj': 'ChatBS-NexGen:query_result_post_processor', 'llm': 'ChatBS-NexGen:LLM-query_result_post_processor', 'inpd': "Concat all the rows into single row at each column by '|' concatenation marker.@en^^<xsd:string>"}, {'obj': 'ChatBS-NexGen:query_result_post_processor', 'llm': 'ChatBS-NexGen:LLM-query_result_post_processor', 'inpd': "If there are duplicate ingredients then select row with most information on `sugarG` and `ingredientCat` columns. Fill all the missing values with '0' in `sugarG` column and with '-' in 'ingredientCat` column.@en^^<xsd:string>"}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?obj ?llm ?inpd\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Post-processes the query results","i"))\n\n     ?llm_out sio:SIO_000202 ?obj .\n     ?llm_out sio:SIO_000232 ?llm .\n     ?llm sio:SIO_000230 ?inp .\n     ?inp prov:value ?inpd\n}\n', description='', inputs=None)], tags={}),
 GT(id='gt_2', question='\nIn what places do we utilize AI in this workflow?\n', answer="\nThe ChatBS System utilizes LLMs to generate the following functions\n\n1. Information extraction function\n2. System Prompt template function\n3. Sparql result post processing function\n\nand further it's used within functions to\n1. Generate the LLM outputs,\n2. Used to extract key information from the system.\n", entities=[{'obj': 'ChatBS-NexGen:Generative_Task-id_20260324230458_784', 'desc': 'Generates the answer using  gpt-4o@en^^<xsd:string>'}, {'obj': 'ChatBS-NexGen:Generative_Task-id_20260324230500_68', 'desc': 'Extracts the information using  gpt-4o@en^^<xsd:string>'}, {'obj': 'ChatBS-NexGen:Generative_Task-information_extractor', 'desc': 'Generates the Information Extractor Function using Large language models@en^^<xsd:string>'}, {'obj': 'ChatBS-NexGen:Generative_Task-query_result_post_processor', 'desc': 'Generates the post processing Function using Large language models@en^^<xsd:string>'}, {'obj': 'ChatBS-NexGen:Generative_Task-system_prompt_generator', 'desc': 'Generates the System Prompt Template using Large language models@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?obj ?desc\nWHERE {\n     ?obj a workflow:Generative_Task .\n     ?obj dc:description ?desc .\n}\n', description='', inputs=None)], tags={}),
 GT(id='gt_3', question='\nWhat are the extracted KG entities for the execution with id 1_1\n', answer='\nThe retrieved entities from the knowledge graph includes the following ingredients,\n\n1. Yogurt\n2. Berry\n3. Cheese\n4. Carrot\n5. Turkey\n6. Bell pepper\n7. Hummus\n8. Almond\n9. Avocado\n10. Pumpkin seed\n11. Water\n12. Pineapple\n13. Cottage cheese\n', entities=['Avocado', 'Yogurt', 'Turkey', 'Cottage cheese', 'Carrot', 'Water', 'Almond', 'Pineapple', 'Hummus', 'Cheese', 'Bell pepper', 'Berry', 'Pumpkin seed'], sparql_querys=[SPARQLTemplate(template='\nSELECT DISTINCT ?member ?prop ?value\nWHERE {\n     ?obj dc:description ?desc .\n     FILTER(REGEX(?desc, "SPARQL queries to extract information", "i"))\n\n     ?obj a provone:Program .\n     ?exe prov:qualifiedAssociation/prov:hadPlan ?obj .\n     ?exe dcterms:identifier ?id .\n     FILTER(REGEX(?id, "1_1", "i"))\n\n     ?data prov:wasGeneratedBy ?exe .\n     ?data a ?class .\n\n     {\n         ?data a provone:Collection .\n         ?data provone:hadMember ?member .\n         ?member ?prop ?value .\n     }\n     UNION\n     {\n         ?data a provone:Data .\n         BIND(?data AS ?member)\n         ?data ?prop ?value .\n     }\n}\n', description='', inputs=None)], tags={}),
 GT(id='gt_4', question='\nwhy did some ingredients have missing values for `sugarG` and `ingredientCat` columns in the final output of the workflow?\n', answer="\nDue to the fact that some information is not available in the knowledge graph for ingredients such as\n'Turkey', 'Hummus', 'Cheese', 'Cottage cheese', 'Berry', 'Water' the sugarG and ingredientCat is not available.\n", entities=['Cottage cheese', 'Turkey', 'Water', 'Hummus', 'Cheese', 'Berry'], sparql_querys=[SPARQLTemplate(template='\nSELECT DISTINCT ?member ?prop ?value\nWHERE {\n     ?obj dc:description ?desc .\n     FILTER(REGEX(?desc, "SPARQL queries to extract information", "i"))\n\n     ?obj a provone:Program .\n     ?exe prov:qualifiedAssociation/prov:hadPlan ?obj .\n     ?exe dcterms:identifier ?id .\n     FILTER(REGEX(?id, "1_1", "i"))\n\n     ?data prov:wasGeneratedBy ?exe .\n     ?data a ?class .\n\n     {\n         ?data a provone:Collection .\n         ?data provone:hadMember ?member .\n         ?member ?prop ?value .\n     }\n     UNION\n     {\n         ?data a provone:Data .\n         BIND(?data AS ?member)\n         ?data ?prop ?value .\n     }\n}\n\norder by ?member ?prop\n', description='', inputs=None)], tags={}),
 GT(id='gt_5', question='\nwhat are the instructions used by the LLM to generate the sparql query post processing function step in the pipeline?\n', answer="\n    We utilize the following input instructions to generate the function responsible for sparql query post processing.\n\n    Funtion | Instruction for function generation\nhttp://testwebsite/testProgram#query_result_post_processor | Concat all the rows into single row at each column by '|' concatenation marker.@en^^<xsd:string>\nhttp://testwebsite/testProgram#query_result_post_processor | If there are duplicate ingredients then select row with most information on `sugarG` and `ingredientCat` columns. Fill all the missing values with '0' in `sugarG` column and with '-' in 'ingredientCat` column.@en^^<xsd:string>\n    ", entities=[{'obj': 'http://testwebsite/testProgram#query_result_post_processor', 'inpd': "Concat all the rows into single row at each column by '|' concatenation marker.@en^^<xsd:string>"}, {'obj': 'http://testwebsite/testProgram#query_result_post_processor', 'inpd': "If there are duplicate ingredients then select row with most information on `sugarG` and `ingredientCat` columns. Fill all the missing values with '0' in `sugarG` column and with '-' in 'ingredientCat` column.@en^^<xsd:string>"}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?obj ?llm ?inpd\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Post-processes the query results","i"))\n\n     ?llm_out sio:SIO_000202 ?obj .\n     ?llm_out sio:SIO_000232 ?llm .\n     ?llm sio:SIO_000230 ?inp .\n     ?inp prov:value ?inpd\n}\n', description='', inputs=None)], tags={}),
 GT(id='gt_6', question='\nwhat are the instructions used by the LLM to generate the system prompt template function step in the pipeline?\n', answer='\n    We utilize the following input instructions to generate the function responsible for system prompt template.\n\n    Funtion | Instruction for function generation\nhttp://testwebsite/testProgram#system_prompt_generator | You are a health care assistant@en^^<xsd:string>\nhttp://testwebsite/testProgram#system_prompt_generator | gpt-4o@en^^<xsd:string>\n    ', entities=[{'obj': 'http://testwebsite/testProgram#system_prompt_generator', 'inpd': 'You are a health care assistant@en^^<xsd:string>'}, {'obj': 'http://testwebsite/testProgram#system_prompt_generator', 'inpd': 'gpt-4o@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?obj ?llm ?inpd\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Generates a system prompt","i"))\n\n     ?llm_out sio:SIO_000202 ?obj .\n     ?llm_out sio:SIO_000232 ?llm .\n     ?llm sio:SIO_000230 ?inp .\n     ?inp prov:value ?inpd\n}\n', description='', inputs=None)], tags={}),
 GT(id='gt_7', question='\nwhat are the instructions used by the LLM to generate the information extraction function step in the pipeline?\n', answer="\n    We utilize the following input instructions to generate the function responsible for information extraction.\n\n    Funtion | Instruction for function generation\nhttp://testwebsite/testProgram#information_extractor | gpt-4o@en^^<xsd:string>\nhttp://testwebsite/testProgram#information_extractor | Extract all the main ingredients without any subsidiary; return in singular noun form and First letter capital. Extract mean and dairy product in its' base form. (e.g., from 'egg white' extract 'Egg')@en^^<xsd:string>\n    ", entities=[{'obj': 'http://testwebsite/testProgram#information_extractor', 'inpd': 'gpt-4o@en^^<xsd:string>'}, {'obj': 'http://testwebsite/testProgram#information_extractor', 'inpd': "Extract all the main ingredients without any subsidiary; return in singular noun form and First letter capital. Extract mean and dairy product in its' base form. (e.g., from 'egg white' extract 'Egg')@en^^<xsd:string>"}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?obj ?llm ?inpd\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Extracts entities or relevant information","i"))\n\n     ?llm_out sio:SIO_000202 ?obj .\n     ?llm_out sio:SIO_000232 ?llm .\n     ?llm sio:SIO_000230 ?inp .\n     ?inp prov:value ?inpd\n}\n', description='', inputs=None)], tags={}),
 GT(id='gt_8', question='\nwhat are the input parameters of the function used in sparql query post processing step in the pipeline?\n', answer='\n    The input parameters to sparql query post processing function.\n\n    Funtion name | Function returns\nQuery Result Post-Processor@en^^<xsd:string> | Post-processing input port: kg_knowledge@en^^<xsd:string>\n    ', entities=[{'flbl': 'Query Result Post-Processor@en^^<xsd:string>', 'lbl': 'Post-processing input port: kg_knowledge@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Post-processes the query results","i"))\n\n     ?obj provone:hasInPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], tags={}),
 GT(id='gt_9', question='\nwhat are the input parameters of the function used in system prompt template step in the pipeline?\n', answer='\n    The input parameters to system prompt template function.\n\n    Funtion name | Function returns\nSystem Prompt Template Generator@en^^<xsd:string> | Input port for age@en^^<xsd:string>\nSystem Prompt Template Generator@en^^<xsd:string> | Input port for allergies@en^^<xsd:string>\nSystem Prompt Template Generator@en^^<xsd:string> | Input port for bodyMassIndex@en^^<xsd:string>\nSystem Prompt Template Generator@en^^<xsd:string> | Input port for diagnosis@en^^<xsd:string>\nSystem Prompt Template Generator@en^^<xsd:string> | Input port for foodPreferences@en^^<xsd:string>\nSystem Prompt Template Generator@en^^<xsd:string> | Input port for gender@en^^<xsd:string>\nSystem Prompt Template Generator@en^^<xsd:string> | Input port for height@en^^<xsd:string>\nSystem Prompt Template Generator@en^^<xsd:string> | Input port for weight@en^^<xsd:string>\n    ', entities=[{'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for age@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for allergies@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for bodyMassIndex@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for diagnosis@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for foodPreferences@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for gender@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for height@en^^<xsd:string>'}, {'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'Input port for weight@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Generates a system prompt","i"))\n\n     ?obj provone:hasInPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], tags={}),
 GT(id='gt_10', question='\nwhat are the input parameters of the function used in information extraction step in the pipeline?\n', answer='\n    The input parameters to information extraction function.\n\n    Funtion name | Function returns\nInformation Extractor@en^^<xsd:string> | Input port for text@en^^<xsd:string>\n    ', entities=[{'flbl': 'Information Extractor@en^^<xsd:string>', 'lbl': 'Input port for text@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Extracts entities or relevant information","i"))\n\n     ?obj provone:hasInPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], tags={}),
 GT(id='gt_11', question='\nwhat are the input parameters of the function used in sparql query function step in the pipeline?\n', answer='\n    The input parameters to sparql query function function.\n\n    Funtion name | Function returns\nSPARQL Query Builder@en^^<xsd:string> | Input port for entity@en^^<xsd:string>\n    ', entities=[{'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'lbl': 'Input port for entity@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Builds SPARQL","i"))\n\n     ?obj provone:hasInPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], tags={}),
 GT(id='gt_12', question='\nwhat are the input parameters of the function used in llm chat function step in the pipeline?\n', answer='\n    The input parameters to llm chat function function.\n\n    Funtion name | Function returns\nLLM Chat@en^^<xsd:string> | LLM Chat input port: system_prompt@en^^<xsd:string>\nLLM Chat@en^^<xsd:string> | LLM Chat input port: user_prompt@en^^<xsd:string>\n    ', entities=[{'flbl': 'LLM Chat@en^^<xsd:string>', 'lbl': 'LLM Chat input port: system_prompt@en^^<xsd:string>'}, {'flbl': 'LLM Chat@en^^<xsd:string>', 'lbl': 'LLM Chat input port: user_prompt@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Chat with","i"))\n\n     ?obj provone:hasInPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], tags={}),
 GT(id='gt_13', question='\nwhat are the input parameters of the function used in sparql query post processing step in the pipeline?\n', answer='\n    The input parameters to sparql query post processing function.\n\n    Funtion name | Function returns\nQuery Result Post-Processor@en^^<xsd:string> | Post-processed output port: post_processed_output@en^^<xsd:string>\n    ', entities=[{'flbl': 'Query Result Post-Processor@en^^<xsd:string>', 'lbl': 'Post-processed output port: post_processed_output@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Post-processes the query results","i"))\n\n     ?obj provone:hasOutPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], tags={}),
 GT(id='gt_14', question='\nwhat are the input parameters of the function used in system prompt template step in the pipeline?\n', answer='\n    The input parameters to system prompt template function.\n\n    Funtion name | Function returns\nSystem Prompt Template Generator@en^^<xsd:string> | System Prompt@en^^<xsd:string>\n    ', entities=[{'flbl': 'System Prompt Template Generator@en^^<xsd:string>', 'lbl': 'System Prompt@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Generates a system prompt","i"))\n\n     ?obj provone:hasOutPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], tags={}),
 GT(id='gt_15', question='\nwhat are the input parameters of the function used in information extraction step in the pipeline?\n', answer='\n    The input parameters to information extraction function.\n\n    Funtion name | Function returns\nInformation Extractor@en^^<xsd:string> | Extracted Entities@en^^<xsd:string>\n    ', entities=[{'flbl': 'Information Extractor@en^^<xsd:string>', 'lbl': 'Extracted Entities@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Extracts entities or relevant information","i"))\n\n     ?obj provone:hasOutPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], tags={}),
 GT(id='gt_16', question='\nwhat are the input parameters of the function used in sparql query function step in the pipeline?\n', answer='\n    The input parameters to sparql query function function.\n\n    Funtion name | Function returns\nSPARQL Query Builder@en^^<xsd:string> | Output port for kg_info@en^^<xsd:string>\n    ', entities=[{'flbl': 'SPARQL Query Builder@en^^<xsd:string>', 'lbl': 'Output port for kg_info@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Builds SPARQL queries to extract","i"))\n\n     ?obj provone:hasOutPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], tags={}),
 GT(id='gt_17', question='\nwhat are the input parameters of the function used in llm chat function step in the pipeline?\n', answer='\n    The input parameters to llm chat function function.\n\n    Funtion name | Function returns\nLLM Chat@en^^<xsd:string> | LLM Chat output port: generated_answer@en^^<xsd:string>\n    ', entities=[{'flbl': 'LLM Chat@en^^<xsd:string>', 'lbl': 'LLM Chat output port: generated_answer@en^^<xsd:string>'}], sparql_querys=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?desc, "Chat with the LLM","i"))\n\n     ?obj provone:hasOutPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], tags={}),