# Paper Summary Tables

Load the analysis summaries and prepare editable tables for the paper. The cells are intentionally simple: change the column lists, rerun, and copy/export the table you want.

In [45]:
from pathlib import Path

# If this import fails in a fresh kernel, install pandas in the notebook environment first.
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 160)

repo_relative_dir = Path("evaluations/chatbs-base")
BASE_DIR = repo_relative_dir if (repo_relative_dir / "analysis").exists() else Path.cwd()
ANALYSIS_DIR = BASE_DIR / "analysis"

TABLE_OUTPUT_DIR = BASE_DIR / "paper_tables"
TABLE_OUTPUT_DIR.mkdir(exist_ok=True)

BASE_DIR

PosixPath('/home/desild/work/research/LLM-Workflow-Explorer/evaluations/chatbs-base')

## Load Summary Results

In [46]:
summary_paths = {
    "bool": ANALYSIS_DIR / "bool" / "results_summary.csv",
    "entity": ANALYSIS_DIR / "entity" / "results_summary.csv",
    "numeric": ANALYSIS_DIR / "numeric" / "results_summary.csv",
    "answer_winrate": ANALYSIS_DIR / "answer_winrate" / "answer_winrate_summary.csv",
    "pairwise_answer_winrate": ANALYSIS_DIR / "answer_winrate" / "pairwise_answer_winrate.csv",
}

summaries = {}
for name, path in summary_paths.items():
    if path.exists():
        summaries[name] = pd.read_csv(path)
    else:
        print(f"Missing: {path}")

summaries.keys()

dict_keys(['bool', 'entity', 'numeric', 'answer_winrate', 'pairwise_answer_winrate'])

In [47]:
# Quick preview of each loaded summary.
for name, df in summaries.items():
    print(f"\n{name}: {df.shape[0]} rows x {df.shape[1]} columns")
    display(df.head())

bool: 7 rows x 36 columns

,run,evaluated_examples,matched_ground_truth,avg_prediction_time_taken,answer_token_precision_mean,answer_token_precision_std,answer_token_recall_mean,answer_token_recall_std,answer_token_f1_mean,answer_token_f1_std,gt_entity_total_mean,gt_entity_total_std,gt_entity_covered_mean,gt_entity_covered_std,gt_entity_coverage_mean,gt_entity_coverage_std,bertscore_precision_mean,bertscore_precision_std,bertscore_recall_mean,bertscore_recall_std,bertscore_f1_mean,bertscore_f1_std,llm_completeness_mean,llm_completeness_std,llm_faithfulness_mean,llm_faithfulness_std,llm_relevance_mean,llm_relevance_std,llm_understanderbility_mean,llm_understanderbility_std,nli_entailment_max_mean,nli_entailment_max_std,nli_pairs_scored_mean,nli_pairs_scored_std,bool_accuracy_mean,bool_accuracy_std
0,fullcontext,38,38,18.636609,0.637632,0.216062,0.472221,0.214535,0.496864,0.190238,2.289474,2.759827,0.394737,0.679406,0.146592,0.277779,0.808490,0.026721,0.836027,0.034423,0.821554,0.023501,0.805263,0.309269,0.810526,0.358518,0.968421,0.055044,0.797368,0.093684,0.655778,0.248837,1.0,0.000000,0.894737,0.311012
1,grasp,38,38,15.282982,0.106623,0.241796,0.093875,0.196543,0.085124,0.182238,2.289474,2.759827,0.026316,0.162221,0.002024,0.012479,0.840972,0.053186,0.766515,0.060298,0.800113,0.040520,0.647368,0.445844,0.639474,0.465304,0.878947,0.309234,0.815789,0.179378,0.492698,0.343165,0.5,0.506712,0.289474,0.459606
2,hipporag,38,38,4.148827,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.289474,2.759827,0.289474,0.459606,0.206140,0.372041,0.709924,0.016835,0.762432,0.010461,0.735114,0.010096,0.371053,0.468989,0.407895,0.482326,0.934211,0.194903,0.942105,0.103013,0.260601,0.248893,1.0,0.000000,0.526316,0.506009
3,hypergraphrag,38,38,9.722721,0.236746,0.114948,0.418532,0.352726,0.258888,0.184904,2.289474,2.759827,0.052632,0.226294,0.008603,0.042108,0.833537,0.020551,0.806944,0.063984,0.819021,0.039187,0.363158,0.459389,0.378947,0.476421,0.548947,0.479012,0.842105,0.148199,0.503595,0.327835,1.0,0.000000,0.421053,0.500355
4,llmbased,38,38,0.891846,0.347558,0.174426,0.165251,0.062034,0.205004,0.074823,2.289474,2.759827,0.000000,0.000000,0.000000,0.000000,0.781740,0.027722,0.776166,0.018446,0.778511,0.014260,0.160526,0.261533,0.100000,0.191721,0.336842,0.329144,0.718421,0.131221,0.277763,0.328332,1.0,0.000000,0.000000,0.000000

entity: 7 rows x 52 columns

,run,evaluated_examples,matched_ground_truth,avg_prediction_time_taken,answer_token_precision_mean,answer_token_precision_std,answer_token_recall_mean,answer_token_recall_std,answer_token_f1_mean,answer_token_f1_std,gt_entity_total_mean,gt_entity_total_std,gt_entity_covered_mean,gt_entity_covered_std,gt_entity_coverage_mean,gt_entity_coverage_std,bertscore_precision_mean,bertscore_precision_std,bertscore_recall_mean,bertscore_recall_std,bertscore_f1_mean,bertscore_f1_std,llm_completeness_mean,llm_completeness_std,llm_faithfulness_mean,llm_faithfulness_std,llm_relevance_mean,llm_relevance_std,llm_understanderbility_mean,llm_understanderbility_std,nli_entailment_max_mean,nli_entailment_max_std,nli_pairs_scored_mean,nli_pairs_scored_std,entity_gt_total_mean,entity_gt_total_std,entity_retrieved_final_total_mean,entity_retrieved_final_total_std,entity_retrieved_total_total_mean,entity_retrieved_total_total_std,entity_recall_final_mean,entity_recall_final_std,entity_precision_final_mean,entity_precision_final_std,entity_f1_final_mean,entity_f1_final_std,entity_recall_total_mean,entity_recall_total_std,entity_precision_total_mean,entity_precision_total_std,entity_f1_total_mean,entity_f1_total_std
0,fullcontext,49,49,17.327311,0.410651,0.241189,0.285590,0.212900,0.250826,0.142330,2.673469,3.118411,0.428571,0.540062,0.350775,0.430162,0.834169,0.063563,0.843230,0.061692,0.838148,0.059509,0.526531,0.326455,0.600000,0.403113,0.820408,0.245993,0.741837,0.119612,0.314016,0.258931,1.000000,0.000000,2.55102,3.075855,6.857143,3.452053,11.142857,4.276876,0.566949,0.441061,0.160490,0.169350,0.379824,0.152705,0.658386,0.443409,0.112145,0.130628,0.268076,0.168961
1,grasp,49,49,16.038171,0.185071,0.260656,0.112896,0.180168,0.097409,0.136544,2.673469,3.118411,0.122449,0.484452,0.044574,0.174753,0.826952,0.036823,0.786332,0.033841,0.805476,0.026598,0.308163,0.367331,0.334694,0.405972,0.466327,0.418876,0.614286,0.278388,0.260185,0.261008,0.551020,0.502545,2.55102,3.075855,0.469388,1.276421,0.469388,1.276421,0.027132,0.125621,0.175000,0.361544,0.583333,0.117851,0.027132,0.125621,0.175000,0.361544,0.583333,0.117851
2,hipporag,49,49,5.224696,0.270040,0.196627,0.114260,0.148249,0.116263,0.116931,2.673469,3.118411,0.265306,1.094979,0.053488,0.216409,0.719528,0.021459,0.781964,0.024599,0.749001,0.013689,0.203197,0.244213,0.189796,0.305672,0.374490,0.353719,0.720408,0.132255,0.201577,0.217731,1.000000,0.000000,2.55102,3.075855,79.979592,7.456792,158.102041,15.426229,0.345458,0.440396,0.009490,0.014862,0.044388,0.027052,0.647933,0.455820,0.013366,0.018663,0.041964,0.036322
3,hypergraphrag,49,49,14.491856,0.203279,0.158600,0.300364,0.258037,0.162739,0.096721,2.673469,3.118411,0.183673,0.882078,0.060078,0.223700,0.810532,0.021702,0.801310,0.039101,0.805147,0.020228,0.327143,0.326752,0.367551,0.384559,0.665306,0.366601,0.765714,0.144971,0.286587,0.222220,0.979592,0.142857,2.55102,3.075855,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN
4,llmbased,49,49,0.896387,0.318264,0.183937,0.149108,0.119394,0.143759,0.099656,2.673469,3.118411,0.000000,0.000000,0.000000,0.000000,0.783663,0.025584,0.779654,0.027518,0.781073,0.015560,0.177551,0.197131,0.114286,0.176777,0.391837,0.290715,0.667347,0.165060,0.145957,0.168293,1.000000,0.000000,2.55102,3.075855,9.224490,5.355158,11.489796,4.354703,0.298974,0.372878,0.045294,0.059751,0.163553,0.076607,0.568353,0.409704,0.085533,0.070205,0.196742,0.089751

numeric: 7 rows x 40 columns

,run,evaluated_examples,matched_ground_truth,avg_prediction_time_taken,answer_token_precision_mean,answer_token_precision_std,answer_token_recall_mean,answer_token_recall_std,answer_token_f1_mean,answer_token_f1_std,gt_entity_total_mean,gt_entity_total_std,gt_entity_covered_mean,gt_entity_covered_std,gt_entity_coverage_mean,gt_entity_coverage_std,bertscore_precision_mean,bertscore_precision_std,bertscore_recall_mean,bertscore_recall_std,bertscore_f1_mean,bertscore_f1_std,llm_completeness_mean,llm_completeness_std,llm_faithfulness_mean,llm_faithfulness_std,llm_relevance_mean,llm_relevance_std,llm_understanderbility_mean,llm_understanderbility_std,nli_entailment_max_mean,nli_entailment_max_std,nli_pairs_scored_mean,nli_pairs_scored_std,numeric_ground_truth_count_mean,numeric_ground_truth_count_std,numeric_predicted_count_mean,numeric_predicted_count_std,numeric_accuracy_mean,numeric_accuracy_std
0,fullcontext,16,16,17.014147,0.660500,0.182352,0.345912,0.201994,0.408937,0.117243,2.8125,4.069705,0.8125,2.762095,0.125,0.341565,0.824401,0.028487,0.831342,0.041486,0.827059,0.023760,0.697917,0.288410,0.68125,0.406971,0.965625,0.023936,0.75000,0.089443,0.286214,0.195454,1.000,0.0,2.8125,4.069705,679.666667,1156.433022,0.0625,0.250000
1,grasp,16,16,14.304717,0.190341,0.346633,0.049062,0.081392,0.055236,0.087070,2.8125,4.069705,0.0000,0.000000,0.000,0.000000,0.820224,0.052872,0.793875,0.068129,0.804871,0.043604,0.750000,0.447214,0.75000,0.447214,0.968750,0.125000,0.80000,0.000000,0.465113,0.313248,0.375,0.5,2.8125,4.069705,0.600000,0.894427,0.1250,0.341565
2,hipporag,16,16,3.712118,0.372024,0.399251,0.040831,0.072612,0.064290,0.095343,2.8125,4.069705,0.0000,0.000000,0.000,0.000000,0.718650,0.017949,0.767990,0.024609,0.742070,0.009379,0.282578,0.442226,0.25000,0.447214,0.656250,0.263233,0.91875,0.098107,0.315796,0.297539,1.000,0.0,2.8125,4.069705,1.666667,1.632993,0.2500,0.447214
3,hypergraphrag,16,16,14.074268,0.297760,0.142971,0.538288,0.219497,0.363903,0.142113,2.8125,4.069705,0.1250,0.341565,0.125,0.341565,0.842689,0.031800,0.867849,0.041684,0.854512,0.030109,0.325000,0.472582,0.31250,0.478714,0.806250,0.254214,0.86250,0.061914,0.324410,0.227343,1.000,0.0,2.8125,4.069705,2.666667,4.082483,0.2500,0.447214
4,llmbased,16,16,0.861491,0.566587,0.193849,0.188141,0.059147,0.267850,0.072131,2.8125,4.069705,0.0000,0.000000,0.000,0.000000,0.825663,0.030009,0.792304,0.033587,0.807957,0.020990,0.031250,0.125000,0.05000,0.200000,0.243750,0.175000,0.76875,0.087321,0.204821,0.246027,1.000,0.0,2.8125,4.069705,1.000000,0.000000,0.1250,0.341565

answer_winrate: 7 rows x 6 columns

             method  comparisons  wins  losses  ties   winrate
0              ours          618   504     113     1  0.816343
1       fullcontext          103    42      61     0  0.407767
2     hypergraphrag          103    38      65     0  0.368932
3  vectorsimilarity          103    10      92     1  0.101942
4             grasp          103    10      93     0  0.097087

pairwise_answer_winrate: 618 rows x 13 columns

,ground_truth_id,ground_truth_qtype,question,ground_truth_answer,method_a,method_b,answer_a,answer_b,winner,judge_rationale,winning_method,method_a_score,method_b_score
0,gt_0,"[""multi"", ""numeric""]","\nHow many ""experiment execution"" are there in...",The answer to the question is 15 unique execut...,fullcontext,ours,There are 13 experiment executions in the prov...,There are **15** experiment executions represe...,method_b,The answer provided by method_b is more unders...,ours,0.0,1.0
1,gt_1,"[""multi"", ""entity""]",\nIn what places do we utilize AI in this work...,\nThe ChatBS System utilizes AI for the follow...,fullcontext,ours,"```json { ""answer"": ""The workflow employs AI (...",AI is employed in several distinct stages of t...,method_b,The answer provided by method_b is more unders...,ours,0.0,1.0
2,gt_10,"[""multi"", ""entity""]",\nwhat are the input parameters of the functio...,\n The input parameters to sparql query fun...,fullcontext,ours,The SPARQL query builder function receives the...,The question asks for the *input parameters* o...,method_a,The answer from method_a is more understandabl...,fullcontext,1.0,0.0
3,gt_100,"[""multi"", ""numeric""]","\nwhat is the number of output for the ""Output...","\n The number of output for the ""Output por...",fullcontext,ours,The execution produces a single output on the ...,The execution “http://testwebsite/testProgram#...,method_b,Method B provides a more detailed and faithful...,ours,0.0,1.0
4,gt_101,"[""multi"", ""numeric""]","\nwhat is the number of output for the ""Output...","\n The number of output for the ""Output por...",fullcontext,ours,The execution **id_20260420105727_300** produc...,The execution “http://testwebsite/testProgram#...,method_b,The answer from method_b is more faithful to t...,ours,0.0,1.0

## Inspect Available Columns

Use this cell when choosing the placeholders below.

In [48]:
for name, df in summaries.items():
    print(f"\n{name}")
    for column in df.columns:
        print(f"  - {column}")

bool
  - run
  - evaluated_examples
  - matched_ground_truth
  - avg_prediction_time_taken
  - answer_token_precision_mean
  - answer_token_precision_std
  - answer_token_recall_mean
  - answer_token_recall_std
  - answer_token_f1_mean
  - answer_token_f1_std
  - gt_entity_total_mean
  - gt_entity_total_std
  - gt_entity_covered_mean
  - gt_entity_covered_std
  - gt_entity_coverage_mean
  - gt_entity_coverage_std
  - bertscore_precision_mean
  - bertscore_precision_std
  - bertscore_recall_mean
  - bertscore_recall_std
  - bertscore_f1_mean
  - bertscore_f1_std
  - llm_completeness_mean
  - llm_completeness_std
  - llm_faithfulness_mean
  - llm_faithfulness_std
  - llm_relevance_mean
  - llm_relevance_std
  - llm_understanderbility_mean
  - llm_understanderbility_std
  - nli_entailment_max_mean
  - nli_entailment_max_std
  - nli_pairs_scored_mean
  - nli_pairs_scored_std
  - bool_accuracy_mean
  - bool_accuracy_std

entity
  - run
  - evaluated_examples
  - matched_ground_truth
  - avg_prediction_time_taken
  - answer_token_precision_mean
  - answer_token_precision_std
  - answer_token_recall_mean
  - answer_token_recall_std
  - answer_token_f1_mean
  - answer_token_f1_std
  - gt_entity_total_mean
  - gt_entity_total_std
  - gt_entity_covered_mean
  - gt_entity_covered_std
  - gt_entity_coverage_mean
  - gt_entity_coverage_std
  - bertscore_precision_mean
  - bertscore_precision_std
  - bertscore_recall_mean
  - bertscore_recall_std
  - bertscore_f1_mean
  - bertscore_f1_std
  - llm_completeness_mean
  - llm_completeness_std
  - llm_faithfulness_mean
  - llm_faithfulness_std
  - llm_relevance_mean
  - llm_relevance_std
  - llm_understanderbility_mean
  - llm_understanderbility_std
  - nli_entailment_max_mean
  - nli_entailment_max_std
  - nli_pairs_scored_mean
  - nli_pairs_scored_std
  - entity_gt_total_mean
  - entity_gt_total_std
  - entity_retrieved_final_total_mean
  - entity_retrieved_final_total_std
  - entity_retrieved_total_total_mean
  - entity_retrieved_total_total_std
  - entity_recall_final_mean
  - entity_recall_final_std
  - entity_precision_final_mean
  - entity_precision_final_std
  - entity_f1_final_mean
  - entity_f1_final_std
  - entity_recall_total_mean
  - entity_recall_total_std
  - entity_precision_total_mean
  - entity_precision_total_std
  - entity_f1_total_mean
  - entity_f1_total_std

numeric
  - run
  - evaluated_examples
  - matched_ground_truth
  - avg_prediction_time_taken
  - answer_token_precision_mean
  - answer_token_precision_std
  - answer_token_recall_mean
  - answer_token_recall_std
  - answer_token_f1_mean
  - answer_token_f1_std
  - gt_entity_total_mean
  - gt_entity_total_std
  - gt_entity_covered_mean
  - gt_entity_covered_std
  - gt_entity_coverage_mean
  - gt_entity_coverage_std
  - bertscore_precision_mean
  - bertscore_precision_std
  - bertscore_recall_mean
  - bertscore_recall_std
  - bertscore_f1_mean
  - bertscore_f1_std
  - llm_completeness_mean
  - llm_completeness_std
  - llm_faithfulness_mean
  - llm_faithfulness_std
  - llm_relevance_mean
  - llm_relevance_std
  - llm_understanderbility_mean
  - llm_understanderbility_std
  - nli_entailment_max_mean
  - nli_entailment_max_std
  - nli_pairs_scored_mean
  - nli_pairs_scored_std
  - numeric_ground_truth_count_mean
  - numeric_ground_truth_count_std
  - numeric_predicted_count_mean
  - numeric_predicted_count_std
  - numeric_accuracy_mean
  - numeric_accuracy_std

answer_winrate
  - method
  - comparisons
  - wins
  - losses
  - ties
  - winrate

pairwise_answer_winrate
  - ground_truth_id
  - ground_truth_qtype
  - question
  - ground_truth_answer
  - method_a
  - method_b
  - answer_a
  - answer_b
  - winner
  - judge_rationale
  - winning_method
  - method_a_score
  - method_b_score

## Editable Paper Table Columns

Edit these lists to decide what goes into each paper table. Keep `run` or `method` first if you want method names visible.

In [63]:
# Main placeholders: edit these columns for the paper.
bool_columns = [
    "run",
    "evaluated_examples",
    #"answer_token_f1_mean",
    "bertscore_f1_mean",
    "bertscore_f1_std",
    "nli_entailment_max_mean",
    "nli_entailment_max_std",
    "bool_accuracy_mean",
    # "llm_completeness_mean",
    # "llm_completeness_std",
    # "llm_faithfulness_mean",
    # "llm_faithfulness_std",
    # "llm_relevance_mean",
    # "llm_relevance_std",
    # "llm_understanderbility_mean",
    # "llm_understanderbility_std",
]

entity_columns = [
    "run",
    "evaluated_examples",
    "answer_token_f1_mean",
    "entity_recall_final_mean",
    "entity_precision_final_mean",
    "entity_f1_final_mean",
    "bertscore_f1_mean",
    "nli_entailment_max_mean",
    
    "entity_recall_final_mean",
    "entity_recall_final_std",
    "entity_precision_final_mean",
    "entity_precision_final_std",
    "entity_f1_final_mean",
    "entity_f1_final_std",
    "entity_recall_total_mean",
    "entity_recall_total_std",
    "entity_precision_total_mean",
    "entity_precision_total_std",
    "entity_f1_total_mean",
    "entity_f1_total_std",
]

numeric_columns = [
    "run",
    "evaluated_examples",
    "answer_token_f1_mean",
    "numeric_accuracy_mean",
    "bertscore_f1_mean",
    "nli_entailment_max_mean",
]

answer_winrate_columns = [
    "method",
    "comparisons",
    "wins",
    "losses",
    "ties",
    "winrate",
]

In [67]:
# Optional display names. Add, remove, or rename as needed for the paper.
column_labels = {
    "run": "Method",
    "method": "Method",
    "evaluated_examples": "N",
    "comparisons": "Comparisons",
    "wins": "Wins",
    "losses": "Losses",
    "ties": "Ties",
    "answer_token_f1_mean": "Answer Token F1",
    "bertscore_f1_mean": "BERTScore F1",
    "nli_entailment_max_mean": "NLI Entailment",
    "bool_accuracy_mean": "Bool Accuracy",
    "entity_recall_final_mean": "Entity Recall",
    "entity_precision_final_mean": "Entity Precision",
    "entity_f1_final_mean": "Entity F1",
    "numeric_accuracy_mean": "Numeric Accuracy",
    "winrate": "Win Rate",
}

method_order = ["GWB", "VSB", "GRASP", "HippoRAG", "HyperGRAG", "Ours"]

method_labels = {
    "fullcontext": "FCB",
    "grasp": "GRASP",
    "hipporag": "HippoRAG",
    "hypergraphrag": "HyperGRAG",
    "llmbased": "GWB",
    "LWE": "Ours",
    "ours": "Ours",
    "vectorsimilarity": "VSB",
}

def order_method_rows(table, method_column="Method"):
    ordered = table[table[method_column].isin(method_order)].copy()
    ordered[method_column] = pd.Categorical(
        ordered[method_column],
        categories=method_order,
        ordered=True,
    )
    sort_columns = [method_column]
    if "Question Type" in ordered.columns:
        sort_columns = ["Question Type", method_column]
    return ordered.sort_values(sort_columns).reset_index(drop=True)

## Build Individual Tables

In [68]:
round_digits = 3

bool_table = summaries["bool"][bool_columns].copy()
bool_table["run"] = bool_table["run"].replace(method_labels)
bool_table = bool_table.rename(columns=column_labels).round(round_digits)
bool_table = order_method_rows(bool_table)

entity_table = summaries["entity"][entity_columns].copy()
entity_table["run"] = entity_table["run"].replace(method_labels)
entity_table = entity_table.rename(columns=column_labels).round(round_digits)
entity_table = order_method_rows(entity_table)

numeric_table = summaries["numeric"][numeric_columns].copy()
numeric_table["run"] = numeric_table["run"].replace(method_labels)
numeric_table = numeric_table.rename(columns=column_labels).round(round_digits)
numeric_table = order_method_rows(numeric_table)

answer_winrate_table = summaries["answer_winrate"][answer_winrate_columns].copy()
answer_winrate_table["method"] = answer_winrate_table["method"].replace(method_labels)
answer_winrate_table = answer_winrate_table.rename(columns=column_labels).round(round_digits)
answer_winrate_table = order_method_rows(answer_winrate_table)

In [69]:
display(bool_table)
display(entity_table)
display(numeric_table)
display(answer_winrate_table)

      Method   N  BERTScore F1  bertscore_f1_std  NLI Entailment  nli_entailment_max_std  Bool Accuracy
0        GWB  38         0.779             0.014           0.278                   0.328          0.000
1        VSB  38         0.791             0.024           0.476                   0.342          0.342
2      GRASP  38         0.800             0.041           0.493                   0.343          0.289
3   HippoRAG  38         0.735             0.010           0.261                   0.249          0.526
4  HyperGRAG  38         0.819             0.039           0.504                   0.328          0.421
5       Ours  38         0.815             0.016           0.362                   0.233          0.632

,Method,N,Answer Token F1,Entity Recall,Entity Precision,Entity F1,BERTScore F1,NLI Entailment,Entity Recall,entity_recall_final_std,Entity Precision,entity_precision_final_std,Entity F1,entity_f1_final_std,entity_recall_total_mean,entity_recall_total_std,entity_precision_total_mean,entity_precision_total_std,entity_f1_total_mean,entity_f1_total_std
0,GWB,49,0.144,0.299,0.045,0.164,0.781,0.146,0.299,0.373,0.045,0.060,0.164,0.077,0.568,0.410,0.086,0.070,0.197,0.090
1,VSB,49,0.195,0.106,0.019,0.158,0.788,0.233,0.106,0.228,0.019,0.043,0.158,0.023,0.189,0.309,0.025,0.048,0.134,0.069
2,GRASP,49,0.097,0.027,0.175,0.583,0.805,0.260,0.027,0.126,0.175,0.362,0.583,0.118,0.027,0.126,0.175,0.362,0.583,0.118
3,HippoRAG,49,0.116,0.345,0.009,0.044,0.749,0.202,0.345,0.440,0.009,0.015,0.044,0.027,0.648,0.456,0.013,0.019,0.042,0.036
4,HyperGRAG,49,0.163,0.000,NaN,NaN,0.805,0.287,0.000,0.000,NaN,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,NaN
5,Ours,49,0.138,0.384,0.017,0.041,0.796,0.336,0.384,0.486,0.017,0.037,0.041,0.070,0.494,0.493,0.014,0.030,0.052,0.066

      Method   N  Answer Token F1  Numeric Accuracy  BERTScore F1  NLI Entailment
0        GWB  16            0.268             0.125         0.808           0.205
1        VSB  16            0.247             0.062         0.795           0.439
2      GRASP  16            0.055             0.125         0.805           0.465
3   HippoRAG  16            0.064             0.250         0.742           0.316
4  HyperGRAG  16            0.364             0.250         0.855           0.324
5       Ours  16            0.188             0.500         0.837           0.426

      Method  Comparisons  Wins  Losses  Ties  Win Rate
0        GWB          103     8      95     0     0.078
1        VSB          103    10      92     1     0.102
2      GRASP          103    10      93     0     0.097
3   HippoRAG          103     5      98     0     0.049
4  HyperGRAG          103    38      65     0     0.369
5       Ours          618   504     113     1     0.816

## Combined Table Placeholder

This creates one compact table across question types. Edit `combined_columns` to choose the shared metrics.

In [70]:
combined_columns = [
    "task",
    "run",
    "evaluated_examples",
    "answer_token_f1_mean",
    "bertscore_f1_mean",
    "nli_entailment_max_mean",
]

combined_parts = []
for task_name in ["bool", "entity", "numeric"]:
    part = summaries[task_name].copy()
    part.insert(0, "task", task_name)
    combined_parts.append(part)

combined_table = pd.concat(combined_parts, ignore_index=True)
combined_table = combined_table[combined_columns].copy()
combined_table["run"] = combined_table["run"].replace(method_labels)
combined_table = combined_table.rename(columns={**column_labels, "task": "Question Type"}).round(round_digits)
combined_table = order_method_rows(combined_table)

display(combined_table)

   Question Type     Method   N  Answer Token F1  BERTScore F1  NLI Entailment
0           bool        GWB  38            0.205         0.779           0.278
1           bool        VSB  38            0.284         0.791           0.476
2           bool      GRASP  38            0.085         0.800           0.493
3           bool   HippoRAG  38            0.000         0.735           0.261
4           bool  HyperGRAG  38            0.259         0.819           0.504
5           bool       Ours  38            0.105         0.815           0.362
6         entity        GWB  49            0.144         0.781           0.146
7         entity        VSB  49            0.195         0.788           0.233
8         entity      GRASP  49            0.097         0.805           0.260
9         entity   HippoRAG  49            0.116         0.749           0.202
10        entity  HyperGRAG  49            0.163         0.805           0.287
11        entity       Ours  49            0.138         0.796           0.336
12       numeric        GWB  16            0.268         0.808           0.205
13       numeric        VSB  16            0.247         0.795           0.439
14       numeric      GRASP  16            0.055         0.805           0.465
15       numeric   HippoRAG  16            0.064         0.742           0.316
16       numeric  HyperGRAG  16            0.364         0.855           0.324
17       numeric       Ours  16            0.188         0.837           0.426

## Overall Summary Table

This combines bool, entity, and numeric summaries into one method-level table using only columns common to all three categories. Metric means are weighted by the number of evaluated examples in each category.

In [71]:
category_names = ["bool", "entity", "numeric"]
common_summary_columns = set.intersection(
    *(set(summaries[category].columns) for category in category_names)
)

overall_summary_columns = [
    "run",
    "evaluated_examples",
    "answer_token_f1_mean",
    "bertscore_f1_mean",
    "bertscore_f1_std",
    "nli_entailment_max_mean",
    "nli_entailment_max_std",
    "llm_completeness_mean",
    "llm_completeness_std",
    "llm_faithfulness_mean",
    "llm_faithfulness_std",
    "llm_relevance_mean",
    "llm_relevance_std",
    "llm_understanderbility_mean",
    "llm_understanderbility_std",
]
overall_summary_columns = [
    column for column in overall_summary_columns
    if column in common_summary_columns
]

overall_summary_source = pd.concat(
    [
        summaries[category][overall_summary_columns].assign(task=category)
        for category in category_names
    ],
    ignore_index=True,
)

overall_metric_columns = [
    column for column in overall_summary_columns
    if column not in {"run", "evaluated_examples"}
]

overall_rows = []
for run_name, run_group in overall_summary_source.groupby("run", dropna=False):
    weights = pd.to_numeric(
        run_group["evaluated_examples"],
        errors="coerce",
    ).fillna(0)
    row = {
        "run": run_name,
        "evaluated_examples": weights.sum(),
    }

    for column in overall_metric_columns:
        values = pd.to_numeric(run_group[column], errors="coerce")
        valid = values.notna() & weights.gt(0)
        if valid.any():
            row[column] = (values[valid] * weights[valid]).sum() / weights[valid].sum()
        else:
            row[column] = values.mean()

    overall_rows.append(row)

overall_summary_table = pd.DataFrame(overall_rows)
overall_summary_table["run"] = overall_summary_table["run"].replace(method_labels)
overall_summary_table = overall_summary_table.rename(columns=column_labels).round(round_digits)
overall_summary_table = order_method_rows(overall_summary_table)

display(overall_summary_table)

,Method,N,Answer Token F1,BERTScore F1,bertscore_f1_std,NLI Entailment,nli_entailment_max_std,llm_completeness_mean,llm_completeness_std,llm_faithfulness_mean,llm_faithfulness_std,llm_relevance_mean,llm_relevance_std,llm_understanderbility_mean,llm_understanderbility_std
0,GWB,103,0.186,0.784,0.016,0.204,0.239,0.149,0.210,0.099,0.186,0.349,0.287,0.702,0.141
1,VSB,103,0.236,0.790,0.020,0.354,0.281,0.220,0.323,0.272,0.400,0.619,0.334,0.840,0.130
2,GRASP,103,0.086,0.803,0.034,0.378,0.299,0.502,0.409,0.512,0.434,0.697,0.333,0.717,0.199
3,HippoRAG,103,0.065,0.743,0.012,0.241,0.242,0.277,0.358,0.280,0.393,0.625,0.281,0.833,0.116
4,HyperGRAG,103,0.229,0.818,0.029,0.373,0.262,0.340,0.398,0.363,0.433,0.644,0.391,0.809,0.133
5,Ours,103,0.134,0.809,0.021,0.360,0.186,0.645,0.321,0.702,0.341,0.895,0.149,0.676,0.111

## Export Tables

Exports CSV and LaTeX versions into `paper_tables/`. Comment out any table you do not need.

In [55]:
tables = {
    "bool_summary": bool_table,
    "entity_summary": entity_table,
    "numeric_summary": numeric_table,
    "answer_winrate_summary": answer_winrate_table,
    "combined_summary": combined_table,
    "overall_summary": overall_summary_table,
}

for table_name, table in tables.items():
    csv_path = TABLE_OUTPUT_DIR / f"{table_name}.csv"
    tex_path = TABLE_OUTPUT_DIR / f"{table_name}.tex"

    table.to_csv(csv_path, index=False)
    table.to_latex(tex_path, index=False, escape=False)

    print(f"Wrote {csv_path}")
    print(f"Wrote {tex_path}")

Wrote /home/desild/work/research/LLM-Workflow-Explorer/evaluations/chatbs-base/paper_tables/bool_summary.csv
Wrote /home/desild/work/research/LLM-Workflow-Explorer/evaluations/chatbs-base/paper_tables/bool_summary.tex
Wrote /home/desild/work/research/LLM-Workflow-Explorer/evaluations/chatbs-base/paper_tables/entity_summary.csv
Wrote /home/desild/work/research/LLM-Workflow-Explorer/evaluations/chatbs-base/paper_tables/entity_summary.tex
Wrote /home/desild/work/research/LLM-Workflow-Explorer/evaluations/chatbs-base/paper_tables/numeric_summary.csv
Wrote /home/desild/work/research/LLM-Workflow-Explorer/evaluations/chatbs-base/paper_tables/numeric_summary.tex
Wrote /home/desild/work/research/LLM-Workflow-Explorer/evaluations/chatbs-base/paper_tables/answer_winrate_summary.csv
Wrote /home/desild/work/research/LLM-Workflow-Explorer/evaluations/chatbs-base/paper_tables/answer_winrate_summary.tex
Wrote /home/desild/work/research/LLM-Workflow-Explorer/evaluations/chatbs-base/paper_tables/combined_summary.csv
Wrote /home/desild/work/research/LLM-Workflow-Explorer/evaluations/chatbs-base/paper_tables/combined_summary.tex
Wrote /home/desild/work/research/LLM-Workflow-Explorer/evaluations/chatbs-base/paper_tables/overall_summary.csv
Wrote /home/desild/work/research/LLM-Workflow-Explorer/evaluations/chatbs-base/paper_tables/overall_summary.tex

## Optional: Pairwise Win Rate Details

In [56]:
if "pairwise_answer_winrate" in summaries:
    pairwise_table = summaries["pairwise_answer_winrate"].copy()
    for column in pairwise_table.columns:
        if pairwise_table[column].dtype == "object":
            pairwise_table[column] = pairwise_table[column].replace(method_labels)
    display(pairwise_table.round(round_digits))

,ground_truth_id,ground_truth_qtype,question,ground_truth_answer,method_a,method_b,answer_a,answer_b,winner,judge_rationale,winning_method,method_a_score,method_b_score
0,gt_0,"[""multi"", ""numeric""]","\nHow many ""experiment execution"" are there in...",The answer to the question is 15 unique execut...,fullcontext,ours,There are 13 experiment executions in the prov...,There are **15** experiment executions represe...,method_b,The answer provided by method_b is more unders...,ours,0.0,1.0
1,gt_1,"[""multi"", ""entity""]",\nIn what places do we utilize AI in this work...,\nThe ChatBS System utilizes AI for the follow...,fullcontext,ours,"```json { ""answer"": ""The workflow employs AI (...",AI is employed in several distinct stages of t...,method_b,The answer provided by method_b is more unders...,ours,0.0,1.0
2,gt_10,"[""multi"", ""entity""]",\nwhat are the input parameters of the functio...,\n The input parameters to sparql query fun...,fullcontext,ours,The SPARQL query builder function receives the...,The question asks for the *input parameters* o...,method_a,The answer from method_a is more understandabl...,fullcontext,1.0,0.0
3,gt_100,"[""multi"", ""numeric""]","\nwhat is the number of output for the ""Output...","\n The number of output for the ""Output por...",fullcontext,ours,The execution produces a single output on the ...,The execution “http://testwebsite/testProgram#...,method_b,Method B provides a more detailed and faithful...,ours,0.0,1.0
4,gt_101,"[""multi"", ""numeric""]","\nwhat is the number of output for the ""Output...","\n The number of output for the ""Output por...",fullcontext,ours,The execution **id_20260420105727_300** produc...,The execution “http://testwebsite/testProgram#...,method_b,The answer from method_b is more faithful to t...,ours,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
613,gt_95,"[""multi"", ""numeric""]","\nwhat is the number of output for the ""Output...","\n The number of output for the ""Output por...",grasp,ours,NaN,The execution `http://testwebsite/testProgram#...,method_b,The answer from method_b is more understandabl...,ours,0.0,1.0
614,gt_96,"[""multi"", ""numeric""]","\nwhat is the number of output for the ""Output...","\n The number of output for the ""Output por...",grasp,ours,<|channel|>final <|constrain|>answer<|message|...,The execution identified by `http://testwebsit...,method_b,The answer provided by method_b is more unders...,ours,0.0,1.0
615,gt_97,"[""multi"", ""numeric""]","\nwhat is the number of output for the ""Output...","\n The number of output for the ""Output por...",grasp,ours,NaN,The execution identified by `http://testwebsit...,method_b,The answer provided by method_b is more unders...,ours,0.0,1.0
616,gt_98,"[""multi"", ""numeric""]","\nwhat is the number of output for the ""Output...","\n The number of output for the ""Output por...",grasp,ours,NaN,The execution `http://testwebsite/testProgram#...,method_b,"Although method_b's answer (""one"") does not ma...",ours,0.0,1.0
617,gt_99,"[""multi"", ""numeric""]","\nwhat is the number of output for the ""Output...","\n The number of output for the ""Output por...",grasp,ours,NaN,The execution identified by `http://testwebsit...,method_b,The answer from method_b is more understandabl...,ours,0.0,1.0