In [38]:
import sys
import logging
from pathlib import Path
from typing import List, Mapping, Sequence, Union, Dict
import pandas as pd
import os

import pandas as pd
import dycomutils as common_utils

repo_root = Path.cwd().resolve()
while repo_root != repo_root.parent and not (repo_root / "src").exists():
    repo_root = repo_root.parent

os.chdir(repo_root)
print(repo_root)
sys.path.append(str(repo_root))

from src.utils.graph_manager import GraphManager
from src.utils.utils import load_config, format_dataframe_to_string, regex_add_strings
from src.config.experiment import ExperimentConfig
from src.experiment.ground_truth import GT, SPARQLTemplate, GTAnswer
from src.experiment.test_questions_templates import build_gt_from_template

CONFIG_PATH = "evaluations/biomni-base/config.yaml"
logging.info(f"Loading config: {CONFIG_PATH}")
lconfig = load_config(CONFIG_PATH)
config = ExperimentConfig.model_validate(lconfig)
config

/home/desild/work/research/LLM-Workflow-Explorer

ExperimentConfig(application=ApplicationInfo(description='The Biomni application is an LLM-driven biomedical agent that plans, reasons,\nexecutes generated code, and optionally critiques intermediate answers to solve\nuser-provided biomedical tasks. The provenance captures the user input, system\nprompt generation, each agent generation iteration, code execution, execution\nobservations, final solution, and optional critic feedback as intermediary\nstates of the agent run.\nAgent stages are represented as provone:Executions of provone:Programs,\nincluding user input recording, system prompt generation, LLM response\ngeneration, generated code execution, and critic review. LLM usage within the\nagent is represented as workflow:Generative_Task activity using\nworkflow:Large_Language_Models. Generated responses, executable code,\nobservations, critic feedback, and final solutions are connected across the\nworkflow using provone:Channel and prov:wasInformedBy relations.\ndcterms:identifier represents the unique identifier for each recorded agent\nstage or experiment step.\n'), file_paths=InputFiles(schema_loc='schema/schemaV2.json', execution_kg_loc='usecases/biomni/data/task3/biomni_sample.ttl', metadata_loc='usecases/biomni/data/task3/biomni_sample_metadata.json', ontology_path='schema/WorkFlow.ttl'), explorer_config=ExplorerConfig(kg_name='Biomni-Task3', ontology_triples_path='schema/extracted_ontology_triples.csv', parallel=True, temp_folder='evaluations/biomni-base/exeprog_creation/tmp/programs', use_cache=False, explorer_metadata_loc='evaluations/biomni-base/exeprog_creation/exeplorer_metadata.pkl', exeprog_save_loc='evaluations/biomni-base/exeprog_creation/exeplored_programs.pkl', entity_length=5, log_file='evaluations/biomni-base/exeprog_creation/explorer_log.txt'), question_creation_config=QuestionCreationConfig(save_questions='evaluations/biomni-base/ques_creation/SyntheticQuestionKG.csv', llm_type='lmstudio', llm_config={'model': 'openai/gpt-oss-20b', 'base_url': 'http://localhost:1234/v1'}, log_file='evaluations/biomni-base/ques_creation/question_creation_log.txt'), explainer_config=ExplainerConfig(llm_type='lmstudio', embedding_type='lmstudio', vectordb_type='milvus', save_answer_loc='evaluations/biomni-base/explainer/results', llm_config={'model': 'openai/gpt-oss-20b', 'base_url': 'http://localhost:1234/v1'}, embedding_config={'model': 'text-embedding-bge-large-en-v1.5'}, vectordb_config={'vector_dim': 1024, 'collection_name': 'biomni'}, object_search_config={'search_limit': 3}, log_file='evaluations/biomni-base/explainer/explainer_log.txt'), ttl=TTLConfig(prefixes=[{'name': 'provone', 'uri': 'http://purl.dataone.org/provone/2015/01/15/ontology#'}, {'name': 'skos', 'uri': 'http://www.w3.org/2004/02/skos/core#'}, {'name': 'prov', 'uri': 'http://www.w3.org/ns/prov#'}, {'name': 'rdfs', 'uri': 'http://www.w3.org/2000/01/rdf-schema#'}, {'name': 'rdf', 'uri': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'}, {'name': 'cwfo', 'uri': 'http://cwf.tw.rpi.edu/vocab#'}, {'name': 'dcterms', 'uri': 'http://purl.org/dc/terms#'}, {'name': 'Biomni', 'uri': 'http://testwebsite/testProgram#'}, {'name': 'user', 'uri': 'http://testwebsite/testUser#'}, {'name': 'eo', 'uri': 'https://purl.org/heals/eo#'}, {'name': 'ep', 'uri': 'http://linkedu.eu/dedalo/explanationPattern.owl#'}, {'name': 'sio', 'uri': 'http://semanticscience.org/resource/'}, {'name': 'dc', 'uri': 'http://purl.org/dc/elements/1.1/'}, {'name': 'DFColumn', 'uri': 'http://testwebsite/testDFColumn#'}, {'name': 'fnom', 'uri': 'https://w3id.org/function/vocabulary/mapping#'}, {'name': 'fnoi', 'uri': 'https://w3id.org/function/vocabulary/implementation#'}, {'name': 'fnoc', 'uri': 'https://w3id.org/function/vocabulary/composition/0.1.0/'}, {'name': 'food', 'uri': 'http://purl.org/heals/food/'}, {'name': 'dbo', 'uri': 'http://dbpedia.org/ontology/'}, {'name': 'dbp', 'uri': 'http://dbpedia.org/property/'}, {'name': 'dbt', 'uri': 'http://dbpedia.org/resource/Template:'}, {'name': 'ques', 'uri': 'http://atomic_questions.org/'}, {'name': 'xsd', 'uri': 'http://www.w3.org/2001/XMLSchema#'}, {'name': 'fno', 'uri': 'https://w3id.org/function/vocabulary/core#'}, {'name': 'workflow', 'uri': 'http://www.semanticweb.org/acer/ontologies/2026/1/WorkFlow/'}]), gt=GTConfig(log_file='evaluations/biomni-base/ground_truth/ground_truth_log.txt', save_loc='evaluations/biomni-base/ground_truth/ground_truth_data.jsonl'))

In [39]:
graph_manager = GraphManager(
    config.ttl,
    config.file_paths.execution_kg_loc,
)

gt_list: List[GT] = []

In [40]:
# Question 1
question1 = """
How many "experiment execution" are there in this?
"""
question_sparql1 = """
SELECT distinct ?obj
WHERE {
     ?obj a provone:Execution .
     ?obj rdfs:label ?lbl .
}
"""


entities1 = graph_manager.query(question_sparql1)
entities1

                                                  obj
0   http://testwebsite/testProgram#id_202605050009...
1   http://testwebsite/testProgram#id_202605050009...
2   http://testwebsite/testProgram#id_202605050009...
3   http://testwebsite/testProgram#id_202605050010...
4   http://testwebsite/testProgram#id_202605050010...
5   http://testwebsite/testProgram#id_202605050010...
6   http://testwebsite/testProgram#id_202605050010...
7   http://testwebsite/testProgram#id_202605050010...
8   http://testwebsite/testProgram#id_202605050010...
9   http://testwebsite/testProgram#id_202605050010...
10  http://testwebsite/testProgram#id_202605050010...
11  http://testwebsite/testProgram#id_202605050010...

In [41]:
answer1 = f"The answer to the question is {len(entities1)} unique executions."

gt_list.append(
    GT(
        question=question1,
        answer=answer1,
        count=len(entities1),
        sparql=[
            SPARQLTemplate(
                template=question_sparql1,
                description="This SPARQL query counts the number of unique executions by counting distinct identifiers in the provone:Execution class.",
            )
        ],
        #qtype=["multi", "numeric", "ISP"],
        qtype=["multi", "numeric"],
        entities=entities1.to_dict(orient="records"),
    )
)

In [42]:
# Question 3
question3 = """
In what places do we utilize AI in this workflow?
"""
question_sparql3 = """
SELECT distinct ?obj ?desc
WHERE {
     ?obj a workflow:Generative_Task .
     ?obj dc:description ?desc .
}
"""

entities3 = graph_manager.query(question_sparql3, resolve_curie=True)
entities3

,obj,desc
0,Biomni:Generative_Task-id_20260505001006_475,Step 4: Records how the agent used an LLM duri...
1,Biomni:Generative_Task-id_20260505001006_475,Step 4: Records how the agent used an LLM duri...
2,Biomni:Generative_Task-id_20260505001009_972,Step 5: Records how the agent used an LLM duri...
3,Biomni:Generative_Task-id_20260505001009_972,Step 5: Records how the agent used an LLM duri...
4,Biomni:Generative_Task-id_20260505001016_956,Step 8: Records how the agent used an LLM duri...
5,Biomni:Generative_Task-id_20260505001016_956,Step 8: Records how the agent used an LLM duri...
6,Biomni:Generative_Task-id_20260505001023_688,Step 9: Records how the agent used an LLM duri...
7,Biomni:Generative_Task-id_20260505001023_688,Step 9: Records how the agent used an LLM duri...
8,Biomni:Generative_Task-id_20260505001035_720,Step 10: Records how the agent used an LLM dur...
9,Biomni:Generative_Task-id_20260505001035_720,Step 10: Records the LLM use that produced sel...
10,Biomni:Generative_Task-id_20260505001037_336,Step 11: Records how the agent used an LLM dur...
11,Biomni:Generative_Task-id_20260505001037_336,Step 11: Records how the agent used an LLM dur...
12,Biomni:Generative_Task-id_20260505001042_313,Step 12: Records how the agent used an LLM dur...
13,Biomni:Generative_Task-id_20260505001042_313,Step 12: Records how the agent used an LLM dur...
14,Biomni:Generative_Task-id_20260505001011_890,Step 6: Records how the agent used an LLM duri...
15,Biomni:Generative_Task-id_20260505001011_890,Step 6: Records how the agent used an LLM duri...

In [43]:
answer3 = """
The ChatBS System utilizes AI for the following

{}
""".format("\n\n".join([f"{n+1} => {v}" for n,v in enumerate(entities3['desc'].to_list())]))

print(answer3)

gt_list.append(
    GT(
        question=question3,
        answer=answer3,
        sparql=[SPARQLTemplate(template=question_sparql3, description="")],
        entities=entities3.to_dict(orient="records"),
        #qtype=["multi", "entity", "SI"],
        qtype=["multi", "entity"],
    )
)

The ChatBS System utilizes AI for the following

1 => Step 4: Records how the agent used an LLM during the generation iteration 1 step.

2 => Step 4: Records how the agent used an LLM during this generation iteration.

3 => Step 5: Records how the agent used an LLM during the generation iteration 2 step.

4 => Step 5: Records how the agent used an LLM during this generation iteration.

5 => Step 8: Records how the agent used an LLM during the generation iteration 4 step.

6 => Step 8: Records how the agent used an LLM during this generation iteration.

7 => Step 9: Records how the agent used an LLM during the generation iteration 5 step.

8 => Step 9: Records how the agent used an LLM during this generation iteration.

9 => Step 10: Records how the agent used an LLM during the critic review 1 step.

10 => Step 10: Records the LLM use that produced self-critic feedback for the agent.

11 => Step 11: Records how the agent used an LLM during the generation iteration 6 step.

12 => Step 11: Records how the agent used an LLM during this generation iteration.

13 => Step 12: Records how the agent used an LLM during the generation iteration 7 step.

14 => Step 12: Records how the agent used an LLM during this generation iteration.

15 => Step 6: Records how the agent used an LLM during the generation iteration 3 step.

16 => Step 6: Records how the agent used an LLM during this generation iteration.

In [44]:
question_sparql1 = """
SELECT distinct ?obj ?lbl
WHERE {
     ?obj a provone:Program .
     ?obj rdfs:label ?lbl .
}
"""


programs = graph_manager.query(question_sparql1).to_dict(orient="records")
template_spec = [{"func_desc":x["lbl"] , "func_desc_term":x["lbl"]} for x in programs]
template_spec;

In [45]:
# Question MULT 2: input ports of the functions


template_spec = template_spec[:5] if len(template_spec) > 5 else template_spec
sparql_spec = template_spec[:5] if len(template_spec) > 5 else template_spec

question_template = """
what are the input parameters of the function used in "{func_desc}" step in the pipeline?
"""
sparql_template = """
SELECT distinct ?flbl ?lbl
WHERE {
     ?obj dc:description ?desc .
     ?obj rdfs:label ?flbl . 
     ?obj a ?class .
     FILTER(REGEX(?flbl, "{func_desc_term}","i"))

     ?obj provone:hasInPort ?port .
     ?port rdfs:label ?lbl .
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The input parameters to {func_desc} function.

    {answer_inst}
    """
    
    _ent = entities[['flbl', 'lbl']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "flbl": "Funtion name",
            "lbl": "Function returns"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )


for gt in gts:
    #gt.qtype = ["multi", "literal", "SI"]
    gt.qtype = ["multi", "entity"]
gt_list.extend(gts)

ic| rquestion: '''
                what are the input parameters of the function used in "Step 10 - Biomni critic review 1" step in the pipeline?
                '''
ic| entities:                                flbl  \
              0  Step 10 - Biomni critic review 1
              1  Step 10 - Biomni critic review 1
              2  Step 10 - Biomni critic review 1
              3  Step 10 - Biomni critic review 1
              4  Step 10 - Biomni critic review 1
              5  Step 10 - Biomni critic review 1
              6  Step 10 - Biomni critic review 1
              7  Step 10 - Biomni critic review 1

                                                               lbl
              0                 Step 10 - candidate solution input
              1  Step 10 - candidate_solution input port for cr...
              2                      Step 10 - critic prompt input
              3  Step 10 - feedback_prompt input port for criti...
              4               Step 10 - conversation history input
              5  Step 10 - message_history input port for criti...
              6                 Step 10 - original user task input
              7  Step 10 - user_task input port for critic revi...
ic| answer: GTAnswer(answer_nlp='
                The input parameters to Step 10 - Biomni critic review 1 function.

                Funtion name | Function returns
            Step 10 - Biomni critic review 1 | Step 10 - candidate solution input
            Step 10 - Biomni critic review 1 | Step 10 - candidate_solution input port for critic review 1
            Step 10 - Biomni critic review 1 | Step 10 - critic prompt input
            Step 10 - Biomni critic review 1 | Step 10 - feedback_prompt input port for critic review 1
            Step 10 - Biomni critic review 1 | Step 10 - conversation history input
            Step 10 - Biomni critic review 1 | Step 10 - message_history input port for critic review 1
            Step 10 - Biomni critic review 1 | Step 10 - original user task input
            Step 10 - Biomni critic review 1 | Step 10 - user_task input port for critic review 1
                ', entities=[{'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - candidate solution input'}, {'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - candidate_solution input port for critic review 1'}, {'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - critic prompt input'}, {'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - feedback_prompt input port for critic review 1'}, {'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - conversation history input'}, {'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - message_history input port for critic review 1'}, {'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - original user task input'}, {'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - user_task input port for critic review 1'}])
ic| rquestion: '''
                what are the input parameters of the function used in "Step 4 - Biomni LLM generation iteration 1" step in the pipeline?
                '''
ic| entities:                                          flbl  \
              0  Step 4 - Biomni LLM generation iteration 1
              1  Step 4 - Biomni LLM generation iteration 1
              2  Step 4 - Biomni LLM generation iteration 1
              3  Step 4 - Biomni LLM generation iteration 1

                                                               lbl
              0                 Step 4 - agent state message input
              1  Step 4 - message input port for generation ite...
              2                       Step 4 - system prompt input
              3  Step 4 - system_prompt input port for generati...
ic| answer: GTAnswer(answer_nlp='
                The input parameters to Step 4 - Biomni LLM generation iteration 1 function.

                Funtion name | Function returns
            Step 4 - Biomni LLM generation iteration 1 | Step 4 - agent state message input
            Step 4 - Biomni LLM generation iteration 1 | Step 4 - message input port for generation iteration 1
            Step 4 - Biomni LLM generation iteration 1 | Step 4 - system prompt input
            Step 4 - Biomni LLM generation iteration 1 | Step 4 - system_prompt input port for generation iteration 1
                ', entities=[{'flbl': 'Step 4 - Biomni LLM generation iteration 1', 'lbl': 'Step 4 - agent state message input'}, {'flbl': 'Step 4 - Biomni LLM generation iteration 1', 'lbl': 'Step 4 - message input port for generation iteration 1'}, {'flbl': 'Step 4 - Biomni LLM generation iteration 1', 'lbl': 'Step 4 - system prompt input'}, {'flbl': 'Step 4 - Biomni LLM generation iteration 1', 'lbl': 'Step 4 - system_prompt input port for generation iteration 1'}])
ic| rquestion: '''
                what are the input parameters of the function used in "Step 5 - Biomni LLM generation iteration 2" step in the pipeline?
                '''
ic| entities:                                          flbl  \
              0  Step 5 - Biomni LLM generation iteration 2
              1  Step 5 - Biomni LLM generation iteration 2
              2  Step 5 - Biomni LLM generation iteration 2
              3  Step 5 - Biomni LLM generation iteration 2

                                                               lbl
              0                 Step 5 - agent state message input
              1  Step 5 - message input port for generation ite...
              2                       Step 5 - system prompt input
              3  Step 5 - system_prompt input port for generati...
ic| answer: GTAnswer(answer_nlp='
                The input parameters to Step 5 - Biomni LLM generation iteration 2 function.

                Funtion name | Function returns
            Step 5 - Biomni LLM generation iteration 2 | Step 5 - agent state message input
            Step 5 - Biomni LLM generation iteration 2 | Step 5 - message input port for generation iteration 2
            Step 5 - Biomni LLM generation iteration 2 | Step 5 - system prompt input
            Step 5 - Biomni LLM generation iteration 2 | Step 5 - system_prompt input port for generation iteration 2
                ', entities=[{'flbl': 'Step 5 - Biomni LLM generation iteration 2', 'lbl': 'Step 5 - agent state message input'}, {'flbl': 'Step 5 - Biomni LLM generation iteration 2', 'lbl': 'Step 5 - message input port for generation iteration 2'}, {'flbl': 'Step 5 - Biomni LLM generation iteration 2', 'lbl': 'Step 5 - system prompt input'}, {'flbl': 'Step 5 - Biomni LLM generation iteration 2', 'lbl': 'Step 5 - system_prompt input port for generation iteration 2'}])
ic| rquestion: '''
                what are the input parameters of the function used in "Step 6 - Biomni LLM generation iteration 3" step in the pipeline?
                '''
ic| entities:                                          flbl  \
              0  Step 6 - Biomni LLM generation iteration 3
              1  Step 6 - Biomni LLM generation iteration 3
              2  Step 6 - Biomni LLM generation iteration 3
              3  Step 6 - Biomni LLM generation iteration 3

                                                               lbl
              0                 Step 6 - agent state message input
              1  Step 6 - message input port for generation ite...
              2                       Step 6 - system prompt input
              3  Step 6 - system_prompt input port for generati...
ic| answer: GTAnswer(answer_nlp='
                The input parameters to Step 6 - Biomni LLM generation iteration 3 function.

                Funtion name | Function returns
            Step 6 - Biomni LLM generation iteration 3 | Step 6 - agent state message input
            Step 6 - Biomni LLM generation iteration 3 | Step 6 - message input port for generation iteration 3
            Step 6 - Biomni LLM generation iteration 3 | Step 6 - system prompt input
            Step 6 - Biomni LLM generation iteration 3 | Step 6 - system_prompt input port for generation iteration 3
                ', entities=[{'flbl': 'Step 6 - Biomni LLM generation iteration 3', 'lbl': 'Step 6 - agent state message input'}, {'flbl': 'Step 6 - Biomni LLM generation iteration 3', 'lbl': 'Step 6 - message input port for generation iteration 3'}, {'flbl': 'Step 6 - Biomni LLM generation iteration 3', 'lbl': 'Step 6 - system prompt input'}, {'flbl': 'Step 6 - Biomni LLM generation iteration 3', 'lbl': 'Step 6 - system_prompt input port for generation iteration 3'}])
ic| rquestion: '''
                what are the input parameters of the function used in "Step 8 - Biomni LLM generation iteration 4" step in the pipeline?
                '''
ic| entities:                                          flbl  \
              0  Step 8 - Biomni LLM generation iteration 4
              1  Step 8 - Biomni LLM generation iteration 4
              2  Step 8 - Biomni LLM generation iteration 4
              3  Step 8 - Biomni LLM generation iteration 4

                                                               lbl
              0                 Step 8 - agent state message input
              1  Step 8 - message input port for generation ite...
              2                       Step 8 - system prompt input
              3  Step 8 - system_prompt input port for generati...
ic| answer: GTAnswer(answer_nlp='
                The input parameters to Step 8 - Biomni LLM generation iteration 4 function.

                Funtion name | Function returns
            Step 8 - Biomni LLM generation iteration 4 | Step 8 - agent state message input
            Step 8 - Biomni LLM generation iteration 4 | Step 8 - message input port for generation iteration 4
            Step 8 - Biomni LLM generation iteration 4 | Step 8 - system prompt input
            Step 8 - Biomni LLM generation iteration 4 | Step 8 - system_prompt input port for generation iteration 4
                ', entities=[{'flbl': 'Step 8 - Biomni LLM generation iteration 4', 'lbl': 'Step 8 - agent state message input'}, {'flbl': 'Step 8 - Biomni LLM generation iteration 4', 'lbl': 'Step 8 - message input port for generation iteration 4'}, {'flbl': 'Step 8 - Biomni LLM generation iteration 4', 'lbl': 'Step 8 - system prompt input'}, {'flbl': 'Step 8 - Biomni LLM generation iteration 4', 'lbl': 'Step 8 - system_prompt input port for generation iteration 4'}])

In [46]:
question_sparql1 = """
SELECT distinct ?obj ?lbl
WHERE {
     ?obj a provone:Program .
     ?obj rdfs:label ?lbl .
}
"""


programs = graph_manager.query(question_sparql1).to_dict(orient="records")
template_spec = [{"func_desc":x["lbl"] , "func_desc_term":x["lbl"]} for x in programs]
template_spec;

In [47]:
# Question MULT 3 : output ports of functions


template_spec = template_spec[:5] if len(template_spec) > 5 else template_spec
sparql_spec = template_spec[:5] if len(template_spec) > 5 else template_spec

question_template = """
what are the output parameters of the function used in "{func_desc}" step in the pipeline?
"""
sparql_template = """
SELECT distinct ?flbl ?lbl
WHERE {
     ?obj dc:description ?desc .
     ?obj rdfs:label ?flbl . 
     ?obj a ?class .
     FILTER(REGEX(?flbl, "{func_desc_term}","i"))

     ?obj provone:hasOutPort ?port .
     ?port rdfs:label ?lbl .
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The input parameters to {func_desc} function.

    {answer_inst}
    """
    
    _ent = entities[['flbl', 'lbl']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "flbl": "Funtion name",
            "lbl": "Function returns"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    #gt.qtype = ["multi", "literal", "SI"]
    gt.qtype = ["multi", "entity"]
gt_list.extend(gts)

ic| rquestion: '''
                what are the output parameters of the function used in "Step 10 - Biomni critic review 1" step in the pipeline?
                '''
ic| entities:                                flbl  \
              0  Step 10 - Biomni critic review 1
              1  Step 10 - Biomni critic review 1
              2  Step 10 - Biomni critic review 1
              3  Step 10 - Biomni critic review 1

                                                               lbl
              0                   Step 10 - critic feedback output
              1  Step 10 - critic_feedback output port for crit...
              2                   Step 10 - next agent step output
              3  Step 10 - next_step output port for critic rev...
ic| answer: GTAnswer(answer_nlp='
                The input parameters to Step 10 - Biomni critic review 1 function.

                Funtion name | Function returns
            Step 10 - Biomni critic review 1 | Step 10 - critic feedback output
            Step 10 - Biomni critic review 1 | Step 10 - critic_feedback output port for critic review 1
            Step 10 - Biomni critic review 1 | Step 10 - next agent step output
            Step 10 - Biomni critic review 1 | Step 10 - next_step output port for critic review 1
                ', entities=[{'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - critic feedback output'}, {'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - critic_feedback output port for critic review 1'}, {'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - next agent step output'}, {'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - next_step output port for critic review 1'}])
ic| rquestion: '''
                what are the output parameters of the function used in "Step 4 - Biomni LLM generation iteration 1" step in the pipeline?
                '''
ic| entities:                                          flbl  \
              0  Step 4 - Biomni LLM generation iteration 1
              1  Step 4 - Biomni LLM generation iteration 1
              2  Step 4 - Biomni LLM generation iteration 1
              3  Step 4 - Biomni LLM generation iteration 1

                                                               lbl
              0                    Step 4 - next agent step output
              1  Step 4 - next_step output port for generation ...
              2                       Step 4 - LLM response output
              3  Step 4 - response output port for generation i...
ic| answer: GTAnswer(answer_nlp='
                The input parameters to Step 4 - Biomni LLM generation iteration 1 function.

                Funtion name | Function returns
            Step 4 - Biomni LLM generation iteration 1 | Step 4 - next agent step output
            Step 4 - Biomni LLM generation iteration 1 | Step 4 - next_step output port for generation iteration 1
            Step 4 - Biomni LLM generation iteration 1 | Step 4 - LLM response output
            Step 4 - Biomni LLM generation iteration 1 | Step 4 - response output port for generation iteration 1
                ', entities=[{'flbl': 'Step 4 - Biomni LLM generation iteration 1', 'lbl': 'Step 4 - next agent step output'}, {'flbl': 'Step 4 - Biomni LLM generation iteration 1', 'lbl': 'Step 4 - next_step output port for generation iteration 1'}, {'flbl': 'Step 4 - Biomni LLM generation iteration 1', 'lbl': 'Step 4 - LLM response output'}, {'flbl': 'Step 4 - Biomni LLM generation iteration 1', 'lbl': 'Step 4 - response output port for generation iteration 1'}])
ic| rquestion: '''
                what are the output parameters of the function used in "Step 5 - Biomni LLM generation iteration 2" step in the pipeline?
                '''
ic| entities:                                          flbl  \
              0  Step 5 - Biomni LLM generation iteration 2
              1  Step 5 - Biomni LLM generation iteration 2
              2  Step 5 - Biomni LLM generation iteration 2
              3  Step 5 - Biomni LLM generation iteration 2

                                                               lbl
              0                    Step 5 - next agent step output
              1  Step 5 - next_step output port for generation ...
              2                       Step 5 - LLM response output
              3  Step 5 - response output port for generation i...
ic| answer: GTAnswer(answer_nlp='
                The input parameters to Step 5 - Biomni LLM generation iteration 2 function.

                Funtion name | Function returns
            Step 5 - Biomni LLM generation iteration 2 | Step 5 - next agent step output
            Step 5 - Biomni LLM generation iteration 2 | Step 5 - next_step output port for generation iteration 2
            Step 5 - Biomni LLM generation iteration 2 | Step 5 - LLM response output
            Step 5 - Biomni LLM generation iteration 2 | Step 5 - response output port for generation iteration 2
                ', entities=[{'flbl': 'Step 5 - Biomni LLM generation iteration 2', 'lbl': 'Step 5 - next agent step output'}, {'flbl': 'Step 5 - Biomni LLM generation iteration 2', 'lbl': 'Step 5 - next_step output port for generation iteration 2'}, {'flbl': 'Step 5 - Biomni LLM generation iteration 2', 'lbl': 'Step 5 - LLM response output'}, {'flbl': 'Step 5 - Biomni LLM generation iteration 2', 'lbl': 'Step 5 - response output port for generation iteration 2'}])
ic| rquestion: '''
                what are the output parameters of the function used in "Step 6 - Biomni LLM generation iteration 3" step in the pipeline?
                '''
ic| entities:                                          flbl  \
              0  Step 6 - Biomni LLM generation iteration 3
              1  Step 6 - Biomni LLM generation iteration 3
              2  Step 6 - Biomni LLM generation iteration 3
              3  Step 6 - Biomni LLM generation iteration 3

                                                               lbl
              0                    Step 6 - next agent step output
              1  Step 6 - next_step output port for generation ...
              2                       Step 6 - LLM response output
              3  Step 6 - response output port for generation i...
ic| answer: GTAnswer(answer_nlp='
                The input parameters to Step 6 - Biomni LLM generation iteration 3 function.

                Funtion name | Function returns
            Step 6 - Biomni LLM generation iteration 3 | Step 6 - next agent step output
            Step 6 - Biomni LLM generation iteration 3 | Step 6 - next_step output port for generation iteration 3
            Step 6 - Biomni LLM generation iteration 3 | Step 6 - LLM response output
            Step 6 - Biomni LLM generation iteration 3 | Step 6 - response output port for generation iteration 3
                ', entities=[{'flbl': 'Step 6 - Biomni LLM generation iteration 3', 'lbl': 'Step 6 - next agent step output'}, {'flbl': 'Step 6 - Biomni LLM generation iteration 3', 'lbl': 'Step 6 - next_step output port for generation iteration 3'}, {'flbl': 'Step 6 - Biomni LLM generation iteration 3', 'lbl': 'Step 6 - LLM response output'}, {'flbl': 'Step 6 - Biomni LLM generation iteration 3', 'lbl': 'Step 6 - response output port for generation iteration 3'}])
ic| rquestion: '''
                what are the output parameters of the function used in "Step 8 - Biomni LLM generation iteration 4" step in the pipeline?
                '''
ic| entities:                                          flbl  \
              0  Step 8 - Biomni LLM generation iteration 4
              1  Step 8 - Biomni LLM generation iteration 4
              2  Step 8 - Biomni LLM generation iteration 4
              3  Step 8 - Biomni LLM generation iteration 4

                                                               lbl
              0                    Step 8 - next agent step output
              1  Step 8 - next_step output port for generation ...
              2                       Step 8 - LLM response output
              3  Step 8 - response output port for generation i...
ic| answer: GTAnswer(answer_nlp='
                The input parameters to Step 8 - Biomni LLM generation iteration 4 function.

                Funtion name | Function returns
            Step 8 - Biomni LLM generation iteration 4 | Step 8 - next agent step output
            Step 8 - Biomni LLM generation iteration 4 | Step 8 - next_step output port for generation iteration 4
            Step 8 - Biomni LLM generation iteration 4 | Step 8 - LLM response output
            Step 8 - Biomni LLM generation iteration 4 | Step 8 - response output port for generation iteration 4
                ', entities=[{'flbl': 'Step 8 - Biomni LLM generation iteration 4', 'lbl': 'Step 8 - next agent step output'}, {'flbl': 'Step 8 - Biomni LLM generation iteration 4', 'lbl': 'Step 8 - next_step output port for generation iteration 4'}, {'flbl': 'Step 8 - Biomni LLM generation iteration 4', 'lbl': 'Step 8 - LLM response output'}, {'flbl': 'Step 8 - Biomni LLM generation iteration 4', 'lbl': 'Step 8 - response output port for generation iteration 4'}])

In [48]:
question_sparql1 = """
SELECT distinct ?obj ?lbl
WHERE {
     ?obj a provone:Program .
     ?obj rdfs:label ?lbl .
}
"""


programs = graph_manager.query(question_sparql1).to_dict(orient="records")
template_spec = [{"func_desc":x["lbl"] , "func_desc_term":x["lbl"]} for x in programs]
template_spec;

In [49]:
# Question MULT 4 : connected functions


template_spec = template_spec[:5] if len(template_spec) > 5 else template_spec

sparql_spec = template_spec[:5] if len(template_spec) > 5 else template_spec

question_template = """
what are the other function ("program") connected to the function used in "{func_desc}" through port parameters?
"""
sparql_template = """

SELECT DISTINCT ?fn2 ?fn2lbl
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl . 
    ?obj a ?class .
    FILTER(REGEX(?flbl, "{func_desc_term}","i"))

    ?obj (provone:hasInPort | provone:hasOutPort) ?port .
    ?port provone:connectsTo ?channel .
    ?portt provone:connectsTo ?channel .
    ?fn2 (provone:hasInPort | provone:hasOutPort) ?portt .
    FILTER(?obj != ?fn2)
    
    ?fn2 rdfs:label ?fn2lbl .
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The connected functions to {func_desc} function.

    {answer_inst}
    """
    
    _ent = entities[['fn2', 'fn2lbl']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "fn2": "Funtion URI",
            "fn2lbl": "Function name"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    #gt.qtype = ["multi", "literal", "entity", "SI"]
    gt.qtype = ["multi",  "entity"]
gt_list.extend(gts)

ic| rquestion: '''
                what are the other function ("program") connected to the function used in "Step 10 - Biomni critic review 1" through port parameters?
                '''
ic| entities:                                                  fn2  \
              0  http://testwebsite/testProgram#generate_agent_...
              1  http://testwebsite/testProgram#generate_agent_...

                                                      fn2lbl
              0   Step 9 - Biomni LLM generation iteration 5
              1  Step 11 - Biomni LLM generation iteration 6
ic| answer: GTAnswer(answer_nlp='
                The connected functions to Step 10 - Biomni critic review 1 function.

                Funtion URI | Function name
            http://testwebsite/testProgram#generate_agent_response_5 | Step 9 - Biomni LLM generation iteration 5
            http://testwebsite/testProgram#generate_agent_response_6 | Step 11 - Biomni LLM generation iteration 6
                ', entities=[{'fn2': 'http://testwebsite/testProgram#generate_agent_response_5', 'fn2lbl': 'Step 9 - Biomni LLM generation iteration 5'}, {'fn2': 'http://testwebsite/testProgram#generate_agent_response_6', 'fn2lbl': 'Step 11 - Biomni LLM generation iteration 6'}])
ic| rquestion: '''
                what are the other function ("program") connected to the function used in "Step 4 - Biomni LLM generation iteration 1" through port parameters?
                '''
ic| entities:                                                  fn2  \
              0   http://testwebsite/testProgram#record_user_input
              1   http://testwebsite/testProgram#record_user_input
              2  http://testwebsite/testProgram#system_prompt_g...
              3  http://testwebsite/testProgram#system_prompt_g...
              4  http://testwebsite/testProgram#system_prompt_g...
              5  http://testwebsite/testProgram#generate_agent_...

                                                           fn2lbl
              0                       Biomni user input recording
              1      Step 3 - Biomni user input recording program
              2                   Biomni system prompt generation
              3  Step 1 - Biomni system prompt generation program
              4  Step 2 - Biomni system prompt generation program
              5        Step 5 - Biomni LLM generation iteration 2
ic| answer: GTAnswer(answer_nlp='
                The connected functions to Step 4 - Biomni LLM generation iteration 1 function.

                Funtion URI | Function name
            http://testwebsite/testProgram#record_user_input | Biomni user input recording
            http://testwebsite/testProgram#record_user_input | Step 3 - Biomni user input recording program
            http://testwebsite/testProgram#system_prompt_generation | Biomni system prompt generation
            http://testwebsite/testProgram#system_prompt_generation | Step 1 - Biomni system prompt generation program
            http://testwebsite/testProgram#system_prompt_generation | Step 2 - Biomni system prompt generation program
            http://testwebsite/testProgram#generate_agent_response_2 | Step 5 - Biomni LLM generation iteration 2
                ', entities=[{'fn2': 'http://testwebsite/testProgram#record_user_input', 'fn2lbl': 'Biomni user input recording'}, {'fn2': 'http://testwebsite/testProgram#record_user_input', 'fn2lbl': 'Step 3 - Biomni user input recording program'}, {'fn2': 'http://testwebsite/testProgram#system_prompt_generation', 'fn2lbl': 'Biomni system prompt generation'}, {'fn2': 'http://testwebsite/testProgram#system_prompt_generation', 'fn2lbl': 'Step 1 - Biomni system prompt generation program'}, {'fn2': 'http://testwebsite/testProgram#system_prompt_generation', 'fn2lbl': 'Step 2 - Biomni system prompt generation program'}, {'fn2': 'http://testwebsite/testProgram#generate_agent_response_2', 'fn2lbl': 'Step 5 - Biomni LLM generation iteration 2'}])
ic| rquestion: '''
                what are the other function ("program") connected to the function used in "Step 5 - Biomni LLM generation iteration 2" through port parameters?
                '''
ic| entities:                                                  fn2  \
              0  http://testwebsite/testProgram#generate_agent_...
              1  http://testwebsite/testProgram#system_prompt_g...
              2  http://testwebsite/testProgram#system_prompt_g...
              3  http://testwebsite/testProgram#system_prompt_g...
              4  http://testwebsite/testProgram#generate_agent_...

                                                           fn2lbl
              0        Step 4 - Biomni LLM generation iteration 1
              1                   Biomni system prompt generation
              2  Step 1 - Biomni system prompt generation program
              3  Step 2 - Biomni system prompt generation program
              4        Step 6 - Biomni LLM generation iteration 3
ic| answer: GTAnswer(answer_nlp='
                The connected functions to Step 5 - Biomni LLM generation iteration 2 function.

                Funtion URI | Function name
            http://testwebsite/testProgram#generate_agent_response_1 | Step 4 - Biomni LLM generation iteration 1
            http://testwebsite/testProgram#system_prompt_generation | Biomni system prompt generation
            http://testwebsite/testProgram#system_prompt_generation | Step 1 - Biomni system prompt generation program
            http://testwebsite/testProgram#system_prompt_generation | Step 2 - Biomni system prompt generation program
            http://testwebsite/testProgram#generate_agent_response_3 | Step 6 - Biomni LLM generation iteration 3
                ', entities=[{'fn2': 'http://testwebsite/testProgram#generate_agent_response_1', 'fn2lbl': 'Step 4 - Biomni LLM generation iteration 1'}, {'fn2': 'http://testwebsite/testProgram#system_prompt_generation', 'fn2lbl': 'Biomni system prompt generation'}, {'fn2': 'http://testwebsite/testProgram#system_prompt_generation', 'fn2lbl': 'Step 1 - Biomni system prompt generation program'}, {'fn2': 'http://testwebsite/testProgram#system_prompt_generation', 'fn2lbl': 'Step 2 - Biomni system prompt generation program'}, {'fn2': 'http://testwebsite/testProgram#generate_agent_response_3', 'fn2lbl': 'Step 6 - Biomni LLM generation iteration 3'}])
ic| rquestion: '''
                what are the other function ("program") connected to the function used in "Step 6 - Biomni LLM generation iteration 3" through port parameters?
                '''
ic| entities:                                                  fn2  \
              0  http://testwebsite/testProgram#generate_agent_...
              1  http://testwebsite/testProgram#system_prompt_g...
              2  http://testwebsite/testProgram#system_prompt_g...
              3  http://testwebsite/testProgram#system_prompt_g...
              4  http://testwebsite/testProgram#execute_agent_c...

                                                           fn2lbl
              0        Step 5 - Biomni LLM generation iteration 2
              1                   Biomni system prompt generation
              2  Step 1 - Biomni system prompt generation program
              3  Step 2 - Biomni system prompt generation program
              4                  Step 7 - Biomni code execution 1
ic| answer: GTAnswer(answer_nlp='
                The connected functions to Step 6 - Biomni LLM generation iteration 3 function.

                Funtion URI | Function name
            http://testwebsite/testProgram#generate_agent_response_2 | Step 5 - Biomni LLM generation iteration 2
            http://testwebsite/testProgram#system_prompt_generation | Biomni system prompt generation
            http://testwebsite/testProgram#system_prompt_generation | Step 1 - Biomni system prompt generation program
            http://testwebsite/testProgram#system_prompt_generation | Step 2 - Biomni system prompt generation program
            http://testwebsite/testProgram#execute_agent_code_1 | Step 7 - Biomni code execution 1
                ', entities=[{'fn2': 'http://testwebsite/testProgram#generate_agent_response_2', 'fn2lbl': 'Step 5 - Biomni LLM generation iteration 2'}, {'fn2': 'http://testwebsite/testProgram#system_prompt_generation', 'fn2lbl': 'Biomni system prompt generation'}, {'fn2': 'http://testwebsite/testProgram#system_prompt_generation', 'fn2lbl': 'Step 1 - Biomni system prompt generation program'}, {'fn2': 'http://testwebsite/testProgram#system_prompt_generation', 'fn2lbl': 'Step 2 - Biomni system prompt generation program'}, {'fn2': 'http://testwebsite/testProgram#execute_agent_code_1', 'fn2lbl': 'Step 7 - Biomni code execution 1'}])
ic| rquestion: '''
                what are the other function ("program") connected to the function used in "Step 8 - Biomni LLM generation iteration 4" through port parameters?
                '''
ic| entities:                                                  fn2  \
              0  http://testwebsite/testProgram#execute_agent_c...
              1  http://testwebsite/testProgram#system_prompt_g...
              2  http://testwebsite/testProgram#system_prompt_g...
              3  http://testwebsite/testProgram#system_prompt_g...
              4  http://testwebsite/testProgram#generate_agent_...

                                                           fn2lbl
              0                  Step 7 - Biomni code execution 1
              1                   Biomni system prompt generation
              2  Step 1 - Biomni system prompt generation program
              3  Step 2 - Biomni system prompt generation program
              4        Step 9 - Biomni LLM generation iteration 5
ic| answer: GTAnswer(answer_nlp='
                The connected functions to Step 8 - Biomni LLM generation iteration 4 function.

                Funtion URI | Function name
            http://testwebsite/testProgram#execute_agent_code_1 | Step 7 - Biomni code execution 1
            http://testwebsite/testProgram#system_prompt_generation | Biomni system prompt generation
            http://testwebsite/testProgram#system_prompt_generation | Step 1 - Biomni system prompt generation program
            http://testwebsite/testProgram#system_prompt_generation | Step 2 - Biomni system prompt generation program
            http://testwebsite/testProgram#generate_agent_response_5 | Step 9 - Biomni LLM generation iteration 5
                ', entities=[{'fn2': 'http://testwebsite/testProgram#execute_agent_code_1', 'fn2lbl': 'Step 7 - Biomni code execution 1'}, {'fn2': 'http://testwebsite/testProgram#system_prompt_generation', 'fn2lbl': 'Biomni system prompt generation'}, {'fn2': 'http://testwebsite/testProgram#system_prompt_generation', 'fn2lbl': 'Step 1 - Biomni system prompt generation program'}, {'fn2': 'http://testwebsite/testProgram#system_prompt_generation', 'fn2lbl': 'Step 2 - Biomni system prompt generation program'}, {'fn2': 'http://testwebsite/testProgram#generate_agent_response_5', 'fn2lbl': 'Step 9 - Biomni LLM generation iteration 5'}])

In [50]:
question_sparql1 = """
SELECT distinct ?obj ?lbl
WHERE {
     ?obj a provone:Program .
     ?obj rdfs:label ?lbl .
}
"""


programs = graph_manager.query(question_sparql1).to_dict(orient="records")
template_spec = [{"func_desc":x["lbl"] , "func_desc_term":x["lbl"]} for x in programs]
template_spec;

In [51]:
# Question MULT 5 : number of execution of the functions


template_spec = template_spec[:5] if len(template_spec) > 5 else template_spec

sparql_spec = template_spec[:5] if len(template_spec) > 5 else template_spec

question_template = """
what are the executions of the {func_desc} step in the pipeline?
"""
sparql_template = """

SELECT DISTINCT ?exe
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl . 
    ?obj a ?class .
    FILTER(REGEX(?flbl, "{func_desc_term}","i"))

    ?asso prov:hadPlan ?obj .
    ?exe prov:qualifiedAssociation ?asso .
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The executions of the  {func_desc} function are.

    {answer_inst}
    """
    
    _ent = entities[['exe']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "exe": "Executions"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    #gt.qtype = ["multi", "entity", "ISP"]
    gt.qtype = ["multi", "entity"]
gt_list.extend(gts)

ic| rquestion: '''
                what are the executions of the Step 10 - Biomni critic review 1 step in the pipeline?
                '''
ic| entities:                                                  exe
              0  http://testwebsite/testProgram#id_202605050010...
ic| answer: GTAnswer(answer_nlp='
                The executions of the  Step 10 - Biomni critic review 1 function are.

                Executions
            http://testwebsite/testProgram#id_20260505001035_720
                ', entities=[{'exe': 'http://testwebsite/testProgram#id_20260505001035_720'}])
ic| rquestion: '''
                what are the executions of the Step 4 - Biomni LLM generation iteration 1 step in the pipeline?
                '''
ic| entities:                                                  exe
              0  http://testwebsite/testProgram#id_202605050010...
ic| answer: GTAnswer(answer_nlp='
                The executions of the  Step 4 - Biomni LLM generation iteration 1 function are.

                Executions
            http://testwebsite/testProgram#id_20260505001006_475
                ', entities=[{'exe': 'http://testwebsite/testProgram#id_20260505001006_475'}])
ic| rquestion: '''
                what are the executions of the Step 5 - Biomni LLM generation iteration 2 step in the pipeline?
                '''
ic| entities:                                                  exe
              0  http://testwebsite/testProgram#id_202605050010...
ic| answer: GTAnswer(answer_nlp='
                The executions of the  Step 5 - Biomni LLM generation iteration 2 function are.

                Executions
            http://testwebsite/testProgram#id_20260505001009_972
                ', entities=[{'exe': 'http://testwebsite/testProgram#id_20260505001009_972'}])
ic| rquestion: '''
                what are the executions of the Step 6 - Biomni LLM generation iteration 3 step in the pipeline?
                '''
ic| entities:                                                  exe
              0  http://testwebsite/testProgram#id_202605050010...
ic| answer: GTAnswer(answer_nlp='
                The executions of the  Step 6 - Biomni LLM generation iteration 3 function are.

                Executions
            http://testwebsite/testProgram#id_20260505001011_890
                ', entities=[{'exe': 'http://testwebsite/testProgram#id_20260505001011_890'}])
ic| rquestion: '''
                what are the executions of the Step 8 - Biomni LLM generation iteration 4 step in the pipeline?
                '''
ic| entities:                                                  exe
              0  http://testwebsite/testProgram#id_202605050010...
ic| answer: GTAnswer(answer_nlp='
                The executions of the  Step 8 - Biomni LLM generation iteration 4 function are.

                Executions
            http://testwebsite/testProgram#id_20260505001016_956
                ', entities=[{'exe': 'http://testwebsite/testProgram#id_20260505001016_956'}])

In [52]:
question_sparql1 = """
SELECT distinct ?obj ?lbl
WHERE {
     ?obj a provone:Program .
     ?obj rdfs:label ?lbl .
}
"""


programs = graph_manager.query(question_sparql1).to_dict(orient="records")
template_spec = [{"func_desc":x["lbl"] , "func_desc_term":x["lbl"]} for x in programs]
template_spec;

In [53]:
# Question MULT 6 : who was the agent that ran the functions 


template_spec = template_spec[:5] if len(template_spec) > 5 else template_spec
sparql_spec = template_spec[:5] if len(template_spec) > 5 else template_spec

question_template = """
who were the agents that ran the {func_desc} step in the pipeline?
"""
sparql_template = """

SELECT DISTINCT ?agent ?albl
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl . 
    ?obj a ?class .
    FILTER(REGEX(?flbl, "{func_desc_term}","i"))

    ?asso prov:hadPlan ?obj .
    ?asso prov:agent ?agent .
    ?agent rdfs:label ?albl
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The executions of the  {func_desc} function are.

    {answer_inst}
    """
    
    _ent = entities[['albl']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "albl": "Agents"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    #gt.qtype = ["multi", "entity", "literal", "ISP"]
    gt.qtype = ["multi", "entity"]
gt_list.extend(gts)

ic| rquestion: '''
                who were the agents that ran the Step 10 - Biomni critic review 1 step in the pipeline?
                '''
ic| entities:                                        agent  \
              0   http://testwebsite/testProgram#test_user
              1   http://testwebsite/testProgram#test_user
              2   http://testwebsite/testProgram#test_user
              3   http://testwebsite/testProgram#test_user
              4   http://testwebsite/testProgram#test_user
              5   http://testwebsite/testProgram#test_user
              6   http://testwebsite/testProgram#test_user
              7   http://testwebsite/testProgram#test_user
              8   http://testwebsite/testProgram#test_user
              9   http://testwebsite/testProgram#test_user
              10  http://testwebsite/testProgram#test_user
              11  http://testwebsite/testProgram#test_user

                                                               albl
              0   Step 1 - agent associated with system prompt g...
              1     Step 10 - agent associated with critic review 1
              2   Step 11 - agent associated with generation ite...
              3   Step 12 - agent associated with generation ite...
              4   Step 2 - agent associated with system prompt g...
              5   Step 3 - agent associated with user input reco...
              6   Step 4 - agent associated with generation iter...
              7   Step 5 - agent associated with generation iter...
              8   Step 6 - agent associated with generation iter...
              9     Step 7 - agent associated with code execution 1
              10  Step 8 - agent associated with generation iter...
              11  Step 9 - agent associated with generation iter...
ic| answer: GTAnswer(answer_nlp='
                The executions of the  Step 10 - Biomni critic review 1 function are.

                Agents
            Step 1 - agent associated with system prompt generation
            Step 10 - agent associated with critic review 1
            Step 11 - agent associated with generation iteration 6
            Step 12 - agent associated with generation iteration 7
            Step 2 - agent associated with system prompt generation
            Step 3 - agent associated with user input recording
            Step 4 - agent associated with generation iteration 1
            Step 5 - agent associated with generation iteration 2
            Step 6 - agent associated with generation iteration 3
            Step 7 - agent associated with code execution 1
            Step 8 - agent associated with generation iteration 4
            Step 9 - agent associated with generation iteration 5
                ', entities=[{'albl': 'Step 1 - agent associated with system prompt generation'}, {'albl': 'Step 10 - agent associated with critic review 1'}, {'albl': 'Step 11 - agent associated with generation iteration 6'}, {'albl': 'Step 12 - agent associated with generation iteration 7'}, {'albl': 'Step 2 - agent associated with system prompt generation'}, {'albl': 'Step 3 - agent associated with user input recording'}, {'albl': 'Step 4 - agent associated with generation iteration 1'}, {'albl': 'Step 5 - agent associated with generation iteration 2'}, {'albl': 'Step 6 - agent associated with generation iteration 3'}, {'albl': 'Step 7 - agent associated with code execution 1'}, {'albl': 'Step 8 - agent associated with generation iteration 4'}, {'albl': 'Step 9 - agent associated with generation iteration 5'}])
ic| rquestion: '''
                who were the agents that ran the Step 4 - Biomni LLM generation iteration 1 step in the pipeline?
                '''
ic| entities:                                        agent  \
              0   http://testwebsite/testProgram#test_user
              1   http://testwebsite/testProgram#test_user
              2   http://testwebsite/testProgram#test_user
              3   http://testwebsite/testProgram#test_user
              4   http://testwebsite/testProgram#test_user
              5   http://testwebsite/testProgram#test_user
              6   http://testwebsite/testProgram#test_user
              7   http://testwebsite/testProgram#test_user
              8   http://testwebsite/testProgram#test_user
              9   http://testwebsite/testProgram#test_user
              10  http://testwebsite/testProgram#test_user
              11  http://testwebsite/testProgram#test_user

                                                               albl
              0   Step 1 - agent associated with system prompt g...
              1     Step 10 - agent associated with critic review 1
              2   Step 11 - agent associated with generation ite...
              3   Step 12 - agent associated with generation ite...
              4   Step 2 - agent associated with system prompt g...
              5   Step 3 - agent associated with user input reco...
              6   Step 4 - agent associated with generation iter...
              7   Step 5 - agent associated with generation iter...
              8   Step 6 - agent associated with generation iter...
              9     Step 7 - agent associated with code execution 1
              10  Step 8 - agent associated with generation iter...
              11  Step 9 - agent associated with generation iter...
ic| answer: GTAnswer(answer_nlp='
                The executions of the  Step 4 - Biomni LLM generation iteration 1 function are.

                Agents
            Step 1 - agent associated with system prompt generation
            Step 10 - agent associated with critic review 1
            Step 11 - agent associated with generation iteration 6
            Step 12 - agent associated with generation iteration 7
            Step 2 - agent associated with system prompt generation
            Step 3 - agent associated with user input recording
            Step 4 - agent associated with generation iteration 1
            Step 5 - agent associated with generation iteration 2
            Step 6 - agent associated with generation iteration 3
            Step 7 - agent associated with code execution 1
            Step 8 - agent associated with generation iteration 4
            Step 9 - agent associated with generation iteration 5
                ', entities=[{'albl': 'Step 1 - agent associated with system prompt generation'}, {'albl': 'Step 10 - agent associated with critic review 1'}, {'albl': 'Step 11 - agent associated with generation iteration 6'}, {'albl': 'Step 12 - agent associated with generation iteration 7'}, {'albl': 'Step 2 - agent associated with system prompt generation'}, {'albl': 'Step 3 - agent associated with user input recording'}, {'albl': 'Step 4 - agent associated with generation iteration 1'}, {'albl': 'Step 5 - agent associated with generation iteration 2'}, {'albl': 'Step 6 - agent associated with generation iteration 3'}, {'albl': 'Step 7 - agent associated with code execution 1'}, {'albl': 'Step 8 - agent associated with generation iteration 4'}, {'albl': 'Step 9 - agent associated with generation iteration 5'}])
ic| rquestion: '''
                who were the agents that ran the Step 5 - Biomni LLM generation iteration 2 step in the pipeline?
                '''
ic| entities:                                        agent  \
              0   http://testwebsite/testProgram#test_user
              1   http://testwebsite/testProgram#test_user
              2   http://testwebsite/testProgram#test_user
              3   http://testwebsite/testProgram#test_user
              4   http://testwebsite/testProgram#test_user
              5   http://testwebsite/testProgram#test_user
              6   http://testwebsite/testProgram#test_user
              7   http://testwebsite/testProgram#test_user
              8   http://testwebsite/testProgram#test_user
              9   http://testwebsite/testProgram#test_user
              10  http://testwebsite/testProgram#test_user
              11  http://testwebsite/testProgram#test_user

                                                               albl
              0   Step 1 - agent associated with system prompt g...
              1     Step 10 - agent associated with critic review 1
              2   Step 11 - agent associated with generation ite...
              3   Step 12 - agent associated with generation ite...
              4   Step 2 - agent associated with system prompt g...
              5   Step 3 - agent associated with user input reco...
              6   Step 4 - agent associated with generation iter...
              7   Step 5 - agent associated with generation iter...
              8   Step 6 - agent associated with generation iter...
              9     Step 7 - agent associated with code execution 1
              10  Step 8 - agent associated with generation iter...
              11  Step 9 - agent associated with generation iter...
ic| answer: GTAnswer(answer_nlp='
                The executions of the  Step 5 - Biomni LLM generation iteration 2 function are.

                Agents
            Step 1 - agent associated with system prompt generation
            Step 10 - agent associated with critic review 1
            Step 11 - agent associated with generation iteration 6
            Step 12 - agent associated with generation iteration 7
            Step 2 - agent associated with system prompt generation
            Step 3 - agent associated with user input recording
            Step 4 - agent associated with generation iteration 1
            Step 5 - agent associated with generation iteration 2
            Step 6 - agent associated with generation iteration 3
            Step 7 - agent associated with code execution 1
            Step 8 - agent associated with generation iteration 4
            Step 9 - agent associated with generation iteration 5
                ', entities=[{'albl': 'Step 1 - agent associated with system prompt generation'}, {'albl': 'Step 10 - agent associated with critic review 1'}, {'albl': 'Step 11 - agent associated with generation iteration 6'}, {'albl': 'Step 12 - agent associated with generation iteration 7'}, {'albl': 'Step 2 - agent associated with system prompt generation'}, {'albl': 'Step 3 - agent associated with user input recording'}, {'albl': 'Step 4 - agent associated with generation iteration 1'}, {'albl': 'Step 5 - agent associated with generation iteration 2'}, {'albl': 'Step 6 - agent associated with generation iteration 3'}, {'albl': 'Step 7 - agent associated with code execution 1'}, {'albl': 'Step 8 - agent associated with generation iteration 4'}, {'albl': 'Step 9 - agent associated with generation iteration 5'}])
ic| rquestion: '''
                who were the agents that ran the Step 6 - Biomni LLM generation iteration 3 step in the pipeline?
                '''
ic| entities:                                        agent  \
              0   http://testwebsite/testProgram#test_user
              1   http://testwebsite/testProgram#test_user
              2   http://testwebsite/testProgram#test_user
              3   http://testwebsite/testProgram#test_user
              4   http://testwebsite/testProgram#test_user
              5   http://testwebsite/testProgram#test_user
              6   http://testwebsite/testProgram#test_user
              7   http://testwebsite/testProgram#test_user
              8   http://testwebsite/testProgram#test_user
              9   http://testwebsite/testProgram#test_user
              10  http://testwebsite/testProgram#test_user
              11  http://testwebsite/testProgram#test_user

                                                               albl
              0   Step 1 - agent associated with system prompt g...
              1     Step 10 - agent associated with critic review 1
              2   Step 11 - agent associated with generation ite...
              3   Step 12 - agent associated with generation ite...
              4   Step 2 - agent associated with system prompt g...
              5   Step 3 - agent associated with user input reco...
              6   Step 4 - agent associated with generation iter...
              7   Step 5 - agent associated with generation iter...
              8   Step 6 - agent associated with generation iter...
              9     Step 7 - agent associated with code execution 1
              10  Step 8 - agent associated with generation iter...
              11  Step 9 - agent associated with generation iter...
ic| answer: GTAnswer(answer_nlp='
                The executions of the  Step 6 - Biomni LLM generation iteration 3 function are.

                Agents
            Step 1 - agent associated with system prompt generation
            Step 10 - agent associated with critic review 1
            Step 11 - agent associated with generation iteration 6
            Step 12 - agent associated with generation iteration 7
            Step 2 - agent associated with system prompt generation
            Step 3 - agent associated with user input recording
            Step 4 - agent associated with generation iteration 1
            Step 5 - agent associated with generation iteration 2
            Step 6 - agent associated with generation iteration 3
            Step 7 - agent associated with code execution 1
            Step 8 - agent associated with generation iteration 4
            Step 9 - agent associated with generation iteration 5
                ', entities=[{'albl': 'Step 1 - agent associated with system prompt generation'}, {'albl': 'Step 10 - agent associated with critic review 1'}, {'albl': 'Step 11 - agent associated with generation iteration 6'}, {'albl': 'Step 12 - agent associated with generation iteration 7'}, {'albl': 'Step 2 - agent associated with system prompt generation'}, {'albl': 'Step 3 - agent associated with user input recording'}, {'albl': 'Step 4 - agent associated with generation iteration 1'}, {'albl': 'Step 5 - agent associated with generation iteration 2'}, {'albl': 'Step 6 - agent associated with generation iteration 3'}, {'albl': 'Step 7 - agent associated with code execution 1'}, {'albl': 'Step 8 - agent associated with generation iteration 4'}, {'albl': 'Step 9 - agent associated with generation iteration 5'}])
ic| rquestion: '''
                who were the agents that ran the Step 8 - Biomni LLM generation iteration 4 step in the pipeline?
                '''
ic| entities:                                        agent  \
              0   http://testwebsite/testProgram#test_user
              1   http://testwebsite/testProgram#test_user
              2   http://testwebsite/testProgram#test_user
              3   http://testwebsite/testProgram#test_user
              4   http://testwebsite/testProgram#test_user
              5   http://testwebsite/testProgram#test_user
              6   http://testwebsite/testProgram#test_user
              7   http://testwebsite/testProgram#test_user
              8   http://testwebsite/testProgram#test_user
              9   http://testwebsite/testProgram#test_user
              10  http://testwebsite/testProgram#test_user
              11  http://testwebsite/testProgram#test_user

                                                               albl
              0   Step 1 - agent associated with system prompt g...
              1     Step 10 - agent associated with critic review 1
              2   Step 11 - agent associated with generation ite...
              3   Step 12 - agent associated with generation ite...
              4   Step 2 - agent associated with system prompt g...
              5   Step 3 - agent associated with user input reco...
              6   Step 4 - agent associated with generation iter...
              7   Step 5 - agent associated with generation iter...
              8   Step 6 - agent associated with generation iter...
              9     Step 7 - agent associated with code execution 1
              10  Step 8 - agent associated with generation iter...
              11  Step 9 - agent associated with generation iter...
ic| answer: GTAnswer(answer_nlp='
                The executions of the  Step 8 - Biomni LLM generation iteration 4 function are.

                Agents
            Step 1 - agent associated with system prompt generation
            Step 10 - agent associated with critic review 1
            Step 11 - agent associated with generation iteration 6
            Step 12 - agent associated with generation iteration 7
            Step 2 - agent associated with system prompt generation
            Step 3 - agent associated with user input recording
            Step 4 - agent associated with generation iteration 1
            Step 5 - agent associated with generation iteration 2
            Step 6 - agent associated with generation iteration 3
            Step 7 - agent associated with code execution 1
            Step 8 - agent associated with generation iteration 4
            Step 9 - agent associated with generation iteration 5
                ', entities=[{'albl': 'Step 1 - agent associated with system prompt generation'}, {'albl': 'Step 10 - agent associated with critic review 1'}, {'albl': 'Step 11 - agent associated with generation iteration 6'}, {'albl': 'Step 12 - agent associated with generation iteration 7'}, {'albl': 'Step 2 - agent associated with system prompt generation'}, {'albl': 'Step 3 - agent associated with user input recording'}, {'albl': 'Step 4 - agent associated with generation iteration 1'}, {'albl': 'Step 5 - agent associated with generation iteration 2'}, {'albl': 'Step 6 - agent associated with generation iteration 3'}, {'albl': 'Step 7 - agent associated with code execution 1'}, {'albl': 'Step 8 - agent associated with generation iteration 4'}, {'albl': 'Step 9 - agent associated with generation iteration 5'}])

In [54]:
question_sparql1 = """
SELECT distinct ?obj ?lbl
WHERE {
     ?obj a provone:Program .
     ?obj rdfs:label ?lbl .
}
"""


programs = graph_manager.query(question_sparql1).to_dict(orient="records")
template_spec = [{"func_desc":x["lbl"] , "func_desc_term":x["lbl"]} for x in programs]
template_spec;

In [55]:
# Question MULT 7 : Is the function made by a Generative Task  


template_spec = template_spec[:5] if len(template_spec) > 5 else template_spec
sparql_spec = template_spec[:5] if len(template_spec) > 5 else template_spec

question_template = """
Is the function with a description as "{func_desc}" made by using Large Language Model output?
"""

sparql_template = """
SELECT DISTINCT ?fnlbl ?llm_gen_out
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?fnlbl .
    FILTER(REGEX(?fnlbl, "{func_desc_term}", "i"))

    OPTIONAL {
        ?llm_out sio:SIO_000202 ?obj .
        ?llm_out sio:SIO_000232 ?llm .
        ?llm_gen prov:used ?llm .
    }

    BIND(COALESCE(?llm_gen, "None") AS ?llm_gen_out)
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The {func_desc} function {decision} by a Generative Task.

    {answer_inst}
    """
    
    _ent = entities[['fnlbl', 'llm_gen_out']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "obj": "Function",
            'llm_gen_out': "Generative Task used to generate function"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent,
        decision = "is made" if _ent['llm_gen_out'].tolist()[0] != "None" else "is not made"
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    #gt.qtype = ["single", "bool", "SI"]
    gt.qtype = ["single", "bool"]
    gt.decision = gt.entities[0]['llm_gen_out'] != "None"
gt_list.extend(gts)

ic| rquestion: '''
                Is the function with a description as "Step 10 - Biomni critic review 1" made by using Large Language Model output?
                '''
ic| entities:                               fnlbl llm_gen_out
              0  Step 10 - Biomni critic review 1        None
ic| answer: GTAnswer(answer_nlp='
                The Step 10 - Biomni critic review 1 function is not made by a Generative Task.

                fnlbl | Generative Task used to generate function
            Step 10 - Biomni critic review 1 | None
                ', entities=[{'fnlbl': 'Step 10 - Biomni critic review 1', 'llm_gen_out': 'None'}])
ic| rquestion: '''
                Is the function with a description as "Step 4 - Biomni LLM generation iteration 1" made by using Large Language Model output?
                '''
ic| entities:                                         fnlbl llm_gen_out
              0  Step 4 - Biomni LLM generation iteration 1        None
ic| answer: GTAnswer(answer_nlp='
                The Step 4 - Biomni LLM generation iteration 1 function is not made by a Generative Task.

                fnlbl | Generative Task used to generate function
            Step 4 - Biomni LLM generation iteration 1 | None
                ', entities=[{'fnlbl': 'Step 4 - Biomni LLM generation iteration 1', 'llm_gen_out': 'None'}])
ic| rquestion: '''
                Is the function with a description as "Step 5 - Biomni LLM generation iteration 2" made by using Large Language Model output?
                '''
ic| entities:                                         fnlbl llm_gen_out
              0  Step 5 - Biomni LLM generation iteration 2        None
ic| answer: GTAnswer(answer_nlp='
                The Step 5 - Biomni LLM generation iteration 2 function is not made by a Generative Task.

                fnlbl | Generative Task used to generate function
            Step 5 - Biomni LLM generation iteration 2 | None
                ', entities=[{'fnlbl': 'Step 5 - Biomni LLM generation iteration 2', 'llm_gen_out': 'None'}])
ic| rquestion: '''
                Is the function with a description as "Step 6 - Biomni LLM generation iteration 3" made by using Large Language Model output?
                '''
ic| entities:                                         fnlbl llm_gen_out
              0  Step 6 - Biomni LLM generation iteration 3        None
ic| answer: GTAnswer(answer_nlp='
                The Step 6 - Biomni LLM generation iteration 3 function is not made by a Generative Task.

                fnlbl | Generative Task used to generate function
            Step 6 - Biomni LLM generation iteration 3 | None
                ', entities=[{'fnlbl': 'Step 6 - Biomni LLM generation iteration 3', 'llm_gen_out': 'None'}])
ic| rquestion: '''
                Is the function with a description as "Step 8 - Biomni LLM generation iteration 4" made by using Large Language Model output?
                '''
ic| entities:                                         fnlbl llm_gen_out
              0  Step 8 - Biomni LLM generation iteration 4        None
ic| answer: GTAnswer(answer_nlp='
                The Step 8 - Biomni LLM generation iteration 4 function is not made by a Generative Task.

                fnlbl | Generative Task used to generate function
            Step 8 - Biomni LLM generation iteration 4 | None
                ', entities=[{'fnlbl': 'Step 8 - Biomni LLM generation iteration 4', 'llm_gen_out': 'None'}])

In [56]:
question_sparql1 = """
SELECT distinct ?obj ?lbl
WHERE {
     ?obj a provone:Program .
     ?obj rdfs:label ?lbl .
}
"""


programs = graph_manager.query(question_sparql1).to_dict(orient="records")
template_spec = [{"func_desc":x["lbl"] , "func_desc_term":x["lbl"]} for x in programs]
template_spec;

In [57]:
# Question MULT 8 : Does any of the executions of the function contain a Generative Task  


template_spec = template_spec[:5] if len(template_spec) > 5 else template_spec
sparql_spec = template_spec[:5] if len(template_spec) > 5 else template_spec

question_template = """
Does any of the executions of the "{func_desc}" function made has a Generative Task as a component within?
"""

sparql_template = """
SELECT DISTINCT ?flbl ?exe ?llm_gen_out
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl .
    FILTER(REGEX(?flbl, "{func_desc_term}","i"))

    ?asso prov:hadPlan ?obj .
    ?exe prov:qualifiedAssociation ?asso .

    OPTIONAL {
        ?exe sio:SIO_000369 ?llm_gen .
    }

    BIND(COALESCE(?llm_gen, "None") AS ?llm_gen_out)
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    Executions of the {func_desc} function {decision} a Generative Task that utilize an LLM.

    {answer_inst}
    """
    
    _ent = entities[['flbl', 'exe', 'llm_gen_out']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "flbl": "Function",
            'exe': "Execution",
            'llm_gen_out': "Generative Task used within execution"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent,
        decision = "contains" if _ent['llm_gen_out'].tolist()[0] != "None" else "does not contain"
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    #gt.qtype = ["single", "bool", "ISP"]
    gt.qtype = ["single", "bool"]
    gt.decision = gt.entities[0]['llm_gen_out'] != "None"
gt_list.extend(gts)

ic| rquestion: '''
                Does any of the executions of the "Step 10 - Biomni critic review 1" function made has a Generative Task as a component within?
                '''
ic| entities:                                flbl  \
              0  Step 10 - Biomni critic review 1

                                                               exe  \
              0  http://testwebsite/testProgram#id_202605050010...

                                                       llm_gen_out
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                Executions of the Step 10 - Biomni critic review 1 function contains a Generative Task that utilize an LLM.

                Function | Execution | Generative Task used within execution
            Step 10 - Biomni critic review 1 | http://testwebsite/testProgram#id_20260505001035_720 | http://testwebsite/testProgram#Generative_Task-id_20260505001035_720
                ', entities=[{'flbl': 'Step 10 - Biomni critic review 1', 'exe': 'http://testwebsite/testProgram#id_20260505001035_720', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-id_20260505001035_720'}])
ic| rquestion: '''
                Does any of the executions of the "Step 4 - Biomni LLM generation iteration 1" function made has a Generative Task as a component within?
                '''
ic| entities:                                          flbl  \
              0  Step 4 - Biomni LLM generation iteration 1

                                                               exe  \
              0  http://testwebsite/testProgram#id_202605050010...

                                                       llm_gen_out
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                Executions of the Step 4 - Biomni LLM generation iteration 1 function contains a Generative Task that utilize an LLM.

                Function | Execution | Generative Task used within execution
            Step 4 - Biomni LLM generation iteration 1 | http://testwebsite/testProgram#id_20260505001006_475 | http://testwebsite/testProgram#Generative_Task-id_20260505001006_475
                ', entities=[{'flbl': 'Step 4 - Biomni LLM generation iteration 1', 'exe': 'http://testwebsite/testProgram#id_20260505001006_475', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-id_20260505001006_475'}])
ic| rquestion: '''
                Does any of the executions of the "Step 5 - Biomni LLM generation iteration 2" function made has a Generative Task as a component within?
                '''
ic| entities:                                          flbl  \
              0  Step 5 - Biomni LLM generation iteration 2

                                                               exe  \
              0  http://testwebsite/testProgram#id_202605050010...

                                                       llm_gen_out
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                Executions of the Step 5 - Biomni LLM generation iteration 2 function contains a Generative Task that utilize an LLM.

                Function | Execution | Generative Task used within execution
            Step 5 - Biomni LLM generation iteration 2 | http://testwebsite/testProgram#id_20260505001009_972 | http://testwebsite/testProgram#Generative_Task-id_20260505001009_972
                ', entities=[{'flbl': 'Step 5 - Biomni LLM generation iteration 2', 'exe': 'http://testwebsite/testProgram#id_20260505001009_972', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-id_20260505001009_972'}])
ic| rquestion: '''
                Does any of the executions of the "Step 6 - Biomni LLM generation iteration 3" function made has a Generative Task as a component within?
                '''
ic| entities:                                          flbl  \
              0  Step 6 - Biomni LLM generation iteration 3

                                                               exe  \
              0  http://testwebsite/testProgram#id_202605050010...

                                                       llm_gen_out
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                Executions of the Step 6 - Biomni LLM generation iteration 3 function contains a Generative Task that utilize an LLM.

                Function | Execution | Generative Task used within execution
            Step 6 - Biomni LLM generation iteration 3 | http://testwebsite/testProgram#id_20260505001011_890 | http://testwebsite/testProgram#Generative_Task-id_20260505001011_890
                ', entities=[{'flbl': 'Step 6 - Biomni LLM generation iteration 3', 'exe': 'http://testwebsite/testProgram#id_20260505001011_890', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-id_20260505001011_890'}])
ic| rquestion: '''
                Does any of the executions of the "Step 8 - Biomni LLM generation iteration 4" function made has a Generative Task as a component within?
                '''
ic| entities:                                          flbl  \
              0  Step 8 - Biomni LLM generation iteration 4

                                                               exe  \
              0  http://testwebsite/testProgram#id_202605050010...

                                                       llm_gen_out
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                Executions of the Step 8 - Biomni LLM generation iteration 4 function contains a Generative Task that utilize an LLM.

                Function | Execution | Generative Task used within execution
            Step 8 - Biomni LLM generation iteration 4 | http://testwebsite/testProgram#id_20260505001016_956 | http://testwebsite/testProgram#Generative_Task-id_20260505001016_956
                ', entities=[{'flbl': 'Step 8 - Biomni LLM generation iteration 4', 'exe': 'http://testwebsite/testProgram#id_20260505001016_956', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-id_20260505001016_956'}])

In [58]:
question_sparql1 = """
SELECT distinct ?obj ?lbl
WHERE {
     ?obj a provone:Program .
     ?obj rdfs:label ?lbl .
}
"""


programs = graph_manager.query(question_sparql1).to_dict(orient="records")
template_spec = [{"func_desc":x["lbl"] , "func_desc_term":x["lbl"]} for x in programs]
template_spec;

In [59]:
# Question MULT 9 : Does any of the executions of the function contain a Generative Task within and the function itself is generated by an LLM


template_spec = template_spec[:5] if len(template_spec) > 5 else template_spec
sparql_spec = template_spec[:5] if len(template_spec) > 5 else template_spec

question_template = """
Does any of the executions of the {func_desc} function made has a Generative Task within as a component and also {func_desc} 
function itself is generated by a Generative Task?
"""

sparql_template = """
SELECT DISTINCT ?flbl ?exe ?llm_gen_out ?llm_gen_out2
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl .
    FILTER(REGEX(?flbl, "{func_desc_term}","i"))

    ?asso prov:hadPlan ?obj .
    ?exe prov:qualifiedAssociation ?asso .

    OPTIONAL {
        ?exe sio:SIO_000369 ?llm_gen .
    }

    BIND(COALESCE(?llm_gen, "None") AS ?llm_gen_out)
    
    OPTIONAL {
        ?llm_out2 sio:SIO_000202 ?obj .
        ?llm_out2 sio:SIO_000232 ?llm2 .
        ?llm_gen2 prov:used ?llm2 .
    }

    BIND(COALESCE(?llm_gen2, "None") AS ?llm_gen_out2)
}

"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    1. Executions of the {func_desc} function {decision1} a Generative Task that utilize an LLM.
    2. The {func_desc} function {decision2} by a Generative Task.

    {answer_inst}
    """
    
    _ent = entities[['flbl', 'exe', 'llm_gen_out', 'llm_gen_out2']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "flbl": "Function",
            'exe': "Execution",
            'llm_gen_out': "Generative Task used within execution",
            'llm_gen_out2': "Generative Task used to generate function"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent,
        decision1 = "contains" if _ent['llm_gen_out'].tolist()[0] != "None" else "does not contain",
        decision2 = "is generated" if _ent['llm_gen_out2'].tolist()[0] != "None" else "is not generated"
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    #gt.qtype = ["single", "bool", "ISP"]
    gt.qtype = ["single", "bool"]
    gt.decision = (gt.entities[0]['llm_gen_out'] != "None") and (gt.entities[0]['llm_gen_out2'] != "None")

gt_list.extend(gts)

ic| rquestion: '''
                Does any of the executions of the Step 10 - Biomni critic review 1 function made has a Generative Task within as a component and also Step 10 - Biomni critic review 1
                function itself is generated by a Generative Task?
                '''
ic| entities:                                flbl  \
              0  Step 10 - Biomni critic review 1

                                                               exe  \
              0  http://testwebsite/testProgram#id_202605050010...

                                                       llm_gen_out llm_gen_out2
              0  http://testwebsite/testProgram#Generative_Task...         None
ic| answer: GTAnswer(answer_nlp='
                1. Executions of the Step 10 - Biomni critic review 1 function contains a Generative Task that utilize an LLM.
                2. The Step 10 - Biomni critic review 1 function is not generated by a Generative Task.

                Function | Execution | Generative Task used within execution | Generative Task used to generate function
            Step 10 - Biomni critic review 1 | http://testwebsite/testProgram#id_20260505001035_720 | http://testwebsite/testProgram#Generative_Task-id_20260505001035_720 | None
                ', entities=[{'flbl': 'Step 10 - Biomni critic review 1', 'exe': 'http://testwebsite/testProgram#id_20260505001035_720', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-id_20260505001035_720', 'llm_gen_out2': 'None'}])
ic| rquestion: '''
                Does any of the executions of the Step 4 - Biomni LLM generation iteration 1 function made has a Generative Task within as a component and also Step 4 - Biomni LLM generation iteration 1
                function itself is generated by a Generative Task?
                '''
ic| entities:                                          flbl  \
              0  Step 4 - Biomni LLM generation iteration 1

                                                               exe  \
              0  http://testwebsite/testProgram#id_202605050010...

                                                       llm_gen_out llm_gen_out2
              0  http://testwebsite/testProgram#Generative_Task...         None
ic| answer: GTAnswer(answer_nlp='
                1. Executions of the Step 4 - Biomni LLM generation iteration 1 function contains a Generative Task that utilize an LLM.
                2. The Step 4 - Biomni LLM generation iteration 1 function is not generated by a Generative Task.

                Function | Execution | Generative Task used within execution | Generative Task used to generate function
            Step 4 - Biomni LLM generation iteration 1 | http://testwebsite/testProgram#id_20260505001006_475 | http://testwebsite/testProgram#Generative_Task-id_20260505001006_475 | None
                ', entities=[{'flbl': 'Step 4 - Biomni LLM generation iteration 1', 'exe': 'http://testwebsite/testProgram#id_20260505001006_475', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-id_20260505001006_475', 'llm_gen_out2': 'None'}])
ic| rquestion: '''
                Does any of the executions of the Step 5 - Biomni LLM generation iteration 2 function made has a Generative Task within as a component and also Step 5 - Biomni LLM generation iteration 2
                function itself is generated by a Generative Task?
                '''
ic| entities:                                          flbl  \
              0  Step 5 - Biomni LLM generation iteration 2

                                                               exe  \
              0  http://testwebsite/testProgram#id_202605050010...

                                                       llm_gen_out llm_gen_out2
              0  http://testwebsite/testProgram#Generative_Task...         None
ic| answer: GTAnswer(answer_nlp='
                1. Executions of the Step 5 - Biomni LLM generation iteration 2 function contains a Generative Task that utilize an LLM.
                2. The Step 5 - Biomni LLM generation iteration 2 function is not generated by a Generative Task.

                Function | Execution | Generative Task used within execution | Generative Task used to generate function
            Step 5 - Biomni LLM generation iteration 2 | http://testwebsite/testProgram#id_20260505001009_972 | http://testwebsite/testProgram#Generative_Task-id_20260505001009_972 | None
                ', entities=[{'flbl': 'Step 5 - Biomni LLM generation iteration 2', 'exe': 'http://testwebsite/testProgram#id_20260505001009_972', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-id_20260505001009_972', 'llm_gen_out2': 'None'}])
ic| rquestion: '''
                Does any of the executions of the Step 6 - Biomni LLM generation iteration 3 function made has a Generative Task within as a component and also Step 6 - Biomni LLM generation iteration 3
                function itself is generated by a Generative Task?
                '''
ic| entities:                                          flbl  \
              0  Step 6 - Biomni LLM generation iteration 3

                                                               exe  \
              0  http://testwebsite/testProgram#id_202605050010...

                                                       llm_gen_out llm_gen_out2
              0  http://testwebsite/testProgram#Generative_Task...         None
ic| answer: GTAnswer(answer_nlp='
                1. Executions of the Step 6 - Biomni LLM generation iteration 3 function contains a Generative Task that utilize an LLM.
                2. The Step 6 - Biomni LLM generation iteration 3 function is not generated by a Generative Task.

                Function | Execution | Generative Task used within execution | Generative Task used to generate function
            Step 6 - Biomni LLM generation iteration 3 | http://testwebsite/testProgram#id_20260505001011_890 | http://testwebsite/testProgram#Generative_Task-id_20260505001011_890 | None
                ', entities=[{'flbl': 'Step 6 - Biomni LLM generation iteration 3', 'exe': 'http://testwebsite/testProgram#id_20260505001011_890', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-id_20260505001011_890', 'llm_gen_out2': 'None'}])
ic| rquestion: '''
                Does any of the executions of the Step 8 - Biomni LLM generation iteration 4 function made has a Generative Task within as a component and also Step 8 - Biomni LLM generation iteration 4
                function itself is generated by a Generative Task?
                '''
ic| entities:                                          flbl  \
              0  Step 8 - Biomni LLM generation iteration 4

                                                               exe  \
              0  http://testwebsite/testProgram#id_202605050010...

                                                       llm_gen_out llm_gen_out2
              0  http://testwebsite/testProgram#Generative_Task...         None
ic| answer: GTAnswer(answer_nlp='
                1. Executions of the Step 8 - Biomni LLM generation iteration 4 function contains a Generative Task that utilize an LLM.
                2. The Step 8 - Biomni LLM generation iteration 4 function is not generated by a Generative Task.

                Function | Execution | Generative Task used within execution | Generative Task used to generate function
            Step 8 - Biomni LLM generation iteration 4 | http://testwebsite/testProgram#id_20260505001016_956 | http://testwebsite/testProgram#Generative_Task-id_20260505001016_956 | None
                ', entities=[{'flbl': 'Step 8 - Biomni LLM generation iteration 4', 'exe': 'http://testwebsite/testProgram#id_20260505001016_956', 'llm_gen_out': 'http://testwebsite/testProgram#Generative_Task-id_20260505001016_956', 'llm_gen_out2': 'None'}])

In [60]:
question_sparql1 = """
SELECT distinct ?obj ?lbl ?llm_gen
WHERE {
     ?obj a provone:Program .
     ?obj rdfs:label ?lbl .
     
     ?asso prov:hadPlan ?obj .
     ?exe prov:qualifiedAssociation ?asso .
     
     ?exe sio:SIO_000369 ?llm_gen .
}
"""


programs = graph_manager.query(question_sparql1).to_dict(orient="records")
template_spec = [{"func_desc":x["lbl"] , "func_desc_term":x["lbl"]} for x in programs]
template_spec;

In [61]:
# Question MULT 10 : Does any of the executions of the function contain a Generative Task within and the function itself is generated by an LLM

template_spec = template_spec[:5] if len(template_spec) > 5 else template_spec
sparql_spec = template_spec[:5] if len(template_spec) > 5 else template_spec

question_template = """
What are the inputs of the Generative Task that was a component in the executions of  the {func_desc} function?
"""

sparql_template = """
SELECT DISTINCT ?flbl ?exe ?lbl
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl .
    FILTER(REGEX(?flbl, "{func_desc_term}","i"))

    ?asso prov:hadPlan ?obj .
    ?exe prov:qualifiedAssociation ?asso .

    ?exe sio:SIO_000369 ?llm_gen .
    ?llm_gen prov:used ?llm .
    ?llm sio:SIO_000230 ?inp .
    ?inp prov:value ?lbl . 
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The inputs to the LLM used for the Generative Task in the executions of the {func_desc} function

    {answer_inst}
    """
    
    _ent = entities[['flbl', 'exe', 'lbl']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "flbl": "Function",
            'exe': "Execution",
            'lbl': "Inputs for the Generative Task used within execution"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent[['exe', 'lbl']].to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    #gt.qtype = ["multi", "entity", 'label', "SI"]
    gt.qtype = ["multi", "entity"]
gt_list.extend(gts)

ic| rquestion: '''
                What are the inputs of the Generative Task that was a component in the executions of  the Step 10 - Biomni critic review 1 function?
                '''
ic| entities:                                flbl  \
              0  Step 10 - Biomni critic review 1
              1  Step 10 - Biomni critic review 1
              2  Step 10 - Biomni critic review 1
              3  Step 10 - Biomni critic review 1

                                                               exe  \
              0  http://testwebsite/testProgram#id_202605050010...
              1  http://testwebsite/testProgram#id_202605050010...
              2  http://testwebsite/testProgram#id_202605050010...
              3  http://testwebsite/testProgram#id_202605050010...

                                                               lbl
              0  I first imported the ADMET prediction function...
              1
                              Here is a reminder of what i...
              2  ["content='Predict ADMET properties for this c...
              3  Predict ADMET properties for this compound: CC...
ic| answer: GTAnswer(answer_nlp='
                The inputs to the LLM used for the Generative Task in the executions of the Step 10 - Biomni critic review 1 function

                Function | Execution | Inputs for the Generative Task used within execution
            Step 10 - Biomni critic review 1 | http://testwebsite/testProgram#id_20260505001035_720 | I first imported the ADMET prediction function, defined the SMILES string for the compound, called the predictor, and printed the output.

            <solution>
            Dataset already downloaded in the local system...
            Drug Property Prediction Mode...
            in total: 1 drugs
            encoding drug...
            unique drugs: 1
            do not do train/test split on the data for already splitted data
            predicting...
            Research Log for ADMET Predictions:
            -------------------------------------

            Compound SMILES: CC(C)CC1=CC=C(C=C1)C(C)C(=O)O
            Predicted ADMET properties:
            - Solubility: -3.47 log mol/L
            - Lipophilicity: 0.17 (log-ratio)
            - Absorption (Caco-2 permeability): -4.89 cm/s
            - Absorption (HIA): 89.76 %
            - Absorption (Pgp Inhibitor): 39.19 %
            - Absorption (Bioavailability): 75.25 %
            - Distribution (BBB permeation): 56.93 %
            - Distribution (PPBR): 83.89 %
            - Metabolism (CYP2C19): 17.12 %
            - Metabolism (CYP2D6): 23.17 %
            - Metabolism (CYP3A4): 3.05 %
            - Metabolism (CYP1A2): 8.95 %
            - Metabolism (CYP2C9): 5.96 %
            - Excretion (Half-life): 8.05 h
            - Excretion (Clearance): 7.15 mL/min/kg
            - Clinical Toxicity: 26.06 %

            -------------------------------------
            </solution>
            Step 10 - Biomni critic review 1 | http://testwebsite/testProgram#id_20260505001035_720 |
                            Here is a reminder of what is the user requested: Predict ADMET properties for this compound: CC(C)CC1=CC=C(C=C1)C(C)C(=O)O
                            Examine the previous executions, reaosning, and solutions.
                            Critic harshly on what could be improved?
                            Be specific and constructive.
                            Think hard what are missing to solve the task.
                            No question asked, just feedbacks.

            Step 10 - Biomni critic review 1 | http://testwebsite/testProgram#id_20260505001035_720 | ["content=\'Predict ADMET properties for this compound: CC(C)CC1=CC=C(C=C1)C(C)C(=O)O\' additional_kwargs={} response_metadata={}", "content=\'<|channel|>commentary to=python code<|message|>from biomni.tool.pharmacology import predict_admet_properties\
            smiles = [\\"CC(C)CC1=CC=C(C=C1)C(C)C(=O)O\\"]\
            result = predict_admet_properties(smiles_list=smiles)\
            print(result)\' additional_kwargs={} response_metadata={}", "content=\'Each response must include thinking process followed by either <execute> or <solution> tag. But there are no tags in the current response. Please follow the instruction, fix and regenerate the response again.\' additional_kwargs={} response_metadata={}", "content=\'<|channel|>commentary to=python code<|message|># Step 1: Import function\
            from biomni.tool.pharmacology import predict_admet_properties\
            \
            # Step 2: Define SMILES list\
            smiles_list = [\\"CC(C)CC1=CC=C(C=C1)C(C)C(=O)O\\"]\
            \
            # Step 3: Call prediction\
            result = predict_admet_properties(smiles_list=smiles_list)\
            \
            # Step 4: Print result\
            print(result)\' additional_kwargs={} response_metadata={}", "content=\'Each response must include thinking process followed by either <execute> or <solution> tag. But there are no tags in the current response. Please follow the instruction, fix and regenerate the response again.\' additional_kwargs={} response_metadata={}", "content=\'I will first import the ADMET prediction function, define the SMILES string for the compound, call the predictor, and then print the result.\
            \
            <execute>\
            from biomni.tool.pharmacology import predict_admet_properties\
            \
            smiles_list = [\\"CC(C)CC1=CC=C(C=C1)C(C)C(=O)O\\"]\
            result = predict_admet_properties(smiles_list=smiles_list)\
            print(result)\
            </execute>\' additional_kwargs={} response_metadata={}", "content=\'<observation>Dataset already downloaded in the local system...\
            Dataset already downloaded in the local system...\
            Dataset already downloaded in the local system...\
            Dataset already downloaded in the local system...\
            Dataset already downloaded in the local system...\
            Dataset already downloaded in the local system...\
            Dataset already downloaded in the local system...\
            Dataset already downloaded in the local system...\
            Dataset already downloaded in the local system...\
            Dataset already downloaded in the local system...\
            Dataset already downloaded in the local system...\
            Dataset already downloaded in the local system...\
            Dataset already downloaded in the local system...\
            Dataset already downloaded in the local system...\
            Dataset already downloaded in the local system...\
            Dataset already downloaded in the local system...\
            Drug Property Prediction Mode...\
            in total: 1 drugs\
            encoding drug...\
            unique drugs: 1\
            do not do train/test split on the data for already splitted data\
            predicting...\
            Drug Property Prediction Mode...\
            in total: 1 drugs\
            encoding drug...\
            unique drugs: 1\
            do not do train/test split on the data for already splitted data\
            predicting...\
            Drug Property Prediction Mode...\
            in total: 1 drugs\
            encoding drug...\
            unique drugs: 1\
            do not do train/test split on the data for already splitted data\
            predicting...\
            Drug Property Prediction Mode...\
            in total: 1 drugs\
            encoding drug...\
            unique drugs: 1\
            do not do train/test split on the data for already splitted data\
            predicting...\
            Drug Property Prediction Mode...\
            in total: 1 drugs\
            encoding drug...\
            unique drugs: 1\
            do not do train/test split on the data for already splitted data\
            predicting...\
            Drug Property Prediction Mode...\
            in total: 1 drugs\
            encoding drug...\
            unique drugs: 1\
            do not do train/test split on the data for already splitted data\
            predicting...\
            Drug Property Prediction Mode...\
            in total: 1 drugs\
            encoding drug...\
            unique drugs: 1\
            do not do train/test split on the data for already splitted data\
            predicting...\
            Drug Property Prediction Mode...\
            in total: 1 drugs\
            encoding drug...\
            unique drugs: 1\
            do not do train/test split on the data for already splitted data\
            predicting...\
            Drug Property Prediction Mode...\
            in total: 1 drugs\
            encoding drug...\
            unique drugs: 1\
            do not do train/test split on the data for already splitted data\
            predicting...\
            Drug Property Prediction Mode...\
            in total: 1 drugs\
            encoding drug...\
            unique drugs: 1\
            do not do train/test split on the data for already splitted data\
            predicting...\
            Drug Property Prediction Mode...\
            in total: 1 drugs\
            encoding drug...\
            unique drugs: 1\
            do not do train/test split on the data for already splitted data\
            predicting...\
            Drug Property Prediction Mode...\
            in total: 1 drugs\
            encoding drug...\
            unique drugs: 1\
            do not do train/test split on the data for already splitted data\
            predicting...\
            Drug Property Prediction Mode...\
            in total: 1 drugs\
            encoding drug...\
            unique drugs: 1\
            do not do train/test split on the data for already splitted data\
            predicting...\
            Drug Property Prediction Mode...\
            in total: 1 drugs\
            encoding drug...\
            unique drugs: 1\
            do not do train/test split on the data for already splitted data\
            predicting...\
            Drug Property Prediction Mode...\
            in total: 1 drugs\
            encoding drug...\
            unique drugs: 1\
            do not do train/test split on the data for already splitted data\
            predicting...\
            Drug Property Prediction Mode...\
            in total: 1 drugs\
            encoding drug...\
            unique drugs: 1\
            do not do train/test split on the data for already splitted data\
            predicting...\
            Research Log for ADMET Predictions:\
            -------------------------------------\
            \
            Compound SMILES: CC(C)CC1=CC=C(C=C1)C(C)C(=O)O\
            Predicted ADMET properties:\
            - Solubility: -3.47 log mol/L\
            - Lipophilicity: 0.17 (log-ratio)\
            - Absorption (Caco-2 permeability): -4.89 cm/s\
            - Absorption (HIA): 89.76 %\
            - Absorption (Pgp Inhibitor): 39.19 %\
            - Absorption (Bioavailability): 75.25 %\
            - Distribution (BBB permeation): 56.93 %\
            - Distribution (PPBR): 83.89 %\
            - Metabolism (CYP2C19): 17.12 %\
            - Metabolism (CYP2D6): 23.17 %\
            - Metabolism (CYP3A4): 3.05 %\
            - Metabolism (CYP1A2): 8.95 %\
            - Metabolism (CYP2C9): 5.96 %\
            - Excretion (Half-life): 8.05 h\
            - Excretion (Clearance): 7.15 mL/min/kg\
            - Clinical Toxicity: 26.06 %\
            -------------------------------------\
            \
            </observation>\' additional_kwargs={} response_metadata={}", "content=\'\' additional_kwargs={} response_metadata={}", "content=\'Each response must include thinking process followed by either <execute> or <solution> tag. But there are no tags in the current response. Please follow the instruction, fix and regenerate the response again.\' additional_kwargs={} response_metadata={}", "content=\'I first imported the ADMET prediction function, defined the SMILES string for the compound, called the predictor, and printed the output.\
            \
            <solution>\
            Dataset already downloaded in the local system...\
            Drug Property Prediction Mode...\
            in total: 1 drugs\
            encoding drug...\
            unique drugs: 1\
            do not do train/test split on the data for already splitted data\
            predicting...\
            Research Log for ADMET Predictions:\
            -------------------------------------\
            \
            Compound SMILES: CC(C)CC1=CC=C(C=C1)C(C)C(=O)O\
            Predicted ADMET properties:\
            - Solubility: -3.47 log mol/L\
            - Lipophilicity: 0.17 (log-ratio)\
            - Absorption (Caco-2 permeability): -4.89 cm/s\
            - Absorption (HIA): 89.76 %\
            - Absorption (Pgp Inhibitor): 39.19 %\
            - Absorption (Bioavailability): 75.25 %\
            - Distribution (BBB permeation): 56.93 %\
            - Distribution (PPBR): 83.89 %\
            - Metabolism (CYP2C19): 17.12 %\
            - Metabolism (CYP2D6): 23.17 %\
            - Metabolism (CYP3A4): 3.05 %\
            - Metabolism (CYP1A2): 8.95 %\
            - Metabolism (CYP2C9): 5.96 %\
            - Excretion (Half-life): 8.05 h\
            - Excretion (Clearance): 7.15 mL/min/kg\
            - Clinical Toxicity: 26.06 %\
            \
            -------------------------------------\
            </solution>\' additional_kwargs={} response_metadata={}"]
            Step 10 - Biomni critic review 1 | http://testwebsite/testProgram#id_20260505001035_720 | Predict ADMET properties for this compound: CC(C)CC1=CC=C(C=C1)C(C)C(=O)O
                ', entities=[{'exe': 'http://testwebsite/testProgram#id_20260505001035_720', 'lbl': 'I first imported the ADMET prediction function, defined the SMILES string for the compound, called the predictor, and printed the output.

            <solution>
            Dataset already downloaded in the local system...
            Drug Property Prediction Mode...
            in total: 1 drugs
            encoding drug...
            unique drugs: 1
            do not do train/test split on the data for already splitted data
            predicting...
            Research Log for ADMET Predictions:
            -------------------------------------

            Compound SMILES: CC(C)CC1=CC=C(C=C1)C(C)C(=O)O
            Predicted ADMET properties:
            - Solubility: -3.47 log mol/L
            - Lipophilicity: 0.17 (log-ratio)
            - Absorption (Caco-2 permeability): -4.89 cm/s
            - Absorption (HIA): 89.76 %
            - Absorption (Pgp Inhibitor): 39.19 %
            - Absorption (Bioavailability): 75.25 %
            - Distribution (BBB permeation): 56.93 %
            - Distribution (PPBR): 83.89 %
            - Metabolism (CYP2C19): 17.12 %
            - Metabolism (CYP2D6): 23.17 %
            - Metabolism (CYP3A4): 3.05 %
            - Metabolism (CYP1A2): 8.95 %
            - Metabolism (CYP2C9): 5.96 %
            - Excretion (Half-life): 8.05 h
            - Excretion (Clearance): 7.15 mL/min/kg
            - Clinical Toxicity: 26.06 %

            -------------------------------------
            </solution>'}, {'exe': 'http://testwebsite/testProgram#id_20260505001035_720', 'lbl': '
                            Here is a reminder of what is the user requested: Predict ADMET properties for this compound: CC(C)CC1=CC=C(C=C1)C(C)C(=O)O
                            Examine the previous executions, reaosning, and solutions.
                            Critic harshly on what could be improved?
                            Be specific and constructive.
                            Think hard what are missing to solve the task.
                            No question asked, just feedbacks.
                            '}, {'exe': 'http://testwebsite/testProgram#id_20260505001035_720', 'lbl': '["content=\'Predict ADMET properties for this compound: CC(C)CC1=CC=C(C=C1)C(C)C(=O)O\' additional_kwargs={} response_metadata={}", "content=\'<|channel|>commentary to=python code<|message|>from biomni.tool.pharmacology import predict_admet_properties\\\
            smiles = [\\"CC(C)CC1=CC=C(C=C1)C(C)C(=O)O\\"]\\\
            result = predict_admet_properties(smiles_list=smiles)\\\
            print(result)\' additional_kwargs={} response_metadata={}", "content=\'Each response must include thinking process followed by either <execute> or <solution> tag. But there are no tags in the current response. Please follow the instruction, fix and regenerate the response again.\' additional_kwargs={} response_metadata={}", "content=\'<|channel|>commentary to=python code<|message|># Step 1: Import function\\\
            from biomni.tool.pharmacology import predict_admet_properties\\\
            \\\
            # Step 2: Define SMILES list\\\
            smiles_list = [\\"CC(C)CC1=CC=C(C=C1)C(C)C(=O)O\\"]\\\
            \\\
            # Step 3: Call prediction\\\
            result = predict_admet_properties(smiles_list=smiles_list)\\\
            \\\
            # Step 4: Print result\\\
            print(result)\' additional_kwargs={} response_metadata={}", "content=\'Each response must include thinking process followed by either <execute> or <solution> tag. But there are no tags in the current response. Please follow the instruction, fix and regenerate the response again.\' additional_kwargs={} response_metadata={}", "content=\'I will first import the ADMET prediction function, define the SMILES string for the compound, call the predictor, and then print the result.\\\
            \\\
            <execute>\\\
            from biomni.tool.pharmacology import predict_admet_properties\\\
            \\\
            smiles_list = [\\"CC(C)CC1=CC=C(C=C1)C(C)C(=O)O\\"]\\\
            result = predict_admet_properties(smiles_list=smiles_list)\\\
            print(result)\\\
            </execute>\' additional_kwargs={} response_metadata={}", "content=\'<observation>Dataset already downloaded in the local system...\\\
            Dataset already downloaded in the local system...\\\
            Dataset already downloaded in the local system...\\\
            Dataset already downloaded in the local system...\\\
            Dataset already downloaded in the local system...\\\
            Dataset already downloaded in the local system...\\\
            Dataset already downloaded in the local system...\\\
            Dataset already downloaded in the local system...\\\
            Dataset already downloaded in the local system...\\\
            Dataset already downloaded in the local system...\\\
            Dataset already downloaded in the local system...\\\
            Dataset already downloaded in the local system...\\\
            Dataset already downloaded in the local system...\\\
            Dataset already downloaded in the local system...\\\
            Dataset already downloaded in the local system...\\\
            Dataset already downloaded in the local system...\\\
            Drug Property Prediction Mode...\\\
            in total: 1 drugs\\\
            encoding drug...\\\
            unique drugs: 1\\\
            do not do train/test split on the data for already splitted data\\\
            predicting...\\\
            Drug Property Prediction Mode...\\\
            in total: 1 drugs\\\
            encoding drug...\\\
            unique drugs: 1\\\
            do not do train/test split on the data for already splitted data\\\
            predicting...\\\
            Drug Property Prediction Mode...\\\
            in total: 1 drugs\\\
            encoding drug...\\\
            unique drugs: 1\\\
            do not do train/test split on the data for already splitted data\\\
            predicting...\\\
            Drug Property Prediction Mode...\\\
            in total: 1 drugs\\\

In [62]:
# Question MULT 11 :


template_spec = template_spec[:5] if len(template_spec) > 5 else template_spec
sparql_spec = template_spec[:5] if len(template_spec) > 5 else template_spec

question_template = """
What are the outputs of the Generative Task that was a component in the executions of the {func_desc} function?
"""

sparql_template = """
SELECT DISTINCT ?flbl ?exe ?lbl
WHERE {
    ?obj dc:description ?desc .
    ?obj rdfs:label ?flbl .
    FILTER(REGEX(?flbl, "{func_desc_term}","i"))

    ?asso prov:hadPlan ?obj .
    ?exe prov:qualifiedAssociation ?asso .

    ?exe sio:SIO_000369 ?llm_gen .
    ?llm_gen prov:used ?llm .
    ?llm sio:SIO_000229 ?out .
    ?out sio:SIO_000202 ?data . 
    ?data prov:value ?lbl . 
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The inputs to the LLM used for the Generative Task in the executions of the {func_desc} function

    {answer_inst}
    """
    
    _ent = entities[['flbl', 'exe', 'lbl']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            "flbl": "Function",
            'exe': "Execution",
            'lbl': "Inputs for the Generative Task used within execution"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        func_desc = question_specs["func_desc"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    #gt.qtype = ["multi", "entity", 'label', "ISP"]
    gt.qtype = ["multi", "entity"]
gt_list.extend(gts)

ic| rquestion: '''
                What are the outputs of the Generative Task that was a component in the executions of the Step 10 - Biomni critic review 1 function?
                '''
ic| entities:                                flbl  \
              0  Step 10 - Biomni critic review 1
              1  Step 10 - Biomni critic review 1

                                                               exe  \
              0  http://testwebsite/testProgram#id_202605050010...
              1  http://testwebsite/testProgram#id_202605050010...

                                                               lbl
              0                                           generate
              1  **Critical Review of the Previous Response**
              ...
ic| answer: GTAnswer(answer_nlp='
                The inputs to the LLM used for the Generative Task in the executions of the Step 10 - Biomni critic review 1 function

                Function | Execution | Inputs for the Generative Task used within execution
            Step 10 - Biomni critic review 1 | http://testwebsite/testProgram#id_20260505001035_720 | generate
            Step 10 - Biomni critic review 1 | http://testwebsite/testProgram#id_20260505001035_720 | **Critical Review of the Previous Response**

            | Aspect | Current State | Issues Identified | Recommendations |
            |--------|---------------|------------------|-----------------|
            | **Adherence to Instruction** | The response contained a `<solution>` tag, but omitted an explicit *thinking process* section before it. | The user explicitly requested that each answer include a “thinking process” followed by either `<execute>` or `<solution>`. This step was missing, violating the instruction hierarchy. | Add a concise “Thinking Process” paragraph at the beginning of the reply. |
            | **Clarity & Structure** | The output is largely a raw log dump from the tool, interspersed with repetitive lines (“Dataset already downloaded…”). | The user likely expects a clean summary rather than debugging logs. | Filter out or summarize boilerplate logs; present only the key predicted values in a tidy table or bullet list. |
            | **Formatting** | Mixed plain text and code block, but no clear separation of code execution from result. | The `<solution>` tag should enclose only the final answer, not the entire log trace. | Wrap only the final, cleaned‑up ADMET summary inside `<solution>`. Keep any execution logs outside or within a separate `<commentary>` section if needed. |
            | **Completeness** | Predicted values were provided but without units or context (e.g., “Solubility: -3.47 log mol/L” is fine, but others like “Absorption (Caco‑2 permeability): -4.89 cm/s” may need clarification). | Some parameters lack explanation of what they mean; the user might benefit from a brief interpretation. | Add short descriptors or a footnote explaining each property’s relevance (e.g., high HIA % indicates good absorption). |
            | **User Intent** | The user wanted ADMET predictions for a specific compound. | The response includes many repeated lines that do not add value and could confuse the user. | Remove redundant execution logs; keep only the final predictive output. |
            | **Technical Accuracy** | Assuming the tool’s output is correct, but no verification step was shown. | No mention of potential uncertainties or confidence intervals associated with predictions. | Acknowledge that these are in silico estimates and may vary from experimental data. |

            ---

            ### Specific Constructive Actions

            1. **Add a “Thinking Process” Section**
               ```text
               Thinking Process:
               1. Import the ADMET prediction module.
               2. Define the SMILES string for the target compound.
               3. Call the predictor and capture its output.
               4. Extract key properties and format them succinctly.
               ```

            2. **Clean Up Output**
               - Strip out repetitive “Dataset already downloaded” lines.
               - Present predictions in a clear table:
                 | Property | Value |
                 |----------|-------|
                 | Solubility (log\u202fS) | –3.47 |
                 | Lipophilicity (LogP) | 0.17 |
                 | ... | ... |

            3. **Use `<solution>` Only for Final Summary**
               ```text
               <solution>
               ADMET predictions for CC(C)CC1=CC=C(C=C1)C(C)C(=O)O:
               ...

                ', entities=[{'flbl': 'Step 10 - Biomni critic review 1', 'exe': 'http://testwebsite/testProgram#id_20260505001035_720', 'lbl': 'generate'}, {'flbl': 'Step 10 - Biomni critic review 1', 'exe': 'http://testwebsite/testProgram#id_20260505001035_720', 'lbl': '**Critical Review of the Previous Response**

            | Aspect | Current State | Issues Identified | Recommendations |
            |--------|---------------|------------------|-----------------|
            | **Adherence to Instruction** | The response contained a `<solution>` tag, but omitted an explicit *thinking process* section before it. | The user explicitly requested that each answer include a “thinking process” followed by either `<execute>` or `<solution>`. This step was missing, violating the instruction hierarchy. | Add a concise “Thinking Process” paragraph at the beginning of the reply. |
            | **Clarity & Structure** | The output is largely a raw log dump from the tool, interspersed with repetitive lines (“Dataset already downloaded…”). | The user likely expects a clean summary rather than debugging logs. | Filter out or summarize boilerplate logs; present only the key predicted values in a tidy table or bullet list. |
            | **Formatting** | Mixed plain text and code block, but no clear separation of code execution from result. | The `<solution>` tag should enclose only the final answer, not the entire log trace. | Wrap only the final, cleaned‑up ADMET summary inside `<solution>`. Keep any execution logs outside or within a separate `<commentary>` section if needed. |
            | **Completeness** | Predicted values were provided but without units or context (e.g., “Solubility: -3.47 log mol/L” is fine, but others like “Absorption (Caco‑2 permeability): -4.89 cm/s” may need clarification). | Some parameters lack explanation of what they mean; the user might benefit from a brief interpretation. | Add short descriptors or a footnote explaining each property’s relevance (e.g., high HIA % indicates good absorption). |
            | **User Intent** | The user wanted ADMET predictions for a specific compound. | The response includes many repeated lines that do not add value and could confuse the user. | Remove redundant execution logs; keep only the final predictive output. |
            | **Technical Accuracy** | Assuming the tool’s output is correct, but no verification step was shown. | No mention of potential uncertainties or confidence intervals associated with predictions. | Acknowledge that these are in silico estimates and may vary from experimental data. |

            ---

            ### Specific Constructive Actions

            1. **Add a “Thinking Process” Section**
               ```text
               Thinking Process:
               1. Import the ADMET prediction module.
               2. Define the SMILES string for the target compound.
               3. Call the predictor and capture its output.
               4. Extract key properties and format them succinctly.
               ```

            2. **Clean Up Output**
               - Strip out repetitive “Dataset already downloaded” lines.
               - Present predictions in a clear table:
                 | Property | Value |
                 |----------|-------|
                 | Solubility (log\u202fS) | –3.47 |
                 | Lipophilicity (LogP) | 0.17 |
                 | ... | ... |

            3. **Use `<solution>` Only for Final Summary**
               ```text
               <solution>
               ADMET predictions for CC(C)CC1=CC=C(C=C1)C(C)C(=O)O:
               ...
               '}])
ic| rquestion: '''
                What are the outputs of the Generative Task that was a component in the executions of the Step 4 - Biomni LLM generation iteration 1 function?
                '''
ic| entities:                                          flbl  \
              0  Step 4 - Biomni LLM generation iteration 1
              1  Step 4 - Biomni LLM generation iteration 1

                                                               exe  \
              0  http://testwebsite/testProgram#id_202605050010...
              1  http://testwebsite/testProgram#id_202605050010...

                                                               lbl
              0                                           generate
              1  <|channel|>commentary to=python code<|message|...
ic| answer: GTAnswer(answer_nlp='
                The inputs to the LLM used for the Generative Task in the executions of the Step 4 - Biomni LLM generation iteration 1 function

                Function | Execution | Inputs for the Generative Task used within execution
            Step 4 - Biomni LLM generation iteration 1 | http://testwebsite/testProgram#id_20260505001006_475 | generate
            Step 4 - Biomni LLM generation iteration 1 | http://testwebsite/testProgram#id_20260505001006_475 | <|channel|>commentary to=python code<|message|>from biomni.tool.pharmacology import predict_admet_properties
            smiles = ["CC(C)CC1=CC=C(C=C1)C(C)C(=O)O"]
            result = predict_admet_properties(smiles_list=smiles)
            print(result)
                ', entities=[{'flbl': 'Step 4 - Biomni LLM generation iteration 1', 'exe': 'http://testwebsite/testProgram#id_20260505001006_475', 'lbl': 'generate'}, {'flbl': 'Step 4 - Biomni LLM generation iteration 1', 'exe': 'http://testwebsite/testProgram#id_20260505001006_475', 'lbl': '<|channel|>commentary to=python code<|message|>from biomni.tool.pharmacology import predict_admet_properties
            smiles = ["CC(C)CC1=CC=C(C=C1)C(C)C(=O)O"]
            result = predict_admet_properties(smiles_list=smiles)
            print(result)'}])
ic| rquestion: '''
                What are the outputs of the Generative Task that was a component in the executions of the Step 5 - Biomni LLM generation iteration 2 function?
                '''
ic| entities:                                          flbl  \
              0  Step 5 - Biomni LLM generation iteration 2
              1  Step 5 - Biomni LLM generation iteration 2

                                                               exe  \
              0  http://testwebsite/testProgram#id_202605050010...
              1  http://testwebsite/testProgram#id_202605050010...

                                                               lbl
              0                                           generate
              1  <|channel|>commentary to=python code<|message|...
ic| answer: GTAnswer(answer_nlp='
                The inputs to the LLM used for the Generative Task in the executions of the Step 5 - Biomni LLM generation iteration 2 function

                Function | Execution | Inputs for the Generative Task used within execution
            Step 5 - Biomni LLM generation iteration 2 | http://testwebsite/testProgram#id_20260505001009_972 | generate
            Step 5 - Biomni LLM generation iteration 2 | http://testwebsite/testProgram#id_20260505001009_972 | <|channel|>commentary to=python code<|message|># Step 1: Import function
            from biomni.tool.pharmacology import predict_admet_properties

            # Step 2: Define SMILES list
            smiles_list = ["CC(C)CC1=CC=C(C=C1)C(C)C(=O)O"]

            # Step 3: Call prediction
            result = predict_admet_properties(smiles_list=smiles_list)

            # Step 4: Print result
            print(result)
                ', entities=[{'flbl': 'Step 5 - Biomni LLM generation iteration 2', 'exe': 'http://testwebsite/testProgram#id_20260505001009_972', 'lbl': 'generate'}, {'flbl': 'Step 5 - Biomni LLM generation iteration 2', 'exe': 'http://testwebsite/testProgram#id_20260505001009_972', 'lbl': '<|channel|>commentary to=python code<|message|># Step 1: Import function
            from biomni.tool.pharmacology import predict_admet_properties

            # Step 2: Define SMILES list
            smiles_list = ["CC(C)CC1=CC=C(C=C1)C(C)C(=O)O"]

            # Step 3: Call prediction
            result = predict_admet_properties(smiles_list=smiles_list)

            # Step 4: Print result
            print(result)'}])
ic| rquestion: '''
                What are the outputs of the Generative Task that was a component in the executions of the Step 6 - Biomni LLM generation iteration 3 function?
                '''
ic| entities:                                          flbl  \
              0  Step 6 - Biomni LLM generation iteration 3
              1  Step 6 - Biomni LLM generation iteration 3

                                                               exe  \
              0  http://testwebsite/testProgram#id_202605050010...
              1  http://testwebsite/testProgram#id_202605050010...

                                                               lbl
              0                                            execute
              1  I will first import the ADMET prediction funct...
ic| answer: GTAnswer(answer_nlp='
                The inputs to the LLM used for the Generative Task in the executions of the Step 6 - Biomni LLM generation iteration 3 function

                Function | Execution | Inputs for the Generative Task used within execution
            Step 6 - Biomni LLM generation iteration 3 | http://testwebsite/testProgram#id_20260505001011_890 | execute
            Step 6 - Biomni LLM generation iteration 3 | http://testwebsite/testProgram#id_20260505001011_890 | I will first import the ADMET prediction function, define the SMILES string for the compound, call the predictor, and then print the result.

            <execute>
            from biomni.tool.pharmacology import predict_admet_properties

            smiles_list = ["CC(C)CC1=CC=C(C=C1)C(C)C(=O)O"]
            result = predict_admet_properties(smiles_list=smiles_list)
            print(result)
            </execute>
                ', entities=[{'flbl': 'Step 6 - Biomni LLM generation iteration 3', 'exe': 'http://testwebsite/testProgram#id_20260505001011_890', 'lbl': 'execute'}, {'flbl': 'Step 6 - Biomni LLM generation iteration 3', 'exe': 'http://testwebsite/testProgram#id_20260505001011_890', 'lbl': 'I will first import the ADMET prediction function, define the SMILES string for the compound, call the predictor, and then print the result.

            <execute>
            from biomni.tool.pharmacology import predict_admet_properties

            smiles_list = ["CC(C)CC1=CC=C(C=C1)C(C)C(=O)O"]
            result = predict_admet_properties(smiles_list=smiles_list)
            print(result)
            </execute>'}])
ic| rquestion: '''
                What are the outputs of the Generative Task that was a component in the executions of the Step 8 - Biomni LLM generation iteration 4 function?
                '''
ic| entities:                                          flbl  \
              0  Step 8 - Biomni LLM generation iteration 4
              1  Step 8 - Biomni LLM generation iteration 4

                                                               exe       lbl
              0  http://testwebsite/testProgram#id_202605050010...  generate
              1  http://testwebsite/testProgram#id_202605050010...
ic| answer: GTAnswer(answer_nlp='
                The inputs to the LLM used for the Generative Task in the executions of the Step 8 - Biomni LLM generation iteration 4 function

                Function | Execution | Inputs for the Generative Task used within execution
            Step 8 - Biomni LLM generation iteration 4 | http://testwebsite/testProgram#id_20260505001016_956 | generate
            Step 8 - Biomni LLM generation iteration 4 | http://testwebsite/testProgram#id_20260505001016_956 |
                ', entities=[{'flbl': 'Step 8 - Biomni LLM generation iteration 4', 'exe': 'http://testwebsite/testProgram#id_20260505001016_956', 'lbl': 'generate'}, {'flbl': 'Step 8 - Biomni LLM generation iteration 4', 'exe': 'http://testwebsite/testProgram#id_20260505001016_956', 'lbl': ''}])

In [63]:
# Question MULT 11 :

_spec = template_spec[:5] if len(template_spec) > 5 else template_spec

template_spec = []
sparql_spec = []

for _s in _spec:
    exe_query = """
    SELECT DISTINCT ?exe
    WHERE {
        ?obj dc:description ?desc .
        ?obj rdfs:label ?flbl .
        FILTER(REGEX(?flbl, "{func_desc_term}","i"))
        
        ?asso prov:hadPlan ?obj .
        ?exe prov:qualifiedAssociation ?asso .      
        
        }
    """
    executions = graph_manager.query(
        regex_add_strings(exe_query, func_desc_term = _s["func_desc_term"])
    )


    for obj in executions.to_dict("records"):
        template_spec.append({
            "exe_id":obj['exe']
        })
        
        sparql_spec.append({
            "exe_id":obj['exe']
        })

question_template = """
What execution created the output data that was used as an input for the generative task within the execution "{exe_id}"?
"""

sparql_template = """
SELECT DISTINCT ?exe2
    WHERE {
        <{exe_id}> sio:SIO_000369 ?llm_gen .
        ?llm_gen prov:used ?llm .
        ?llm sio:SIO_000229 ?out .
        ?out sio:SIO_000202 ?data . 
        ?data prov:wasGeneratedBy ?exe2 . 
}
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The inputs to the Generative Task in the execution of "{exe_id}" was generated by executions

    {answer_inst}
    """
    
    _ent = entities[['exe2']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            'exe2': "Execution"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        exe_id = question_specs["exe_id"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    #gt.qtype = ["multi", "entity", 'label', "ISP"]
    gt.qtype = ["multi", "entity"]
gt_list.extend(gts)

ic| rquestion: '''
                What execution created the output data that was used as an input for the generative task within the execution "http://testwebsite/testProgram#id_20260505001035_720"?
                '''
ic| entities:                                                 exe2
              0  http://testwebsite/testProgram#id_202605050010...
              1  http://testwebsite/testProgram#id_202605050010...
ic| answer: GTAnswer(answer_nlp='
                The inputs to the Generative Task in the execution of "http://testwebsite/testProgram#id_20260505001035_720" was generated by executions

                Execution
            http://testwebsite/testProgram#id_20260505001035_720
            http://testwebsite/testProgram#id_20260505001037_336
                ', entities=[{'exe2': 'http://testwebsite/testProgram#id_20260505001035_720'}, {'exe2': 'http://testwebsite/testProgram#id_20260505001037_336'}])
ic| rquestion: '''
                What execution created the output data that was used as an input for the generative task within the execution "http://testwebsite/testProgram#id_20260505001006_475"?
                '''
ic| entities:                                                 exe2
              0  http://testwebsite/testProgram#id_202605050010...
              1  http://testwebsite/testProgram#id_202605050010...
ic| answer: GTAnswer(answer_nlp='
                The inputs to the Generative Task in the execution of "http://testwebsite/testProgram#id_20260505001006_475" was generated by executions

                Execution
            http://testwebsite/testProgram#id_20260505001006_475
            http://testwebsite/testProgram#id_20260505001009_972
                ', entities=[{'exe2': 'http://testwebsite/testProgram#id_20260505001006_475'}, {'exe2': 'http://testwebsite/testProgram#id_20260505001009_972'}])
ic| rquestion: '''
                What execution created the output data that was used as an input for the generative task within the execution "http://testwebsite/testProgram#id_20260505001009_972"?
                '''
ic| entities:                                                 exe2
              0  http://testwebsite/testProgram#id_202605050010...
              1  http://testwebsite/testProgram#id_202605050010...
ic| answer: GTAnswer(answer_nlp='
                The inputs to the Generative Task in the execution of "http://testwebsite/testProgram#id_20260505001009_972" was generated by executions

                Execution
            http://testwebsite/testProgram#id_20260505001009_972
            http://testwebsite/testProgram#id_20260505001011_890
                ', entities=[{'exe2': 'http://testwebsite/testProgram#id_20260505001009_972'}, {'exe2': 'http://testwebsite/testProgram#id_20260505001011_890'}])
ic| rquestion: '''
                What execution created the output data that was used as an input for the generative task within the execution "http://testwebsite/testProgram#id_20260505001011_890"?
                '''
ic| entities:                                                 exe2
              0  http://testwebsite/testProgram#id_202605050010...
              1  http://testwebsite/testProgram#id_202605050010...
ic| answer: GTAnswer(answer_nlp='
                The inputs to the Generative Task in the execution of "http://testwebsite/testProgram#id_20260505001011_890" was generated by executions

                Execution
            http://testwebsite/testProgram#id_20260505001011_890
            http://testwebsite/testProgram#id_20260505001013_746
                ', entities=[{'exe2': 'http://testwebsite/testProgram#id_20260505001011_890'}, {'exe2': 'http://testwebsite/testProgram#id_20260505001013_746'}])
ic| rquestion: '''
                What execution created the output data that was used as an input for the generative task within the execution "http://testwebsite/testProgram#id_20260505001016_956"?
                '''
ic| entities:                                                 exe2
              0  http://testwebsite/testProgram#id_202605050010...
              1  http://testwebsite/testProgram#id_202605050010...
ic| answer: GTAnswer(answer_nlp='
                The inputs to the Generative Task in the execution of "http://testwebsite/testProgram#id_20260505001016_956" was generated by executions

                Execution
            http://testwebsite/testProgram#id_20260505001016_956
            http://testwebsite/testProgram#id_20260505001023_688
                ', entities=[{'exe2': 'http://testwebsite/testProgram#id_20260505001016_956'}, {'exe2': 'http://testwebsite/testProgram#id_20260505001023_688'}])

In [64]:
question_sparql1 = """
SELECT distinct ?obj ?lbl ?llm_gen
WHERE {
     ?obj a provone:Program .
     ?obj rdfs:label ?lbl .
     
     ?asso prov:hadPlan ?obj .
     ?exe prov:qualifiedAssociation ?asso .
     
     ?exe sio:SIO_000369 ?llm_gen .
}
"""


programs = graph_manager.query(question_sparql1).to_dict(orient="records")
template_spec = [{"func_desc":x["lbl"] , "func_desc_term":x["lbl"]} for x in programs]
template_spec;

In [65]:
# Question MULT 12 :

_spec = template_spec[:5] if len(template_spec) > 5 else template_spec

template_spec = []
sparql_spec = []

for _s in _spec:
    exe_query = """
    SELECT DISTINCT ?exe
    WHERE {
        ?obj dc:description ?desc .
        ?obj rdfs:label ?flbl .
        FILTER(REGEX(?flbl, "{func_desc_term}","i"))
        
        ?asso prov:hadPlan ?obj .
        ?exe prov:qualifiedAssociation ?asso .      
        
        }
    """
    executions = graph_manager.query(
        regex_add_strings(exe_query, func_desc_term = _s["func_desc_term"])
    )


    for obj in executions.to_dict("records"):
        template_spec.append({
            "exe_id":obj['exe']
        })
        
        sparql_spec.append({
            "exe_id":obj['exe']
        })

question_template = """
The execution "{exe_id}" used data were created by what Generative Task?
"""

sparql_template = """
SELECT DISTINCT ?gtask ?glbl
            WHERE {
                <{exe_id}> prov:used ?data .
                ?llm_out sio:SIO_000202 ?data .
                ?llm_out sio:SIO_000232 ?llm .
                ?gtask prov:used ?llm .
                ?gtask rdfs:label ?glbl
        }
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The Generative Task that generated the data that was used by the execution "{exe_id}" is 

    {answer_inst}
    """
    
    _ent = entities[['gtask', 'glbl']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            'gtask': "Generative Task"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        exe_id = question_specs["exe_id"],
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent[['gtask']].to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    #gt.qtype = ["single", "entity", "ISP"]
    gt.qtype = ["single", "entity"]
gt_list.extend(gts)

ic| rquestion: '''
                The execution "http://testwebsite/testProgram#id_20260505001035_720" used data were created by what Generative Task?
                '''
ic| entities:                                                gtask  \
              0  http://testwebsite/testProgram#Generative_Task...
              1  http://testwebsite/testProgram#Generative_Task...

                                                              glbl
              0  Step 9 - Biomni LLM use for generation iterati...
              1    Step 9 - generation iteration 5 generative task
ic| answer: GTAnswer(answer_nlp='
                The Generative Task that generated the data that was used by the execution "http://testwebsite/testProgram#id_20260505001035_720" is

                Generative Task | glbl
            http://testwebsite/testProgram#Generative_Task-id_20260505001023_688 | Step 9 - Biomni LLM use for generation iteration 5
            http://testwebsite/testProgram#Generative_Task-id_20260505001023_688 | Step 9 - generation iteration 5 generative task
                ', entities=[{'gtask': 'http://testwebsite/testProgram#Generative_Task-id_20260505001023_688'}, {'gtask': 'http://testwebsite/testProgram#Generative_Task-id_20260505001023_688'}])
ic| rquestion: '''
                The execution "http://testwebsite/testProgram#id_20260505001006_475" used data were created by what Generative Task?
                '''
ic| entities: Empty DataFrame
              Columns: [gtask, glbl]
              Index: []
ic| answer: GTAnswer(answer_nlp='
                The Generative Task that generated the data that was used by the execution "http://testwebsite/testProgram#id_20260505001006_475" is

                Generative Task | glbl
                ', entities=[])
ic| rquestion: '''
                The execution "http://testwebsite/testProgram#id_20260505001009_972" used data were created by what Generative Task?
                '''
ic| entities:                                                gtask  \
              0  http://testwebsite/testProgram#Generative_Task...
              1  http://testwebsite/testProgram#Generative_Task...

                                                              glbl
              0  Step 4 - Biomni LLM use for generation iterati...
              1    Step 4 - generation iteration 1 generative task
ic| answer: GTAnswer(answer_nlp='
                The Generative Task that generated the data that was used by the execution "http://testwebsite/testProgram#id_20260505001009_972" is

                Generative Task | glbl
            http://testwebsite/testProgram#Generative_Task-id_20260505001006_475 | Step 4 - Biomni LLM use for generation iteration 1
            http://testwebsite/testProgram#Generative_Task-id_20260505001006_475 | Step 4 - generation iteration 1 generative task
                ', entities=[{'gtask': 'http://testwebsite/testProgram#Generative_Task-id_20260505001006_475'}, {'gtask': 'http://testwebsite/testProgram#Generative_Task-id_20260505001006_475'}])
ic| rquestion: '''
                The execution "http://testwebsite/testProgram#id_20260505001011_890" used data were created by what Generative Task?
                '''
ic| entities:                                                gtask  \
              0  http://testwebsite/testProgram#Generative_Task...
              1  http://testwebsite/testProgram#Generative_Task...

                                                              glbl
              0  Step 5 - Biomni LLM use for generation iterati...
              1    Step 5 - generation iteration 2 generative task
ic| answer: GTAnswer(answer_nlp='
                The Generative Task that generated the data that was used by the execution "http://testwebsite/testProgram#id_20260505001011_890" is

                Generative Task | glbl
            http://testwebsite/testProgram#Generative_Task-id_20260505001009_972 | Step 5 - Biomni LLM use for generation iteration 2
            http://testwebsite/testProgram#Generative_Task-id_20260505001009_972 | Step 5 - generation iteration 2 generative task
                ', entities=[{'gtask': 'http://testwebsite/testProgram#Generative_Task-id_20260505001009_972'}, {'gtask': 'http://testwebsite/testProgram#Generative_Task-id_20260505001009_972'}])
ic| rquestion: '''
                The execution "http://testwebsite/testProgram#id_20260505001016_956" used data were created by what Generative Task?
                '''
ic| entities: Empty DataFrame
              Columns: [gtask, glbl]
              Index: []
ic| answer: GTAnswer(answer_nlp='
                The Generative Task that generated the data that was used by the execution "http://testwebsite/testProgram#id_20260505001016_956" is

                Generative Task | glbl
                ', entities=[])

In [66]:
question_sparql1 = """
SELECT distinct ?obj ?lbl
WHERE {
     ?obj a provone:Program .
     ?obj rdfs:label ?lbl .
}
"""


programs = graph_manager.query(question_sparql1).to_dict(orient="records")
template_spec = [{"func_desc":x["lbl"] , "func_desc_term":x["lbl"]} for x in programs]
template_spec;

In [67]:
# Input port data created by AI 

_spec = template_spec[:5] if len(template_spec) > 5 else template_spec

template_spec = []
sparql_spec = []

for _s in _spec:
    exe_query = """
    SELECT DISTINCT ?exe
    WHERE {
        ?obj dc:description ?desc .
        ?obj rdfs:label ?flbl .
        FILTER(REGEX(?flbl, "{func_desc_term}","i"))
        
        ?asso prov:hadPlan ?obj .
        ?exe prov:qualifiedAssociation ?asso .      
        
        }
    """
    executions = graph_manager.query(
        regex_add_strings(exe_query, func_desc_term = _s["func_desc_term"])
    )


    for obj in executions.to_dict("records"):
        usage_query = """
        SELECT DISTINCT ?usage ?lbl
        WHERE {
            <{exe_id}> prov:qualifiedUsage ?usage .
            ?usage provone:hadInPort ?port .
            ?port rdfs:label ?lbl .
            }
        """
        usages = graph_manager.query(
                regex_add_strings(
                    usage_query,
                    exe_id = obj["exe"]
                )
            )
        
        for usage in usages.to_dict("records"):
            # df = graph_manager.query(
            #     regex_add_strings(
            #         sparql_template,
            #         exe_id = obj["exe"],
            #         port_label = usage["lbl"].split("@")[0]
            #     )
            # )

            # print(df)
            
            template_spec.append({
                "exe_id":obj['exe'],
                "port_label" : usage["lbl"].split("@")[0]
            })
            
            sparql_spec.append({
                "exe_id":obj['exe'],
                "port_label" : usage["lbl"].split("@")[0]
            })
            
question_template = """
Was the input to the "{port_label}" in the execution "{exe_id}" generated by a Generative Task?
"""

sparql_template = """
SELECT DISTINCT ?plbl ?gtask2
            WHERE {
                <{exe_id}> prov:qualifiedUsage ?usage .
                ?usage provone:hadInPort ?port .
                ?port rdfs:label ?plbl .
                FILTER(REGEX(?plbl, "{port_label}","i"))
                
                ?usage provone:hadEntity ?data .
                OPTIONAL {
                    ?llm_out sio:SIO_000202 ?data .
                    ?llm_out sio:SIO_000232 ?llm .
                    ?gtask prov:used ?llm .
                }
                
                BIND(COALESCE(?gtask, "None") AS ?gtask2)
        }
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The input to the "{port_label}" in the execution "{exe_id}" {decision} generated by a 
    Generative Task

    {answer_inst}
    """
    
    _ent = entities[['gtask2']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            'gtask2': "Generative Task"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        exe_id = question_specs["exe_id"],
        port_label = question_specs["port_label"],
        decision = "was" if _ent['gtask2'].tolist()[0] != "None" else "was not",
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    #gt.qtype = ["single", "bool", "ISP"]
    gt.qtype = ["single", "bool"]
    gt.decision = gt.entities[0]['gtask2'] != "None"
gt_list.extend(gts)

ic| rquestion: '''
                Was the input to the "Step 10 - critic prompt input" in the execution "http://testwebsite/testProgram#id_20260505001035_720" generated by a Generative Task?
                '''
ic| entities:                             plbl gtask2
              0  Step 10 - critic prompt input   None
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 10 - critic prompt input" in the execution "http://testwebsite/testProgram#id_20260505001035_720" was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the "Step 10 - feedback_prompt input port for critic review 1" in the execution "http://testwebsite/testProgram#id_20260505001035_720" generated by a Generative Task?
                '''
ic| entities:                                                 plbl gtask2
              0  Step 10 - feedback_prompt input port for criti...   None
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 10 - feedback_prompt input port for critic review 1" in the execution "http://testwebsite/testProgram#id_20260505001035_720" was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the "Step 10 - candidate solution input" in the execution "http://testwebsite/testProgram#id_20260505001035_720" generated by a Generative Task?
                '''
ic| entities:                                  plbl  \
              0  Step 10 - candidate solution input

                                                            gtask2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 10 - candidate solution input" in the execution "http://testwebsite/testProgram#id_20260505001035_720" was generated by a
                Generative Task

                Generative Task
            http://testwebsite/testProgram#Generative_Task-id_20260505001023_688
                ', entities=[{'gtask2': 'http://testwebsite/testProgram#Generative_Task-id_20260505001023_688'}])
ic| rquestion: '''
                Was the input to the "Step 10 - candidate_solution input port for critic review 1" in the execution "http://testwebsite/testProgram#id_20260505001035_720" generated by a Generative Task?
                '''
ic| entities:                                                 plbl  \
              0  Step 10 - candidate_solution input port for cr...

                                                            gtask2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 10 - candidate_solution input port for critic review 1" in the execution "http://testwebsite/testProgram#id_20260505001035_720" was generated by a
                Generative Task

                Generative Task
            http://testwebsite/testProgram#Generative_Task-id_20260505001023_688
                ', entities=[{'gtask2': 'http://testwebsite/testProgram#Generative_Task-id_20260505001023_688'}])
ic| rquestion: '''
                Was the input to the "Step 10 - conversation history input" in the execution "http://testwebsite/testProgram#id_20260505001035_720" generated by a Generative Task?
                '''
ic| entities:                                    plbl gtask2
              0  Step 10 - conversation history input   None
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 10 - conversation history input" in the execution "http://testwebsite/testProgram#id_20260505001035_720" was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the "Step 10 - message_history input port for critic review 1" in the execution "http://testwebsite/testProgram#id_20260505001035_720" generated by a Generative Task?
                '''
ic| entities:                                                 plbl gtask2
              0  Step 10 - message_history input port for criti...   None
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 10 - message_history input port for critic review 1" in the execution "http://testwebsite/testProgram#id_20260505001035_720" was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the "Step 10 - original user task input" in the execution "http://testwebsite/testProgram#id_20260505001035_720" generated by a Generative Task?
                '''
ic| entities:                                  plbl gtask2
              0  Step 10 - original user task input   None
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 10 - original user task input" in the execution "http://testwebsite/testProgram#id_20260505001035_720" was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the "Step 10 - user_task input port for critic review 1" in the execution "http://testwebsite/testProgram#id_20260505001035_720" generated by a Generative Task?
                '''
ic| entities:                                                 plbl gtask2
              0  Step 10 - user_task input port for critic revi...   None
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 10 - user_task input port for critic review 1" in the execution "http://testwebsite/testProgram#id_20260505001035_720" was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the "Step 4 - agent state message input" in the execution "http://testwebsite/testProgram#id_20260505001006_475" generated by a Generative Task?
                '''
ic| entities:                                  plbl gtask2
              0  Step 4 - agent state message input   None
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 4 - agent state message input" in the execution "http://testwebsite/testProgram#id_20260505001006_475" was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the "Step 4 - message input port for generation iteration 1" in the execution "http://testwebsite/testProgram#id_20260505001006_475" generated by a Generative Task?
                '''
ic| entities:                                                 plbl gtask2
              0  Step 4 - message input port for generation ite...   None
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 4 - message input port for generation iteration 1" in the execution "http://testwebsite/testProgram#id_20260505001006_475" was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the "Step 4 - system prompt input" in the execution "http://testwebsite/testProgram#id_20260505001006_475" generated by a Generative Task?
                '''
ic| entities:                            plbl gtask2
              0  Step 4 - system prompt input   None
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 4 - system prompt input" in the execution "http://testwebsite/testProgram#id_20260505001006_475" was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the "Step 4 - system_prompt input port for generation iteration 1" in the execution "http://testwebsite/testProgram#id_20260505001006_475" generated by a Generative Task?
                '''
ic| entities:                                                 plbl gtask2
              0  Step 4 - system_prompt input port for generati...   None
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 4 - system_prompt input port for generation iteration 1" in the execution "http://testwebsite/testProgram#id_20260505001006_475" was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the "Step 5 - agent state message input" in the execution "http://testwebsite/testProgram#id_20260505001009_972" generated by a Generative Task?
                '''
ic| entities:                                  plbl  \
              0  Step 5 - agent state message input

                                                            gtask2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 5 - agent state message input" in the execution "http://testwebsite/testProgram#id_20260505001009_972" was generated by a
                Generative Task

                Generative Task
            http://testwebsite/testProgram#Generative_Task-id_20260505001006_475
                ', entities=[{'gtask2': 'http://testwebsite/testProgram#Generative_Task-id_20260505001006_475'}])
ic| rquestion: '''
                Was the input to the "Step 5 - message input port for generation iteration 2" in the execution "http://testwebsite/testProgram#id_20260505001009_972" generated by a Generative Task?
                '''
ic| entities:                                                 plbl  \
              0  Step 5 - message input port for generation ite...

                                                            gtask2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 5 - message input port for generation iteration 2" in the execution "http://testwebsite/testProgram#id_20260505001009_972" was generated by a
                Generative Task

                Generative Task
            http://testwebsite/testProgram#Generative_Task-id_20260505001006_475
                ', entities=[{'gtask2': 'http://testwebsite/testProgram#Generative_Task-id_20260505001006_475'}])
ic| rquestion: '''
                Was the input to the "Step 5 - system prompt input" in the execution "http://testwebsite/testProgram#id_20260505001009_972" generated by a Generative Task?
                '''
ic| entities:                            plbl gtask2
              0  Step 5 - system prompt input   None
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 5 - system prompt input" in the execution "http://testwebsite/testProgram#id_20260505001009_972" was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the "Step 5 - system_prompt input port for generation iteration 2" in the execution "http://testwebsite/testProgram#id_20260505001009_972" generated by a Generative Task?
                '''
ic| entities:                                                 plbl gtask2
              0  Step 5 - system_prompt input port for generati...   None
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 5 - system_prompt input port for generation iteration 2" in the execution "http://testwebsite/testProgram#id_20260505001009_972" was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the "Step 6 - system prompt input" in the execution "http://testwebsite/testProgram#id_20260505001011_890" generated by a Generative Task?
                '''
ic| entities:                            plbl gtask2
              0  Step 6 - system prompt input   None
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 6 - system prompt input" in the execution "http://testwebsite/testProgram#id_20260505001011_890" was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the "Step 6 - system_prompt input port for generation iteration 3" in the execution "http://testwebsite/testProgram#id_20260505001011_890" generated by a Generative Task?
                '''
ic| entities:                                                 plbl gtask2
              0  Step 6 - system_prompt input port for generati...   None
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 6 - system_prompt input port for generation iteration 3" in the execution "http://testwebsite/testProgram#id_20260505001011_890" was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the "Step 6 - agent state message input" in the execution "http://testwebsite/testProgram#id_20260505001011_890" generated by a Generative Task?
                '''
ic| entities:                                  plbl  \
              0  Step 6 - agent state message input

                                                            gtask2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 6 - agent state message input" in the execution "http://testwebsite/testProgram#id_20260505001011_890" was generated by a
                Generative Task

                Generative Task
            http://testwebsite/testProgram#Generative_Task-id_20260505001009_972
                ', entities=[{'gtask2': 'http://testwebsite/testProgram#Generative_Task-id_20260505001009_972'}])
ic| rquestion: '''
                Was the input to the "Step 6 - message input port for generation iteration 3" in the execution "http://testwebsite/testProgram#id_20260505001011_890" generated by a Generative Task?
                '''
ic| entities:                                                 plbl  \
              0  Step 6 - message input port for generation ite...

                                                            gtask2
              0  http://testwebsite/testProgram#Generative_Task...
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 6 - message input port for generation iteration 3" in the execution "http://testwebsite/testProgram#id_20260505001011_890" was generated by a
                Generative Task

                Generative Task
            http://testwebsite/testProgram#Generative_Task-id_20260505001009_972
                ', entities=[{'gtask2': 'http://testwebsite/testProgram#Generative_Task-id_20260505001009_972'}])
ic| rquestion: '''
                Was the input to the "Step 8 - agent state message input" in the execution "http://testwebsite/testProgram#id_20260505001016_956" generated by a Generative Task?
                '''
ic| entities:                                  plbl gtask2
              0  Step 8 - agent state message input   None
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 8 - agent state message input" in the execution "http://testwebsite/testProgram#id_20260505001016_956" was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the "Step 8 - message input port for generation iteration 4" in the execution "http://testwebsite/testProgram#id_20260505001016_956" generated by a Generative Task?
                '''
ic| entities:                                                 plbl gtask2
              0  Step 8 - message input port for generation ite...   None
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 8 - message input port for generation iteration 4" in the execution "http://testwebsite/testProgram#id_20260505001016_956" was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the "Step 8 - system prompt input" in the execution "http://testwebsite/testProgram#id_20260505001016_956" generated by a Generative Task?
                '''
ic| entities:                            plbl gtask2
              0  Step 8 - system prompt input   None
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 8 - system prompt input" in the execution "http://testwebsite/testProgram#id_20260505001016_956" was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])
ic| rquestion: '''
                Was the input to the "Step 8 - system_prompt input port for generation iteration 4" in the execution "http://testwebsite/testProgram#id_20260505001016_956" generated by a Generative Task?
                '''
ic| entities:                                                 plbl gtask2
              0  Step 8 - system_prompt input port for generati...   None
ic| answer: GTAnswer(answer_nlp='
                The input to the "Step 8 - system_prompt input port for generation iteration 4" in the execution "http://testwebsite/testProgram#id_20260505001016_956" was not generated by a
                Generative Task

                Generative Task
            None
                ', entities=[{'gtask2': 'None'}])

In [68]:
question_sparql1 = """
SELECT distinct ?obj ?lbl
WHERE {
     ?obj a provone:Program .
     ?obj rdfs:label ?lbl .
}
"""


programs = graph_manager.query(question_sparql1).to_dict(orient="records")
template_spec = [{"func_desc":x["lbl"] , "func_desc_term":x["lbl"]} for x in programs]
template_spec;

In [69]:
# Output data of execution with port

_spec = template_spec[:5] if len(template_spec) > 5 else template_spec
# sparql_template = """
# SELECT DISTINCT ?data
#             WHERE {
#                 <{exe_id}> prov:qualifiedGeneration ?generation .
#                 ?generation provone:hadOutPort ?port .
#                 ?port rdfs:label ?plbl .
#                 FILTER(REGEX(?plbl, "{port_label}","i"))
                
#                 ?generation provone:hadEntity ?data .
#         }
# """

template_spec = []
sparql_spec = []

for _s in _spec:
    exe_query = """
    SELECT DISTINCT ?exe
    WHERE {
        ?obj dc:description ?desc .
        ?obj rdfs:label ?flbl .
        FILTER(REGEX(?flbl, "{func_desc_term}","i"))
        
        ?asso prov:hadPlan ?obj .
        ?exe prov:qualifiedAssociation ?asso .      
        
        }
    """
    executions = graph_manager.query(
        regex_add_strings(exe_query, func_desc_term = _s["func_desc_term"])
    )


    for obj in executions.to_dict("records"):
        usage_query = """
        SELECT DISTINCT ?lbl
        WHERE {
            <{exe_id}> prov:qualifiedGeneration ?generation .
            ?generation provone:hadOutPort ?port .
            ?port rdfs:label ?lbl .
            }
        """
        usages = graph_manager.query(
                regex_add_strings(
                    usage_query,
                    exe_id = obj["exe"]
                )
            )
        
        for usage in usages.to_dict("records"):
            # df = graph_manager.query(
            #     regex_add_strings(
            #         sparql_template,
            #         exe_id = obj["exe"],
            #         port_label = usage["lbl"].split("@")[0]
            #     )
            # )

            # print(df)
            
            template_spec.append({
                "exe_id":obj['exe'],
                "port_label" : usage["lbl"].split("@")[0]
            })
            
            sparql_spec.append({
                "exe_id":obj['exe'],
                "port_label" : usage["lbl"].split("@")[0]
            })

           
question_template = """
what is the number of output for the "{port_label}" in the execution "{exe_id}" ?
"""

sparql_template = """
SELECT DISTINCT ?data
            WHERE {
                <{exe_id}> prov:qualifiedGeneration ?generation .
                ?generation provone:hadOutPort ?port .
                ?port rdfs:label ?plbl .
                FILTER(REGEX(?plbl, "{port_label}","i"))
                
                ?generation provone:hadEntity ?data .
        }
"""

def answer_template_function(
    entities:pd.DataFrame, 
    question_specs:Mapping[str, Union[str,int]], 
    sparql_specs:Mapping[str, Union[str,int]]
    ) -> GTAnswer:

    answer_template = """
    The number of output for the "{port_label}" in the execution "{exe_id}" is {count}

    {answer_inst}
    """
    
    _ent = entities[['data']]
    _temp_ent = format_dataframe_to_string(
        _ent,
        header_map={
            'data': "Output Data"
        }
    )
    
    answer_nlp = regex_add_strings(
        answer_template, 
        exe_id = question_specs["exe_id"],
        port_label = question_specs["port_label"],
        count = len(_ent['data'].tolist()),
        answer_inst = _temp_ent
        )
    
    return GTAnswer(
        answer_nlp= answer_nlp,
        entities= _ent.to_dict(orient="records")
    )

gts = build_gt_from_template(
        template=question_template,
        answer_template=answer_template_function,
        sparql_query=sparql_template,
        specs_template=template_spec,
        specs_sparql=sparql_spec,
        graph_manager= graph_manager,
        verbose=True
    )

for gt in gts:
    #gt.qtype = ["multi", "numeric", "ISP"]
    gt.qtype = ["multi", "numeric"]
    gt.count = len(gt.entities)
gt_list.extend(gts)

ic| rquestion: '''
                what is the number of output for the "Step 10 - next agent step output" in the execution "http://testwebsite/testProgram#id_20260505001035_720" ?
                '''
ic| entities:                                                 data
              0  http://testwebsite/testProgram#Data-id_2026050...
ic| answer: GTAnswer(answer_nlp='
                The number of output for the "Step 10 - next agent step output" in the execution "http://testwebsite/testProgram#id_20260505001035_720" is 1

                Output Data
            http://testwebsite/testProgram#Data-id_20260505001035_545-next_step
                ', entities=[{'data': 'http://testwebsite/testProgram#Data-id_20260505001035_545-next_step'}])
ic| rquestion: '''
                what is the number of output for the "Step 10 - next_step output port for critic review 1" in the execution "http://testwebsite/testProgram#id_20260505001035_720" ?
                '''
ic| entities:                                                 data
              0  http://testwebsite/testProgram#Data-id_2026050...
ic| answer: GTAnswer(answer_nlp='
                The number of output for the "Step 10 - next_step output port for critic review 1" in the execution "http://testwebsite/testProgram#id_20260505001035_720" is 1

                Output Data
            http://testwebsite/testProgram#Data-id_20260505001035_545-next_step
                ', entities=[{'data': 'http://testwebsite/testProgram#Data-id_20260505001035_545-next_step'}])
ic| rquestion: '''
                what is the number of output for the "Step 10 - critic feedback output" in the execution "http://testwebsite/testProgram#id_20260505001035_720" ?
                '''
ic| entities:                                                 data
              0  http://testwebsite/testProgram#Data-id_2026050...
ic| answer: GTAnswer(answer_nlp='
                The number of output for the "Step 10 - critic feedback output" in the execution "http://testwebsite/testProgram#id_20260505001035_720" is 1

                Output Data
            http://testwebsite/testProgram#Data-id_20260505001035_624-critic_feedback
                ', entities=[{'data': 'http://testwebsite/testProgram#Data-id_20260505001035_624-critic_feedback'}])
ic| rquestion: '''
                what is the number of output for the "Step 10 - critic_feedback output port for critic review 1" in the execution "http://testwebsite/testProgram#id_20260505001035_720" ?
                '''
ic| entities:                                                 data
              0  http://testwebsite/testProgram#Data-id_2026050...
ic| answer: GTAnswer(answer_nlp='
                The number of output for the "Step 10 - critic_feedback output port for critic review 1" in the execution "http://testwebsite/testProgram#id_20260505001035_720" is 1

                Output Data
            http://testwebsite/testProgram#Data-id_20260505001035_624-critic_feedback
                ', entities=[{'data': 'http://testwebsite/testProgram#Data-id_20260505001035_624-critic_feedback'}])
ic| rquestion: '''
                what is the number of output for the "Step 4 - next agent step output" in the execution "http://testwebsite/testProgram#id_20260505001006_475" ?
                '''
ic| entities:                                                 data
              0  http://testwebsite/testProgram#Data-id_2026050...
ic| answer: GTAnswer(answer_nlp='
                The number of output for the "Step 4 - next agent step output" in the execution "http://testwebsite/testProgram#id_20260505001006_475" is 1

                Output Data
            http://testwebsite/testProgram#Data-id_20260505001006_205-next_step
                ', entities=[{'data': 'http://testwebsite/testProgram#Data-id_20260505001006_205-next_step'}])
ic| rquestion: '''
                what is the number of output for the "Step 4 - next_step output port for generation iteration 1" in the execution "http://testwebsite/testProgram#id_20260505001006_475" ?
                '''
ic| entities:                                                 data
              0  http://testwebsite/testProgram#Data-id_2026050...
ic| answer: GTAnswer(answer_nlp='
                The number of output for the "Step 4 - next_step output port for generation iteration 1" in the execution "http://testwebsite/testProgram#id_20260505001006_475" is 1

                Output Data
            http://testwebsite/testProgram#Data-id_20260505001006_205-next_step
                ', entities=[{'data': 'http://testwebsite/testProgram#Data-id_20260505001006_205-next_step'}])
ic| rquestion: '''
                what is the number of output for the "Step 4 - LLM response output" in the execution "http://testwebsite/testProgram#id_20260505001006_475" ?
                '''
ic| entities:                                                 data
              0  http://testwebsite/testProgram#Data-id_2026050...
ic| answer: GTAnswer(answer_nlp='
                The number of output for the "Step 4 - LLM response output" in the execution "http://testwebsite/testProgram#id_20260505001006_475" is 1

                Output Data
            http://testwebsite/testProgram#Data-id_20260505001006_90-response
                ', entities=[{'data': 'http://testwebsite/testProgram#Data-id_20260505001006_90-response'}])
ic| rquestion: '''
                what is the number of output for the "Step 4 - response output port for generation iteration 1" in the execution "http://testwebsite/testProgram#id_20260505001006_475" ?
                '''
ic| entities:                                                 data
              0  http://testwebsite/testProgram#Data-id_2026050...
ic| answer: GTAnswer(answer_nlp='
                The number of output for the "Step 4 - response output port for generation iteration 1" in the execution "http://testwebsite/testProgram#id_20260505001006_475" is 1

                Output Data
            http://testwebsite/testProgram#Data-id_20260505001006_90-response
                ', entities=[{'data': 'http://testwebsite/testProgram#Data-id_20260505001006_90-response'}])
ic| rquestion: '''
                what is the number of output for the "Step 5 - next agent step output" in the execution "http://testwebsite/testProgram#id_20260505001009_972" ?
                '''
ic| entities:                                                 data
              0  http://testwebsite/testProgram#Data-id_2026050...
ic| answer: GTAnswer(answer_nlp='
                The number of output for the "Step 5 - next agent step output" in the execution "http://testwebsite/testProgram#id_20260505001009_972" is 1

                Output Data
            http://testwebsite/testProgram#Data-id_20260505001009_349-next_step
                ', entities=[{'data': 'http://testwebsite/testProgram#Data-id_20260505001009_349-next_step'}])
ic| rquestion: '''
                what is the number of output for the "Step 5 - next_step output port for generation iteration 2" in the execution "http://testwebsite/testProgram#id_20260505001009_972" ?
                '''
ic| entities:                                                 data
              0  http://testwebsite/testProgram#Data-id_2026050...
ic| answer: GTAnswer(answer_nlp='
                The number of output for the "Step 5 - next_step output port for generation iteration 2" in the execution "http://testwebsite/testProgram#id_20260505001009_972" is 1

                Output Data
            http://testwebsite/testProgram#Data-id_20260505001009_349-next_step
                ', entities=[{'data': 'http://testwebsite/testProgram#Data-id_20260505001009_349-next_step'}])
ic| rquestion: '''
                what is the number of output for the "Step 5 - LLM response output" in the execution "http://testwebsite/testProgram#id_20260505001009_972" ?
                '''
ic| entities:                                                 data
              0  http://testwebsite/testProgram#Data-id_2026050...
ic| answer: GTAnswer(answer_nlp='
                The number of output for the "Step 5 - LLM response output" in the execution "http://testwebsite/testProgram#id_20260505001009_972" is 1

                Output Data
            http://testwebsite/testProgram#Data-id_20260505001009_976-response
                ', entities=[{'data': 'http://testwebsite/testProgram#Data-id_20260505001009_976-response'}])
ic| rquestion: '''
                what is the number of output for the "Step 5 - response output port for generation iteration 2" in the execution "http://testwebsite/testProgram#id_20260505001009_972" ?
                '''
ic| entities:                                                 data
              0  http://testwebsite/testProgram#Data-id_2026050...
ic| answer: GTAnswer(answer_nlp='
                The number of output for the "Step 5 - response output port for generation iteration 2" in the execution "http://testwebsite/testProgram#id_20260505001009_972" is 1

                Output Data
            http://testwebsite/testProgram#Data-id_20260505001009_976-response
                ', entities=[{'data': 'http://testwebsite/testProgram#Data-id_20260505001009_976-response'}])
ic| rquestion: '''
                what is the number of output for the "Step 6 - next agent step output" in the execution "http://testwebsite/testProgram#id_20260505001011_890" ?
                '''
ic| entities:                                                 data
              0  http://testwebsite/testProgram#Data-id_2026050...
ic| answer: GTAnswer(answer_nlp='
                The number of output for the "Step 6 - next agent step output" in the execution "http://testwebsite/testProgram#id_20260505001011_890" is 1

                Output Data
            http://testwebsite/testProgram#Data-id_20260505001011_540-next_step
                ', entities=[{'data': 'http://testwebsite/testProgram#Data-id_20260505001011_540-next_step'}])
ic| rquestion: '''
                what is the number of output for the "Step 6 - next_step output port for generation iteration 3" in the execution "http://testwebsite/testProgram#id_20260505001011_890" ?
                '''
ic| entities:                                                 data
              0  http://testwebsite/testProgram#Data-id_2026050...
ic| answer: GTAnswer(answer_nlp='
                The number of output for the "Step 6 - next_step output port for generation iteration 3" in the execution "http://testwebsite/testProgram#id_20260505001011_890" is 1

                Output Data
            http://testwebsite/testProgram#Data-id_20260505001011_540-next_step
                ', entities=[{'data': 'http://testwebsite/testProgram#Data-id_20260505001011_540-next_step'}])
ic| rquestion: '''
                what is the number of output for the "Step 6 - LLM response output" in the execution "http://testwebsite/testProgram#id_20260505001011_890" ?
                '''
ic| entities:                                                 data
              0  http://testwebsite/testProgram#Data-id_2026050...
ic| answer: GTAnswer(answer_nlp='
                The number of output for the "Step 6 - LLM response output" in the execution "http://testwebsite/testProgram#id_20260505001011_890" is 1

                Output Data
            http://testwebsite/testProgram#Data-id_20260505001011_622-response
                ', entities=[{'data': 'http://testwebsite/testProgram#Data-id_20260505001011_622-response'}])
ic| rquestion: '''
                what is the number of output for the "Step 6 - response output port for generation iteration 3" in the execution "http://testwebsite/testProgram#id_20260505001011_890" ?
                '''
ic| entities:                                                 data
              0  http://testwebsite/testProgram#Data-id_2026050...
ic| answer: GTAnswer(answer_nlp='
                The number of output for the "Step 6 - response output port for generation iteration 3" in the execution "http://testwebsite/testProgram#id_20260505001011_890" is 1

                Output Data
            http://testwebsite/testProgram#Data-id_20260505001011_622-response
                ', entities=[{'data': 'http://testwebsite/testProgram#Data-id_20260505001011_622-response'}])
ic| rquestion: '''
                what is the number of output for the "Step 8 - next agent step output" in the execution "http://testwebsite/testProgram#id_20260505001016_956" ?
                '''
ic| entities:                                                 data
              0  http://testwebsite/testProgram#Data-id_2026050...
ic| answer: GTAnswer(answer_nlp='
                The number of output for the "Step 8 - next agent step output" in the execution "http://testwebsite/testProgram#id_20260505001016_956" is 1

                Output Data
            http://testwebsite/testProgram#Data-id_20260505001016_765-next_step
                ', entities=[{'data': 'http://testwebsite/testProgram#Data-id_20260505001016_765-next_step'}])
ic| rquestion: '''
                what is the number of output for the "Step 8 - next_step output port for generation iteration 4" in the execution "http://testwebsite/testProgram#id_20260505001016_956" ?
                '''
ic| entities:                                                 data
              0  http://testwebsite/testProgram#Data-id_2026050...
ic| answer: GTAnswer(answer_nlp='
                The number of output for the "Step 8 - next_step output port for generation iteration 4" in the execution "http://testwebsite/testProgram#id_20260505001016_956" is 1

                Output Data
            http://testwebsite/testProgram#Data-id_20260505001016_765-next_step
                ', entities=[{'data': 'http://testwebsite/testProgram#Data-id_20260505001016_765-next_step'}])
ic| rquestion: '''
                what is the number of output for the "Step 8 - LLM response output" in the execution "http://testwebsite/testProgram#id_20260505001016_956" ?
                '''
ic| entities:                                                 data
              0  http://testwebsite/testProgram#Data-id_2026050...
ic| answer: GTAnswer(answer_nlp='
                The number of output for the "Step 8 - LLM response output" in the execution "http://testwebsite/testProgram#id_20260505001016_956" is 1

                Output Data
            http://testwebsite/testProgram#Data-id_20260505001016_949-response
                ', entities=[{'data': 'http://testwebsite/testProgram#Data-id_20260505001016_949-response'}])
ic| rquestion: '''
                what is the number of output for the "Step 8 - response output port for generation iteration 4" in the execution "http://testwebsite/testProgram#id_20260505001016_956" ?
                '''
ic| entities:                                                 data
              0  http://testwebsite/testProgram#Data-id_2026050...
ic| answer: GTAnswer(answer_nlp='
                The number of output for the "Step 8 - response output port for generation iteration 4" in the execution "http://testwebsite/testProgram#id_20260505001016_956" is 1

                Output Data
            http://testwebsite/testProgram#Data-id_20260505001016_949-response
                ', entities=[{'data': 'http://testwebsite/testProgram#Data-id_20260505001016_949-response'}])

In [70]:
os.makedirs(os.path.dirname(config.gt.save_loc), exist_ok=True)
for i, gt in enumerate(gt_list):
    gt.id = f"gt_{i}"

common_utils.serialization.save_jsonl(
    [gt.model_dump() for gt in gt_list],
    config.gt.save_loc
)

In [71]:
gt_list

[GT(id='gt_0', question='\nHow many "experiment execution" are there in this?\n', answer='The answer to the question is 12 unique executions.', entities=[{'obj': 'http://testwebsite/testProgram#id_20260505000949_750'}, {'obj': 'http://testwebsite/testProgram#id_20260505000949_550'}, {'obj': 'http://testwebsite/testProgram#id_20260505000949_654'}, {'obj': 'http://testwebsite/testProgram#id_20260505001013_746'}, {'obj': 'http://testwebsite/testProgram#id_20260505001035_720'}, {'obj': 'http://testwebsite/testProgram#id_20260505001042_313'}, {'obj': 'http://testwebsite/testProgram#id_20260505001006_475'}, {'obj': 'http://testwebsite/testProgram#id_20260505001009_972'}, {'obj': 'http://testwebsite/testProgram#id_20260505001011_890'}, {'obj': 'http://testwebsite/testProgram#id_20260505001016_956'}, {'obj': 'http://testwebsite/testProgram#id_20260505001023_688'}, {'obj': 'http://testwebsite/testProgram#id_20260505001037_336'}], sparql=[SPARQLTemplate(template='\nSELECT distinct ?obj\nWHERE {\n     ?obj a provone:Execution .\n     ?obj rdfs:label ?lbl .\n}\n', description='This SPARQL query counts the number of unique executions by counting distinct identifiers in the provone:Execution class.', inputs=None)], qtype=['multi', 'numeric'], decision=None, count=12, tags={}),
 GT(id='gt_1', question='\nIn what places do we utilize AI in this workflow?\n', answer='\nThe ChatBS System utilizes AI for the following\n\n1 => Step 4: Records how the agent used an LLM during the generation iteration 1 step.\n\n2 => Step 4: Records how the agent used an LLM during this generation iteration.\n\n3 => Step 5: Records how the agent used an LLM during the generation iteration 2 step.\n\n4 => Step 5: Records how the agent used an LLM during this generation iteration.\n\n5 => Step 8: Records how the agent used an LLM during the generation iteration 4 step.\n\n6 => Step 8: Records how the agent used an LLM during this generation iteration.\n\n7 => Step 9: Records how the agent used an LLM during the generation iteration 5 step.\n\n8 => Step 9: Records how the agent used an LLM during this generation iteration.\n\n9 => Step 10: Records how the agent used an LLM during the critic review 1 step.\n\n10 => Step 10: Records the LLM use that produced self-critic feedback for the agent.\n\n11 => Step 11: Records how the agent used an LLM during the generation iteration 6 step.\n\n12 => Step 11: Records how the agent used an LLM during this generation iteration.\n\n13 => Step 12: Records how the agent used an LLM during the generation iteration 7 step.\n\n14 => Step 12: Records how the agent used an LLM during this generation iteration.\n\n15 => Step 6: Records how the agent used an LLM during the generation iteration 3 step.\n\n16 => Step 6: Records how the agent used an LLM during this generation iteration.\n', entities=[{'obj': 'Biomni:Generative_Task-id_20260505001006_475', 'desc': 'Step 4: Records how the agent used an LLM during the generation iteration 1 step.'}, {'obj': 'Biomni:Generative_Task-id_20260505001006_475', 'desc': 'Step 4: Records how the agent used an LLM during this generation iteration.'}, {'obj': 'Biomni:Generative_Task-id_20260505001009_972', 'desc': 'Step 5: Records how the agent used an LLM during the generation iteration 2 step.'}, {'obj': 'Biomni:Generative_Task-id_20260505001009_972', 'desc': 'Step 5: Records how the agent used an LLM during this generation iteration.'}, {'obj': 'Biomni:Generative_Task-id_20260505001016_956', 'desc': 'Step 8: Records how the agent used an LLM during the generation iteration 4 step.'}, {'obj': 'Biomni:Generative_Task-id_20260505001016_956', 'desc': 'Step 8: Records how the agent used an LLM during this generation iteration.'}, {'obj': 'Biomni:Generative_Task-id_20260505001023_688', 'desc': 'Step 9: Records how the agent used an LLM during the generation iteration 5 step.'}, {'obj': 'Biomni:Generative_Task-id_20260505001023_688', 'desc': 'Step 9: Records how the agent used an LLM during this generation iteration.'}, {'obj': 'Biomni:Generative_Task-id_20260505001035_720', 'desc': 'Step 10: Records how the agent used an LLM during the critic review 1 step.'}, {'obj': 'Biomni:Generative_Task-id_20260505001035_720', 'desc': 'Step 10: Records the LLM use that produced self-critic feedback for the agent.'}, {'obj': 'Biomni:Generative_Task-id_20260505001037_336', 'desc': 'Step 11: Records how the agent used an LLM during the generation iteration 6 step.'}, {'obj': 'Biomni:Generative_Task-id_20260505001037_336', 'desc': 'Step 11: Records how the agent used an LLM during this generation iteration.'}, {'obj': 'Biomni:Generative_Task-id_20260505001042_313', 'desc': 'Step 12: Records how the agent used an LLM during the generation iteration 7 step.'}, {'obj': 'Biomni:Generative_Task-id_20260505001042_313', 'desc': 'Step 12: Records how the agent used an LLM during this generation iteration.'}, {'obj': 'Biomni:Generative_Task-id_20260505001011_890', 'desc': 'Step 6: Records how the agent used an LLM during the generation iteration 3 step.'}, {'obj': 'Biomni:Generative_Task-id_20260505001011_890', 'desc': 'Step 6: Records how the agent used an LLM during this generation iteration.'}], sparql=[SPARQLTemplate(template='\nSELECT distinct ?obj ?desc\nWHERE {\n     ?obj a workflow:Generative_Task .\n     ?obj dc:description ?desc .\n}\n', description='', inputs=None)], qtype=['multi', 'entity'], decision=None, count=None, tags={}),
 GT(id='gt_2', question='\nwhat are the input parameters of the function used in "Step 10 - Biomni critic review 1" step in the pipeline?\n', answer='\n    The input parameters to Step 10 - Biomni critic review 1 function.\n\n    Funtion name | Function returns\nStep 10 - Biomni critic review 1 | Step 10 - candidate solution input\nStep 10 - Biomni critic review 1 | Step 10 - candidate_solution input port for critic review 1\nStep 10 - Biomni critic review 1 | Step 10 - critic prompt input\nStep 10 - Biomni critic review 1 | Step 10 - feedback_prompt input port for critic review 1\nStep 10 - Biomni critic review 1 | Step 10 - conversation history input\nStep 10 - Biomni critic review 1 | Step 10 - message_history input port for critic review 1\nStep 10 - Biomni critic review 1 | Step 10 - original user task input\nStep 10 - Biomni critic review 1 | Step 10 - user_task input port for critic review 1\n    ', entities=[{'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - candidate solution input'}, {'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - candidate_solution input port for critic review 1'}, {'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - critic prompt input'}, {'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - feedback_prompt input port for critic review 1'}, {'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - conversation history input'}, {'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - message_history input port for critic review 1'}, {'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - original user task input'}, {'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - user_task input port for critic review 1'}], sparql=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?flbl, "Step 10 - Biomni critic review 1","i"))\n\n     ?obj provone:hasInPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], qtype=['multi', 'entity'], decision=None, count=None, tags={}),
 GT(id='gt_3', question='\nwhat are the input parameters of the function used in "Step 4 - Biomni LLM generation iteration 1" step in the pipeline?\n', answer='\n    The input parameters to Step 4 - Biomni LLM generation iteration 1 function.\n\n    Funtion name | Function returns\nStep 4 - Biomni LLM generation iteration 1 | Step 4 - agent state message input\nStep 4 - Biomni LLM generation iteration 1 | Step 4 - message input port for generation iteration 1\nStep 4 - Biomni LLM generation iteration 1 | Step 4 - system prompt input\nStep 4 - Biomni LLM generation iteration 1 | Step 4 - system_prompt input port for generation iteration 1\n    ', entities=[{'flbl': 'Step 4 - Biomni LLM generation iteration 1', 'lbl': 'Step 4 - agent state message input'}, {'flbl': 'Step 4 - Biomni LLM generation iteration 1', 'lbl': 'Step 4 - message input port for generation iteration 1'}, {'flbl': 'Step 4 - Biomni LLM generation iteration 1', 'lbl': 'Step 4 - system prompt input'}, {'flbl': 'Step 4 - Biomni LLM generation iteration 1', 'lbl': 'Step 4 - system_prompt input port for generation iteration 1'}], sparql=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?flbl, "Step 4 - Biomni LLM generation iteration 1","i"))\n\n     ?obj provone:hasInPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], qtype=['multi', 'entity'], decision=None, count=None, tags={}),
 GT(id='gt_4', question='\nwhat are the input parameters of the function used in "Step 5 - Biomni LLM generation iteration 2" step in the pipeline?\n', answer='\n    The input parameters to Step 5 - Biomni LLM generation iteration 2 function.\n\n    Funtion name | Function returns\nStep 5 - Biomni LLM generation iteration 2 | Step 5 - agent state message input\nStep 5 - Biomni LLM generation iteration 2 | Step 5 - message input port for generation iteration 2\nStep 5 - Biomni LLM generation iteration 2 | Step 5 - system prompt input\nStep 5 - Biomni LLM generation iteration 2 | Step 5 - system_prompt input port for generation iteration 2\n    ', entities=[{'flbl': 'Step 5 - Biomni LLM generation iteration 2', 'lbl': 'Step 5 - agent state message input'}, {'flbl': 'Step 5 - Biomni LLM generation iteration 2', 'lbl': 'Step 5 - message input port for generation iteration 2'}, {'flbl': 'Step 5 - Biomni LLM generation iteration 2', 'lbl': 'Step 5 - system prompt input'}, {'flbl': 'Step 5 - Biomni LLM generation iteration 2', 'lbl': 'Step 5 - system_prompt input port for generation iteration 2'}], sparql=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?flbl, "Step 5 - Biomni LLM generation iteration 2","i"))\n\n     ?obj provone:hasInPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], qtype=['multi', 'entity'], decision=None, count=None, tags={}),
 GT(id='gt_5', question='\nwhat are the input parameters of the function used in "Step 6 - Biomni LLM generation iteration 3" step in the pipeline?\n', answer='\n    The input parameters to Step 6 - Biomni LLM generation iteration 3 function.\n\n    Funtion name | Function returns\nStep 6 - Biomni LLM generation iteration 3 | Step 6 - agent state message input\nStep 6 - Biomni LLM generation iteration 3 | Step 6 - message input port for generation iteration 3\nStep 6 - Biomni LLM generation iteration 3 | Step 6 - system prompt input\nStep 6 - Biomni LLM generation iteration 3 | Step 6 - system_prompt input port for generation iteration 3\n    ', entities=[{'flbl': 'Step 6 - Biomni LLM generation iteration 3', 'lbl': 'Step 6 - agent state message input'}, {'flbl': 'Step 6 - Biomni LLM generation iteration 3', 'lbl': 'Step 6 - message input port for generation iteration 3'}, {'flbl': 'Step 6 - Biomni LLM generation iteration 3', 'lbl': 'Step 6 - system prompt input'}, {'flbl': 'Step 6 - Biomni LLM generation iteration 3', 'lbl': 'Step 6 - system_prompt input port for generation iteration 3'}], sparql=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?flbl, "Step 6 - Biomni LLM generation iteration 3","i"))\n\n     ?obj provone:hasInPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], qtype=['multi', 'entity'], decision=None, count=None, tags={}),
 GT(id='gt_6', question='\nwhat are the input parameters of the function used in "Step 8 - Biomni LLM generation iteration 4" step in the pipeline?\n', answer='\n    The input parameters to Step 8 - Biomni LLM generation iteration 4 function.\n\n    Funtion name | Function returns\nStep 8 - Biomni LLM generation iteration 4 | Step 8 - agent state message input\nStep 8 - Biomni LLM generation iteration 4 | Step 8 - message input port for generation iteration 4\nStep 8 - Biomni LLM generation iteration 4 | Step 8 - system prompt input\nStep 8 - Biomni LLM generation iteration 4 | Step 8 - system_prompt input port for generation iteration 4\n    ', entities=[{'flbl': 'Step 8 - Biomni LLM generation iteration 4', 'lbl': 'Step 8 - agent state message input'}, {'flbl': 'Step 8 - Biomni LLM generation iteration 4', 'lbl': 'Step 8 - message input port for generation iteration 4'}, {'flbl': 'Step 8 - Biomni LLM generation iteration 4', 'lbl': 'Step 8 - system prompt input'}, {'flbl': 'Step 8 - Biomni LLM generation iteration 4', 'lbl': 'Step 8 - system_prompt input port for generation iteration 4'}], sparql=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?flbl, "Step 8 - Biomni LLM generation iteration 4","i"))\n\n     ?obj provone:hasInPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], qtype=['multi', 'entity'], decision=None, count=None, tags={}),
 GT(id='gt_7', question='\nwhat are the output parameters of the function used in "Step 10 - Biomni critic review 1" step in the pipeline?\n', answer='\n    The input parameters to Step 10 - Biomni critic review 1 function.\n\n    Funtion name | Function returns\nStep 10 - Biomni critic review 1 | Step 10 - critic feedback output\nStep 10 - Biomni critic review 1 | Step 10 - critic_feedback output port for critic review 1\nStep 10 - Biomni critic review 1 | Step 10 - next agent step output\nStep 10 - Biomni critic review 1 | Step 10 - next_step output port for critic review 1\n    ', entities=[{'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - critic feedback output'}, {'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - critic_feedback output port for critic review 1'}, {'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - next agent step output'}, {'flbl': 'Step 10 - Biomni critic review 1', 'lbl': 'Step 10 - next_step output port for critic review 1'}], sparql=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?flbl, "Step 10 - Biomni critic review 1","i"))\n\n     ?obj provone:hasOutPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], qtype=['multi', 'entity'], decision=None, count=None, tags={}),
 GT(id='gt_8', question='\nwhat are the output parameters of the function used in "Step 4 - Biomni LLM generation iteration 1" step in the pipeline?\n', answer='\n    The input parameters to Step 4 - Biomni LLM generation iteration 1 function.\n\n    Funtion name | Function returns\nStep 4 - Biomni LLM generation iteration 1 | Step 4 - next agent step output\nStep 4 - Biomni LLM generation iteration 1 | Step 4 - next_step output port for generation iteration 1\nStep 4 - Biomni LLM generation iteration 1 | Step 4 - LLM response output\nStep 4 - Biomni LLM generation iteration 1 | Step 4 - response output port for generation iteration 1\n    ', entities=[{'flbl': 'Step 4 - Biomni LLM generation iteration 1', 'lbl': 'Step 4 - next agent step output'}, {'flbl': 'Step 4 - Biomni LLM generation iteration 1', 'lbl': 'Step 4 - next_step output port for generation iteration 1'}, {'flbl': 'Step 4 - Biomni LLM generation iteration 1', 'lbl': 'Step 4 - LLM response output'}, {'flbl': 'Step 4 - Biomni LLM generation iteration 1', 'lbl': 'Step 4 - response output port for generation iteration 1'}], sparql=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?flbl, "Step 4 - Biomni LLM generation iteration 1","i"))\n\n     ?obj provone:hasOutPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], qtype=['multi', 'entity'], decision=None, count=None, tags={}),
 GT(id='gt_9', question='\nwhat are the output parameters of the function used in "Step 5 - Biomni LLM generation iteration 2" step in the pipeline?\n', answer='\n    The input parameters to Step 5 - Biomni LLM generation iteration 2 function.\n\n    Funtion name | Function returns\nStep 5 - Biomni LLM generation iteration 2 | Step 5 - next agent step output\nStep 5 - Biomni LLM generation iteration 2 | Step 5 - next_step output port for generation iteration 2\nStep 5 - Biomni LLM generation iteration 2 | Step 5 - LLM response output\nStep 5 - Biomni LLM generation iteration 2 | Step 5 - response output port for generation iteration 2\n    ', entities=[{'flbl': 'Step 5 - Biomni LLM generation iteration 2', 'lbl': 'Step 5 - next agent step output'}, {'flbl': 'Step 5 - Biomni LLM generation iteration 2', 'lbl': 'Step 5 - next_step output port for generation iteration 2'}, {'flbl': 'Step 5 - Biomni LLM generation iteration 2', 'lbl': 'Step 5 - LLM response output'}, {'flbl': 'Step 5 - Biomni LLM generation iteration 2', 'lbl': 'Step 5 - response output port for generation iteration 2'}], sparql=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?flbl, "Step 5 - Biomni LLM generation iteration 2","i"))\n\n     ?obj provone:hasOutPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], qtype=['multi', 'entity'], decision=None, count=None, tags={}),
 GT(id='gt_10', question='\nwhat are the output parameters of the function used in "Step 6 - Biomni LLM generation iteration 3" step in the pipeline?\n', answer='\n    The input parameters to Step 6 - Biomni LLM generation iteration 3 function.\n\n    Funtion name | Function returns\nStep 6 - Biomni LLM generation iteration 3 | Step 6 - next agent step output\nStep 6 - Biomni LLM generation iteration 3 | Step 6 - next_step output port for generation iteration 3\nStep 6 - Biomni LLM generation iteration 3 | Step 6 - LLM response output\nStep 6 - Biomni LLM generation iteration 3 | Step 6 - response output port for generation iteration 3\n    ', entities=[{'flbl': 'Step 6 - Biomni LLM generation iteration 3', 'lbl': 'Step 6 - next agent step output'}, {'flbl': 'Step 6 - Biomni LLM generation iteration 3', 'lbl': 'Step 6 - next_step output port for generation iteration 3'}, {'flbl': 'Step 6 - Biomni LLM generation iteration 3', 'lbl': 'Step 6 - LLM response output'}, {'flbl': 'Step 6 - Biomni LLM generation iteration 3', 'lbl': 'Step 6 - response output port for generation iteration 3'}], sparql=[SPARQLTemplate(template='\nSELECT distinct ?flbl ?lbl\nWHERE {\n     ?obj dc:description ?desc .\n     ?obj rdfs:label ?flbl . \n     ?obj a ?class .\n     FILTER(REGEX(?flbl, "Step 6 - Biomni LLM generation iteration 3","i"))\n\n     ?obj provone:hasOutPort ?port .\n     ?port rdfs:label ?lbl .\n}\n', description='', inputs=None)], qtype=['multi', 'entity'], decision=None, count=None, tags={}),

In [72]:
all_qtypes = {}
for gt in gt_list:
    if gt.qtype:
        for t in gt.qtype:
            if t in all_qtypes:
                all_qtypes[t] += 1
            else:
                all_qtypes[t] = 1
        
all_qtypes

{'multi': 62, 'numeric': 21, 'entity': 46, 'single': 44, 'bool': 39}

In [73]:
all_qtypes = {}
for gt in gt_list:
    if gt.qtype:
        tags_concat = "|".join(sorted(gt.qtype))
        if tags_concat not in all_qtypes:
            all_qtypes[tags_concat] = 0
        
        all_qtypes[tags_concat] += 1
        
all_qtypes

{'multi|numeric': 21,
 'entity|multi': 41,
 'bool|single': 39,
 'entity|single': 5}

In [74]:
sel_groups = ["multi", "single|bool", "single|entity"]
groups = {}
_temp = []
for gt in gt_list:
    if gt.qtype:
        nadd = False
        for sg in sel_groups:
            tags = sg.split("|")
            if len(set(tags) - set(gt.qtype)) == 0:
                nadd = True
                
        if not nadd:
            _temp.append(gt)
                
        
for gt in _temp:
    if gt.qtype:
        
        _g = "|"+"|".join(sorted(gt.qtype))+"|"
        if _g not in groups:
            groups[_g] = 0
        
        groups[_g] += 1
        
groups

{}